import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import {PGlite} from '@electric-sql/pglite';
import {pg_trgm} from '@electric-sql/pglite/contrib/pg_trgm';
import {btree_gist} from '@electric-sql/pglite/contrib/btree_gist';
import {injectTestDB} from '../lib/db';
import {seed} from '../lib/seed';
import {identityFor} from '../lib/auth-core';
import * as a from '../lib/academy';
import * as o from '../lib/orientation';
import {agenda} from '../lib/meetings';
import {completeTraining} from '../lib/people';
import {myArea} from '../lib/organization';
import {learningProvider} from '../lib/learning-provider';
import {can} from '../lib/permissions';
test('Phase 2A-17 Academy and orientation integration',async t=>{
Object.assign(process.env,{NODE_ENV:'test'});const pg=new PGlite({extensions:{pg_trgm,btree_gist}}),db={query:async<T>(sql:string,v?:unknown[])=>({rows:(await pg.query(sql,v)).rows as T[]})};injectTestDB(db);for(const f of ['001_phase2.sql','002_inventory.sql','003_content.sql','005_workflows.sql','006_engagement.sql','007_meetings.sql','008_directory.sql','009_brand_center.sql','010_notification_v2.sql','011_ticket_v2.sql','012_surveys.sql','013_people_assets.sql','014_fleet.sql','016_organization.sql','017_academy.sql'])await pg.exec(await readFile('db/'+f,'utf8'));await seed(db);
const company=randomUUID(),location=randomUUID(),department=randomUUID();await db.query("INSERT INTO companies(id,name,code) VALUES($1,'Company','CO')",[company]);await db.query("INSERT INTO locations(id,name,code,company_id) VALUES($1,'Location','LOC',$2)",[location,company]);await db.query("INSERT INTO departments(id,name,code,company_id) VALUES($1,'Department','DEP',$2)",[department,company]);const ids=Array.from({length:8},()=>randomUUID()),roles=['SUPER_ADMIN','EMPLOYEE','MANAGER','EMPLOYEE','HR_ADMIN','IT_ADMIN','CONTENT_ADMIN','ADMIN'];for(let i=0;i<ids.length;i++){await db.query("INSERT INTO users(id,personnel_no,first_name,last_name,email,username,company_id,location_id,department_id,must_change_password) VALUES($1,$2,'Academy','Person',$3,$2,$4,$5,$6,false)",[ids[i],'academy'+i,'academy'+i+'@example.test',company,location,department]);await db.query('INSERT INTO user_roles VALUES($1,$2)',[ids[i],roles[i]]);}await db.query('UPDATE users SET manager_user_id=$1 WHERE id=$2',[ids[2],ids[1]]);const root=(await identityFor(db,ids[0]))!,emp=(await identityFor(db,ids[1]))!,manager=(await identityFor(db,ids[2]))!,other=(await identityFor(db,ids[3]))!,hr=(await identityFor(db,ids[4]))!;const cat=(await a.academyOptions(root)).categories[0].id;
const payload={title:'Hybrid Training',category_id:cat,description:'Test',cover:null,duration_minutes:60,language:'TR',method:'HYBRID',obligation:'OPTIONAL',provider:'INTERNAL',content_type:'TEXT',external_content_id:'',launch_url:'',package_reference:'',content:'Read this',requirements:{content:true,exam:true,attendance:true},exam:[{id:'q1',title:'Question',type:'SINGLE',options:['A','B'],correct:[1]},{id:'q2',title:'Multiple',type:'MULTIPLE',options:['A','B','C'],correct:[0,2]}],passing_score:70,attempt_limit:2,certificate_available:true,validity_months:12,repeat_months:12,active:true};let course='',assignment='',session='',orientation='',plan='';
await t.test('all seven roles retain own Academy and employee cannot manage',async()=>{for(let i=0;i<ids.length;i++){const actor=(await identityFor(db,ids[i]))!;assert.ok(can(actor,'academy.view'));assert.equal((await a.assignments(actor)).total,0);}await assert.rejects(()=>a.saveCourse(emp,payload),{status:403});course=(await a.saveCourse(root,payload)).id;assert.equal((await a.catalogue(emp)).total,1);});
await t.test('optional enrollment is current-user and idempotent; course answers never exposed',async()=>{assignment=(await a.enroll(emp,course)).id;assert.equal((await a.enroll(emp,course)).id,assignment);assert.equal((await a.assignments(other)).total,0);const detail=await a.learningDetail(emp,assignment);assert.ok(!('correct' in detail.course.exam[0]));assert.ok(!('learning_snapshot' in detail.item));await assert.rejects(()=>a.learningDetail(other,assignment),{status:403});});
await t.test('manager assignment scope and HR audience assignment',async()=>{const target={course_id:course,starts_on:'2020-01-01',due_date:'2027-01-01',audience_all:false,targets:[{type:'user_id',id:emp.id}]};assert.equal((await a.assignAcademy(manager,target)).count,0);await assert.rejects(()=>a.assignAcademy(manager,{...target,targets:[{type:'user_id',id:other.id}]}),{status:403});assert.equal((await a.assignAcademy(hr,{...target,targets:[{type:'user_id',id:other.id}]})).count,1);});
await t.test('mandatory self enrollment forbidden and course snapshots remain stable',async()=>{await a.saveCourse(root,{...payload,obligation:'LEGAL'},course);await assert.rejects(()=>a.enroll(other,course),{status:403});const d=await a.learningDetail(emp,assignment);assert.equal(d.course.obligation,'OPTIONAL');await a.saveCourse(root,payload,course);});
await t.test('content alone cannot complete hybrid and legacy completion cannot bypass rules',async()=>{await a.completeContent(emp,assignment);assert.equal((await a.learningDetail(emp,assignment)).item.progress,33);await assert.rejects(()=>completeTraining(root,assignment,{valid_until:null,certificate:null}),{status:409});await assert.rejects(()=>a.completeContent(other,assignment),{status:403});});
await t.test('server grading evaluates exact multiple choices and ignores forged score',async()=>{assert.equal(a.grade(payload.exam as Parameters<typeof a.grade>[0],{q1:[1],q2:[0]}),50);await assert.rejects(()=>a.takeExam(emp,assignment,{score:100}));const r=await a.takeExam(emp,assignment,{q1:[1],q2:[0,2]});assert.equal(r.score,100);assert.equal(r.completed,false);assert.equal((await a.learningDetail(emp,assignment)).item.progress,67);});
await t.test('session joins existing calendar without duplicate records and excludes others',async()=>{session=(await a.saveSession(root,{course_id:course,title:'Live Session',start_at:'2020-01-01T10:00:00+03:00',end_at:'2020-01-01T11:00:00+03:00',instructor:'Teacher',platform:'Teams',meeting_url:'https://example.test/meeting',location_id:location,venue:'Room',capacity:1,assignment_ids:[assignment]})).id;const data=await agenda(emp,new URLSearchParams({date:'2020-01-01'}));assert.equal(data.rows.filter(r=>r.kind==='TRAINING').length,1);assert.equal((await agenda(other,new URLSearchParams({date:'2020-01-01'}))).rows.filter(r=>r.kind==='TRAINING').length,0);});
await t.test('authorized attendance completes all requirements, employee attendance denied',async()=>{await assert.rejects(()=>a.attendance(emp,session,[{assignment_id:assignment,status:'ATTENDED'}]),{status:403});await a.attendance(root,session,[{assignment_id:assignment,status:'ATTENDED'}]);const d=await a.learningDetail(emp,assignment);assert.equal(d.item.status,'COMPLETED');assert.equal(d.item.progress,100);assert.ok(d.item.valid_until);await assert.rejects(()=>a.attendance(root,session,[{assignment_id:assignment,status:'ABSENT'}]),{status:409});await assert.rejects(()=>db.query("UPDATE training_assignments SET status='ASSIGNED',completed_at=NULL WHERE id=$1",[assignment]));});
await t.test('certificate retains issue/expiry and private download',async()=>{const r=await a.addCertificate(root,assignment,{kind:'CERTIFICATE',issued_on:'2026-01-01',valid_until:'2027-01-01',reference:'CERT-1',file:{name:'cert.pdf',mime:'application/pdf',data:Buffer.from('%PDF-test').toString('base64')}});assert.equal((await a.certificate(emp,r.id)).name,'cert.pdf');await assert.rejects(()=>a.certificate(other,r.id),{status:403});await assert.rejects(()=>db.query('DELETE FROM training_certificates'));});
await t.test('development plan scope and real training progress',async()=>{plan=(await a.savePlan(manager,{user_id:emp.id,title:'2027 Gelişim',period:'2027',goals:'Learn',notes:'',assignment_ids:[assignment]})).id;assert.equal((await a.plans(emp))[0].completed,1);assert.equal((await a.plans(other)).length,0);await assert.rejects(()=>a.savePlan(manager,{user_id:other.id,title:'Not allowed',period:'2027',assignment_ids:[]}),{status:403});await a.savePlan(manager,{user_id:emp.id,title:'Updated plan',period:'2027',goals:'Updated',notes:'',assignment_ids:[assignment]},plan);});
const step=(title:string,kind='INFO',reference_id:string|null=null)=>({title,description:'',stage:'DAY',kind,reference_id,reference_kind:null,url:'',responsible_id:null});
await t.test('group company department templates combine; training reused; buddy retained',async()=>{const ts=[];for(const [layer,target_id] of [['GROUP',null],['COMPANY',company],['DEPARTMENT',department]])ts.push((await o.saveTemplate(root,{title:String(layer),layer,target_id,steps:[layer==='GROUP'?step('Training','TRAINING',course):step(String(layer))],active:true})).id);orientation=(await o.startOrientation(root,{user_id:emp.id,title:'Welcome',starts_on:'2026-01-01',buddy_id:other.id,template_ids:ts})).id;const d=await o.orientationDetail(emp,orientation);assert.equal(d.rows.length,3);assert.equal(d.progress,33);assert.equal(d.item.buddy_id,other.id);assert.equal((await a.assignments(emp)).total,1);await assert.rejects(()=>o.orientationDetail(other,orientation),{status:403});});
await t.test('manager task scope; linked steps cannot be manually completed',async()=>{await o.managerTask(manager,orientation,{title:'CRM',description:'Learn CRM',stage:'WEEK',due_date:'2027-01-01',responsible_id:other.id});await assert.rejects(()=>o.managerTask(other,orientation,{title:'Attack',stage:'DAY',due_date:'2027-01-01',responsible_id:null}),{status:403});const d=await o.orientationDetail(emp,orientation);await assert.rejects(()=>o.completeStep(emp,d.rows.find(s=>s.kind==='TRAINING')!.id),{status:409});for(const s of d.rows.filter(s=>s.kind!=='TRAINING'))await o.completeStep(emp,s.id);const complete=await o.orientationDetail(emp,orientation);assert.equal(complete.progress,100);assert.equal(complete.item.status,'COMPLETED');assert.ok(complete.item.completed_at);assert.equal((await myArea(emp)).find(x=>x.label==='Oryantasyon Adımları')?.count,0);});
await t.test('new training cycle preserves old completion and exam attempts',async()=>{const old=(await a.learningDetail(emp,assignment)).item.completed_at;const next=await a.assignAcademy(root,{course_id:course,starts_on:'2020-01-01',due_date:'2028-01-01',audience_all:false,targets:[{type:'user_id',id:emp.id}]});assert.equal(next.count,1);assert.equal((await a.assignments(emp)).total,2);assert.equal((await a.learningDetail(emp,assignment)).item.completed_at,old);assert.equal((await a.learningDetail(emp,assignment)).attempts.length,1);});
await t.test('provider foundation disabled, reports aggregate and migrations repeat safely',async()=>{assert.equal(learningProvider.launch({type:'SCORM',url:'https://example.test',externalId:'a',packageReference:'a'}).status,'NOT_CONFIGURED');const r=await a.academyReports(root);assert.ok(Number(r.summary.Atanan)>=3);await assert.rejects(()=>a.academyReports(emp),{status:403});await pg.exec(await readFile('db/017_academy.sql','utf8'));});
await t.test('current acknowledgement revision and assignment acceptance drive orientation',async()=>{
const content=randomUUID(),asset=randomUUID(),assigned=randomUUID(),category=randomUUID();
await db.query("INSERT INTO announcements(id,title,slug,author_id,status,acknowledgement_required) VALUES($1,'Policy','academy-policy',$2,'PUBLISHED',true)",[content,root.id]);
await db.query("INSERT INTO inventory_categories(id,name,code) VALUES($1,'Academy devices','ACDEV')",[category]);
await db.query("BEGIN");
await db.query("INSERT INTO inventory_items(id,asset_number,category_id,company_id,location_id) VALUES($1,'AC-1',$2,$3,$4)",[asset,category,company,location]);
await db.query("INSERT INTO asset_assignments(id,inventory_id,user_id,assigned_at,delivered_by) VALUES($1,$2,$3,current_date,$4)",[assigned,asset,other.id,root.id]);
await db.query("UPDATE inventory_items SET status='ASSIGNED' WHERE id=$1",[asset]);await db.query('COMMIT');
const template=await o.saveTemplate(root,{title:'Linked steps',layer:'GROUP',target_id:null,active:true,steps:[{...step('Policy','ACK',content),reference_kind:'announcements'},step('Accept equipment','ASSET',assigned)]});
const result=await o.startOrientation(root,{user_id:other.id,title:'Linked orientation',starts_on:'2026-01-01',buddy_id:null,template_ids:[template.id]});
assert.equal((await o.orientationDetail(other,result.id)).progress,0);
await db.query("INSERT INTO content_acknowledgements(kind,content_id,revision,user_id) VALUES('announcements',$1,1,$2)",[content,other.id]);
assert.equal((await o.orientationDetail(other,result.id)).progress,50);
await db.query("UPDATE announcements SET body='Updated policy' WHERE id=$1",[content]);
assert.equal((await o.orientationDetail(other,result.id)).progress,0);
await db.query("INSERT INTO content_acknowledgements(kind,content_id,revision,user_id) VALUES('announcements',$1,2,$2)",[content,other.id]);
await db.query("INSERT INTO assignment_acceptances(id,assignment_id,user_id,phase) VALUES($1,$2,$3,'DELIVERY')",[randomUUID(),assigned,other.id]);
assert.equal((await o.orientationDetail(other,result.id)).progress,100);
});
await t.test('failed exam cannot reset attempts by self enrollment',async()=>{
const c=await a.saveCourse(root,{...payload,title:'Exam only',method:'ONLINE_SELF_PACED',requirements:{content:false,exam:true,attendance:false},attempt_limit:1});
const assigned=await a.enroll(other,c.id);
assert.equal((await a.takeExam(other,assigned.id,{q1:[0],q2:[1]})).completed,false);
assert.equal((await a.learningDetail(other,assigned.id)).item.status,'FAILED');
await assert.rejects(()=>a.takeExam(other,assigned.id,{q1:[1],q2:[0,2]}),{status:409});
await assert.rejects(()=>a.enroll(other,c.id),{status:409});
});
await t.test('face to face attendance completes only after authorized recording',async()=>{
const c=await a.saveCourse(root,{...payload,title:'Onsite',method:'FACE_TO_FACE',requirements:{content:false,exam:false,attendance:true},exam:[]});
const assigned=await a.enroll(other,c.id);
const session=await a.saveSession(root,{course_id:c.id,title:'Onsite',start_at:'2020-01-02T08:00:00Z',end_at:'2020-01-02T09:00:00Z',instructor:'Teacher',platform:'',meeting_url:'',location_id:location,venue:'Room',capacity:2,assignment_ids:[assigned.id]});
await a.attendance(root,session.id,[{assignment_id:assigned.id,status:'ABSENT'}]);
assert.notEqual((await a.learningDetail(other,assigned.id)).item.status,'COMPLETED');
await a.attendance(root,session.id,[{assignment_id:assigned.id,status:'ATTENDED'}]);
assert.equal((await a.learningDetail(other,assigned.id)).item.status,'COMPLETED');
});
await t.test('unconfigured SCORM cannot be manually completed and future start enforced',async()=>{
const c=await a.saveCourse(root,{...payload,title:'SCORM',method:'ONLINE_SELF_PACED',content_type:'SCORM',requirements:{content:true,exam:false,attendance:false},exam:[]});
const assigned=await a.enroll(other,c.id);
await assert.rejects(()=>a.completeContent(other,assigned.id),{status:409});
const future=await a.saveCourse(root,{...payload,title:'Future',method:'ONLINE_SELF_PACED',requirements:{content:true,exam:false,attendance:false},exam:[]});
await a.assignAcademy(root,{course_id:future.id,starts_on:'2099-01-01',due_date:'2099-01-30',audience_all:false,targets:[{type:'user_id',id:other.id}]});
const id=(await db.query<{id:string}>('SELECT id FROM training_assignments WHERE course_id=$1 AND user_id=$2',[future.id,other.id])).rows[0].id;
await assert.rejects(()=>a.completeContent(other,id),{status:409});
assert.ok((await a.assignments(other,new URLSearchParams({status:'COMPLETED'}))).rows.every(r=>r.status==='COMPLETED'));
});
await t.test('explicit permission deny blocks manager assignment and own learning',async()=>{await db.query("INSERT INTO user_permission_overrides VALUES($1,'academy.training.assign_team',false)",[manager.id]);const denied=(await identityFor(db,manager.id))!;await assert.rejects(()=>a.assignAcademy(denied,{course_id:course,starts_on:'2020-01-01',due_date:'2027-01-01',audience_all:false,targets:[{type:'user_id',id:emp.id}]}),{status:403});});
await pg.close();});
