import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import {PGlite} from '@electric-sql/pglite';
import {injectTestDB} from '../lib/db';
import {seed} from '../lib/seed';
import {identityFor} from '../lib/auth-core';
import * as f from '../lib/fleet';
test('Phase 2A-14 fleet lifecycle and security',async t=>{
Object.assign(process.env,{NODE_ENV:'test'});const pg=new PGlite(),db={query:async<T>(sql:string,v?:unknown[])=>({rows:(await pg.query(sql,v)).rows as T[]})};injectTestDB(db);for(const name of ['001_phase2.sql','005_workflows.sql','014_fleet.sql'])await pg.exec(await readFile('db/'+name,'utf8'));await seed(db);
const company=randomUUID(),location=randomUUID();await db.query("INSERT INTO companies(id,name,code) VALUES($1,'Company','CO')",[company]);await db.query("INSERT INTO locations(id,name,code,company_id) VALUES($1,'Location','LOC',$2)",[location,company]);const ids=[randomUUID(),randomUUID()];for(let i=0;i<2;i++){await db.query("INSERT INTO users(id,personnel_no,first_name,last_name,email,username,must_change_password) VALUES($1,$2,'Fleet','Person',$3,$2,false)",[ids[i],'fleet'+i,'fleet'+i+'@example.test']);await db.query('INSERT INTO user_roles VALUES($1,$2)',[ids[i],i===0?'SUPER_ADMIN':'EMPLOYEE']);}const root=(await identityFor(db,ids[0]))!,emp=(await identityFor(db,ids[1]))!;let vehicle='';const data={plate:'34 ABC 123',brand:'Test',model:'Car',model_year:2026,vin:null,fuel:'Benzin',km:100,company_id:company,location_id:location,status:'POOL',registration:'Ruhsat',insurance_end:'2026-10-10',casco_end:null,inspection_date:null,last_service_date:null,next_service_date:null,next_service_km:null,tires:'Yaz',hgs_reference:'ref',notes:''};
await t.test('create and scoped list require admin permissions',async()=>{await assert.rejects(()=>f.saveVehicle(emp,data),{status:403});vehicle=(await f.saveVehicle(root,data)).id;assert.equal((await f.fleetList(root)).total,1);await assert.rejects(()=>f.fleetList(emp),{status:403});assert.equal((await f.fleetDetail(root,vehicle)).item.plate,'34ABC123');});
await t.test('allocation prevents duplicate and reverse kilometre',async()=>{await assert.rejects(()=>f.allocateVehicle(root,vehicle,{user_id:emp.id,start_km:99}),{status:400});await f.allocateVehicle(root,vehicle,{user_id:emp.id,start_km:100});await assert.rejects(()=>f.allocateVehicle(root,vehicle,{user_id:root.id,start_km:101}),{status:409});await assert.rejects(()=>db.query('INSERT INTO fleet_allocations(id,vehicle_id,user_id,assigned_by,start_km) VALUES($1,$2,$3,$3,100)',[randomUUID(),vehicle,emp.id]),{code:'23505'});});
await t.test('assigned status cannot be overridden directly',async()=>{await assert.rejects(()=>f.saveVehicle(root,{...data,km:100},vehicle),{status:409});await assert.rejects(()=>db.query("UPDATE fleet_vehicles SET status='POOL' WHERE id=$1",[vehicle]),{code:'23514'});});
await t.test('return preserves historical allocation',async()=>{await assert.rejects(()=>f.returnVehicle(root,vehicle,{end_km:90}),{status:400});await f.returnVehicle(root,vehicle,{end_km:110,status:'POOL'});await f.allocateVehicle(root,vehicle,{user_id:root.id,start_km:110});assert.equal((await f.fleetDetail(root,vehicle)).allocations.length,2);await assert.rejects(()=>db.query('DELETE FROM fleet_allocations'),{code:'23514'});});
await t.test('documents require independent permission and append-only service',async()=>{const file={name:'reg.pdf',mime:'application/pdf',data:Buffer.from('%PDF-test').toString('base64')};const saved=await f.fleetFileSave(root,vehicle,{kind:'DOCUMENT',file});await assert.rejects(()=>f.fleetFile(emp,saved.id),{status:403});const restricted={...root,roles:['ADMIN'],permissions:['admin.view','fleet.view']};await assert.rejects(()=>f.fleetFile(restricted,saved.id),{status:403});assert.equal((await f.fleetDetail(restricted,vehicle)).item.registration,'');await f.fleetService(root,vehicle,{kind:'MAINTENANCE',date:'2026-01-01',km:120,provider:'Servis',description:'Bakım',cost:100,document:null,next_service_date:'2027-01-01',next_service_km:10000});assert.equal((await f.fleetDetail(root,vehicle)).service.length,1);await assert.rejects(()=>db.query('DELETE FROM fleet_service_history'),{code:'23514'});});
await t.test('inactive vehicle is not assignable and migration repeatable',async()=>{await f.returnVehicle(root,vehicle,{end_km:120,status:'INACTIVE'});await assert.rejects(()=>f.allocateVehicle(root,vehicle,{user_id:emp.id,start_km:120}),{status:409});await pg.exec(await readFile('db/014_fleet.sql','utf8'));});
await pg.close();});
