import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
import {injectTestDB} from '../lib/db';
import {bootstrap} from '../lib/seed';
import {login,changePassword,sessionIdentity,logout,identityFor} from '../lib/auth-core';
import {saveUser,saveOrg,saveRole,userAction,adminRead} from '../lib/admin';
import {assertOrigin,digest} from '../lib/security';
import {can} from '../lib/permissions';
test('Phase 2A-1 PostgreSQL integration',async t=>{
 Object.assign(process.env,{NODE_ENV:'test'});const pg=new PGlite();await pg.exec(await readFile('db/001_phase2.sql','utf8'));const db={query:async(text:string,values?:unknown[])=>pg.query<any>(text,values)};injectTestDB(db);
 const rootId=await bootstrap('root@example.test','root','Root-test-923!');let root=(await identityFor(db,rootId))!;let employeeId='',companyId='',departmentId='',token='';
 const payload={personnel_no:'P001',first_name:'Test',last_name:'Person',email:'person@example.test',username:'person',status:'ACTIVE',role_ids:['EMPLOYEE'],overrides:{},temporary_password:'Temp-test-923!'};
 await t.test('bootstrap forces change and stores salted hash',async()=>{assert.equal(root.must_change_password,true);const r=await db.query('SELECT password_hash FROM credentials');assert.match(r.rows[0].password_hash,/^scrypt\$/);});
 await t.test('username login and hashed session',async()=>{const s=await login('root','Root-test-923!',false,'1');token=s.token;assert.equal((await sessionIdentity(token))?.id,rootId);assert.equal((await db.query('SELECT token_hash FROM sessions')).rows[0].token_hash,digest(token));});
 await t.test('forced change blocks admin writes',async()=>{await assert.rejects(()=>saveOrg(root,'companies',{name:'Test',code:'T',active:true}),{status:401});});
 await t.test('password change revokes old session',async()=>{const old=token;token=await changePassword(rootId,'Root-test-923!','New-root-923!');assert.equal(await sessionIdentity(old),null);root=(await sessionIdentity(token))!;assert.equal(root.must_change_password,false);});
 await t.test('wrong password rejected',async()=>{await assert.rejects(()=>login('root','incorrect',false,'1'),{status:401});});
 await t.test('email and remember login',async()=>{const s=await login('ROOT@example.test','New-root-923!',true,'1');assert.equal(s.seconds,2592000);});
 await t.test('company and department create',async()=>{companyId=(await saveOrg(root,'companies',{name:'Test Co',code:'TC',active:true})).id;departmentId=(await saveOrg(root,'departments',{name:'IT',code:'IT',company_id:companyId,active:true})).id;});
 await t.test('create employee',async()=>{employeeId=(await saveUser(root,{...payload,company_id:companyId,department_id:departmentId,manager_user_id:rootId})).id;assert.equal((await identityFor(db,employeeId))?.must_change_password,true);});
 for(const field of ['username','email','personnel_no'])await t.test('unique '+field,async()=>{await assert.rejects(()=>saveUser(root,{...payload,username:'other',email:'other@example.test',personnel_no:'P002',[field]:payload[field as keyof typeof payload]}),(e:any)=>e.code==='23505');});
 await t.test('employee cannot read admin',async()=>{const actor=(await identityFor(db,employeeId))!;await assert.rejects(()=>adminRead(actor,'users',new URL('https://portal.test/api/admin/users')),{status:403});});
 await t.test('employee cannot escalate own role',async()=>{await changePassword(employeeId,'Temp-test-923!','Employee-923!');const actor=(await identityFor(db,employeeId))!;await assert.rejects(()=>saveUser(actor,{...payload,role_ids:['SUPER_ADMIN']},employeeId),{status:403});});
 await t.test('manager self-cycle rejected',async()=>{await assert.rejects(()=>saveUser(root,{...payload,manager_user_id:employeeId},employeeId),{status:400});});
 await t.test('department cycle rejected',async()=>{await assert.rejects(()=>saveOrg(root,'departments',{name:'IT',code:'IT',company_id:companyId,parent_id:departmentId,active:true},departmentId),{status:400});});
 await t.test('permission override applied and session revoked',async()=>{const s=await login('person','Employee-923!',false,'2');await saveUser(root,{...payload,overrides:{'portal.documents.view':false}},employeeId);assert.equal(await sessionIdentity(s.token),null);assert.equal(can((await identityFor(db,employeeId))!,'portal.documents.view'),false);});
 await t.test('disable revokes login and sessions',async()=>{const s=await login('person','Employee-923!',false,'2');await userAction(root,employeeId,'status',{status:'INACTIVE'});assert.equal(await sessionIdentity(s.token),null);await assert.rejects(()=>login('person','Employee-923!',false,'2'),{status:401});});
 await t.test('reactivate and password reset',async()=>{await userAction(root,employeeId,'status',{status:'ACTIVE'});const reset=await userAction(root,employeeId,'reset-password',{});assert.ok('temporaryPassword' in reset);const s=await login('person',reset.temporaryPassword!,false,'2');assert.equal(s.actor.must_change_password,true);});
 await t.test('last super cannot deactivate self',async()=>{await assert.rejects(()=>userAction(root,rootId,'status',{status:'INACTIVE'}),{status:400});});
 await t.test('custom role persistence',async()=>{await saveRole(root,{id:'AUDITOR',name:'Auditor',active:true,permissions:['portal.home.view']});assert.equal((await db.query("SELECT permission_id FROM role_permissions WHERE role_id='AUDITOR'")).rows.length,1);});
 await t.test('lookup snapshot preserves arrays, relations and access checks',async()=>{
  const opts=await adminRead(root,'options',new URL('https://portal.test/api/admin/options')) as any;
  for(const key of ['companies','locations','departments','units','job-titles','managers','employeeTypes','roles','rolePermissions'])assert.ok(Array.isArray(opts[key]),key);
  assert.equal(opts.departments.find((r:any)=>r.id===departmentId).company_id,companyId);
  assert.ok(opts.roles.some((r:any)=>r.id==='SUPER_ADMIN'));
  const employee=(await identityFor(db,employeeId))!;await assert.rejects(()=>adminRead(employee,'options',new URL('https://portal.test')),{status:403});
 });
 await t.test('fresh session snapshot enforces role changes, overrides and expiry',async()=>{
  const {newToken}=await import('../lib/security');const fresh=newToken();
  await db.query("INSERT INTO sessions(token_hash,user_id,expires_at) VALUES($1,$2,now()+interval '1 hour')",[digest(fresh),employeeId]);
  await db.query("INSERT INTO user_roles VALUES($1,'AUDITOR')",[employeeId]);
  await db.query("INSERT INTO role_permissions VALUES('AUDITOR','users.view')");
  assert.equal(can((await sessionIdentity(fresh))!,'users.view'),true);
  await db.query("UPDATE roles SET active=false WHERE id='AUDITOR'");
  assert.equal(can((await sessionIdentity(fresh))!,'users.view'),false);
  await db.query("INSERT INTO user_permission_overrides VALUES($1,'users.view',true)",[employeeId]);
  assert.equal(can((await sessionIdentity(fresh))!,'users.view'),true);
  await db.query("UPDATE user_permission_overrides SET allowed=false WHERE user_id=$1 AND permission_id='users.view'",[employeeId]);
  assert.equal(can((await sessionIdentity(fresh))!,'users.view'),false);
  await db.query("UPDATE users SET status='INACTIVE' WHERE id=$1",[employeeId]);assert.equal(await sessionIdentity(fresh),null);
  await db.query("UPDATE users SET status='ACTIVE' WHERE id=$1",[employeeId]);
  await db.query("UPDATE sessions SET expires_at=now()-interval '1 second' WHERE token_hash=$1",[digest(fresh)]);assert.equal(await sessionIdentity(fresh),null);
 });
 await t.test('logout invalidates token',async()=>{await logout(token);assert.equal(await sessionIdentity(token),null);});
 await t.test('CSRF rejects foreign or absent origins',()=>{for(const origin of ['', 'https://evil.test'])assert.throws(()=>assertOrigin(new Request('https://portal.test/api/auth/login',{headers:{origin,'content-type':'application/json'}})),{status:403});});
 await t.test('audit excludes credentials',async()=>{const rows=(await db.query('SELECT * FROM audit_logs')).rows;assert.ok(rows.length>4);assert.ok(!JSON.stringify(rows).includes('923!'));});
 await t.test('account rate limiting',async()=>{for(let i=0;i<10;i++)try{await login('absent','invalid',false,'3');}catch{}await assert.rejects(()=>login('absent','invalid',false,'3'),{status:429});});
 await pg.close();
});
