import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import {PGlite} from '@electric-sql/pglite';
import {pg_trgm} from '@electric-sql/pglite/contrib/pg_trgm';
import {injectTestDB} from '../lib/db';
import {seed} from '../lib/seed';
import {identityFor} from '../lib/auth-core';
import * as w from '../lib/workflows';
import * as tasks from '../lib/tickets';
import {slaDue,slaState} from '../lib/ticket-shared';
test('Phase 2A-11 ticket tasks routing and SLA',async t=>{
 Object.assign(process.env,{NODE_ENV:'test'});const pg=new PGlite({extensions:{pg_trgm}});const db={query:async(s:string,v?:unknown[])=>pg.query<any>(s,v)};injectTestDB(db);for(const f of ['001_phase2.sql','003_content.sql','005_workflows.sql','006_engagement.sql','008_directory.sql','009_brand_center.sql','010_notification_v2.sql','011_ticket_v2.sql'])await pg.exec(await readFile('db/'+f,'utf8'));await seed(db);
 const company=randomUUID(),department=randomUUID(),department2=randomUUID();await db.query("INSERT INTO companies(id,name,code) VALUES($1,'Test','TEST')",[company]);for(const d of [department,department2])await db.query('INSERT INTO departments(id,name,code,company_id) VALUES($1,$2,$2,$3)',[d,d,company]);
 const ids={root:randomUUID(),emp:randomUUID(),other:randomUUID(),it:randomUUID()};for(const [name,id] of Object.entries(ids)){await db.query("INSERT INTO users(id,personnel_no,first_name,last_name,email,username,department_id,must_change_password) VALUES($1,$2,$2,'Test',$3,$2,$4,false)",[id,name,name+'@example.test',name==='it'?department2:department]);await db.query('INSERT INTO user_roles VALUES($1,$2)',[id,name==='root'?'SUPER_ADMIN':name==='it'?'IT_ADMIN':'EMPLOYEE']);}
 const root=(await identityFor(db,ids.root))!,emp=(await identityFor(db,ids.emp))!,other=(await identityFor(db,ids.other))!,it=(await identityFor(db,ids.it))!;
 const type=(await w.saveType(root,'request-types',{name:'Hardware',code:'TEST_HARDWARE',active:true,department_id:department,manager_approval:false,description_required:false,attachments_allowed:false,priority_allowed:true,sla_policy:{NORMAL:{amount:2,unit:'BUSINESS_DAYS'},URGENT:{amount:2,unit:'HOURS'}}})).id;let ticket='',task='';
 await t.test('repeatable migration and employee task defaults',async()=>{await pg.exec(await readFile('db/011_ticket_v2.sql','utf8'));assert.ok(emp.permissions.includes('tasks.view_own'));});
 await t.test('need date validates independently from priority',async()=>{await assert.rejects(()=>w.createRequest(emp,{type_id:type,subject:'Laptop',need_when:'DATE'}),{status:400});ticket=(await w.createRequest(emp,{type_id:type,subject:'Laptop',need_when:'DATE',needed_on:'2027-01-01',priority:'NORMAL'})).id;const r=(await w.detail(emp,'requests',ticket)).item;assert.equal(r.needed_on,'2027-01-01');assert.equal(r.priority,'NORMAL');assert.ok(r.sla_due_at);});
 await t.test('department scope prevents unrelated staff management',async()=>{await assert.rejects(()=>w.updateRequest(it,ticket,{status:'ACCEPTED'}),{status:404});await assert.rejects(()=>w.updateRequest(emp,ticket,{status:'ACCEPTED'}),{status:403});});
 await t.test('acceptance records actor time and notification outbox',async()=>{await w.updateRequest(root,ticket,{status:'ACCEPTED'});const r=(await w.detail(root,'requests',ticket,true)).item;assert.equal(r.accepted_by,root.id);assert.ok(r.accepted_at);assert.equal((await db.query("SELECT id FROM email_outbox WHERE event_type='request.accepted' AND recipient_id=$1",[emp.id])).rows.length,1);});
 await t.test('changing deadline preserves old and new timeline',async()=>{for(const deadline of ['2027-01-02T10:00:00Z','2027-01-03T10:00:00Z'])await w.updateRequest(root,ticket,{deadline});const h=(await w.detail(emp,'requests',ticket)).history.filter((h:any)=>h.event==='request.deadline');assert.equal(h.length,2);assert.match(h[1].note,/2027-01-02/);assert.match(h[1].note,/2027-01-03/);});
 await t.test('task assignment is parent scoped and own list excludes another employee',async()=>{task=(await tasks.saveTask(root,ticket,{title:'Prepare laptop',assignee_id:other.id})).id;assert.equal((await tasks.myTasks(emp)).total,0);assert.equal((await tasks.myTasks(other)).total,1);assert.equal((await db.query("SELECT id FROM workflow_notifications WHERE recipient_id=$1 AND event='task.assigned' AND link='/tasks'",[other.id])).rows.length,1);await assert.rejects(()=>tasks.ticketTasks(other,ticket),{status:404});await assert.rejects(()=>tasks.updateOwnTask(emp,task,{status:'DONE'}),{status:404});});
 await t.test('open task blocks completion and completion finality is enforced',async()=>{await w.updateRequest(root,ticket,{status:'IN_PROGRESS'});await assert.rejects(()=>w.updateRequest(root,ticket,{status:'COMPLETED'}),{status:409});await tasks.updateOwnTask(other,task,{status:'DONE'});await assert.rejects(()=>tasks.updateOwnTask(other,task,{status:'DONE'}),{status:409});await w.updateRequest(root,ticket,{status:'COMPLETED'});await assert.rejects(()=>db.query("UPDATE requests SET status='REJECTED' WHERE id=$1",[ticket]));assert.ok((await w.detail(emp,'requests',ticket)).item.completed_at);});
 await t.test('SLA business days exclude weekend and hours are exact',()=>{const friday=new Date('2026-10-02T10:00:00Z');assert.equal(slaDue(friday,{amount:2,unit:'BUSINESS_DAYS'}),'2026-10-06T10:00:00.000Z');assert.equal(slaDue(friday,{amount:2,unit:'HOURS'}),'2026-10-02T12:00:00.000Z');assert.equal(slaState(friday.toISOString(),'2026-10-02T12:00:00Z','IN_PROGRESS',null,+friday+110*60000),'SLA Yaklaşıyor');assert.equal(slaState(friday.toISOString(),'2026-10-02T12:00:00Z','IN_PROGRESS',null,+friday+121*60000),'SLA Aşıldı');});
 await t.test('permission override revocation is checked fresh for task writes',async()=>{await db.query("INSERT INTO user_permission_overrides(user_id,permission_id,allowed) VALUES($1,'tasks.update_own',false)",[other.id]);await assert.rejects(()=>tasks.updateOwnTask(other,task,{status:'DONE'}),{status:403});});
 await pg.close();
});
