import {PlanEditor} from './AcademyPanel';
import Link from 'next/link';
import {Assignment,Course,methods,obligations} from '@/lib/academy-shared';
import {Plan} from '@/lib/academy';
export const learningStatus:Record<string,string>={ASSIGNED:'Başlanmadı',IN_PROGRESS:'Devam Ediyor',COMPLETED:'Tamamlandı',FAILED:'Başarısız',CANCELLED:'İptal'};
export function AssignmentCards({rows}:{rows:Assignment[]}){return <>{rows.map(r=><section className="a-card" key={r.id}><h2><Link href={'/academy/learning/'+r.id}>{r.title}</Link></h2>{r.employee&&<p>{r.employee}</p>}<p>{obligations[r.obligation]} · {learningStatus[r.status]??r.status} · Son Tarih: {r.due_date}</p><progress max={100} value={r.progress} aria-label="Eğitim ilerlemesi"/> %{r.progress}{r.score!==null&&<p>Sınav: {r.score}</p>}{r.valid_until&&<p>Geçerlilik: {r.valid_until}</p>}</section>)}{!rows.length&&<p className="a-card">Henüz eğitim ataması bulunmuyor.</p>}</>;}
export function CourseCards({rows,admin=false}:{rows:Course[];admin?:boolean}){return <div className="form-grid">{rows.map(c=><section className="a-card" key={c.id}>{c.cover&&<img src={c.cover} alt="" loading="lazy" width={240} height={130} style={{maxWidth:'100%',objectFit:'cover'}}/>}<h2><Link href={(admin?'/admin/academy/courses/':'/academy/course/')+c.id}>{c.title}</Link></h2><p>{c.category} · {methods[c.method]}</p><p>{obligations[c.obligation]} · {c.duration_minutes} dakika</p><p>{c.description.slice(0,160)}</p></section>)}{!rows.length&&<p>Bu filtrede eğitim bulunmuyor.</p>}</div>;}
export function PlanCards({rows,edit}:{rows:Plan[];edit?:{users:{id:string;name:string}[];assignments:{id:string;name:string;user_id:string}[]}}){return <>{rows.map(p=><section className="a-card" key={p.id}><h2>{p.title}</h2><p>{p.employee} · {p.period}</p><p>{p.goals}</p><progress max={Math.max(1,p.total)} value={p.completed}/><p>{p.completed} / {p.total} eğitim tamamlandı</p>{p.items.map(t=><p key={t.id}><Link href={'/academy/learning/'+t.id}>{t.title}</Link> · {learningStatus[t.status]}</p>)}<p>{p.notes}</p>{edit&&<details><summary>Planı Düzenle</summary><PlanEditor {...edit} plan={p}/></details>}</section>)}{!rows.length&&<p className="a-card">Henüz gelişim planı bulunmuyor.</p>}</>;}
export function Pages({page,total,path,query}:{page:number;total?:number;path:string;query?:URLSearchParams}){return <nav className="a-actions"><span>Sayfa {page}{total!==undefined?' · '+total+' kayıt':''}</span>{[page-1,page+1].filter(n=>n>=1&&(total===undefined||n<=Math.ceil(total/20))).map(n=>{const q=new URLSearchParams(query);q.set('page',String(n));return <Link className="a-button" key={n} href={path+'?'+q}>{n<page?'Önceki':'Sonraki'}</Link>;})}</nav>;}
