'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {Identity,can} from '@/lib/permissions';
import {Choice,Course,TrainingAssignment,TrainingSession} from '@/lib/people-shared';
const labels:Record<string,string>={LEGAL_MANDATORY:'Yasal Zorunlu',COMPANY_MANDATORY:'Şirket Zorunlu',MANAGER_ASSIGNED:'Yönetici Ataması',OPTIONAL:'İsteğe Bağlı',SELF_PACED:'Online Self-Paced',LIVE_ONLINE:'Canlı Online',FACE_TO_FACE:'Yüz Yüze',HYBRID:'Hibrit'};
async function post(path:string,body:unknown={}){const r=await fetch('/api/academy/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error??'İşlem tamamlanamadı.');return d;}
export default function AcademyPortal({courses,assignments,sessions,targets,actor}:{courses:Course[];assignments:TrainingAssignment[];sessions:TrainingSession[];targets:Choice[];actor:Identity}){const router=useRouter(),[error,setError]=useState(''),[message,setMessage]=useState(''),[answers,setAnswers]=useState<Record<string,number[]>>({}),[busy,setBusy]=useState('');const assigned=new Set(assignments.map(a=>a.course_id));const canAssign=can(actor,'training.manage')||can(actor,'academy.assign_direct');async function run(key:string,fn:()=>Promise<unknown>){setBusy(key);setError('');setMessage('');try{await fn();setMessage('Kaydedildi.');router.refresh();}catch(e){setError((e as Error).message);}finally{setBusy('');}}
return <main className="admin-content academy-page" style={{maxWidth:1200,margin:'auto'}}><nav className="a-actions"><a className="a-button" href="/">Çalışan Portalı</a><a className="a-button" href="/orientation">Oryantasyon</a></nav><header className="academy-hero"><span className="eyebrow">KOYUNCU GRUP GELİŞİM AKADEMİSİ</span><h1>Koyuncu Akademi</h1><p>Türkçe ağırlıklı şirket eğitimleri, zorunlu gelişim adımları ve sertifikalarınız tek yerde.</p></header>{error&&<p role="alert" className="form-error">{error}</p>}{message&&<p role="status" className="a-card">{message}</p>}
{canAssign&&<details className="a-card"><summary>Doğrudan raporunuza eğitim atayın</summary><form className="form-grid" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run('assign',()=>post('assign',{course_id:f.get('course_id'),user_id:f.get('user_id'),due_date:f.get('due_date')}));}}><label className="a-field">Eğitim<select name="course_id" required>{courses.filter(c=>c.active).map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label><label className="a-field">Çalışan<select name="user_id" required><option value="">Çalışan seçin</option>{targets.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label><label className="a-field">Son tarih<input name="due_date" type="date" required/></label><button className="a-primary" disabled={!!busy}>Eğitim Ata</button></form></details>}
<section><h2>Eğitim Kataloğu</h2><div className="content-cards">{courses.map(c=><article className="a-card academy-course" key={c.id}><div className="a-actions"><span className="a-status">{labels[c.requirement_type]??c.requirement_type}</span><span className="a-status">{labels[c.delivery_mode]??c.delivery_mode}</span></div><h3>{c.title}</h3><p>{c.category} · {c.language_code==='tr'?'Türkçe':c.language_code==='en'?'İngilizce':'Diğer dil'}{c.duration_minutes?` · ${c.duration_minutes} dk`:''}</p><p>{c.description}</p>{c.content&&<details><summary>Eğitim içeriği</summary><div className="content-body">{c.content}</div></details>}{c.assessment?.length>0&&<details><summary>Ölçme ve değerlendirme · {c.assessment.length} soru</summary><form onSubmit={e=>{e.preventDefault();const selected=answers[c.id]??[];void run('exam:'+c.id,()=>post('assessment/'+assignments.find(a=>a.course_id===c.id)!.id,{answers:selected}));}}>{c.assessment.map((q,index)=><fieldset key={index}><legend>{index+1}. {q.prompt}</legend>{q.options.map((option,j)=><label className="a-check" key={j}><input type="radio" name={`${c.id}-${index}`} required checked={(answers[c.id]??[])[index]===j} onChange={()=>setAnswers({...answers,[c.id]:Object.assign([...(answers[c.id]??[])],{[index]:j})})}/>{option}</label>)}</fieldset>)}{assigned.has(c.id)&&<button className="a-button" disabled={!!busy}>Sınavı Gönder</button>}</form></details>}{c.self_enrollment&&!assigned.has(c.id)&&<button className="a-primary" disabled={!!busy} onClick={()=>void run('enroll:'+c.id,()=>post('enroll/'+c.id))}>Kendim Kaydol</button>}{assigned.has(c.id)&&<p className="academy-hint">Bu eğitim atamalarımda görünüyor.</p>}</article>)}</div>{!courses.length&&<p className="a-card">Katalogda şu anda aktif eğitim yok.</p>}</section>
<section><h2>Eğitimlerim ve Sicilim</h2>{assignments.map(a=><article className="a-card academy-assignment" key={a.id}><h3>{a.title}</h3><p>{labels[a.requirement_type]??a.requirement_type} · {labels[a.delivery_mode]??a.delivery_mode} · {a.status==='COMPLETED'?'Tamamlandı':a.status==='IN_PROGRESS'?'Devam ediyor':a.status==='CANCELLED'?'İptal edildi':'Atandı'}</p><p>Son tarih: {a.due_date} · İlerleme: {a.progress}%{a.score!==null?` · Sınav puanı: ${a.score}%`:''}{a.valid_until?` · Belge geçerliliği: ${a.valid_until}`:''}</p>{a.has_certificate&&<a className="a-button" href={'/api/people/certificate/'+a.id}>Sertifika / eğitim belgesi indir</a>}{a.status!=='COMPLETED'&&a.status!=='CANCELLED'&&<div className="a-actions"><label className="a-field">İlerleme<select value={a.progress} onChange={e=>void run('progress:'+a.id,()=>post('progress/'+a.id,{progress:Number(e.target.value)}))}>{[0,25,50,75,100].map(n=><option key={n} value={n}>{n}%</option>)}</select></label><button className="a-primary" disabled={!!busy||a.progress<100} onClick={()=>void run('complete:'+a.id,()=>post('complete/'+a.id))}>Tamamlandı olarak işaretle</button></div>}</article>)}{!assignments.length&&<p className="a-card">Henüz atanmış eğitim yok.</p>}</section>
<section><h2>Eğitim Oturumları</h2>{sessions.map(s=><article className="a-card" key={s.id}><h3>{s.title}</h3><p>{s.course_title} · {labels[s.mode]??s.mode} · {new Date(s.starts_at).toLocaleString('tr-TR',{timeZone:'Europe/Istanbul'})}</p><p>{s.venue} · Katılım: {s.attendance_status==='PRESENT'?'Katıldı':s.attendance_status==='ABSENT'?'Katılmadı':s.attendance_status==='EXCUSED'?'Mazeretli':'Bekleniyor'}</p>{s.join_url&&new Date(s.ends_at)>new Date()&&<a className="a-primary" href={s.join_url} target="_blank" rel="noopener noreferrer">{labels[s.provider]??s.provider} oturumuna katıl</a>}</article>)}{!sessions.length&&<p className="a-card">Yakın tarihli canlı oturum bulunmuyor.</p>}</section></main>}
