'use client';
import WorkflowNav from './WorkflowNav';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import Image from 'next/image';
import {useRouter} from 'next/navigation';
import {Identity,can,canAction} from '@/lib/permissions';
import {ContentKind,contentNames,contentStatus,targetNames,contentDate,contentTime,homepageDefaults} from '@/lib/content-shared';
import InventoryNav from './InventoryNav';
import ContentNav from './ContentNav';
import ProfileMenu from './ProfileMenu';
type Row=Record<string,any>;
async function api(path:string,method='GET',body?:unknown){const response=await fetch('/api/content-admin/'+path,{method,cache:'no-store',...(body?{headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});const result=await response.json();if(!response.ok)throw Error(result.error||'İşlem tamamlanamadı.');return result;}
const local=(v:string)=>v?new Date(v).toLocaleString('sv-SE',{timeZone:'Europe/Istanbul'}).replace(' ','T').slice(0,16):'';
const iso=(v:string)=>v?new Date(v+':00+03:00').toISOString():null;
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="a-field"><span>{label}</span>{children}</label>}
const commonKeys=['title','slug','category_id','summary','body','cover','thumbnail','author_id','priority','publish_at','expires_at','audience_all','targets'];
const eventKeys=['event_start','event_end','venue','online','online_url','capacity','participation_required','rsvp_deadline'];
const docKeys=['version','file_name','file_type','file_data'];
const dateKeys=['publish_at','expires_at','event_start','event_end','rsvp_deadline'];
export default function ContentAdminPanel({actor,path,initial}:{actor:Identity;path:string[];initial:Row}){const router=useRouter(),section=path[0],kind=section as ContentKind,home=section==='homepage',isNew=path[1]==='new',id=!isNew?path[1]:undefined,editing=isNew||path[2]==='edit';const permit=(action:string)=>can(actor,section+'.'+action);
 const empty:Row={title:'',slug:'',summary:'',body:'',cover:null,thumbnail:null,category_id:'',author_id:actor.id,priority:0,publish_at:local(new Date().toISOString()),expires_at:'',audience_all:true,targets:[],event_start:'',event_end:'',venue:'',online:false,online_url:'',capacity:null,participation_required:true,rsvp_deadline:'',version:'1.0',file_name:'',file_type:'application/pdf'};
 const base=home?initial:initial.item?{...initial.item,targets:initial.targets,...Object.fromEntries(dateKeys.map(k=>[k,local(initial.item[k]??'')]))}:empty;
 const [data,setData]=useState(initial),[form,setForm]=useState<Row>(base),[options,setOptions]=useState<Row>({}),[ready,setReady]=useState(home),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[filters,setFilters]=useState<Row>({q:'',page:1,sort:'publish_at',dir:'desc'});const first=useRef(true),sequence=useRef(0);
 const set=(key:string,value:unknown)=>setForm(f=>({...f,[key]:value}));
 useEffect(()=>{if(home)return;let alive=true;api(section+'/options').then(v=>{if(alive){setOptions(v);setReady(true);}}).catch(e=>{if(alive)setError(e.message);});return ()=>{alive=false;};},[home,section]);
 async function load(){const seq=++sequence.current;setLoading(true);try{const query=new URLSearchParams(Object.entries(filters).filter(([,v])=>v!==''&&v!=null).map(([k,v])=>[k,String(v)]));const value=await api(section+(id?'/'+id:'?'+query));if(seq===sequence.current)setData(value);}catch(e){setError((e as Error).message);}finally{if(seq===sequence.current)setLoading(false);}}
 useEffect(()=>{if(home||id||editing)return;if(first.current){first.current=false;return;}const timer=setTimeout(()=>void load(),220);return ()=>clearTimeout(timer);},[filters]);
 async function run(fn:()=>Promise<any>){setBusy(true);setError('');setNotice('');try{const value=await fn();setNotice('İşlem kaydedildi.');return value;}catch(e){setError((e as Error).message);return null;}finally{setBusy(false);}}
 const input=(key:string,label:string,type='text',required=false,disabled=false)=><Field key={key} label={label}><input type={type} required={required} disabled={disabled} maxLength={500} value={form[key]??''} onChange={e=>set(key,e.target.value)}/></Field>;
 const check=(key:string,label:string)=><label className="permission-check"><input type="checkbox" checked={!!form[key]} onChange={e=>set(key,e.target.checked)}/>{label}</label>;
 const select=(key:string,label:string,rows:Row[],required=false)=><Field key={key} label={label}><select required={required} value={form[key]??''} onChange={e=>set(key,key==='priority'?Number(e.target.value):e.target.value)}><option value="">Seçin</option>{rows.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></Field>;
 const upload=(key:string,label:string,document=false)=><Field key={key} label={label+' (en fazla 200 KB)'}><input type="file" accept={document?'.pdf,.txt':'image/png,image/jpeg,image/webp'} onChange={e=>{const file=e.target.files?.[0];if(!file)return;const type=document&&file.name.toLowerCase().endsWith('.txt')?'text/plain':file.type;if(file.size>200000||!(document?['application/pdf','text/plain']:['image/png','image/jpeg','image/webp']).includes(type)){setError('Geçerli formatta, en fazla 200 KB dosya seçin.');return;}const reader=new FileReader();reader.onload=()=>{const result=String(reader.result);if(document)setForm(f=>({...f,file_name:file.name,file_type:type,file_data:result.split(',')[1]}));else set(key,result);};reader.readAsDataURL(file);}}/>{document?<small>{form.file_name||'PDF veya TXT dosyası seçin.'}</small>:form[key]&&<><img src={form[key]} alt={label} style={{width:180,height:100,objectFit:'cover'}}/><button type="button" className="a-link" onClick={()=>set(key,null)}>Görseli kaldır</button></>}</Field>;
 const filter=(key:string,label:string,rows:Row[])=><Field key={key} label={label}><select value={filters[key]??''} onChange={e=>setFilters({...filters,[key]:e.target.value,page:1})}><option value="">Tümü</option>{rows.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></Field>;
 async function save(publish=false){const result=await run(async()=>{if(home)return api('homepage','PATCH',form);const keys=[...commonKeys.filter(k=>kind!=='events'||k!=='category_id'),...(kind==='events'?eventKeys:kind==='documents'?docKeys:[])];const payload=Object.fromEntries(keys.filter(k=>form[k]!==undefined).map(k=>[k,dateKeys.includes(k)?iso(form[k]):form[k]]));const result=await api(section+(id?'/'+id:''),id?'PATCH':'POST',payload);if(publish)await api(section+'/'+result.id+'/publish','POST',{});return result;});if(result&&!home){router.push(permit('view')?'/admin/'+section+'/'+result.id:'/admin');router.refresh();}}
 const detail=data.item;
 return <div className="admin-shell"><aside className="admin-nav"><Link className="admin-brand" href="/admin"><Image src="/brand/koyuncu-grup.png" alt="Koyuncu Grup" width={145} height={51}/></Link><small>YÖNETİM PANELİ</small><Link href="/admin">Yönetim Özeti</Link>{[['users','Kullanıcılar'],['companies','Şirketler'],['locations','Lokasyonlar'],['departments','Departmanlar'],['units','Birimler'],['job-titles','Ünvanlar'],['roles','Roller & Yetkiler'],['settings','Sistem Ayarları']].filter(([r])=>canAction(actor,r==='job-titles'?'jobtitles':r,'view')).map(([r,n])=><Link key={r} href={'/admin/'+r}>{n}</Link>)}<InventoryNav actor={actor}/><ContentNav actor={actor}/><WorkflowNav actor={actor}/><Link className="back-portal" href="/">← Çalışan Portalı</Link></aside><div className="admin-main"><header className="admin-header"><span>Koyuncu Grup <b>/ İçerik Yönetimi</b></span><ProfileMenu actor={actor}/></header><main className="admin-content"><div className="admin-heading"><div><span className="eyebrow">İÇERİK YÖNETİMİ</span><h1>{home?'Ana Sayfa Yönetimi':contentNames[kind]+(isNew?' · Yeni Kayıt':editing?' · Düzenle':id?' · Detay':'')}</h1></div>{!home&&!id&&!editing&&permit('create')&&<Link className="a-primary" href={'/admin/'+section+'/new'}>+ Yeni Kayıt</Link>}</div>{error&&<p className="form-error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {home?<form className="content-form" onSubmit={e=>{e.preventDefault();void save();}}><p>Yerleşim sabittir. Yalnızca aşağıdaki metin ve görseller düzenlenebilir.</p><fieldset disabled={!permit('manage')||busy} style={{border:0,padding:0}}><section className="a-card"><h2>Karşılama Alanı</h2><div className="form-grid">{input('hero_title','Başlık ({ad} çalışanın adıyla değiştirilir)')}{input('hero_subtitle','Alt Başlık')}{upload('hero_image','Arka Plan Görseli')}{check('hero_active','Aktif')}</div></section><section className="a-card"><h2>Kurumsal Görsel</h2><div className="form-grid">{upload('corporate_image','Kurumsal Görsel')}{input('corporate_quote','Ana Söz')}{input('corporate_caption','Alt Yazı')}{check('corporate_active','Aktif')}</div></section><section className="a-card"><h2>Bölüm Başlıkları</h2><div className="form-grid">{input('announcements_title','Duyurular Başlığı','text',true)}{input('events_title','Etkinlikler Başlığı','text',true)}{input('news_title','Haberler Başlığı','text',true)}</div></section>{permit('manage')&&<button className="a-primary" disabled={busy}>Kaydet</button>}</fieldset></form>:
 editing?<form className="content-form" onSubmit={e=>{e.preventDefault();const button=(e.nativeEvent as SubmitEvent).submitter as HTMLButtonElement|null;void save(button?.dataset.publish==='1');}}><section className="a-card"><div className="form-grid">{input('title',kind==='events'?'Etkinlik Adı':'Başlık','text',true)}{input('slug','Slug (boşsa başlıktan oluşturulur)','text',false,!!id)}{kind!=='events'&&select('category_id','Kategori',options.categories??[],true)}{select('author_id','Yazar',options.user_id??[],true)}{input('summary',kind==='documents'?'Açıklama':'Kısa Açıklama / Özet')}{kind==='announcements'&&select('priority','Önem Derecesi',[{id:0,name:'Normal'},{id:1,name:'Önemli'},{id:2,name:'Acil'}],true)}{input('publish_at','Yayın Başlangıcı (Türkiye saati)','datetime-local',true)}{kind==='announcements'&&input('expires_at','Yayın Bitişi (Türkiye saati)','datetime-local')}{kind!=='documents'&&upload('cover','Kapak Görseli')}{kind==='news'&&upload('thumbnail','Thumbnail')}{kind==='documents'&&<>{input('version','Versiyon','text',true)}{upload('file_data','Doküman (PDF / TXT)',true)}</>}</div>{kind!=='documents'&&<Field label={kind==='events'?'Etkinlik Açıklaması':'İçerik'}><textarea className="content-textarea" maxLength={50000} value={form.body??''} onChange={e=>set('body',e.target.value)}/><small>Düz metin ve paragraflar desteklenir; HTML çalıştırılmaz.</small></Field>}</section>
 {kind==='events'&&<section className="a-card"><h2>Etkinlik Bilgileri</h2><div className="form-grid">{input('event_start','Başlangıç Tarihi / Saati','datetime-local',true)}{input('event_end','Bitiş Tarihi / Saati','datetime-local',true)}{input('venue','Lokasyon / Mekan')}{check('online','Online etkinlik')}{form.online&&input('online_url','Online Link','url',true)}<Field label="Kapasite (opsiyonel)"><input type="number" min={1} value={form.capacity??''} onChange={e=>set('capacity',e.target.value?Number(e.target.value):null)}/></Field>{check('participation_required','Katılım yanıtı gerekiyor')}{form.participation_required&&input('rsvp_deadline','Son Katılım Tarihi / Saati','datetime-local')}</div></section>}
 <section className="a-card"><h2>Hedef Kitle</h2><label className="permission-check"><input type="checkbox" checked={form.audience_all} onChange={e=>setForm({...form,audience_all:e.target.checked,targets:[]})}/>Tüm Kullanıcılar</label>{!form.audience_all&&<><p>Seçimlerden herhangi birine uyan kullanıcılar görebilir. Birden fazla seçim için Ctrl/Cmd kullanın.</p><div className="audience-options">{Object.entries(targetNames).map(([key,label])=><Field key={key} label={label}><select multiple value={(form.targets??[]).filter((t:Row)=>t.type===key).map((t:Row)=>t.id)} onChange={e=>set('targets',[...(form.targets??[]).filter((t:Row)=>t.type!==key),...Array.from(e.target.selectedOptions).map(o=>({type:key,id:o.value}))])}>{(options[key]??[]).map((r:Row)=><option key={r.id} value={r.id}>{r.name}{r.company_id?' · '+((options.company_id??[]).find((c:Row)=>c.id===r.company_id)?.name??''):''}</option>)}</select></Field>)}</div></>}</section><div className="a-actions"><button className="a-primary" disabled={busy||!ready}>{busy?'Kaydediliyor…':initial.item?.status==='PUBLISHED'?'Değişiklikleri Kaydet':'Taslak Kaydet'}</button>{permit('publish')&&<button data-publish="1" className="a-button" disabled={busy||!ready}>Kaydet ve Yayınla</button>}<Link className="a-button" href={'/admin/'+section}>Listeye Dön</Link></div></form>:
 id&&detail?<><section className="a-card"><div className="a-actions">{permit('edit')&&<Link className="a-button" href={'/admin/'+section+'/'+id+'/edit'}>Düzenle</Link>}{[['publish','Yayınla','publish'],['unpublish','Yayından Kaldır','publish'],['archive','Arşivle','manage'],...(kind==='events'?[['cancel','İptal Et','manage'],['complete','Tamamlandı','manage']]:[])].filter(([, ,permission])=>permit(permission)).map(([action,label])=><button key={action} className="a-button" disabled={busy} onClick={async()=>{if(await run(()=>api(section+'/'+id+'/'+action,'POST',{})))await load();}}>{label}</button>)}<Link className="a-button" href={'/admin/'+section}>Listeye Dön</Link></div><h2>{detail.title}</h2><p>Durum: {contentStatus[detail.display_status]} · Yayın: {contentDate(detail.publish_at)} {contentTime(detail.publish_at)}</p><p>Yazar: {(options.user_id??[]).find((u:Row)=>u.id===detail.author_id)?.name??'—'}</p><p>Hedef Kitle: {detail.audience_all?'Tüm Kullanıcılar':data.targets?.map((t:Row)=>targetNames[t.type]+': '+((options[t.type]??[]).find((r:Row)=>r.id===t.id)?.name??'Seçilmiş kayıt')).join(' / ')}</p>{detail.cover&&<img className="content-cover" src={detail.cover} alt={detail.title}/>}<p>{detail.summary}</p><div className="content-body">{detail.body}</div>{kind==='documents'&&<p>{detail.file_name} · Versiyon {detail.version}</p>}{kind==='events'&&<p>{contentDate(detail.event_start)} {contentTime(detail.event_start)} — {contentDate(detail.event_end)} {contentTime(detail.event_end)} · {detail.venue}</p>}</section>{kind==='events'&&<section className="a-card"><h2>Katılım Yanıtları</h2><p>Katılıyorum: {data.participants?.filter((p:Row)=>p.attending).length??0} · Katılmıyorum: {data.participants?.filter((p:Row)=>!p.attending).length??0}</p><div className="a-table-wrap"><table className="a-table"><thead><tr><th>Çalışan</th><th>Yanıt</th><th>Güncelleme</th></tr></thead><tbody>{data.participants?.map((p:Row)=><tr key={p.user_id}><td>{p.name}</td><td>{p.attending?'Katılıyorum':'Katılmıyorum'}</td><td>{contentDate(p.updated_at)} {contentTime(p.updated_at)}</td></tr>)}</tbody></table></div></section>}</>:
 <><div className="a-filters"><Field label="Ara"><input value={filters.q} onChange={e=>setFilters({...filters,q:e.target.value,page:1})}/></Field>{filter('status','Durum',Object.entries(contentStatus).filter(([k])=>kind==='events'||!['CANCELLED','COMPLETED'].includes(k)).map(([id,name])=>({id,name})))}{kind!=='events'&&filter('category_id','Kategori',options.categories??[])}{filter('audience','Hedef Kitle',[{id:'all',name:'Tüm Kullanıcılar'},...Object.entries(targetNames).map(([id,name])=>({id,name}))])}{['from','to'].map(key=><Field key={key} label={key==='from'?'Yayın Tarihi Başlangıç':'Yayın Tarihi Bitiş'}><input type="date" value={filters[key]??''} onChange={e=>setFilters({...filters,[key]:e.target.value,page:1})}/></Field>)}{filter('sort','Sırala',[{id:'publish_at',name:'Yayın Tarihi'},{id:'title',name:'Başlık'}])}{filter('dir','Yön',[{id:'desc',name:'Azalan'},{id:'asc',name:'Artan'}])}</div>{loading&&<p role="status">Yükleniyor…</p>}<div className="a-table-wrap"><table className="a-table"><thead><tr>{['Başlık','Kategori','Durum','Yayın Tarihi','Hedef Kitle'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{data.rows?.map((r:Row)=><tr key={r.id}><td><Link className="a-link" href={'/admin/'+section+'/'+r.id}>{r.title}</Link></td><td>{r.category_name||'—'}</td><td>{contentStatus[r.display_status]}</td><td>{contentDate(r.publish_at)} {contentTime(r.publish_at)}</td><td>{r.audience_all?'Tüm Kullanıcılar':'Seçilmiş Hedefler'}</td></tr>)}</tbody></table>{!data.rows?.length&&<p className="a-empty">Henüz içerik bulunmuyor.</p>}</div><div className="a-actions"><button className="a-button" disabled={filters.page<=1||loading} onClick={()=>setFilters({...filters,page:filters.page-1})}>Önceki</button><span>{data.total??0} kayıt · Sayfa {filters.page}</span><button className="a-button" disabled={filters.page*20>=(data.total??0)||loading} onClick={()=>setFilters({...filters,page:filters.page+1})}>Sonraki</button></div></>}
 </main></div></div>;
}
