'use client';
import { useState } from 'react';
import Image from 'next/image';
import {Home, Megaphone, ClipboardList, Contact, Timer, FileText, CalendarDays, UserRound, CalendarPlus, MessageSquare, CircleHelp, Building2, PanelsTopLeft, Phone, Settings, Search, Bell, ChevronDown, ChevronRight, ChevronLeft, ArrowRight, Laptop, Files, ClipboardCheck, MapPin, CloudSun, Headphones, Plane, Lightbulb, UsersRound, CalendarClock, Mail, Menu, X, Leaf, Check, Send} from 'lucide-react';
import type {LucideIcon} from 'lucide-react';
const menus:[string,LucideIcon,string?][]=[['Ana Sayfa',Home],['Duyurular',Megaphone,'3'],['Talepler',ClipboardList,'1'],['İletişim Rehberi',Contact],['Zimmetlerim',Timer],['Dokümanlar',FileText],['Etkinlikler',CalendarDays],['İK İşlemleri',UserRound],['Şirket Bilgileri',CalendarPlus],['Öneri & Bildirim',MessageSquare],['BT Destek',CircleHelp],['Sürdürülebilirlik',Building2],['Kurumsal İletişim',PanelsTopLeft],['Yardım & Destek',Phone],['Ayarlar',Settings]];
const sections:Record<string,string>={'Ana Sayfa':'top','Duyurular':'duyurular','İletişim Rehberi':'rehber','Zimmetlerim':'zimmet','Etkinlikler':'etkinlik','Öneri & Bildirim':'oneriler'};
const people=[['Ahmet Yılmaz','Genel Müdür','Yönetim','ahmet.yilmaz','1001'],['Ayşe Demir','İK Müdürü','İnsan Kaynakları','ayse.demir','1201'],['Mehmet Kaya','BT Müdürü','Bilgi Teknolojileri','mehmet.kaya','1301'],['Zeynep Arslan','Finans Müdürü','Finans','zeynep.arslan','1401'],['Can Öztürk','Operasyon Müdürü','Operasyon','can.ozturk','1501']];
const announcements=[{title:'Yıl Sonu Etkinlik Programı Açıklandı',category:'Genel',text:'31 Aralık’ta gerçekleşecek yıl sonu etkinlik programı yayınlandı.',date:'15 Aralık 2024',image:'gifts',color:'red'},{title:'Siber Güvenlik Farkındalık Eğitimi',category:'BT',text:'Tüm çalışanlarımız için zorunlu online eğitim.',date:'12 Aralık 2024',image:'security',color:'cyan'},{title:'Yeni Ofis Çalışma Düzeni Hakkında',category:'İK',text:'1 Ocak 2025 itibarıyla geçerli olacak yeni ofis çalışma düzeni duyurusu.',date:'14 Aralık 2024',image:'office',color:'orange'}];
const quick:[string,LucideIcon,string][]=[['Yeni Talep',FileText,'blue'],['BT Destek',Headphones,'purple'],['İK İşlemleri',UserRound,'green'],['Dokümanlar',FileText,'orange'],['İzin Talebi',Plane,'blue'],['Toplantı Odası',CalendarDays,'blue'],['Şirket Politikaları',FileText,'purple'],['Öneri & Bildirim',Lightbulb,'orange']];
function Photo({src,alt,className='',priority=false}:{src:string,alt:string,className?:string,priority?:boolean}){return <Image src={src} alt={alt} fill sizes="(max-width: 720px) 90vw, 40vw" className={className} priority={priority}/>}
function SectionTitle({title,onClick}:{title:string,onClick:()=>void}){return <div className="section-title"><h2>{title}</h2><button className="text-link" onClick={onClick}>Tümünü Gör <ArrowRight size={13}/></button></div>}
export default function Dashboard(){
 const [sidebar,setSidebar]=useState(false),[modal,setModal]=useState<{title:string,text:string}|null>(null),[suggestionTab,setSuggestionTab]=useState(0),[department,setDepartment]=useState('Tüm Departmanlar'),[search,setSearch]=useState(''),[globalSearch,setGlobalSearch]=useState(''),[joined,setJoined]=useState<number[]>([]),[selectedDay,setSelectedDay]=useState(16),[month,setMonth]=useState(11),[slide,setSlide]=useState(0);
 const demo=(title:string,text='Bu bölüm ana sayfa demosunda önizleme olarak yer alıyor. Henüz gerçek bir işlem yapılmıyor.')=>setModal({title,text});
 const navigate=(label:string)=>{setSidebar(false);const id=sections[label];if(id)document.getElementById(id)?.scrollIntoView({behavior:'smooth'});else demo(label)};
 const shown=people.filter(p=>(department==='Tüm Departmanlar'||p[2]===department)&&p.join(' ').toLocaleLowerCase('tr').includes(search.toLocaleLowerCase('tr')));
 const results=[...menus.map(x=>x[0]),...announcements.map(x=>x.title),...people.map(x=>x[0])].filter(x=>x.toLocaleLowerCase('tr').includes(globalSearch.toLocaleLowerCase('tr')));
 const date=new Date(2024,month,1),monthTitle=date.toLocaleDateString('tr-TR',{month:'long',year:'numeric'}),firstDay=(date.getDay()+6)%7,days=new Date(2024,month+1,0).getDate();
 return <div id="top" className="portal">
 {sidebar&&<button className="scrim" aria-label="Menüyü kapat" onClick={()=>setSidebar(false)}/>}
 <aside className={`sidebar ${sidebar?'open':''}`}><a href="#top" className="logo" aria-label="Koyuncu Grup ana sayfa"><Image src="/brand/koyuncu-grup.png" alt="Koyuncu Grup" width={132} height={46} priority/></a><button className="mobile-close" aria-label="Menüyü kapat" onClick={()=>setSidebar(false)}><X/></button><nav aria-label="Ana menü">{menus.map(([label,Icon,badge],i)=><button key={label} className={`nav-item ${i===0?'active':''}`} onClick={()=>navigate(label)}><Icon size={20}/><span>{label}</span>{badge&&<b className="badge">{badge}</b>}</button>)}</nav><div className="sidebar-bottom"><Building2 size={66} strokeWidth={.6}/><span>Birlikte<br/>Daha Güçlüyüz</span></div></aside>
 <div className="workspace"><header className="header"><button className="hamburger" onClick={()=>setSidebar(true)} aria-label="Menüyü aç"><Menu/></button><div className="global-search"><Search size={17}/><input aria-label="Portal genelinde ara" placeholder="Kişi, duyuru, talep veya doküman ara..." value={globalSearch} onChange={e=>setGlobalSearch(e.target.value)}/>{globalSearch&&<div className="search-results">{results.length?results.slice(0,8).map(r=><button key={r} onClick={()=>{setGlobalSearch('');sections[r]?navigate(r):demo(r)}}>{r}<ChevronRight size={14}/></button>):<p>Sonuç bulunamadı.</p>}</div>}</div><div className="header-right"><button className="notification" aria-label="3 demo bildirimi görüntüle" onClick={()=>demo('Bildirimler','Yeni duyuru: Yıl Sonu Etkinlik Programı • BT güvenlik eğitimi • Yeni ofis çalışma düzeni')}><Bell size={24}/><b className="badge">3</b></button><button className="profile" onClick={()=>demo('Enis Demir','BT Departmanı · Demo kullanıcı profili')}><Image src="/images/people/enis.png" alt="Enis Demir" width={37} height={37}/><span><strong>Enis Demir</strong><small>BT Departmanı</small></span><ChevronDown size={14}/></button><div className="header-date"><span>16 Aralık 2024, Pazartesi</span><strong>10:24</strong></div></div></header>
 <main className="dashboard"><div className="main-column"><section className="hero" aria-labelledby="welcome"><Photo src="/images/hero/building.webp" alt="Gün batımında modern Koyuncu Grup merkez binası" priority/><div className="hero-shade"/><div className="welcome"><b>16 Aralık 2024, Pazartesi</b><h1 id="welcome">Hoş geldin, Enis <span>👋</span></h1><p>Koyuncu Grup’ta güzel bir gün geçirmeni dileriz.</p></div><div className="weather"><div><MapPin size={14}/> İstanbul</div><strong><CloudSun size={47}/>12°C</strong><span>Parçalı Bulutlu</span><small>↓ 15° <i>↑</i> 8°</small></div></section>
 <section className="summary" aria-label="Özet bilgiler">{([['Taleplerim','3','Açık Talep',Files,'blue'],['Zimmetlerim','2','Aktif Zimmet',Laptop,'blue'],['Yaklaşan Etkinlikler','2','Bu Hafta',CalendarDays,'orange'],['Onaylarım','1','Onay Bekliyor',FileText,'blue']] as [string,string,string,LucideIcon,string][]).map(([label,count,sub,Icon,color])=><button className="summary-card" key={label} onClick={()=>label==='Zimmetlerim'?navigate(label):label==='Yaklaşan Etkinlikler'?navigate('Etkinlikler'):demo(label)}><div className={`summary-icon ${color}`}><Icon size={32}/></div><div><h3>{label}</h3><strong>{count}</strong><small>{sub}</small></div><ChevronRight size={16}/></button>)}</section>
 <div className="middle-grid"><section className="panel assets" id="zimmet"><SectionTitle title="Zimmetlerim" onClick={()=>demo('Zimmetlerim','2 aktif zimmet: Lenovo ThinkPad X1 Carbon Gen 11 ve Apple iPhone 15 Pro 256 GB.')}/><div className="asset-grid">{[['Lenovo ThinkPad X1 Carbon','Gen 11','laptop','KG-IT-001234','PF4X2C9','12.01.2024'],['Apple iPhone 15 Pro','256 GB','phone','KG-IT-005678','F17Q93K1A2','03.03.2024']].map(a=><article className="asset-card" key={a[2]}><div className="asset-top"><div className="product-photo"><Photo src={`/images/assets/${a[2]}.webp`} alt={`${a[0]} ${a[1]}`}/></div><div><h3>{a[0]}<br/>{a[1]}</h3><span className="status active-status"><Check size={11}/> Aktif</span></div></div><dl><dt>Demirbaş No</dt><dd>{a[3]}</dd><dt>Seri No</dt><dd>{a[4]}</dd><dt>Zimmet Tarihi</dt><dd>{a[5]}</dd></dl></article>)}</div></section>
 <section className="panel agenda"><SectionTitle title="Ajandam" onClick={()=>demo('Ajandam','16 Aralık: 10:00 BT Güvenlik Toplantısı, 14:00 Proje Değerlendirme, 16:30 Aylık Departman Toplantısı.')}/><div className="agenda-grid"><div className="calendar"><div className="calendar-title"><button aria-label="Önceki ay" onClick={()=>setMonth(month-1)}><ChevronLeft size={12}/></button><b>{monthTitle}</b><button aria-label="Sonraki ay" onClick={()=>setMonth(month+1)}><ArrowRight size={13}/></button></div><div className="calendar-days">{['Pzt','Sal','Çar','Per','Cum','Cmt','Paz'].map(d=><span key={d}>{d}</span>)}{Array.from({length:firstDay},(_,i)=><span key={`empty${i}`}/>)}{Array.from({length:days},(_,i)=><button aria-label={`${i+1} ${monthTitle}`} aria-pressed={selectedDay===i+1} key={i} onClick={()=>setSelectedDay(i+1)} className={selectedDay===i+1?'selected':''}>{i+1}</button>)}</div></div><div className="meetings">{month===11&&selectedDay===16?[['10:00','BT Güvenlik Toplantısı','Toplantı Odası A','purple'],['14:00','Proje Değerlendirme','Teams Toplantısı','orange'],['16:30','Aylık Departman Toplantısı','Toplantı Odası B','green']].map(m=><div className={`meeting ${m[3]}`} key={m[0]}><span>{m[0]}</span><strong>{m[1]}</strong><small>{m[2]}</small></div>):<p className="empty-agenda">{selectedDay} {monthTitle}<br/><br/>Planlanmış etkinlik yok.</p>}</div></div></section>
 <section className="panel announcements" id="duyurular"><SectionTitle title="Duyurular" onClick={()=>demo('Duyurular',announcements.map(a=>a.title).join(' • '))}/><div className="announcement-grid">{announcements.map(a=><button className="announcement" key={a.title} onClick={()=>demo(a.title,a.text)}><div className="announcement-photo"><Photo src={`/images/announcements/${a.image}.webp`} alt={a.title}/></div><div className="announcement-body"><span className={`category ${a.color}`}>{a.category}</span><h3>{a.title}</h3><p>{a.text}</p><small><CalendarDays size={11}/>{a.date}</small></div></button>)}</div></section>
 <section className="panel events" id="etkinlik"><SectionTitle title="Şirket Etkinlikleri" onClick={()=>demo('Şirket Etkinlikleri','20 Aralık Yıl Sonu Toplantısı • 25 Aralık BT Güvenlik Eğitimi • 8 Ocak Yeni Ofis Tanıtım Turu')}/><div className="event-list">{[['20','Ara','Yıl Sonu Toplantısı','Koyuncu Grup Konferans Salonu'],['25','Ara','BT Güvenlik Eğitimi','Online / Teams'],['08','Oca','Yeni Ofis Tanıtım Turu','Merkez Ofis']].map((e,i)=><div className="event" key={e[0]}><div className="event-date"><strong>{e[0]}</strong><span>{e[1]}</span></div><div className="event-info"><h3>{e[2]}</h3><small>{e[3]}</small></div><UsersRound size={19}/><button aria-pressed={joined.includes(i)} className={joined.includes(i)?'joined':''} onClick={()=>setJoined(joined.includes(i)?joined.filter(n=>n!==i):[...joined,i])}>{joined.includes(i)?'Katılıyorum':'Katılıyorum'}{joined.includes(i)?<Check size={13}/>:<ChevronRight size={13}/>}</button></div>)}</div></section></div>
 <section className="panel directory" id="rehber"><div className="directory-head"><h2>İletişim Rehberi</h2><label className="directory-search"><Search size={16}/><input placeholder="İsim, departman, ünvan veya e-posta ile ara..." aria-label="İletişim rehberinde ara" value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="Departman filtresi" value={department} onChange={e=>setDepartment(e.target.value)}><option>Tüm Departmanlar</option>{people.map(p=><option key={p[2]}>{p[2]}</option>)}</select><button className="text-link" onClick={()=>{setSearch('');setDepartment('Tüm Departmanlar')}}>Tümünü Gör <ArrowRight size={12}/></button></div><div className="people-grid">{shown.length?shown.map(p=><article className="person" key={p[0]}><button className="person-top" onClick={()=>demo(p[0],`${p[1]} · ${p[2]} · ${p[3]}@koyuncugrup.com · Dahili ${p[4]}`)}><Image src={`/images/people/${people.indexOf(p)}.png`} alt={p[0]} width={42} height={42}/><div><h3>{p[0]}</h3><small>{p[1]}<br/>{p[2]}</small></div><ChevronRight size={13}/></button><div className="person-contact"><Mail size={13}/><span>{p[3]}@koyuncugrup.com</span></div><div className="person-contact"><Phone size={13}/><span>+90 212 123 45 67</span><span>Dahili {p[4]}</span></div></article>):<p className="no-results">Aramanızla eşleşen kişi bulunamadı.</p>}</div></section></div>
 <aside className="right-column"><section className="office-banner"><Photo src={slide===0?'/images/hero/lounge.webp':'/images/hero/building.webp'} alt="Koyuncu Grup modern ofis yaşam alanı" priority/><div className="office-shade"/><blockquote>{slide===0?<>“İnsan,<br/>başarımızın<br/>en önemli gücüdür.”</>:<>“Birlikte<br/>Daha Güçlüyüz.”</>}<cite>Koyuncu Grup Ailesi</cite></blockquote><div className="slider-controls"><button aria-label="Önceki görsel" onClick={()=>setSlide(1-slide)}><ChevronLeft size={13}/></button>{[0,1].map(i=><button className={`dot ${slide===i?'current':''}`} key={i} aria-label={`${i+1}. görsel`} aria-pressed={slide===i} onClick={()=>setSlide(i)}/>)}<button aria-label="Sonraki görsel" onClick={()=>setSlide(1-slide)}><ChevronRight size={13}/></button></div></section>
 <section className="panel quick-access"><h2>Hızlı Erişim</h2><div className="quick-grid">{quick.map(([label,Icon,color])=><button className={color} key={label} onClick={()=>navigate(label)}><Icon size={28}/><span>{label}</span></button>)}</div></section>
 <section className="panel suggestions" id="oneriler"><SectionTitle title="Öneri ve Bildirimler" onClick={()=>demo('Öneri ve Bildirimler','2 öneri ve 3 bildirim görüntüleniyor.')}/><div className="tabs" role="tablist" aria-label="Öneri ve bildirimler">{['Son Öneriler (2)','Son Bildirimler (3)'].map((t,i)=><button key={t} role="tab" aria-selected={suggestionTab===i} className={suggestionTab===i?'selected':''} onClick={()=>setSuggestionTab(i)}>{t}</button>)}</div><div role="tabpanel">{(suggestionTab===0?[['Ofislerde Geri Dönüşüm Alanlarının Artırılması','Çevre dostu bir çalışma ortamı için geri dönüşüm kutularının sayısının artırılmasını öneriyorum.','15 Aralık 2024','İnceleniyor'],['Otopark Alanı Talebi','Merkez ofis otopark alanının yetersizliği hakkında...','14 Aralık 2024','Yanıtlandı']]:[['Yeni Duyuru Yayınlandı','Yıl sonu etkinlik programı yayınlandı.','15 Aralık 2024','Yeni'],['Eğitim Hatırlatması','BT güvenlik eğitiminizi tamamlamayı unutmayın.','14 Aralık 2024','Yeni'],['Ofis Düzeni Güncellendi','Yeni çalışma düzenine göz atabilirsiniz.','14 Aralık 2024','Yeni']]).map((s,i)=><button className="suggestion" key={s[0]} onClick={()=>demo(s[0],s[1])}><span className={`suggestion-icon ${i===0?'orange':'red'}`}>{i===0?<Lightbulb size={23}/>:<MessageSquare size={23}/>}</span><div><h3>{s[0]}</h3><p>{s[1]}</p><div className="suggestion-meta"><small><CalendarDays size={11}/>{s[2]}</small><span className={`status ${s[3]==='Yanıtlandı'?'active-status':'review-status'}`}>{s[3]}</span></div></div><ChevronRight size={13}/></button>)}</div></section>
 <section className="panel news"><SectionTitle title="Haberler" onClick={()=>demo('Haberler','Koyuncu Grup’tan sürdürülebilirlik alanında yeni adım • Yeni ofisimiz açıldı • Yıl sonu etkinliği')}/>{[['Koyuncu Grup’tan Sürdürülebilirlik Alanında Yeni Adım','13 Aralık 2024','courtyard'],['Yeni Ofisimiz Açıldı','10 Aralık 2024','office'],['Koyuncu Grup Ailesi Yıl Sonu Etkinliğinde Bir Araya Geldi','05 Aralık 2024','meeting']].map(n=><button className="news-row" key={n[0]} onClick={()=>demo(n[0],'Bu haber, ana sayfa tasarımını göstermek için hazırlanmış örnek içeriktir.')}><div className="news-photo"><Photo src={`/images/news/${n[2]}.webp`} alt={n[0]}/></div><div><h3>{n[0]}</h3><small>{n[1]}</small></div><ChevronRight size={13}/></button>)}</section></aside></main></div>
 {modal&&<div className="modal-overlay" onClick={()=>setModal(null)}><section role="dialog" aria-modal="true" aria-labelledby="dialog-title" className="modal" onClick={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==='Escape')setModal(null)}}><button autoFocus className="modal-close" onClick={()=>setModal(null)} aria-label="Kapat"><X size={21}/></button><span className="demo-tag">Önizleme</span><h2 id="dialog-title">{modal.title}</h2><p>{modal.text}</p><button className="primary-button" onClick={()=>setModal(null)}>Tamam</button></section></div>}
 </div>
}
