'use client';
import Agenda from './Agenda';
import {AgendaData} from '@/lib/meeting-shared';
import {NotificationBell} from './NotificationCenter';
import DashboardSuggestions from './DashboardSuggestions';
import {EngagementSummary,emptyEngagement} from '@/lib/engagement-shared';
import { useState } from 'react';
import {LiveClock,MarketStrip,WeatherCard,useDashboardData} from './DashboardLiveData';
import {useRouter} from 'next/navigation';
import {AnnouncementBlock,EventBlock,NewsBlock} from './DashboardContentBlocks';
import {DashboardContent,contentDate,contentTime} from '@/lib/content-shared';
import AssetCards from './AssetCards';
import type {AssetSummary} from '@/lib/inventory-shared';
import Image from 'next/image';
import ProfileMenu from './ProfileMenu';
import {Identity,can,portalPermissions} from '@/lib/permissions';
import {Home, Megaphone, ClipboardList, Contact, Timer, FileText, CalendarDays, UserRound, CalendarPlus, MessageSquare, CircleHelp, Building2, PanelsTopLeft, Phone, Settings, Search, Bell, ChevronDown, ChevronRight, ChevronLeft, ArrowRight, Laptop, Files, ClipboardCheck, MapPin, CloudSun, Headphones, Plane, Lightbulb, UsersRound, CalendarClock, Mail, Menu, X, Leaf, Check, Send} from 'lucide-react';
import type {LucideIcon} from 'lucide-react';
const menus:[string,LucideIcon,string?][]=[['Ana Sayfa',Home],['Duyurular',Megaphone],['Talepler',ClipboardList],['İletişim Rehberi',Contact],['Zimmetlerim',Timer],['Dokümanlar',FileText],['Etkinlikler',CalendarDays],['Ajandam',CalendarClock],['İK İşlemleri',UserRound],['Şirket Bilgileri',CalendarPlus],['Öneri & Bildirim',MessageSquare],['BT Destek',CircleHelp],['Sürdürülebilirlik',Building2],['Kurumsal İletişim',PanelsTopLeft],['Yardım & Destek',Phone],['Ayarlar',Settings]];
const sections:Record<string,string>={'Ana Sayfa':'top','Duyurular':'duyurular','İletişim Rehberi':'rehber','Zimmetlerim':'zimmet','Etkinlikler':'etkinlik','Öneri & Bildirim':'oneriler'};
const people=[['Ahmet Yılmaz','Genel Müdür','Yönetim','ahmet.yilmaz','1001'],['Ayşe Demir','İK Müdürü','İnsan Kaynakları','ayse.demir','1201'],['Mehmet Kaya','BT Müdürü','Bilgi Teknolojileri','mehmet.kaya','1301'],['Zeynep Arslan','Finans Müdürü','Finans','zeynep.arslan','1401'],['Can Öztürk','Operasyon Müdürü','Operasyon','can.ozturk','1501']];
const quick:[string,LucideIcon,string][]=[['Yeni Talep',FileText,'blue'],['BT Destek',Headphones,'purple'],['İK İşlemleri',UserRound,'green'],['Dokümanlar',FileText,'orange'],['İzin Talebi',Plane,'blue'],['Toplantı Odası',CalendarDays,'blue'],['Şirket Politikaları',FileText,'purple'],['Öneri & Bildirim',Lightbulb,'orange']];
function Photo({src,alt,className='',priority=false}:{src:string,alt:string,className?:string,priority?:boolean}){return <Image src={src} alt={alt} fill sizes="(max-width: 720px) 90vw, 40vw" className={className} priority={priority}/>}
function SectionTitle({title,onClick}:{title:string,onClick:()=>void}){return <div className="section-title"><h2>{title}</h2><button className="text-link" onClick={onClick}>Tümünü Gör <ArrowRight size={13}/></button></div>}
export default function Dashboard({actor,assets,content,counts={requests:0,approvals:0},engagement=emptyEngagement,agendaData}:{actor:Identity;assets:AssetSummary;content:DashboardContent;counts?:{requests:number;approvals:number};engagement?:EngagementSummary;agendaData?:AgendaData}){
 const liveData=useDashboardData(actor.id);
 const router=useRouter();const announcements=content.announcements,home=content.homepage;
 const [sidebar,setSidebar]=useState(false),[modal,setModal]=useState<{title:string,text:string}|null>(null),[department,setDepartment]=useState('Tüm Departmanlar'),[search,setSearch]=useState(''),[globalSearch,setGlobalSearch]=useState('');
 const demo=(title:string,text='Bu bölüm ana sayfa demosunda önizleme olarak yer alıyor. Henüz gerçek bir işlem yapılmıyor.')=>setModal({title,text});
 const navigate=(label:string)=>{const route:Record<string,string>={'Ajandam':'/calendar','Toplantı Odası':'/meeting-rooms','Öneri & Bildirim':'/suggestions','Talepler':'/requests','Taleplerim':'/requests','Yeni Talep':'/requests/new','İzin Talebi':'/leave/new','İK İşlemleri':'/leave','Onaylarım':'/approvals','Duyurular':'/announcements','Dokümanlar':'/documents','Etkinlikler':'/events','Zimmetlerim':'/my-assets','Şirket Politikaları':'/documents'};if(route[label]){router.push(route[label]);setSidebar(false);return;}if(label==='Ayarlar'&&can(actor,'admin.view')){window.location.assign('/admin');return;}setSidebar(false);const id=sections[label];if(id)document.getElementById(id)?.scrollIntoView({behavior:'smooth'});else demo(label)};
 const shown=people.filter(p=>(department==='Tüm Departmanlar'||p[2]===department)&&p.join(' ').toLocaleLowerCase('tr').includes(search.toLocaleLowerCase('tr')));
 const results=[...menus.filter(([name])=>name==='Ajandam'?can(actor,'calendar.view_own'):name==='Ayarlar'?can(actor,'admin.view'):can(actor,portalPermissions.find(p=>p.name===name)?.id??'portal.home.view')).map(x=>x[0]),...(can(actor,'portal.announcements.view')?announcements.map(x=>x.title):[]),...(can(actor,'portal.directory.view')?people.map(x=>x[0]):[])].filter(x=>x.toLocaleLowerCase('tr').includes(globalSearch.toLocaleLowerCase('tr')));
 return <div id="top" className="portal">
 {sidebar&&<button className="scrim" aria-label="Menüyü kapat" onClick={()=>setSidebar(false)}/>}
 <aside className={`sidebar ${sidebar?'open':''}`}><a href="#top" className="logo" aria-label="Koyuncu Grup ana sayfa"><Image src="/brand/koyuncu-grup.png" alt="Koyuncu Grup" width={132} height={46} priority/></a><button className="mobile-close" aria-label="Menüyü kapat" onClick={()=>setSidebar(false)}><X/></button><nav aria-label="Ana menü">{menus.filter(([name])=>name==='Ajandam'?can(actor,'calendar.view_own'):name==='Ayarlar'?can(actor,'admin.view'):can(actor,portalPermissions.find(p=>p.name===name)?.id??'portal.home.view')).map(([label,Icon,badge],i)=><button key={label} className={`nav-item ${i===0?'active':''}`} onClick={()=>navigate(label)}><Icon size={20}/><span>{label}</span>{badge&&<b className="badge">{badge}</b>}</button>)}</nav><div className="sidebar-bottom"><Building2 size={66} strokeWidth={.6}/><span>Birlikte<br/>Daha Güçlüyüz</span></div></aside>
 <div className="workspace"><header className="header"><button className="hamburger" onClick={()=>setSidebar(true)} aria-label="Menüyü aç"><Menu/></button><div className="global-search"><Search size={17}/><input aria-label="Portal genelinde ara" placeholder="Kişi, duyuru, talep veya doküman ara..." value={globalSearch} onChange={e=>setGlobalSearch(e.target.value)}/>{globalSearch&&<div className="search-results">{results.length?results.slice(0,8).map(r=><button key={r} onClick={()=>{setGlobalSearch('');announcements.some(a=>a.title===r)?router.push('/announcements/'+announcements.find(a=>a.title===r)!.slug):sections[r]?navigate(r):demo(r)}}>{r}<ChevronRight size={14}/></button>):<p>Sonuç bulunamadı.</p>}</div>}</div><MarketStrip data={liveData}/><div className="header-right">{can(actor,'notifications.view_own')&&<NotificationBell initialUnread={engagement.unread}/>}<ProfileMenu actor={actor} portalStyle/><LiveClock/></div></header>
 <main className="dashboard"><div className="main-column"><section className="hero" aria-labelledby="welcome">{home.hero_active&&<Photo src={home.hero_image||'/images/hero/building.webp'} alt="Koyuncu Grup merkez binası" priority/>}<div className="hero-shade"/>{home.hero_active&&<div className="welcome"><b>{contentDate(new Date().toISOString())}</b><h1 id="welcome">{home.hero_title.replaceAll('{ad}',actor.first_name)}</h1><p>{home.hero_subtitle}</p></div>}<WeatherCard data={liveData}/></section>
 <section className="summary" aria-label="Özet bilgiler">{([['Taleplerim',String(counts.requests),'Açık Talep',Files,'blue'],['Zimmetlerim',String(assets.total),'Aktif Zimmet',Laptop,'blue'],['Yaklaşan Etkinlikler',String(content.events.length),'Yaklaşan',CalendarDays,'orange'],['Onaylarım',String(counts.approvals),'Onay Bekliyor',FileText,'blue']] as [string,string,string,LucideIcon,string][]).map(([label,count,sub,Icon,color])=><button className="summary-card" key={label} onClick={()=>label==='Zimmetlerim'?navigate(label):label==='Yaklaşan Etkinlikler'?navigate('Etkinlikler'):navigate(label)}><div className={`summary-icon ${color}`}><Icon size={32}/></div><div><h3>{label}</h3><strong>{count}</strong><small>{sub}</small></div><ChevronRight size={16}/></button>)}</section>
 <div className="middle-grid">{can(actor,'portal.assets.view')&&<section className="panel assets" id="zimmet"><SectionTitle title="Zimmetlerim" onClick={()=>router.push('/my-assets')}/><AssetCards rows={assets.rows}/></section>}
 {can(actor,'calendar.view_own')&&agendaData&&<Agenda initial={agendaData} compact/>}
 {can(actor,'portal.announcements.view')&&<AnnouncementBlock rows={content.announcements} title={home.announcements_title}/>}
 {can(actor,'portal.events.view')&&<EventBlock rows={content.events} title={home.events_title}/>}</div>
 {can(actor,'portal.directory.view')&&<section className="panel directory" id="rehber"><div className="directory-head"><h2>İletişim Rehberi</h2><label className="directory-search"><Search size={16}/><input placeholder="İsim, departman, ünvan veya e-posta ile ara..." aria-label="İletişim rehberinde ara" value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="Departman filtresi" value={department} onChange={e=>setDepartment(e.target.value)}><option>Tüm Departmanlar</option>{people.map(p=><option key={p[2]}>{p[2]}</option>)}</select><button className="text-link" onClick={()=>{setSearch('');setDepartment('Tüm Departmanlar')}}>Tümünü Gör <ArrowRight size={12}/></button></div><div className="people-grid">{shown.length?shown.map(p=><article className="person" key={p[0]}><button className="person-top" onClick={()=>demo(p[0],`${p[1]} · ${p[2]} · ${p[3]}@koyuncugrup.com · Dahili ${p[4]}`)}><Image src={`/images/people/${people.indexOf(p)}.png`} alt={p[0]} width={42} height={42}/><div><h3>{p[0]}</h3><small>{p[1]}<br/>{p[2]}</small></div><ChevronRight size={13}/></button><div className="person-contact"><Mail size={13}/><span>{p[3]}@koyuncugrup.com</span></div><div className="person-contact"><Phone size={13}/><span>+90 212 123 45 67</span><span>Dahili {p[4]}</span></div></article>):<p className="no-results">Aramanızla eşleşen kişi bulunamadı.</p>}</div></section>}</div>
 <aside className="right-column"><section className="office-banner">{home.corporate_active&&<><Photo src={home.corporate_image||'/images/hero/lounge.webp'} alt="Koyuncu Grup kurumsal görseli" priority/><div className="office-shade"/><blockquote style={{whiteSpace:'pre-line'}}>{home.corporate_quote}<cite>{home.corporate_caption}</cite></blockquote></>}</section>
 <section className="panel quick-access"><h2>Hızlı Erişim</h2><div className="quick-grid">{quick.map(([label,Icon,color])=><button className={color} key={label} onClick={()=>navigate(label)}><Icon size={28}/><span>{label}</span></button>)}</div></section>
 {can(actor,'suggestions.view_own')&&<DashboardSuggestions data={engagement} canCreate={can(actor,'suggestions.create')}/>}
 {can(actor,'portal.communications.view')&&<NewsBlock rows={content.news} title={home.news_title}/>}</aside></main></div>
 {modal&&<div className="modal-overlay" onClick={()=>setModal(null)}><section role="dialog" aria-modal="true" aria-labelledby="dialog-title" className="modal" onClick={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==='Escape')setModal(null)}}><button autoFocus className="modal-close" onClick={()=>setModal(null)} aria-label="Kapat"><X size={21}/></button><span className="demo-tag">Önizleme</span><h2 id="dialog-title">{modal.title}</h2><p>{modal.text}</p><button className="primary-button" onClick={()=>setModal(null)}>Tamam</button></section></div>}
 </div>
}

