'use client';
import React from 'react';
import Link from 'next/link';
import Image from 'next/image';
import {ArrowRight,CalendarDays,ChevronRight,UsersRound} from 'lucide-react';
import {ContentRow,contentDate} from '@/lib/content-shared';
import ParticipationButton from './ParticipationButton';
function Heading({title,href}:{title:string;href:string}){return <div className="section-title"><h2>{title}</h2><Link className="text-link" href={href}>Tümünü Gör <ArrowRight size={13}/></Link></div>}
export function AnnouncementBlock({rows,title}:{rows:ContentRow[];title:string}){return <section className="panel announcements" id="duyurular"><Heading title={title} href="/announcements"/>{rows.length?<div className="announcement-grid">{rows.map(a=><Link className="announcement" key={a.id} href={'/announcements/'+a.slug}><div className="announcement-photo"><Image src={a.cover||'/images/announcements/office.webp'} alt={a.title} fill sizes="(max-width:720px) 90vw, 30vw"/></div><div className="announcement-body"><span className={'category '+(a.priority===2?'red':a.priority===1?'orange':'cyan')}>{a.category_name}</span><h3>{a.title}</h3><p>{a.summary}</p><small><CalendarDays size={11}/>{contentDate(a.publish_at)}</small></div></Link>)}</div>:<p className="content-dashboard-empty">Şu anda görüntüleyebileceğiniz duyuru bulunmuyor.</p>}</section>}
export function EventBlock({rows,title}:{rows:ContentRow[];title:string}){return <section className="panel events" id="etkinlik"><Heading title={title} href="/events"/><div className="event-list">{rows.length?rows.map(e=><div className="event" key={e.id}><div className="event-date"><strong>{new Date(e.event_start!).toLocaleDateString('tr-TR',{timeZone:'Europe/Istanbul',day:'2-digit'})}</strong><span>{new Date(e.event_start!).toLocaleDateString('tr-TR',{timeZone:'Europe/Istanbul',month:'short'})}</span></div><div className="event-info"><Link href={'/events/'+e.slug}><h3>{e.title}</h3></Link><small>{e.venue}</small></div><UsersRound size={19}/>{e.participation_required?<ParticipationButton slug={e.slug} attending={e.attending} disabled={!!e.rsvp_deadline&&new Date(e.rsvp_deadline).getTime()<Date.now()}/>:<Link href={'/events/'+e.slug}>Detay</Link>}</div>):<p className="content-dashboard-empty">Yaklaşan etkinlik bulunmuyor.</p>}</div></section>}
export function NewsBlock({rows,title}:{rows:ContentRow[];title:string}){return <section className="panel news"><Heading title={title} href="/news"/>{rows.length?rows.map(n=><Link className="news-row" key={n.id} href={'/news/'+n.slug}><div className="news-photo"><Image src={n.thumbnail||n.cover||'/images/news/office.webp'} alt={n.title} fill sizes="100px"/></div><div><h3>{n.title}</h3><small>{contentDate(n.publish_at)}</small></div><ChevronRight size={13}/></Link>):<p className="content-dashboard-empty">Şu anda görüntüleyebileceğiniz haber bulunmuyor.</p>}</section>}
