'use client';
import { useState, useEffect } from 'react';
import Image from 'next/image';
import {Home, Megaphone, ClipboardList, Contact, Timer, FileText, CalendarDays, UserRound, CalendarPlus, MessageSquare, CircleHelp, Building2, PanelsTopLeft, Phone, Settings, Search, Bell, ChevronDown, Menu, ChevronRight, ChevronLeft, ArrowRight, X, Files, Laptop, Headphones} from 'lucide-react';
import type {LucideIcon} from 'lucide-react';
import WeatherWidget from './WeatherWidget';

const menus:[string,LucideIcon,string?][]=[['Ana Sayfa',Home],['Duyurular',Megaphone,'3'],['Talepler',ClipboardList,'1'],['İletişim Rehberi',Contact],['Zimmetlerim',Timer],['Dokümanlar',FileText],['Etkinlikler',CalendarDays],['Öneri & Bildirim',MessageSquare]];
const sections:Record<string,string>={'Ana Sayfa':'top','Duyurular':'duyurular','İletişim Rehberi':'rehber','Zimmetlerim':'zimmet','Etkinlikler':'etkinlik','Öneri & Bildirim':'oneriler'};
const people=[['Ahmet Yılmaz','Genel Müdür','Yönetim','ahmet.yilmaz','1001'],['Ayşe Demir','İK Müdürü','İnsan Kaynakları','ayse.demir','1201'],['Mehmet Kaya','BT Müdürü','Bilgi Teknolojileri','mehmet.kaya','1401'],['Fatih Çetin','Pazarlama Müdürü','Pazarlama','fatih.cetin','2001'],['Zeynep Acar','İş Yönetimi','Operasyonlar','zeynep.acar','2101']];
const announcements=[{title:'Yıl Sonu Etkinlik Programı Açıklandı',category:'Genel',text:"31 Aralık\'ta gerçekleşecek yıl sonu etkinlik programı yayınlandı.",date:'15 Aralık 2024',image:'/images/announcements/event.webp'},{title:'Yeni Ofis Kolaylaştırmaları',category:'Operasyon',text:'Yeni kafe alanı ve dinlenme odaları hizmetinize sunulmuştur.',date:'12 Aralık 2024',image:'/images/announcements/office.webp'},{title:'BT Güvenlik Güncellemeleri',category:'BT',text:'Tüm cihazlara en son güvenlik yamaları uygulanacaktır.',date:'10 Aralık 2024',image:'/images/announcements/security.webp'}];
const quick:[string,LucideIcon,string][]=[['Yeni Talep',FileText,'blue'],['BT Destek',Headphones,'purple'],['İK İşlemleri',UserRound,'green'],['Dokümanlar',FileText,'orange'],['İzin Talebi',CalendarPlus,'red']];

function Photo({src,alt,className='',priority=false}:{src:string,alt:string,className?:string,priority?:boolean}){return <Image src={src} alt={alt} fill sizes="(max-width: 720px) 90vw, 40vw" className={`photo ${className}`} priority={priority}/>}
function SectionTitle({title,onClick}:{title:string,onClick:()=>void}){return <div className="section-title"><h2>{title}</h2><button className="text-link" onClick={onClick}>Tümünü Gör <ArrowRight size={14}/></button></div>}

export default function Dashboard(){
  const [sidebar,setSidebar]=useState(false),[modal,setModal]=useState<{title:string,text:string}|null>(null),[suggestionTab,setSuggestionTab]=useState(0),[department,setDepartment]=useState('Tüm Departmanlar'),[search,setSearch]=useState(''),[globalSearch,setGlobalSearch]=useState(''),[month,setMonth]=useState(new Date().getMonth()),[slide,setSlide]=useState(0);

  useEffect(()=>{
    const updateTime=()=>setTime(new Date().toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit'}));
    updateTime();
    const interval=setInterval(updateTime,1000);
    return ()=>clearInterval(interval);
  },[]);

  const demo=(title:string,text='Bu bölüm ana sayfa demosunda önizleme olarak yer alıyor. Henüz gerçek bir işlem yapılmıyor.')=>setModal({title,text});
  const navigate=(label:string)=>{setSidebar(false);const id=sections[label];if(id)document.getElementById(id)?.scrollIntoView({behavior:'smooth'});else demo(label)};
  const shown=people.filter(p=>(department==='Tüm Departmanlar'||p[2]===department)&&p.join(' ').toLocaleLowerCase('tr').includes(search.toLocaleLowerCase('tr')));
  const results=[...menus.map(x=>x[0]),...announcements.map(x=>x.title),...people.map(x=>x[0])].filter(x=>x.toLocaleLowerCase('tr').includes(globalSearch.toLocaleLowerCase('tr')));
  const date=new Date(2024,month,1),monthTitle=date.toLocaleDateString('tr-TR',{month:'long',year:'numeric'}),firstDay=(date.getDay()+6)%7,days=new Date(2024,month+1,0).getDate();

  return <div id="top" className="portal">
  {sidebar&&<button className="scrim" aria-label="Menüyü kapat" onClick={()=>setSidebar(false)}/>}
  <aside className={`sidebar ${sidebar?'open':''}`}><a href="#top" className="logo" aria-label="Koyuncu Grup ana sayfa"><Image src="/brand/koyuncu-grup.png" alt="Koyuncu Grup" width={132} height={44}/></a><nav><div className="search-input"><Search size={16}/><input placeholder="Ara" value={globalSearch} onChange={(e)=>setGlobalSearch(e.target.value)} role="searchbox" aria-label="Sitede ara"/></div>{globalSearch&&<div className="search-results">{results.length===0?<div className="search-empty">Sonuç yok</div>:results.map((r,i)=><button key={i} className="search-item" onClick={()=>{setGlobalSearch('');navigate(r)}}>{r}</button>)}</div>}{!globalSearch&&menus.map(([label,Icon,badge])=><button key={label} className={`nav-item ${sections[label]?'':'disabled'}`} onClick={()=>navigate(label)}><Icon size={16}/>{label}{badge&&<span className="badge">{badge}</span>}</button>)}</nav><div className="sidebar-bottom"><div className="profile-mini"><Image src="/avatars/user.webp" alt="Kullanıcı" width={32} height={32}/><div><div className="name">Kullanıcı</div><div className="role">Çalışan</div></div></div><button className="sidebar-item"><Settings size={16}/><span>Ayarlar</span></button></div></aside>
  <div className="workspace"><header className="header"><button className="hamburger" onClick={()=>setSidebar(true)} aria-label="Menüyü aç"><Menu/></button><div className="global-search"><Search size={16}/><input placeholder="Ara" value={globalSearch} onChange={(e)=>setGlobalSearch(e.target.value)}/>{globalSearch&&<div className="search-results">{results.map((r,i)=><button key={i} className="search-item" onClick={()=>{setGlobalSearch('');navigate(r)}}>{r}</button>)}</div>}</div><div className="header-actions"><button aria-label="Bildirim"><Bell size={20}/></button><button className="profile-btn" onClick={()=>demo('Profil')}><Image src="/avatars/user.webp" alt="Profil" width={32} height={32}/><ChevronDown size={16}/></button></div></header>
  <main className="dashboard"><div className="main-column"><section className="hero" aria-labelledby="welcome"><Photo src="/images/hero/building.webp" alt="Gün batımında modern Koyuncu Grup merkez binası"/><div className="hero-content"><h1 id="welcome">Hoş geldiniz</h1><p>Koyuncu Grup Portalı'na hoş geldiniz. Tüm araçlar ve bilgiler burada.</p></div></section>
  <section className="summary" aria-label="Özet bilgiler">{([['Taleplerim','3','Açık Talep',Files,'blue'],['Zimmetlerim','2','Aktif Zimmet',Laptop,'blue'],['Yaklaşan Etkinlikler','2','Bu Hafta',CalendarPlus,'purple']]).map(([label,count,desc,Icon,color])=><button key={label} className={`summary-card ${color}`} onClick={()=>navigate(desc)}><div className="summary-icon"><Icon size={28}/></div><div className="summary-text"><div className="summary-count">{count}</div><div className="summary-label">{label}</div><div className="summary-desc">{desc}</div></div></button>)}</section>
  <div className="middle-grid"><section className="panel assets" id="zimmet"><SectionTitle title="Zimmetlerim" onClick={()=>demo('Zimmetlerim','2 aktif zimmet: Lenovo ThinkPad X1 Carbon Gen 11 ve Apple AirPods Pro')}/><div className="assets-grid">{[{name:'Lenovo ThinkPad',type:'Laptop',status:'Aktif'},{name:'Apple AirPods',type:'Donanım',status:'Aktif'}].map((a,i)=><div key={i} className="asset-card"><div className="asset-icon"><Laptop size={24}/></div><div className="asset-info"><div className="asset-name">{a.name}</div><div className="asset-type">{a.type}</div><div className={`asset-status ${a.status.toLowerCase()}`}>{a.status}</div></div></div>)}</div></section>
  <section className="panel agenda"><SectionTitle title="Ajandam" onClick={()=>demo('Ajandam')}/><div className="agenda-items">{[{time:'10:00',title:'BT Güvenlik Toplantısı'},{time:'14:00',title:'Proje Değerlendirme'},{time:'16:30',title:'Aylık Departman Toplantısı'}].map((e,i)=><div key={i} className="agenda-item"><div className="agenda-time">{e.time}</div><div className="agenda-title">{e.title}</div></div>)}</div></section>
  <section className="panel announcements" id="duyurular"><SectionTitle title="Duyurular" onClick={()=>demo('Duyurular',announcements.map(a=>a.title).join(' • '))}/><div className="announcement-grid">{announcements.map((a,i)=><div key={i} className="announcement-card"><div className="announcement-photo"><Photo src={a.image} alt={a.title}/></div><div className="announcement-info"><div className="announcement-category">{a.category}</div><div className="announcement-title">{a.title}</div><div className="announcement-date">{a.date}</div></div></div>)}</div></section>
  <section className="panel events" id="etkinlik"><SectionTitle title="Şirket Etkinlikleri" onClick={()=>demo('Şirket Etkinlikleri')}/><div className="events-list">{[{date:'20 Ara',title:'Yıl Sonu Toplantısı'},{date:'25 Ara',title:'BT Güvenlik Eğitimi'},{date:'31 Ara',title:'Yıl Sonu Partisi'}].map((e,i)=><div key={i} className="event-item"><div className="event-date">{e.date}</div><div className="event-title">{e.title}</div></div>)}</div></section>
  <section className="panel directory" id="rehber"><div className="directory-head"><h2>İletişim Rehberi</h2><label className="directory-search"><Search size={16}/><input placeholder="İsim, departman, telefon..." value={search} onChange={(e)=>setSearch(e.target.value)}/></label><select value={department} onChange={(e)=>setDepartment(e.target.value)} aria-label="Departman seç"><option>Tüm Departmanlar</option>{[...new Set(people.map(p=>p[2]))].sort().map(d=><option key={d}>{d}</option>)}</select></div><div className="directory-list">{shown.map(([name,title,dept,email,phone],i)=><div key={i} className="directory-item"><Image src={`/avatars/avatar-${i}.webp`} alt={name} width={40} height={40}/><div className="directory-info"><div className="directory-name">{name}</div><div className="directory-title">{title}</div><div className="directory-contact"><span>{email}</span> • <span>{phone}</span></div></div></div>)}</div></section></div>
  <aside className="right-column"><section className="office-banner"><WeatherWidget/></section>
  <section className="panel quick-access"><h2>Hızlı Erişim</h2><div className="quick-grid">{quick.map(([label,Icon,color])=><button className={color} key={label} onClick={()=>navigate(label)}><Icon size={20}/><span>{label}</span></button>)}</div></section>
  <section className="panel suggestions" id="oneriler"><SectionTitle title="Öneri ve Bildirimler" onClick={()=>demo('Öneri ve Bildirimler','2 öneri ve 3 bildirim görüntüleniyor.')}/><div className="suggestion-tabs"><button className={`tab ${suggestionTab===0?'active':''}`} onClick={()=>setSuggestionTab(0)}>Öneriler</button><button className={`tab ${suggestionTab===1?'active':''}`} onClick={()=>setSuggestionTab(1)}>Bildirimler</button></div><div className="suggestion-content">{suggestionTab===0?[{icon:CircleHelp,title:'İzin Talebi Formu',text:'Yeni izin talebi formu kullanıma açıldı.'},{icon:Building2,title:'Ofis Kullanım Rehberi',text:'Ofis ortamı kuralları güncellenmiştir.'}]:[{icon:Bell,title:'Zimmet Yoklaması',text:'Sistem tarafından otomatik zimmet yoklaması yapıldı.'},{icon:FileText,title:'Aylık Rapor',text:'Aylık verimlilik raporu hazırlanmıştır.'}]}.map(({icon:Icon,title,text},i)=><div key={i} className="suggestion-item"><Icon size={16}/><div className="suggestion-text"><div className="suggestion-title">{title}</div><div className="suggestion-desc">{text}</div></div></div>)}</div></section>
  <section className="panel news"><SectionTitle title="Haberler" onClick={()=>demo('Haberler',"Koyuncu Grup\'tan sürdürülebilirlik alanında yeni adım • Yeni ofisimiz açıldı • Yıl sonu etkinliği başlıyor")}/><div className="news-list">{[{title:'Koyuncu Grup Sürdürülebilirlik Raporu',date:'14 Aralık'},{title:'Yeni Teknoloji Yatırımları',date:'12 Aralık'},{title:'Çalışan Memnuniyet Anketi',date:'10 Aralık'}].map((n,i)=><div key={i} className="news-item"><div className="news-title">{n.title}</div><div className="news-date">{n.date}</div></div>)}</div></section></aside></main></div>
  {modal&&<div className="modal-overlay" onClick={()=>setModal(null)}><section role="dialog" aria-modal="true" aria-labelledby="dialog-title" className="modal" onClick={e=>e.stopPropagation()} onKeyDown={e=>e.key==='Escape'&&setModal(null)}><button className="modal-close" onClick={()=>setModal(null)} aria-label="Kapat"><X size={20}/></button><h2 id="dialog-title">{modal.title}</h2><p>{modal.text}</p></section></div>}
  </div>
  </div>
}
