'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {Search,ArrowRight,ChevronRight} from 'lucide-react';
import {Person,DirectoryData,Birthday,shortDate} from '@/lib/directory-shared';
export function PersonPhoto({person}:{person:{photo:string|null;name:string}}){return person.photo?<img src={person.photo} alt={person.name} width={42} height={42}/>:<span className="directory-avatar">{person.name.split(' ').map(s=>s[0]).slice(0,2).join('')}</span>;}
export function Absence({person}:{person:Person}){const a=person.absence;if(!a)return null;return <div className="person-absence"><strong>Ofis Dışında{a.leave_type?' · '+a.leave_type:''}</strong><small>{a.from?shortDate(a.from)+' – ':''}{shortDate(a.until)} tarihine kadar · Dönüş: {shortDate(a.return_date)}</small>{a.backup&&<small>Yerine Bakan: <Link href={'/directory/'+a.backup.id}>{a.backup.name}</Link>{a.backup.job_title?' · '+a.backup.job_title:''}</small>}</div>;}
export function PersonCards({rows}:{rows:Person[]}){return <div className="people-grid">{rows.length?rows.map(p=><article className="person" key={p.id}><Link className="person-top" href={'/directory/'+p.id}><PersonPhoto person={p}/><div><h3>{p.name}</h3><small>{p.job_title||'—'}<br/>{p.department||''}</small></div><ChevronRight size={13}/></Link><div className="person-contact"><span>{p.company||''}</span></div><div className="person-contact"><span>{[p.location,p.unit].filter(Boolean).join(' · ')}</span></div><Absence person={p}/></article>):<p className="no-results">Aramanızla eşleşen kişi bulunamadı.</p>}</div>;}
export default function Directory({initial,compact=false,filters={}}:{initial?:DirectoryData;compact?:boolean;filters?:Record<string,string>}){const router=useRouter(),[data,setData]=useState<DirectoryData>(initial??{rows:[],total:0,page:1,size:5}),[birthdays,setBirthdays]=useState<Birthday[]>([]),[q,setQ]=useState(filters.q??''),[department,setDepartment]=useState(filters.department_id??''),[options,setOptions]=useState<Record<string,{id:string;name:string}[]>>({}),[loading,setLoading]=useState(!initial),[error,setError]=useState(''),loaded=useRef(false);useEffect(()=>{if(compact)return;fetch('/api/directory/options',{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);setOptions(d);}).catch(e=>setError(e.message));},[]);useEffect(()=>{if(!compact)return;const c=new AbortController();setLoading(true);const timer=setTimeout(()=>{const p=new URLSearchParams({compact:'1',q,department_id:department});if(!loaded.current)p.set('birthdays','1');fetch('/api/directory?'+p,{signal:c.signal,cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error||'Rehber yüklenemedi.');setData(d);if(d.birthdays)setBirthdays(d.birthdays);if(d.options)setOptions(d.options);loaded.current=true;setError('');}).catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>{if(!c.signal.aborted)setLoading(false);});},q?350:0);return()=>{clearTimeout(timer);c.abort();};},[q,department,compact]);const filter=(key:string,label:string,group:string)=><label className="a-field"><span>{label}</span><select name={key} defaultValue={filters[key]??''}><option value="">Tümü</option>{options[group]?.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label>;
return <section className={compact?'panel directory':'directory-page'} id={compact?'rehber':undefined}>{compact?<div className="directory-head"><h2>İletişim Rehberi</h2><label className="directory-search"><Search size={16}/><input placeholder="İsim, departman, ünvan veya e-posta ile ara..." aria-label="İletişim rehberinde ara" value={q} maxLength={100} onChange={e=>setQ(e.target.value)}/></label><select aria-label="Departman filtresi" value={department} onChange={e=>setDepartment(e.target.value)}><option value="">Tüm Departmanlar</option>{options.departments?.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select><Link className="text-link" href="/directory">Tümünü Gör <ArrowRight size={12}/></Link></div>:<form className="a-card a-filters" onSubmit={e=>{e.preventDefault();const p=new URLSearchParams();new FormData(e.currentTarget).forEach((v,k)=>{if(typeof v==='string'&&v)p.set(k,v);});router.push('/directory?'+p);}}><label className="a-field"><span>Ara</span><input name="q" defaultValue={filters.q??''} maxLength={100} placeholder="Ad, ünvan, departman, lokasyon…"/></label>{filter('company_id','Şirket','companies')}{filter('location_id','Lokasyon','locations')}{filter('department_id','Departman','departments')}{filter('unit_id','Birim','units')}<button className="a-primary">Filtrele</button><Link href="/directory">Temizle</Link></form>}{error&&<p role="alert">{error}</p>}{loading?<p className="no-results" role="status">Rehber yükleniyor…</p>:<PersonCards rows={data.rows}/>} {!compact&&<div className="a-pagination"><span>{data.total} kişi · Sayfa {data.page}</span>{data.page>1&&<Link href={'/directory?'+new URLSearchParams({...filters,page:String(data.page-1)})}>← Önceki</Link>}{data.page*data.size<data.total&&<Link href={'/directory?'+new URLSearchParams({...filters,page:String(data.page+1)})}>Sonraki →</Link>}</div>}{compact&&birthdays.length>0&&<div className="birthday-strip"><h3>🎂 Doğum Günleri</h3><div>{birthdays.map(p=><Link href={'/directory/'+p.id} key={p.id}><PersonPhoto person={p}/><span><b>{p.days_away===0?'Bugün':`${p.day} ${shortDate(`2000-${String(p.month).padStart(2,'0')}-01`).split(' ').slice(1).join(' ')}`}</b><strong>{p.name}</strong><small>{p.job_title}</small></span></Link>)}</div></div>}</section>;}
