 'use client';
import {useState,FormEvent} from 'react';
import {useRouter} from 'next/navigation';
import {Vehicle,fleetStates} from '@/lib/fleet-shared';
import {readProof} from './ProofFiles';
type Option={id:string;name:string;company_id?:string};
export function FleetForm({action,children,convert}:{action:string;children:React.ReactNode;convert?:(d:Record<string,unknown>)=>Record<string,unknown>}){const [error,setError]=useState(''),[busy,setBusy]=useState(false);const router=useRouter();async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');try{const d:Record<string,unknown>={};for(const [k,v] of new FormData(e.currentTarget)){if(v instanceof File){if(v.size)d[k]=await readProof(v);else d[k]=null;}else d[k]=v;}for(const k of ['km','start_km','end_km','model_year','next_service_km','cost'])if(k in d)d[k]=d[k]===''?null:Number(d[k]);for(const k of ['vin','insurance_end','casco_end','inspection_date','last_service_date','next_service_date'])if(d[k]==='')d[k]=null;const res=await fetch('/api/fleet/'+action,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(convert?convert(d):d)});const result=await res.json();if(!res.ok)throw Error(result.error||'İşlem yapılamadı.');if(action==='vehicles')router.push('/admin/fleet/'+result.id);else router.refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}return <form className="a-card a-form" onSubmit={submit}>{children}{error&&<p role="alert">{error}</p>}<button className="a-primary" disabled={busy}>{busy?'Kaydediliyor…':'Kaydet'}</button></form>;}
export function Field({name,label,type='text',value,required=false}:{name:string;label:string;type?:string;value?:string|number|null;required?:boolean}){return <label className="a-field">{label}<input name={name} type={type} defaultValue={value??''} required={required} min={type==='number'?0:undefined}/></label>;}
export function VehicleEditor({item,companies,locations,documents}:{item?:Vehicle;companies:Option[];locations:Option[];documents:boolean}){const [company,setCompany]=useState(item?.company_id??'');return <FleetForm action={'vehicles'+(item?'/'+item.id:'')}><div className="form-grid">{[['plate','Plaka'],['brand','Marka'],['model','Model'],['fuel','Yakıt Türü']].map(([n,l])=><Field key={n} name={n} label={l} value={item?.[n as keyof Vehicle] as string} required/>)}<Field name="model_year" label="Model Yılı" type="number" value={item?.model_year} required/><Field name="km" label="Kilometre" type="number" value={item?.km??0} required/><Field name="vin" label="Şasi No" value={item?.vin}/><label className="a-field">Şirket<select name="company_id" value={company} onChange={e=>setCompany(e.target.value)} required><option value="">Seçin</option>{companies.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="a-field">Lokasyon<select name="location_id" defaultValue={item?.location_id} required><option value="">Seçin</option>{locations.filter(x=>x.company_id===company).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="a-field">Durum<select name="status" defaultValue={item?.status??'POOL'}>{Object.entries(fleetStates).filter(([k])=>k!=='ASSIGNED'||item?.status==='ASSIGNED').map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>{[['insurance_end','Trafik Sigortası Bitiş'],['casco_end','Kasko Bitiş'],['inspection_date','Muayene'],['last_service_date','Son Bakım'],['next_service_date','Sonraki Bakım']].map(([n,l])=><Field key={n} name={n} label={l} type="date" value={item?.[n as keyof Vehicle] as string}/>)}<Field name="next_service_km" label="Sonraki Bakım KM" type="number" value={item?.next_service_km}/><Field name="tires" label="Lastik Bilgisi" value={item?.tires}/>{documents&&<><Field name="registration" label="Ruhsat Bilgileri" value={item?.registration}/><Field name="hgs_reference" label="HGS Referansı" value={item?.hgs_reference}/></>}<Field name="notes" label="Not" value={item?.notes}/></div></FleetForm>;}
export function AllocationForm({item,users}:{item:Vehicle;users:Option[]}){return <FleetForm action={(item.status==='ASSIGNED'?'return/':'assign/')+item.id}><h2>{item.status==='ASSIGNED'?'Tahsis İadesi':'Araç Tahsis Et'}</h2>{item.status==='ASSIGNED'?<><Field name="end_km" label="Bitiş KM" type="number" value={item.km} required/><label className="a-field">İade Durumu<select name="status">{Object.entries(fleetStates).filter(([k])=>k!=='ASSIGNED').map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label></>:<><label className="a-field">Çalışan<select name="user_id" required><option value="">Seçin</option>{users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label><Field name="start_km" label="Başlangıç KM" type="number" value={item.km} required/></>}<Field name="note" label="Not"/></FleetForm>;}
export function FleetUpload({id,documents}:{id:string;documents:boolean}){return <FleetForm action={'file/'+id}><h2>Görsel / Evrak Ekle</h2><label className="a-field">Tür<select name="kind"><option value="IMAGE">Görsel</option>{documents&&<option value="DOCUMENT">Evrak</option>}</select></label><label className="a-field">Dosya (en fazla 200 KB)<input type="file" name="file" accept="image/png,image/jpeg,image/webp,application/pdf" required/></label></FleetForm>;}
export function FleetServiceForm({item,documents}:{item:Vehicle;documents:boolean}){return <FleetForm action={'service/'+item.id} convert={d=>({...d,document:d.document??null})}><h2>Servis / Bakım Kaydı</h2><label className="a-field">İşlem<select name="kind">{[['MAINTENANCE','Bakım'],['FAULT','Arıza'],['SERVICE','Servis'],['ACCIDENT','Hasar / Kaza']].map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label><Field name="date" label="Tarih" type="date" required/><Field name="km" label="Kilometre" type="number" value={item.km} required/><Field name="provider" label="Servis Firması" required/><Field name="description" label="Açıklama"/><Field name="cost" label="Maliyet" type="number"/>{documents&&<label className="a-field">Evrak (en fazla 200 KB)<input type="file" name="document" accept="application/pdf,image/png,image/jpeg,image/webp"/></label>}<Field name="next_service_date" label="Sonraki Bakım Tarihi" type="date"/><Field name="next_service_km" label="Sonraki Bakım KM" type="number"/></FleetForm>;}
