'use client';
import WorkflowNav from './WorkflowNav';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import Image from 'next/image';
import {useRouter} from 'next/navigation';
import {Identity,can,canAction} from '@/lib/permissions';
import {statusLabels,profileLabels,extraFields,dateLabel} from '@/lib/inventory-shared';
import InventoryNav from './InventoryNav';
import ContentNav from './ContentNav';
import ProfileMenu from './ProfileMenu';
type Row=Record<string,any>;
async function api(path='',method='GET',body?:unknown){const response=await fetch('/api/inventory/'+path,{method,cache:'no-store',...(body?{headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});const data=await response.json();if(!response.ok)throw Error(data.error||'İşlem tamamlanamadı.');return data;}
const empty={asset_number:'',category_id:'',brand:'',model:'',serial_number:'',company_id:'',location_id:'',department_id:'',purchase_date:'',warranty_end:'',supplier:'',invoice_number:'',notes:'',image:null,status:'STOCK',extras:{}};
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="a-field"><span>{label}</span>{children}</label>}
export default function InventoryPanel({actor,path,initial}:{actor:Identity;path:string[];initial:Row}){
 const router=useRouter(),category=path[1]==='categories',assignments=path[0]==='assignments',isNew=path[1]==='new',id=!category&&!assignments&&!isNew?path[1]:undefined,editing=isNew||path[2]==='edit';
 const [data,setData]=useState(initial),[options,setOptions]=useState<Row>({}),[form,setForm]=useState<Row>(initial.item??empty),[modal,setModal]=useState<Row|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[ready,setReady]=useState(false),[filters,setFilters]=useState<Row>({q:'',page:1,sort:'asset_number',dir:'asc'}),[loading,setLoading]=useState(false);
 const initialized=useRef(false),sequence=useRef(0);const allowed=(p:string)=>can(actor,p);const endpoint=category?'categories':assignments?'assignments':id?'items/'+id:'';
 async function load(){const seq=++sequence.current;setLoading(true);try{const qs=new URLSearchParams(Object.entries(filters).filter(([,v])=>v!==''&&v!=null).map(([k,v])=>[k,String(v)]));const result=await api(endpoint+(id||category?'':'?'+qs));if(seq===sequence.current)setData(result);}catch(e){setError((e as Error).message);}finally{if(seq===sequence.current)setLoading(false);}}
 useEffect(()=>{if(category){setReady(true);return;}let alive=true;api('options').then(v=>{if(alive){setOptions(v);setReady(true);}}).catch(e=>{if(alive)setError(e.message);});return ()=>{alive=false;};},[category]);
 useEffect(()=>{if(editing||id||category)return;if(!initialized.current){initialized.current=true;return;}const timer=setTimeout(()=>void load(),220);return ()=>clearTimeout(timer);},[filters]);
 async function action(fn:()=>Promise<any>){setBusy(true);setError('');setNotice('');try{const result=await fn();setNotice('İşlem kaydedildi.');return result;}catch(e){setError((e as Error).message);return null;}finally{setBusy(false);}}
 const set=(k:string,v:unknown)=>setForm(f=>({...f,[k]:v,...(k==='company_id'?{location_id:'',department_id:''}:k==='category_id'?{extras:{}}:{})}));
 const input=(k:string,label:string,type='text',required=false)=><Field key={k} label={label}><input type={type} required={required} maxLength={k==='notes'?2000:200} value={form[k]??''} onChange={e=>set(k,e.target.value)}/></Field>;
 const select=(k:string,label:string,rows:Row[],required=false,disabled=false)=><Field key={k} label={label}><select required={required} disabled={disabled} value={form[k]??''} onChange={e=>set(k,e.target.value)}><option value="">Seçin</option>{rows.map(r=><option key={r.id} value={r.id} disabled={r.active===false&&form[k]!==r.id}>{r.name}{r.active===false?' (Pasif)':''}</option>)}</select></Field>;
 const filter=(k:string,label:string,rows:Row[])=><Field key={k} label={label}><select value={filters[k]??''} onChange={e=>setFilters({...filters,[k]:e.target.value,page:1,...(k==='company_id'?{location_id:''}:{})})}><option value="">Tümü</option>{rows.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></Field>;
 const open=(kind:string,row:Row={})=>{setError('');setModal({kind,...row});if(kind==='category')setForm({name:'',code:'',icon:'package',description:'',active:true,field_profile:'BASIC',...row});else if(kind==='assign')setForm({inventory_id:row.id,user_id:'',assigned_at:new Date().toISOString().slice(0,10),note:''});else if(kind==='return')setForm({returned_at:new Date().toISOString().slice(0,10),return_note:'',return_condition:'STOCK'});else if(kind==='note')setForm({note:row.note});else setForm({status:row.status||'STOCK'});};
 const historyTable=(rows:Row[])=><div className="a-table-wrap"><table className="a-table"><thead><tr>{['Envanter','Çalışan','Zimmet Tarihi','Teslim Eden','Not','İade Tarihi','İade Alan','İade Durumu / Not','İşlem'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{rows.map(a=><tr key={a.id}><td>{allowed('inventory.view')?<Link className="a-link" href={'/admin/inventory/'+a.inventory_id}>{a.asset_number}</Link>:a.asset_number}</td><td>{a.employee}</td><td>{dateLabel(a.assigned_at)}</td><td>{a.delivered_by_name}</td><td>{a.note||'—'}</td><td>{a.returned_at?dateLabel(a.returned_at):<span className="a-status ACTIVE">Aktif</span>}</td><td>{a.received_by_name||'—'}</td><td>{statusLabels[a.return_condition]||'—'} {a.return_note}</td><td>{!a.returned_at&&<>{allowed('assignments.return')&&<button className="a-link" onClick={()=>open('return',a)}>İade Al</button>} {allowed('assignments.manage')&&<button className="a-link" onClick={()=>open('note',a)}>Not Düzenle</button>}</>}</td></tr>)}</tbody></table>{!rows.length&&<p className="a-empty">Zimmet kaydı bulunmuyor.</p>}</div>;
 const title=category?'Envanter Kategorileri':assignments?'Zimmetler':editing?isNew?'Yeni Envanter':'Envanter Düzenle':id?'Envanter Detayı':'Envanter Listesi';
 return <div className="admin-shell"><aside className="admin-nav"><Link className="admin-brand" href="/admin"><Image src="/brand/koyuncu-grup.png" alt="Koyuncu Grup" width={145} height={51}/></Link><small>YÖNETİM PANELİ</small><Link href="/admin">Yönetim Özeti</Link>{[['users','Kullanıcılar'],['companies','Şirketler'],['locations','Lokasyonlar'],['departments','Departmanlar'],['units','Birimler'],['job-titles','Ünvanlar'],['roles','Roller & Yetkiler'],['settings','Sistem Ayarları']].filter(([r])=>canAction(actor,r==='job-titles'?'jobtitles':r,'view')).map(([r,n])=><Link key={r} href={'/admin/'+r}>{n}</Link>)}<InventoryNav actor={actor}/><ContentNav actor={actor}/><WorkflowNav actor={actor}/><Link className="back-portal" href="/">← Çalışan Portalı</Link></aside><div className="admin-main"><header className="admin-header"><span>Koyuncu Grup <b>/ Yönetim</b></span><ProfileMenu actor={actor}/></header><main className="admin-content"><div className="admin-heading"><div><span className="eyebrow">ENVANTER YÖNETİMİ</span><h1>{title}</h1></div>{category&&allowed('inventory_categories.manage')&&<button className="a-primary" onClick={()=>open('category')}>+ Yeni Kategori</button>}{!category&&!assignments&&!id&&!editing&&allowed('inventory.create')&&<Link className="a-primary" href="/admin/inventory/new">+ Yeni Envanter</Link>}{assignments&&allowed('inventory.view')&&allowed('assignments.create')&&<Link className="a-primary" href="/admin/inventory">Envanter Seç / Zimmetle</Link>}</div>
 {error&&<p className="form-error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {editing?<form onSubmit={async e=>{e.preventDefault();const payload=Object.fromEntries(Object.keys(empty).map(k=>[k,form[k]??(empty as Row)[k]]));const result=await action(()=>api('items'+(id?'/'+id:''),id?'PATCH':'POST',payload));if(result){router.push(allowed('inventory.view')?'/admin/inventory/'+result.id:'/admin');router.refresh();}}}><section className="a-card"><div className="form-grid">{input('asset_number','Demirbaş No','text',true)}{select('category_id','Kategori',options.categories??[],true)}{input('brand','Marka')}{input('model','Model')}{input('serial_number','Seri No')}{select('company_id','Şirket',options.companies??[],true)}{select('location_id','Lokasyon',(options.locations??[]).filter((r:Row)=>r.company_id===form.company_id),true)}{select('department_id','Departman',(options.departments??[]).filter((r:Row)=>r.company_id===form.company_id))}{input('purchase_date','Satın Alma Tarihi','date')}{input('warranty_end','Garanti Bitiş Tarihi','date')}{input('supplier','Tedarikçi')}{input('invoice_number','Fatura No')}{select('status','Durum',Object.entries(statusLabels).filter(([k])=>k!=='ASSIGNED'||form.status==='ASSIGNED').map(([id,name])=>({id,name})),true,!!id&&(!allowed('inventory.manage')||initial.item?.status==='ASSIGNED'))}{input('notes','Açıklama / Not')}{(extraFields[(options.categories??[]).find((r:Row)=>r.id===form.category_id)?.field_profile??'BASIC']??[]).map(([key,label])=><Field key={key} label={label}><input maxLength={200} value={form.extras?.[key]??''} onChange={e=>set('extras',{...form.extras,[key]:e.target.value})}/></Field>)}<Field label="Görsel (PNG / JPG / WebP, en fazla 200 KB)"><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>200000||!['image/png','image/jpeg','image/webp'].includes(file.type)){setError('En fazla 200 KB PNG, JPG veya WebP seçin.');return;}const reader=new FileReader();reader.onload=()=>set('image',reader.result);reader.readAsDataURL(file);}}/>{form.image&&<><img src={form.image} alt="Envanter görseli" style={{width:160,height:120,objectFit:'contain'}}/><button type="button" className="a-link" onClick={()=>set('image',null)}>Görseli kaldır</button></>}</Field></div></section><div className="a-actions"><button className="a-primary" disabled={busy||!ready}>{busy?'Kaydediliyor…':'Kaydet'}</button><Link className="a-button" href="/admin/inventory">Listeye Dön</Link></div></form>:
 category?<div className="a-table-wrap"><table className="a-table"><thead><tr>{['Kod','Ad','İkon','Açıklama','Alanlar','Durum','İşlem'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{data.rows?.map((r:Row)=><tr key={r.id}><td>{r.code}</td><td>{r.name}</td><td>{r.icon}</td><td>{r.description}</td><td>{profileLabels[r.field_profile]}</td><td>{r.active?'Aktif':'Pasif'}</td><td>{allowed('inventory_categories.manage')&&<button className="a-link" onClick={()=>open('category',r)}>Düzenle</button>}</td></tr>)}</tbody></table></div>:
 id?<><section className="a-card">{data.item.image&&<img src={data.item.image} alt={data.item.asset_number} style={{width:220,height:160,objectFit:'contain'}}/>}<div className="a-actions">{allowed('inventory.edit')&&<Link className="a-button" href={'/admin/inventory/'+id+'/edit'}>Düzenle</Link>}{allowed('assignments.create')&&['STOCK','RETURNED'].includes(data.item.status)&&<button disabled={!ready} className="a-primary" onClick={()=>open('assign',{id})}>Zimmetle</button>}{allowed('inventory.manage')&&data.item.status!=='ASSIGNED'&&<><button className="a-button" onClick={()=>open('status',{id,status:'SERVICE'})}>Servise Gönder</button><button className="a-button" onClick={()=>open('status',{id,status:data.item.status})}>Durum Değiştir</button><button className="a-button" onClick={()=>open('status',{id,status:'INACTIVE'})}>Pasife Al</button></>}<Link className="a-button" href="/admin/inventory">Listeye Dön</Link></div><dl className="detail-grid">{[['asset_number','Demirbaş No'],['category_name','Kategori'],['brand','Marka'],['model','Model'],['serial_number','Seri No'],['company_name','Şirket'],['location_name','Lokasyon'],['department_name','Departman'],['assignee','Mevcut Zimmetli Kişi'],['purchase_date','Satın Alma'],['warranty_end','Garanti Bitiş'],['supplier','Tedarikçi'],['invoice_number','Fatura No'],['notes','Not']].map(([k,l])=><div key={k}><dt>{l}</dt><dd>{data.item[k]||'—'}</dd></div>)}<div><dt>Durum</dt><dd>{statusLabels[data.item.status]}</dd></div>{(extraFields[data.item.field_profile]??[]).map(([k,l])=><div key={k}><dt>{l}</dt><dd>{data.item.extras?.[k]||'—'}</dd></div>)}</dl></section>{allowed('assignments.view')&&<section className="a-card"><h2>Zimmet Geçmişi</h2>{historyTable(data.history??[])}</section>}</>:
 <><div className="a-filters"><Field label="Ara"><input placeholder={assignments?'Demirbaş / Çalışan':'Demirbaş / Seri / Marka / Model'} value={filters.q} onChange={e=>setFilters({...filters,q:e.target.value,page:1})}/></Field>{assignments?filter('status','Durum',[{id:'ACTIVE',name:'Aktif'},{id:'RETURNED',name:'İade Edildi'}]):<>{filter('category_id','Kategori',options.categories??[])}{filter('company_id','Şirket',options.companies??[])}{filter('location_id','Lokasyon',(options.locations??[]).filter((r:Row)=>!filters.company_id||r.company_id===filters.company_id))}{filter('status','Durum',Object.entries(statusLabels).map(([id,name])=>({id,name})))}{filter('assigned','Zimmet',[{id:'yes',name:'Zimmetli'},{id:'no',name:'Stokta'}])}{filter('sort','Sırala',[{id:'asset_number',name:'Demirbaş No'},{id:'category',name:'Kategori'},{id:'brand',name:'Marka'},{id:'status',name:'Durum'},{id:'created',name:'Oluşturma'}])}{filter('dir','Yön',[{id:'asc',name:'Artan'},{id:'desc',name:'Azalan'}])}</>}</div>{loading&&<p role="status">Yükleniyor…</p>}{assignments?historyTable(data.rows??[]):<div className="a-table-wrap"><table className="a-table"><thead><tr>{['Demirbaş No','Kategori','Marka / Model','Seri No','Şirket','Lokasyon','Durum','Zimmetli Kişi'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{data.rows?.map((r:Row)=><tr key={r.id}><td><Link className="a-link" href={'/admin/inventory/'+r.id}>{r.asset_number}</Link></td><td>{r.category_name}</td><td>{r.brand} {r.model}</td><td>{r.serial_number||'—'}</td><td>{r.company_name}</td><td>{r.location_name}</td><td>{statusLabels[r.status]}</td><td>{r.assignee||'—'}</td></tr>)}</tbody></table>{!data.rows?.length&&<p className="a-empty">Envanter bulunmuyor.</p>}</div>}<div className="a-actions"><button className="a-button" disabled={filters.page<=1||loading} onClick={()=>setFilters({...filters,page:filters.page-1})}>Önceki</button><span>{data.total??0} kayıt · Sayfa {filters.page}</span><button className="a-button" disabled={filters.page*20>=(data.total??0)||loading} onClick={()=>setFilters({...filters,page:filters.page+1})}>Sonraki</button></div></>}
 {modal&&<div className="admin-modal-backdrop"><section className="admin-modal" role="dialog" aria-modal="true" aria-label="Envanter işlemi"><button className="a-close" onClick={()=>setModal(null)} aria-label="Kapat">×</button><h2>{{category:'Kategori',assign:'Zimmetle',return:'İade Al',note:'Zimmet Notu',status:'Durum Değiştir'}[modal.kind as string]}</h2>{error&&<p role="alert" className="form-error">{error}</p>}<form onSubmit={async e=>{e.preventDefault();const kind=modal.kind;const payload=kind==='category'?Object.fromEntries(['name','code','icon','description','active','field_profile'].map(k=>[k,form[k]])):form;const result=await action(()=>kind==='category'?api('categories'+(modal.id?'/'+modal.id:''),modal.id?'PATCH':'POST',payload):kind==='assign'?api('assignments','POST',payload):kind==='return'?api('assignments/'+modal.id+'/return','POST',payload):kind==='note'?api('assignments/'+modal.id,'PATCH',payload):api('items/'+modal.id+'/status','POST',payload));if(result){setModal(null);await load();}}}><div className="form-grid">{modal.kind==='category'?<>{input('name','Ad','text',true)}{input('code','Kod','text',true)}{input('icon','İkon')}{input('description','Açıklama')}{select('field_profile','Kategori Alanları',Object.entries(profileLabels).map(([id,name])=>({id,name})),true)}<Field label="Durum"><select value={form.active?'1':'0'} onChange={e=>set('active',e.target.value==='1')}><option value="1">Aktif</option><option value="0">Pasif</option></select></Field></>:modal.kind==='assign'?<>{select('user_id','Çalışan',options.users??[],true)}{input('assigned_at','Zimmet Tarihi','date',true)}{input('note','Not')}<p>Teslim Eden: {actor.first_name} {actor.last_name}</p></>:modal.kind==='return'?<>{input('returned_at','İade Tarihi','date',true)}{select('return_condition','İade Durumu',Object.entries(statusLabels).filter(([k])=>!['ASSIGNED','RETURNED'].includes(k)).map(([id,name])=>({id,name})),true)}{input('return_note','İade Notu')}<p>İade Alan: {actor.first_name} {actor.last_name}</p></>:modal.kind==='note'?input('note','Not'):select('status','Durum',Object.entries(statusLabels).filter(([k])=>k!=='ASSIGNED').map(([id,name])=>({id,name})),true)}</div><div className="a-actions"><button className="a-primary" disabled={busy}>{busy?'Kaydediliyor…':'Kaydet'}</button><button type="button" className="a-button" onClick={()=>setModal(null)}>Vazgeç</button></div></form></section></div>}
 </main></div></div>;
}
