'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import Image from 'next/image';
import {useRouter} from 'next/navigation';
import {Identity,can} from '@/lib/permissions';
import {roomFeatures,reservationStatuses} from '@/lib/meeting-shared';
import ProfileMenu from './ProfileMenu';
import WorkflowNav from './WorkflowNav';
import ContentNav from './ContentNav';
import InventoryNav from './InventoryNav';
type Row=Record<string,any>;
async function api(path:string,body?:unknown){const r=await fetch('/api/meetings/'+path,{cache:'no-store',method:body?'POST':'GET',...(body?{headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});const data=await r.json();if(!r.ok)throw Error(data.error||'İşlem tamamlanamadı.');return data;}
export default function MeetingPanel({actor,admin,view,id,initial,filters}:{actor:Identity;admin:boolean;view:string;id?:string;initial:Row;filters:Row}){const router=useRouter(),roomForm=admin&&view==='rooms'&&!!id,bookingForm=!admin&&!!id,base=admin?'/admin/'+(view==='rooms'?'meeting-rooms':'meeting-reservations'):view==='rooms'?'/meeting-rooms':'/meeting-rooms/my-reservations';const [options,setOptions]=useState<Row>({locations:[],rooms:[]}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[location,setLocation]=useState(initial.location_id??filters.location_id??''),[form,setForm]=useState<Row>(roomForm?{name:initial.name??'',code:initial.code??'',location_id:initial.location_id??'',floor:initial.floor??'',capacity:initial.capacity??8,description:initial.description??'',image:initial.image??null,features:initial.features??[],active:initial.active??true}:{title:initial.title??'',room_id:initial.room_id??filters.room_id??'',description:initial.description??'',start:initial.start_local??filters.start??'',end:initial.end_local??filters.end??''});
useEffect(()=>{api('options'+(admin?'?admin=1':'')).then(d=>{setOptions(d);if(!location&&!Object.prototype.hasOwnProperty.call(filters,'location_id')&&(!admin||roomForm)){setLocation(d.default_location_id??'');if(roomForm)setForm(v=>({...v,location_id:d.default_location_id??''}));}}).catch(e=>setError(e.message));},[admin]);const availableRooms=(options.rooms??[]).filter((r:Row)=>r.location_id===location);const timezone=options.locations.find((l:Row)=>l.id===location)?.timezone??options.timezone??'Europe/Istanbul';
async function save(){if(busy)return;setBusy(true);setError('');try{const body=roomForm?{...form,location_id:location}:form;await api((roomForm?'rooms':'reservations')+(id&&id!=='new'?'/'+id:''),body);router.push(roomForm?'/admin/meeting-rooms':'/meeting-rooms/my-reservations');router.refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
async function cancel(r:Row){if(busy||!window.confirm('Bu rezervasyonu iptal etmek istiyor musunuz?'))return;setBusy(true);setError('');try{await api('reservations/'+r.id+'/cancel'+(admin?'?admin=1':''),{});setNotice('Rezervasyon iptal edildi.');router.refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
const field=(key:string,label:string,type='text',required=false)=><label className="a-field"><span>{label}</span><input type={type} required={required} maxLength={key==='title'?160:120} min={type==='number'?1:undefined} value={form[key]??''} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>;
const locSelect=(filter=false)=><label className="a-field"><span>Lokasyon</span><select name="location_id" required={!filter} value={location} onChange={e=>{setLocation(e.target.value);if(bookingForm)setForm(v=>({...v,room_id:''}));}}><option value="">{filter?'Tüm aktif lokasyonlar':'Seçin'}</option>{options.locations.map((r:Row)=><option key={r.id} value={r.id}>{r.company_name} · {r.name}</option>)}</select></label>;
const stamp=(r:Row,value:string)=>new Date(value).toLocaleString('tr-TR',{timeZone:r.timezone,dateStyle:'short',timeStyle:'short'});
const companies=[...new Map<string,Row>(options.locations.map((l:Row)=>[l.company_id,{id:l.company_id,name:l.company_name}] as [string,Row])).values()];
const paginate=()=>{const page=Number(filters.page||1);function url(n:number){return base+'?'+new URLSearchParams({...filters,page:String(n)});}return <div className="a-pagination"><span>{initial.total??0} kayıt · Sayfa {page}</span>{page>1&&<Link href={url(page-1)}>← Önceki</Link>}{page*20<(initial.total??0)&&<Link href={url(page+1)}>Sonraki →</Link>}</div>;};
return <div className={admin?'admin-shell':''}>{admin&&<aside className="admin-nav"><Link className="admin-brand" href="/admin"><Image src="/brand/koyuncu-grup.png" alt="Koyuncu Grup" width={145} height={51}/></Link>{can(actor,'admin.view')&&<Link href="/admin">Genel Bakış</Link>}<WorkflowNav actor={actor}/><InventoryNav actor={actor}/><ContentNav actor={actor}/><Link href="/">← Çalışan Portalı</Link></aside>}<div className={admin?'admin-main':''}><header className="admin-header"><Link href="/">← Çalışan Portalı</Link><ProfileMenu actor={actor}/></header><main className="admin-content" style={admin?undefined:{maxWidth:1150,margin:'auto'}}><div className="admin-heading"><div><span className="eyebrow">{admin?'TOPLANTI YÖNETİMİ':'ÇALIŞAN PORTALI'}</span><h1>{roomForm?(id==='new'?'Yeni Toplantı Odası':'Toplantı Odasını Düzenle'):bookingForm?(id==='new'?'Yeni Rezervasyon':'Rezervasyonu Düzenle'):view==='rooms'?'Toplantı Odaları':admin?'Rezervasyonlar':'Rezervasyonlarım'}</h1></div><div className="a-actions">{admin&&view==='rooms'&&!id&&<Link className="a-primary" href="/admin/meeting-rooms/new">+ Yeni Oda</Link>}{!admin&&<><Link className="a-button" href="/calendar">Ajandam</Link><Link className="a-button" href={view==='rooms'?'/meeting-rooms/my-reservations':'/meeting-rooms'}>{view==='rooms'?'Rezervasyonlarım':'Toplantı Odaları'}</Link>{can(actor,'meeting_reservations.create')&&id!=='new'&&<Link className="a-primary" href="/meeting-rooms/new">+ Rezervasyon</Link>}</>}</div></div>{error&&<p className="form-error" role="alert">{error}</p>}{notice&&<p className="form-success" role="status">{notice}</p>}
{(roomForm||bookingForm)&&<form className="a-card a-form" onSubmit={e=>{e.preventDefault();void save();}}><div className="form-grid">{roomForm?<>{field('name','Oda Adı','text',true)}{field('code','Kod','text',true)}{locSelect()}{field('floor','Kat')}{field('capacity','Kapasite','number',true)}<label className="a-field"><span>Durum</span><select value={String(form.active)} onChange={e=>setForm({...form,active:e.target.value==='true'})}><option value="true">Aktif</option><option value="false">Pasif</option></select></label></>:<>{field('title','Toplantı Başlığı','text',true)}{locSelect()}<label className="a-field"><span>Toplantı Odası</span><select required value={form.room_id} onChange={e=>setForm({...form,room_id:e.target.value})}><option value="">Seçin</option>{availableRooms.map((r:Row)=><option key={r.id} value={r.id}>{r.name} · {r.capacity} kişi</option>)}</select></label>{field('start','Başlangıç','datetime-local',true)}{field('end','Bitiş','datetime-local',true)}<p>Saatler lokasyonun {timezone} saat dilimindedir.</p></>}</div><label className="a-field"><span>Açıklama (opsiyonel)</span><textarea rows={4} maxLength={2000} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label>{roomForm&&<><fieldset><legend>Özellikler</legend><div className="meeting-features">{roomFeatures.map(f=><label key={f}><input type="checkbox" checked={form.features.includes(f)} onChange={e=>setForm({...form,features:e.target.checked?[...form.features,f]:form.features.filter((x:string)=>x!==f)})}/>{f}</label>)}</div></fieldset><label className="a-field"><span>Görsel (opsiyonel, PNG/JPEG/WebP, en fazla 200 KB)</span><input type="file" accept="image/png,image/jpeg,image/webp" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>200000){setError('Görsel en fazla 200 KB olabilir.');e.target.value='';return;}const value=await new Promise<string>(resolve=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.readAsDataURL(f);});setForm({...form,image:value});}}/></label>{form.image&&<button type="button" className="a-button" onClick={()=>setForm({...form,image:null})}>Görseli kaldır</button>}</>}<div className="a-actions"><button className="a-primary" disabled={busy||bookingForm&&!can(actor,id==='new'?'meeting_reservations.create':'meeting_reservations.edit_own')}>{busy?'Kaydediliyor…':'Kaydet'}</button><Link className="a-button" href={base}>Vazgeç</Link></div></form>}
{roomForm&&initial.upcoming&&<section className="a-card"><h2>Yaklaşan Rezervasyonlar</h2>{initial.upcoming.length?initial.upcoming.map((r:Row)=><p key={r.id}><strong>{r.title}</strong> · {r.organizer_name}<br/>{stamp(initial,r.start_at)} – {stamp(initial,r.end_at)}</p>):<p>Yaklaşan rezervasyon yok.</p>}<Link href={'/admin/meeting-reservations?room_id='+id}>Tüm rezervasyonları gör</Link></section>}
{!id&&<><form className="a-card a-filters" action={base} onSubmit={e=>{e.preventDefault();const p=new URLSearchParams();new FormData(e.currentTarget).forEach((v,k)=>{if(typeof v==='string')p.set(k,v);});router.push(base+'?'+p);}}><label className="a-field"><span>Ara</span><input name="q" defaultValue={filters.q??''} placeholder={view==='rooms'?'Oda adı / kod':'Başlık / oda'}/></label>{locSelect(true)}{admin&&<label className="a-field"><span>Şirket</span><select name="company_id" defaultValue={filters.company_id??''}><option value="">Tümü</option>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>}{view==='rooms'?<><label className="a-field"><span>Kapasite ihtiyacı</span><input name="capacity" type="number" min={1} defaultValue={filters.capacity??''}/></label>{!admin&&<><label className="a-field"><span>Başlangıç</span><input name="start" type="datetime-local" defaultValue={filters.start??''}/></label><label className="a-field"><span>Bitiş</span><input name="end" type="datetime-local" defaultValue={filters.end??''}/></label></>}{admin&&<label className="a-field"><span>Durum</span><select name="active" defaultValue={filters.active??''}><option value="">Tümü</option><option value="true">Aktif</option><option value="false">Pasif</option></select></label>}</>:<><label className="a-field"><span>Durum</span><select name="status" defaultValue={filters.status??(admin?'':'ACTIVE')}><option value="">Tümü</option><option value="ACTIVE">Yaklaşan / Aktif</option><option value="COMPLETED">Geçmiş</option><option value="CANCELLED">İptal Edilenler</option></select></label><label className="a-field"><span>Tarih</span><input type="date" name="date" defaultValue={filters.date??''}/></label><label className="a-field"><span>Sıralama</span><select name="sort" defaultValue={filters.sort??'asc'}><option value="asc">Tarih ↑</option><option value="desc">Tarih ↓</option></select></label>{admin&&<><label className="a-field"><span>Oda</span><select name="room_id" defaultValue={filters.room_id??''}><option value="">Tümü</option>{options.rooms.map((r:Row)=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label className="a-field"><span>Organizatör</span><input name="organizer" defaultValue={filters.organizer??''}/></label></>}</>}<button className="a-primary">Filtrele</button><Link className="a-button" href={base}>Temizle</Link></form>{!admin&&view==='rooms'&&<p>Saatler seçilen odanın lokasyonuna göredir. Tarih ve saat seçerek müsaitliği kontrol edin.</p>}
{view==='rooms'?<div className="meeting-room-grid">{initial.rows?.map((r:Row)=><article className="a-card" key={r.id}>{r.image&&<img className="meeting-room-image" src={r.image} alt={r.name}/>}<h2>{r.name}</h2><p>{r.company_name} · {r.location_name}{r.floor?' · Kat '+r.floor:''}</p><p>{r.capacity} kişi · {r.timezone}</p><p>{r.features.join(' · ')||'Standart oda'}</p><p>{r.description}</p><span className="a-badge">{!r.active?'Pasif':filters.start?(r.available?'Müsait':'Dolu / Uygun değil'):'Aktif'}</span><div className="a-actions">{admin?<Link className="a-button" href={base+'/'+r.id}>Düzenle / Rezervasyonlar</Link>:r.available&&can(actor,'meeting_reservations.create')&&<Link className="a-primary" href={'/meeting-rooms/new?'+new URLSearchParams({room_id:r.id,location_id:r.location_id,...(filters.start?{start:filters.start,end:filters.end}:{})})}>Rezerve Et</Link>}</div></article>)}</div>:<div className="a-card a-table-wrap"><table className="a-table"><thead><tr>{['Toplantı','Oda / Lokasyon','Organizatör','Başlangıç / Bitiş','Durum','İşlem'].map(s=><th key={s}>{s}</th>)}</tr></thead><tbody>{initial.rows?.map((r:Row)=><tr key={r.id}><td>{r.title}</td><td>{r.room_name}<small style={{display:'block'}}>{r.location_name}</small></td><td>{r.organizer_name}</td><td>{stamp(r,r.start_at)}<br/>{stamp(r,r.end_at)}<small style={{display:'block'}}>{r.timezone}</small></td><td>{reservationStatuses[r.status]}</td><td>{r.status==='ACTIVE'&&new Date(r.start_at)>new Date()&&<div className="a-actions">{!admin&&can(actor,'meeting_reservations.edit_own')&&<Link href={base+'/'+r.id}>Düzenle</Link>}{(admin||can(actor,'meeting_reservations.cancel_own'))&&<button className="a-button" disabled={busy} onClick={()=>cancel(r)}>İptal Et</button>}</div>}</td></tr>)}</tbody></table></div>}{!initial.rows?.length&&<p className="a-card">Kayıt bulunamadı.</p>}{paginate()}</>}
</main></div></div>;}
