'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {Bell,X} from 'lucide-react';
import {NotificationRow} from '@/lib/engagement-shared';
async function api(path:string,body?:unknown){const r=await fetch('/api/notifications/'+path,{cache:'no-store',method:body?'POST':'GET',...(body?{headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});const data=await r.json();if(!r.ok)throw Error(data.error||'Bildirimler yüklenemedi.');return data;}
const stamp=(s:string)=>new Date(s).toLocaleString('tr-TR');
export function NotificationIndicator({unread}:{unread:number}){return <><Bell size={24}/>{unread>0&&<b className="badge">{unread>99?'99+':unread}</b>}</>;}
export function NotificationBell({initialUnread}:{initialUnread:number}){const router=useRouter(),[unread,setUnread]=useState(initialUnread),[open,setOpen]=useState(false),[rows,setRows]=useState<NotificationRow[]>([]),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),ref=useRef<HTMLDivElement>(null);useEffect(()=>setUnread(initialUnread),[initialUnread]);useEffect(()=>{let alive=true;void api('sync',{}).then(d=>{if(alive)setUnread(d.unread);}).catch(()=>{});return()=>{alive=false;};},[]);useEffect(()=>{if(!open)return;const close=(e:PointerEvent)=>{if(!ref.current?.contains(e.target as Node))setOpen(false);};const escape=(e:KeyboardEvent)=>{if(e.key==='Escape')setOpen(false);};document.addEventListener('pointerdown',close);document.addEventListener('keydown',escape);return()=>{document.removeEventListener('pointerdown',close);document.removeEventListener('keydown',escape);};},[open]);async function toggle(){if(open){setOpen(false);return;}setOpen(true);setLoading(true);setError('');try{const d=await api('recent');setRows(d.rows);setUnread(d.unread);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}async function read(id:string){setBusy(true);setError('');try{const r=await api(id,{read:true});if(id==='all'){setRows(v=>v.map(n=>({...n,is_read:true})));setUnread(0);}else {if(!rows.find(n=>n.id===id)?.is_read)setUnread(v=>Math.max(0,v-1));setRows(v=>v.map(n=>n.id===id?{...n,is_read:true}:n));setOpen(false);router.push(r.link);}router.refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}return <div className="notification-wrap" ref={ref}><button className="notification" aria-label={`Bildirimler${unread?' · '+unread+' okunmamış':''}`} aria-expanded={open} aria-controls="notification-dropdown" onClick={()=>void toggle()}><NotificationIndicator unread={unread}/></button>{open&&<section id="notification-dropdown" className="notification-dropdown" aria-label="Son bildirimler"><div className="notification-title"><strong>Bildirimler</strong><button aria-label="Bildirimleri kapat" onClick={()=>setOpen(false)}><X size={17}/></button></div>{error&&<p role="alert" className="form-error">{error}</p>}{loading?<p className="notification-empty">Yükleniyor…</p>:rows.length?rows.map(n=><button disabled={busy} key={n.id} className={'notification-row '+(!n.is_read?'unread':'')} onClick={()=>void read(n.id)}><strong>{n.title}</strong><span>{n.message}</span><small>{stamp(n.created_at)} · {n.is_read?'Okundu':'Okunmadı'}</small></button>):<p className="notification-empty">Henüz bildiriminiz yok.</p>}<div className="notification-footer"><button disabled={busy||!unread} onClick={()=>void read('all')}>Tümünü Okundu İşaretle</button><Link href="/notifications" onClick={()=>setOpen(false)}>Tüm Bildirimler →</Link></div></section>}</div>;}
export function NotificationList({rows}:{rows:NotificationRow[]}){const router=useRouter(),[busy,setBusy]=useState(false),[error,setError]=useState('');async function act(id:string,read:boolean,open=false){setBusy(true);setError('');try{const r=await api(id,{read});if(open)router.push(r.link);router.refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}return <><button className="a-button" disabled={busy} onClick={()=>void act('all',true)}>Tümünü Okundu İşaretle</button>{error&&<p role="alert" className="form-error">{error}</p>}<div className="notification-list">{rows.map(n=><article className={'a-card '+(!n.is_read?'notification-unread':'')} key={n.id}><h2><button className="a-link" disabled={busy} onClick={()=>void act(n.id,true,true)}>{n.title}</button></h2><p>{n.message}</p><small>{stamp(n.created_at)} · {n.is_read?'Okundu':'Okunmadı'}</small><div className="a-actions"><button className="a-button" disabled={busy} onClick={()=>void act(n.id,!n.is_read)}>{n.is_read?'Okunmadı İşaretle':'Okundu İşaretle'}</button></div></article>)}</div>{!rows.length&&<p className="a-empty">Bu filtrede bildirim bulunmuyor.</p>}</>;}
