'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {OrientationPlan} from '@/lib/people-shared';
const phaseLabels:Record<string,string>={FIRST_DAY:'İlk Gün',FIRST_WEEK:'İlk Hafta',FIRST_MONTH:'İlk Ay'};
const kinds:Record<string,string>={TASK:'Görev',READ_ACKNOWLEDGEMENT:'Okuma onayı',ASSET_ACCEPTANCE:'Zimmet kabulü',TRAINING:'Zorunlu eğitim',DOCUMENT:'Doküman'};
const safeHref=(v:string)=>v.startsWith('/')&&!v.startsWith('//')||/^https:\/\//i.test(v);
export default function OrientationPortal({plans,canManage}:{plans:OrientationPlan[];canManage:boolean}){const router=useRouter(),[error,setError]=useState(''),[busy,setBusy]=useState('');async function complete(id:string){setBusy(id);setError('');try{const r=await fetch('/api/academy/orientation/complete/'+id,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'}),d=await r.json();if(!r.ok)throw Error(d.error);router.refresh();}catch(e){setError((e as Error).message);}finally{setBusy('');}}
return <main className="admin-content orientation-page" style={{maxWidth:1120,margin:'auto'}}><nav className="a-actions"><a href="/">Çalışan Portalı</a><a href="/training">Koyuncu Akademi</a>{canManage&&<a href="/orientation/manage">Yönetici görünümü</a>}</nav><header className="academy-hero"><span className="eyebrow">İLK GÜN · İLK HAFTA · İLK AY</span><h1>Koyuncu Grup Genel Oryantasyon</h1><p>Şirketi, yöneticinizi, ekibinizi ve ofisinizi tanıyın; İK ve BT adımlarınızı tamamlayın.</p></header>{error&&<p role="alert" className="form-error">{error}</p>}{!plans.length&&<p className="a-card">Henüz sizin için bir oryantasyon planı oluşturulmadı.</p>}{plans.map(p=><article className="a-card orientation-plan" key={p.id}><div className="a-actions"><span className="a-status">{p.orientation_track==='COMPANY'?'Şirket Oryantasyonu':p.orientation_track==='DEPARTMENT'?'Departman / Birim Oryantasyonu':p.orientation_track==='ROLE'?'Role Özel Oryantasyon':'Genel Oryantasyon'}</span><span className="a-status">{p.completed_count} / {p.required_count} zorunlu adım</span></div><h2>{p.title}</h2><p>Başlangıç: {p.start_date??'Belirtilmedi'} · Durum: {p.status==='COMPLETED'?'Tamamlandı':'Devam ediyor'}</p><div className="orientation-context"><div><b>Şirket</b><span>{p.company_name??'—'}</span></div><div><b>Yönetici</b><span>{p.manager_name??'—'}</span></div><div><b>Ekip / Birim</b><span>{p.unit_name??p.department_name??'—'}</span></div><div><b>Ofis</b><span>{p.location_name??'—'}</span></div><div><b>Görev</b><span>{p.job_title_name??'—'}</span></div><div><b>Oryantasyon Buddy</b><span>{p.buddy_id?<a href={'/directory/'+p.buddy_id}>{p.buddy_name}</a>:'Henüz atanmadı'}</span></div></div>{(['FIRST_DAY','FIRST_WEEK','FIRST_MONTH'] as const).map(phase=><section key={phase}><h3>{phaseLabels[phase]}</h3>{p.steps.filter(s=>s.phase===phase).map(s=><div className="orientation-step" key={s.id}><div><strong>{s.title}</strong><small>{kinds[s.step_kind]}{s.required?' · Zorunlu':' · İsteğe Bağlı'}{s.deadline?` · Son tarih ${s.deadline}`:''}</small>{s.resource_url&&safeHref(s.resource_url)&&<a href={s.resource_url} target={s.resource_url.startsWith('https://')?'_blank':undefined} rel={s.resource_url.startsWith('https://')?'noopener noreferrer':undefined}>Kaynağı aç</a>}</div><div>{s.status==='DONE'?<span className="a-status">Tamamlandı</span>:s.step_kind==='TRAINING'?<a className="a-button" href="/training">Eğitime git</a>:s.step_kind==='READ_ACKNOWLEDGEMENT'&&s.resource_url&&safeHref(s.resource_url)?<a className="a-button" href={s.resource_url}>Oku ve onayla</a>:s.step_kind==='ASSET_ACCEPTANCE'?<a className="a-button" href="/my-assets">Zimmetlerime git</a>:<button className="a-button" disabled={!!busy} onClick={()=>void complete(s.id)}>{busy===s.id?'Kaydediliyor…':'Tamamlandı olarak işaretle'}</button>}</div></div>)}</section>)}</article>)}</main>}
