'use client';
import Link from 'next/link';
import Image from 'next/image';
import {usePathname} from 'next/navigation';
import {useEffect,useRef} from 'react';
import {Identity,can,portalPermissions} from '@/lib/permissions';
import {Home, Megaphone, ClipboardList, Contact, Timer, FileText, CalendarDays, UserRound, CalendarPlus, MessageSquare, CircleHelp, Building2, PanelsTopLeft, Phone, Settings, Search, Bell, ChevronDown, ChevronRight, ChevronLeft, ArrowRight, Laptop, Files, ClipboardCheck, MapPin, CloudSun, Headphones, Plane, Lightbulb, UsersRound, CalendarClock, Mail, Menu, X, Leaf, Check, Send} from 'lucide-react';
import type {LucideIcon} from 'lucide-react';
const menus:[string,LucideIcon,string?][]=[['Benden Beklenenler',ClipboardCheck],['Organizasyon Şeması',UsersRound],['Yaklaşan Süreler',CalendarClock],['Koyuncu Akademi',ClipboardCheck],['Görevlerim',ClipboardList],['Anketler',ClipboardCheck],['Duyurular',Megaphone],['Talepler',ClipboardList],['İletişim Rehberi',Contact],['Zimmetlerim',Timer],['Dokümanlar',FileText],['Etkinlikler',CalendarDays],['Ajandam',CalendarClock],['İK İşlemleri',UserRound],['Şirket Bilgileri',CalendarPlus],['Öneri & Bildirim',MessageSquare],['BT Destek',CircleHelp],['Sürdürülebilirlik',Building2],['Kurumsal İletişim',PanelsTopLeft],['Yardım & Destek',Phone],['Ayarlar',Settings]];
export const portalRoutes:Record<string,string>={'Benden Beklenenler':'/my-area','Organizasyon Şeması':'/organization','Yaklaşan Süreler':'/deadlines','Şirket Bilgileri':'/companies','Koyuncu Akademi':'/academy','Görevlerim':'/tasks','Anketler':'/surveys','İletişim Rehberi':'/directory','Ajandam':'/calendar','Toplantı Odası':'/meeting-rooms','Öneri & Bildirim':'/suggestions','Talepler':'/requests','Taleplerim':'/requests','Yeni Talep':'/requests/new','İzin Talebi':'/leave/new','İK İşlemleri':'/leave','Onaylarım':'/approvals','Duyurular':'/announcements','Dokümanlar':'/documents','Etkinlikler':'/events','Zimmetlerim':'/my-assets','Şirket Politikaları':'/documents','BT Destek':'/requests/new','Yardım & Destek':'/requests/new','Kurumsal İletişim':'/corporate-communications'};
portalRoutes['Ayarlar']='/admin';

export default function PortalSidebar({actor,open,onClose}:{actor:Identity;open:boolean;onClose:()=>void}){
 const path=usePathname(),ref=useRef<HTMLElement>(null);
 useEffect(()=>{if(!open)return;const previous=document.activeElement as HTMLElement|null,old=document.body.style.overflow;document.body.style.overflow='hidden';ref.current?.querySelector<HTMLButtonElement>('.mobile-close')?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const items=Array.from(ref.current?.querySelectorAll<HTMLElement>('a,button')??[]).filter(x=>x.getClientRects().length);const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',key);return()=>{document.body.style.overflow=old;document.removeEventListener('keydown',key);previous?.focus();};},[open,onClose]);
 return <>{open&&<button className="scrim" aria-label="Menüyü kapat" onClick={onClose}/>}<aside ref={ref} id="portal-sidebar" className={'sidebar '+(open?'open':'')}><Link href="/" className="logo" aria-label="Koyuncu Grup ana sayfa" onClick={onClose}><Image src="/brand/koyuncu-grup.png" alt="Koyuncu Grup" width={148} height={52} priority/></Link><button className="mobile-close" aria-label="Menüyü kapat" onClick={onClose}><X/></button><nav aria-label="Ana menü">{menus.filter(([name])=>name!=='Sürdürülebilirlik').filter(([name])=>name==='Benden Beklenenler'?can(actor,'my_area.view'):name==='Organizasyon Şeması'?can(actor,'organization.view_portal'):name==='Yaklaşan Süreler'?can(actor,'deadlines.view'):name==='Koyuncu Akademi'?can(actor,'academy.view'):name==='Görevlerim'?can(actor,'tasks.view_own'):name==='Anketler'?can(actor,'surveys.view_own'):name==='İletişim Rehberi'?can(actor,'directory.view')&&can(actor,'portal.directory.view'):name==='Ajandam'?can(actor,'calendar.view_own'):name==='Kurumsal İletişim'?can(actor,'corporate_communications.view'):name==='Ayarlar'?can(actor,'admin.view'):can(actor,portalPermissions.find(p=>p.name===name)?.id??'portal.home.view')).map(([label,Icon])=>{const href=portalRoutes[label];if(!href)return null;const active=path===href||path.startsWith(href+'/');return <Link key={label} href={href} className={'nav-item '+(active?'active':'')} aria-current={active?'page':undefined} onClick={onClose}><Icon size={19} strokeWidth={1.6}/><span>{label}</span></Link>;})}</nav><div className="sidebar-bottom"><Building2 size={42} strokeWidth={.8}/><span>Birlikte<br/>Daha Güçlüyüz</span></div></aside></>;
}
