'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import Image from 'next/image';
import {useRouter} from 'next/navigation';
import {Identity,can} from '@/lib/permissions';
import {suggestionStatuses,suggestionEvents} from '@/lib/engagement-shared';
import ProfileMenu from './ProfileMenu';
import WorkflowNav from './WorkflowNav';
import ContentNav from './ContentNav';
import InventoryNav from './InventoryNav';
type Row=Record<string,any>;
const date=(s:string)=>new Date(s).toLocaleString('tr-TR');
async function api(path:string,body?:unknown){const r=await fetch('/api/suggestions/'+path,{cache:'no-store',method:body?'POST':'GET',...(body?{headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw Error(d.error||'İşlem tamamlanamadı.');return d;}
export default function SuggestionPanel({actor,id,admin,initial,filters}:{actor:Identity;id?:string;admin:boolean;initial:Row;filters:Row}){const router=useRouter(),[options,setOptions]=useState<Row>({}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[reply,setReply]=useState<Row|null>(null),[form,setForm]=useState<Row>({type_id:'',subject:'',description:'',category:'',priority:'NORMAL',attachment:null}),[note,setNote]=useState(''),[assignee,setAssignee]=useState('');const base=(admin?'/admin':'')+'/suggestions',isNew=id==='new',item=initial.item;useEffect(()=>{if(admin)api('options').then(setOptions).catch(e=>setError(e.message));},[admin]);async function action(body:unknown,create=false){if(busy)return;setBusy(true);setError('');try{const d=await api(create?'':id!,body);setReply(null);setNotice('İşlem kaydedildi.');if(create)router.push('/suggestions/'+d.id);else router.refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
const input=(key:string,label:string,required=false)=><label className="a-field"><span>{label}</span><input required={required} value={form[key]??''} maxLength={key==='subject'?200:100} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>;
const filter=(key:string,label:string,rows:Row[])=><label className="a-field" key={key}><span>{label}</span><select name={key} defaultValue={filters[key]??''}><option value="">Tümü</option>{rows.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label>;
return <div className={admin?'admin-shell':''}>{admin&&<aside className="admin-nav"><Link className="admin-brand" href="/admin"><Image src="/brand/koyuncu-grup.png" alt="Koyuncu Grup" width={145} height={51}/></Link>{can(actor,'admin.view')&&<Link href="/admin">Genel Bakış</Link>}<WorkflowNav actor={actor}/><InventoryNav actor={actor}/><ContentNav actor={actor}/><Link href="/">← Çalışan Portalı</Link></aside>}<div className={admin?'admin-main':''}><header className="admin-header"><Link href="/">← Çalışan Portalı</Link><ProfileMenu actor={actor}/></header><main className="admin-content" style={admin?undefined:{maxWidth:1150,margin:'auto'}}><div className="admin-heading"><div><span className="eyebrow">{admin?'YÖNETİM':'ÇALIŞAN PORTALI'}</span><h1>{isNew?'Yeni Öneri / Bildirim':item?'Kayıt #'+item.number:admin?'Öneri & Bildirimler':'Önerilerim ve Bildirimlerim'}</h1></div>{!id&&!admin&&can(actor,'suggestions.create')&&<Link className="a-primary" href="/suggestions/new">+ Yeni Öneri / Bildirim</Link>}{!admin&&can(actor,'suggestions.manage')&&<Link className="a-button" href="/admin/suggestions">Yönetim</Link>}</div>{error&&<p role="alert" className="form-error">{error}</p>}{notice&&<p role="status" className="form-success">{notice}</p>}
{isNew&&<form className="a-card a-form" onSubmit={e=>{e.preventDefault();void action(form,true);}}><div className="form-grid"><label className="a-field"><span>Tür</span><select required value={form.type_id} onChange={e=>setForm({...form,type_id:e.target.value})}><option value="">Seçin</option>{initial.rows.map((t:Row)=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>{input('subject','Konu',true)}{input('category','Kategori (opsiyonel)')}<label className="a-field"><span>Öncelik</span><select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}>{[['LOW','Düşük'],['NORMAL','Normal'],['HIGH','Yüksek'],['URGENT','Acil']].map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label></div><label className="a-field"><span>Açıklama</span><textarea required maxLength={5000} rows={6} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label className="a-field"><span>Ek (PDF/PNG/JPEG/WebP · en fazla 200 KB)</span><input type="file" accept="application/pdf,image/png,image/jpeg,image/webp" onChange={async e=>{const f=e.target.files?.[0];if(!f){setForm(v=>({...v,attachment:null}));return;}if(f.size>200000){e.target.value='';setForm(v=>({...v,attachment:null}));setError('Ek en fazla 200 KB olabilir.');return;}const data=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(f);});setForm(v=>({...v,attachment:{name:f.name,mime:f.type,data}}));}}/></label><div className="a-actions"><button className="a-primary" disabled={busy}>Gönder</button><Link className="a-button" href={base}>Vazgeç</Link></div></form>}
{item&&<><section className="a-card"><h2>{item.subject}</h2><dl className="detail-grid">{[['type_name','Tür'],['status','Durum'],['owner_name','Gönderen'],['company_name','Şirket'],['location_name','Lokasyon'],['department_name','Departman'],['assignee_name','Sorumlu Kişi'],['category','Kategori'],['priority','Öncelik'],['created_at','Oluşturma Tarihi'],['updated_at','Son Güncelleme']].map(([key,label])=><div key={key}><dt>{label}</dt><dd>{key==='status'?suggestionStatuses[item[key]]:key.endsWith('_at')?date(item[key]):item[key]||'—'}</dd></div>)}</dl><p style={{whiteSpace:'pre-wrap'}}>{item.description}</p>{item.file_name&&<a className="a-link" href={'/api/suggestions/'+id+'/file'+(admin?'?admin=1':'')}>{item.file_name} · İndir</a>}</section><section className="a-card"><h2>Yetkili Yanıtları</h2>{initial.responses.length?initial.responses.map((r:Row)=><article key={r.id}><strong>{r.actor_name}</strong><small> · {date(r.created_at)}</small><p style={{whiteSpace:'pre-wrap'}}>{r.body}</p></article>):<p>Henüz yanıt verilmedi.</p>}</section>{admin&&!['CLOSED','REJECTED'].includes(item.status)&&<section className="a-card"><h2>Kaydı Yönet</h2><label className="a-field"><span>İşlem Notu / Red Nedeni</span><textarea maxLength={1000} value={note} onChange={e=>setNote(e.target.value)}/></label><div className="a-actions">{['REVIEW','WAITING','CLOSED','REJECTED'].filter(s=>s!==item.status).map(status=><button className="a-button" disabled={busy} key={status} onClick={()=>void action({action:'status',status,note})}>{suggestionStatuses[status]}</button>)}<button className="a-primary" disabled={busy} onClick={()=>setReply({body:'',idempotency_key:crypto.randomUUID()})}>Yanıtla</button></div><div className="a-actions"><label className="a-field"><span>Sorumlu Kişi</span><select value={assignee} onChange={e=>setAssignee(e.target.value)}><option value="">Seçin</option>{options.users?.map((u:Row)=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label><button className="a-button" disabled={busy||!assignee} onClick={()=>void action({action:'assign',assignee_id:assignee})}>Ata</button></div>{reply&&<form onSubmit={e=>{e.preventDefault();void action({action:'reply',...reply});}}><label className="a-field"><span>Yanıtınız</span><textarea required maxLength={5000} rows={5} value={reply.body} onChange={e=>setReply({...reply,body:e.target.value})}/></label><div className="a-actions"><button className="a-primary" disabled={busy}>Yanıtı Gönder</button><button type="button" className="a-button" onClick={()=>setReply(null)}>Vazgeç</button></div></form>}</section>}<section className="a-card"><h2>İşlem Geçmişi</h2>{initial.history.map((h:Row)=><div key={h.id}><small>{date(h.created_at)} · {h.actor_name}</small><p>{suggestionEvents[h.event]} · {suggestionStatuses[h.status]}{h.note&&' · '+h.note}</p></div>)}</section><Link className="a-button" href={base}>← Liste</Link></>}
{!id&&<><form className="a-filters" method="GET"><input name="q" aria-label="Önerilerde ara" placeholder="Kayıt no, konu veya gönderen" defaultValue={filters.q??''}/>{filter('status','Durum',[{id:'open',name:'Açık'},...Object.entries(suggestionStatuses).map(([id,name])=>({id,name}))])}{admin&&<>{filter('type_id','Tür',options.types??[])}{filter('company_id','Şirket',options.companies??[])}{filter('location_id','Lokasyon',options.locations??[])}{filter('department_id','Departman',options.departments??[])}{filter('assignee_id','Sorumlu',options.users??[])}<label>Başlangıç<input type="date" name="from" defaultValue={filters.from??''}/></label><label>Bitiş<input type="date" name="to" defaultValue={filters.to??''}/></label></>}{filter('sort','Sıralama',[{id:'created_at',name:'Tarih'},{id:'updated_at',name:'Son Güncelleme'},{id:'number',name:'Kayıt No'},{id:'subject',name:'Konu'},{id:'status',name:'Durum'}])}{filter('dir','Yön',[{id:'desc',name:'Azalan'},{id:'asc',name:'Artan'}])}<button className="a-button">Filtrele</button><Link href={base}>Temizle</Link></form><div className="a-table-wrap"><table className="a-table"><thead><tr>{['Kayıt No','Tür','Konu',...(admin?['Gönderen','Şirket','Lokasyon','Departman','Sorumlu']:[]),'Tarih','Durum','Son Güncelleme'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{initial.rows.map((r:Row)=><tr key={r.id}><td><Link href={base+'/'+r.id}>#{r.number}</Link></td><td>{r.type_name}</td><td><Link href={base+'/'+r.id}>{r.subject}</Link></td>{admin&&['owner_name','company_name','location_name','department_name','assignee_name'].map(k=><td key={k}>{r[k]||'—'}</td>)}<td>{date(r.created_at)}</td><td>{suggestionStatuses[r.status]}</td><td>{date(r.updated_at)}</td></tr>)}</tbody></table></div>{!initial.rows.length&&<p className="a-empty">Gösterilecek kayıt bulunmuyor.</p>}<div className="a-pagination"><span>{initial.total} kayıt · Sayfa {initial.page}</span>{initial.page>1&&<Link className="a-button" href={base+'?'+new URLSearchParams({...filters,page:String(initial.page-1)})}>Önceki</Link>}{initial.page*20<initial.total&&<Link className="a-button" href={base+'?'+new URLSearchParams({...filters,page:String(initial.page+1)})}>Sonraki</Link>}</div></>}
</main></div></div>;}
