import Link from 'next/link';
import {notFound} from 'next/navigation';
import {requireIdentity} from '@/lib/auth';
import {can} from '@/lib/permissions';
import {AppError} from '@/lib/security';
import {surveyList,surveyDetail,surveyResults,surveyOptions} from '@/lib/surveys';
import {SurveyAnswer,SurveyEditor,SurveyStatus} from './SurveyPanel';
import ProfileMenu from './ProfileMenu';
export default async function SurveyPage({params,searchParams,admin=false}:{params:Promise<{path?:string[]}>;searchParams:Promise<Record<string,string|string[]|undefined>>;admin?:boolean}){const a=await requireIdentity(admin?'surveys.manage':'surveys.view_own');if(admin&&!can(a,'admin.view'))notFound();const path=(await params).path??[],search=await searchParams,base=admin?'/admin/surveys':'/surveys';if(path.length>1)notFound();let content;if(path[0]==='new'){if(!admin)notFound();content=<SurveyEditor options={await surveyOptions(a)}/>;}else if(path[0]){try{const s=await surveyDetail(a,path[0],admin),results=admin&&can(a,'surveys.results')?await surveyResults(a,s.id):null;content=<><h1>{s.title}</h1><p>{s.description}</p>{admin?<>{s.status==='DRAFT'&&<SurveyEditor survey={s} options={await surveyOptions(a)}/>}<SurveyStatus id={s.id} status={s.status}/>{results&&<section className="a-card"><h2>Anket Sonuçları</h2><p>Atanan: {results.assigned} · Cevaplayan: {results.answered} · Bekleyen: {results.pending} · Katılım: %{results.participation}</p>{results.suppressed?<p>Anonim sonuçlar en az {s.privacy_threshold} yanıt sonrası açılır. Kimlik veya küçük grup kırılımı gösterilmez.</p>:results.questions.map((q,i)=><section key={i}><h3>{q.title}</h3>{q.counts.map(c=><p key={c.label}>{c.label}: {c.count} <meter min={0} max={Math.max(1,results.answered)} value={c.count} aria-label={c.label}/></p>)}{q.texts.map((text,j)=><p key={j}>{text}</p>)}</section>)}</section>}</>:<SurveyAnswer survey={s}/>}</>;}catch(e){if(e instanceof AppError&&e.status===404)notFound();throw e;}}else{const p=new URLSearchParams();for(const k of ['page','q'])if(typeof search[k]==='string')p.set(k,search[k]);const d=await surveyList(a,p,admin);content=<><div className="admin-heading"><h1>Anket Merkezi</h1>{admin&&<Link className="a-primary" href={base+'/new'}>Yeni Anket</Link>}</div><form className="a-filters"><input aria-label="Anket ara" name="q" placeholder="Anket ara" defaultValue={p.get('q')??''}/><button className="a-primary">Ara</button></form>{d.rows.map(s=><article className="a-card" key={s.id}><h2><Link href={base+'/'+s.id}>{s.title}</Link></h2><p>{s.anonymous?'Anonim':'İsimli'} · {s.required?'Zorunlu':'İsteğe bağlı'} · {s.answered?'Yanıtlandı':new Date(s.ends_at)<new Date()?'Sona erdi':s.status==='DRAFT'?'Taslak':s.status==='CLOSED'?'Kapalı':'Açık'}</p><p>Son tarih: {new Date(s.ends_at).toLocaleString('tr-TR',{timeZone:'Europe/Istanbul'})}</p></article>)}{!d.rows.length&&<p className="a-card">Gösterilecek anket bulunmuyor.</p>}<div className="a-pagination"><span>{d.total} anket · Sayfa {d.page}</span>{d.page>1&&<Link href={base+'?'+new URLSearchParams({q:p.get('q')??'',page:String(d.page-1)})}>Önceki</Link>}{d.page*20<d.total&&<Link href={base+'?'+new URLSearchParams({q:p.get('q')??'',page:String(d.page+1)})}>Sonraki</Link>}</div></>;}
return <><header className="admin-header"><Link href={admin?'/admin':'/'}>← {admin?'Yönetim':'Çalışan Portalı'}</Link><ProfileMenu actor={a}/></header><main className="admin-content" style={{maxWidth:1200}}>{path.length>0&&<nav className="a-actions"><Link className="a-button" href={base}>Anketler</Link></nav>}{content}</main></>;}
