import * as academy from '@/lib/academy';
import {currentIdentity} from '@/lib/auth';
import {AppError,readJSON} from '@/lib/security';
import {fail,json} from '@/lib/http';
type Context={params:Promise<{path?:string[]}>};
async function actor(){const a=await currentIdentity();if(!a||a.must_change_password)throw new AppError(401,'Yeniden giriş yapın.');return a;}
async function body(request:Request){return readJSON(request);}
export async function GET(_request:Request,ctx:Context){try{const a=await actor(),p=(await ctx.params).path??[];if(!p.length)return json(await academy.catalog(a));if(p.length===1&&p[0]==='assignments')return json(await academy.assignments(a));if(p.length===1&&p[0]==='targets')return json({rows:await academy.assignmentTargets(a)});if(p.length===1&&p[0]==='sessions')return json({rows:await academy.sessionList(a)});if(p.length===1&&p[0]==='sessions-managed')return json({rows:await academy.managedSessions(a)});if(p.length===1&&p[0]==='orientation')return json({rows:await academy.orientationOwn(a)});if(p.length===1&&p[0]==='orientation-team')return json({rows:await academy.managerOrientations(a)});if(p.length===1&&p[0]==='orientation-options')return json(await academy.orientationOptions(a));if(p.length===1&&p[0]==='compliance')return json({rows:await academy.compliance(a)});if(p.length===2&&p[0]==='courses')return json(await academy.courseDetail(a,p[1]));if(p.length===3&&p[0]==='provider'&&p[2]==='launch')return json(await academy.providerLaunch(a,p[1]));throw new AppError(404,'Bulunamadı.');}catch(e){return fail(e);}}
export async function POST(request:Request,ctx:Context){try{const a=await actor(),p=(await ctx.params).path??[],d=await body(request);if(p.length===1&&p[0]==='courses')return json(await academy.saveAcademyCourse(a,d));if(p.length===2&&p[0]==='courses')return json(await academy.saveAcademyCourse(a,d,p[1]));if(p.length===2&&p[0]==='enroll')return json(await academy.enrollSelf(a,p[1]));if(p.length===1&&p[0]==='assign')return json(await academy.assignCourse(a,d));if(p.length===2&&p[0]==='progress')return json(await academy.progress(a,p[1],d));if(p.length===2&&p[0]==='complete')return json(await academy.completeOwn(a,p[1]));if(p.length===2&&p[0]==='assessment')return json(await academy.submitAssessment(a,p[1],d));if(p.length===1&&p[0]==='sessions')return json(await academy.saveSession(a,d));if(p.length===3&&p[0]==='attendance')return json(await academy.attendance(a,p[1],p[2],d));if(p.length===1&&p[0]==='orientation')return json(await academy.createOrientation(a,d));if(p.length===3&&p[0]==='orientation'&&p[2]==='tasks')return json(await academy.addOrientationTask(a,p[1],d));if(p.length===3&&p[0]==='orientation'&&p[1]==='complete')return json(await academy.completeOrientationTask(a,p[2]));throw new AppError(404,'Bulunamadı.');}catch(e){return fail(e);}}
