import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {DB,database,transaction,lock} from './db';
import {Identity,can,canAction,allPermissionIds} from './permissions';
import {AppError,hashPassword,temporaryPassword} from './security';
import {identityFor} from './auth-core';
const optionalText=z.string().max(250).nullish();
const optionalId=z.string().uuid().nullable().optional();
const photo=z.string().max(280000).nullable().optional().refine(value=>!value||/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(value),'Yalnızca PNG, JPEG veya WebP görselleri kabul edilir.');
const status=z.enum(['ACTIVE','INACTIVE','ON_LEAVE','LEFT']);
const userSchema=z.object({personnel_no:z.string().trim().min(1).max(50).transform(s=>s.toUpperCase()),first_name:z.string().trim().min(1).max(80),last_name:z.string().trim().min(1).max(80),email:z.string().trim().email().max(254).transform(s=>s.toLowerCase()),username:z.string().trim().regex(/^[a-zA-Z0-9._-]{3,64}$/).transform(s=>s.toLowerCase()),photo,phone:optionalText,extension:optionalText,company_id:optionalId,location_id:optionalId,department_id:optionalId,unit_id:optionalId,job_title_id:optionalId,manager_user_id:optionalId,start_date:z.string().date().nullable().optional(),employee_type_id:z.string().max(50).nullable().optional(),status,role_ids:z.array(z.string().max(64)).min(1).max(15),overrides:z.record(z.string(),z.boolean()).default({}),temporary_password:z.string().min(6).max(128).optional()}).strict();
const orgSchema=z.object({name:z.string().trim().min(1).max(120),code:z.string().trim().min(1).max(40).transform(s=>s.toUpperCase()),active:z.boolean().default(true),company_id:optionalId,department_id:optionalId,parent_id:optionalId,manager_user_id:optionalId,logo:photo,address:z.string().max(500).nullish(),city:optionalText,district:optionalText,country:optionalText,latitude:z.number().min(-90).max(90).nullable().optional(),longitude:z.number().min(-180).max(180).nullable().optional(),timezone:z.string().max(100).refine(s=>{try{new Intl.DateTimeFormat('tr',{timeZone:s});return true;}catch{return false;}},'Geçerli saat dilimi girin.').optional(),phone:optionalText}).strict();
export const orgResources:Record<string,{table:string;permission:string;fields:string[]}>= {companies:{table:'companies',permission:'companies',fields:['name','code','logo','active']},locations:{table:'locations',permission:'locations',fields:['name','code','company_id','address','city','district','country','latitude','longitude','timezone','phone','active']},departments:{table:'departments',permission:'departments',fields:['name','code','company_id','parent_id','manager_user_id','active']},units:{table:'units',permission:'units',fields:['name','code','company_id','department_id','manager_user_id','active']},'job-titles':{table:'job_titles',permission:'jobtitles',fields:['name','code','company_id','department_id','active']}};
export function required(actor:Identity,resource:string,action:string){if(!can(actor,'admin.view')||!canAction(actor,resource,action))throw new AppError(403,'Bu işlem için yetkiniz bulunmuyor.');}
export function requirePermission(actor:Identity,permission:string){if(!can(actor,'admin.view')||!can(actor,permission))throw new AppError(403,'Bu işlem için yetkiniz bulunmuyor.');}
async function acting(db:DB,actor:Identity){const live=await identityFor(db,actor.id);if(!live||live.must_change_password)throw new AppError(401,'Yeniden giriş yapın.');return live;}
async function audit(db:DB,actor:string,action:string,type:string,id:string){await db.query('INSERT INTO audit_logs(id,actor_user_id,action,entity_type,entity_id) VALUES($1,$2,$3,$4,$5)',[randomUUID(),actor,action,type,id]);}
async function record(db:DB,table:string,id:string){const row=(await db.query<Record<string,unknown>>(`SELECT * FROM ${table} WHERE id=$1`,[id])).rows[0];if(!row)throw new AppError(404,'Kayıt bulunamadı.');return row;}
async function validateManager(db:DB,id:string,manager:string|null|undefined){if(!manager)return;const m=await record(db,'users',manager);if(m.status!=='ACTIVE'||m.archived_at)throw new AppError(400,'Aktif bir yönetici seçin.');const chain=(await db.query<{id:string}>('WITH RECURSIVE chain AS (SELECT id,manager_user_id FROM users WHERE id=$1 UNION SELECT u.id,u.manager_user_id FROM users u JOIN chain c ON u.id=c.manager_user_id) SELECT id FROM chain',[manager])).rows;if(chain.some(r=>r.id===id))throw new AppError(400,'Yönetici ilişkisi döngü oluşturamaz.');}
async function checkCompany(db:DB,table:string,id:unknown,company:unknown){if(!id)return;const row=await record(db,table,String(id));if(!row.active||row.archived_at)throw new AppError(400,'Pasif organizasyon kaydı seçilemez.');if(table!=='companies'&&row.company_id!==company)throw new AppError(400,'Seçilen kayıtlar aynı şirkete bağlı olmalıdır.');return row;}
async function validateUserOrg(db:DB,data:z.infer<typeof userSchema>,id:string){await checkCompany(db,'companies',data.company_id,data.company_id);for(const [field,table]of [['location_id','locations'],['department_id','departments'],['unit_id','units'],['job_title_id','job_titles']] as const){const row=await checkCompany(db,table,data[field],data.company_id);if(row&&row.department_id&&row.department_id!==data.department_id)throw new AppError(400,'Birim ve ünvan seçilen departmana bağlı olmalıdır.');}await validateManager(db,id,data.manager_user_id);if(data.employee_type_id&&!(await db.query('SELECT id FROM employee_types WHERE id=$1 AND active=true',[data.employee_type_id])).rows.length)throw new AppError(400,'Geçerli çalışan tipi seçin.');}
async function rolesFor(db:DB,id:string){return (await db.query<{role_id:string}>('SELECT role_id FROM user_roles WHERE user_id=$1',[id])).rows.map(r=>r.role_id);}
async function protectUser(db:DB,actor:Identity,id:string){const roles=await rolesFor(db,id);if(roles.includes('SUPER_ADMIN')&&!actor.roles.includes('SUPER_ADMIN'))throw new AppError(403,'Süper yönetici hesabını yalnızca süper yönetici değiştirebilir.');return roles;}
async function validateGrants(db:DB,actor:Identity,roles:string[],overrides:Record<string,boolean>){
 if(roles.includes('SUPER_ADMIN')&&!actor.roles.includes('SUPER_ADMIN'))throw new AppError(403,'Süper yönetici rolü veremezsiniz.');
 for(const role of roles){const r=await record(db,'roles',role);if(!r.active)throw new AppError(400,'Pasif rol atanamaz.');const ps=(await db.query<{permission_id:string}>('SELECT permission_id FROM role_permissions WHERE role_id=$1',[role])).rows;if(ps.some(p=>!can(actor,p.permission_id)))throw new AppError(403,'Kendi yetkilerinizden daha geniş bir rol atayamazsınız.');}
 for(const [p,value]of Object.entries(overrides)){if(!allPermissionIds.includes(p))throw new AppError(400,'Bilinmeyen yetki.');if(value&&!can(actor,p))throw new AppError(403,'Sahip olmadığınız yetkiyi veremezsiniz.');}
}
async function writeGrants(db:DB,id:string,roles:string[],overrides:Record<string,boolean>){await db.query('DELETE FROM user_roles WHERE user_id=$1',[id]);for(const r of new Set(roles))await db.query('INSERT INTO user_roles VALUES($1,$2)',[id,r]);await db.query('DELETE FROM user_permission_overrides WHERE user_id=$1',[id]);for(const [p,v]of Object.entries(overrides))await db.query('INSERT INTO user_permission_overrides VALUES($1,$2,$3)',[id,p,v]);}
export async function saveUser(actor:Identity,payload:unknown,id?:string){const data=userSchema.parse(payload);const password=id?null:data.temporary_password??temporaryPassword();const passwordHash=password?await hashPassword(password):null;return transaction(async db=>{await lock(db);actor=await acting(db,actor);required(actor,'users',id?'edit':'create');const target=id??randomUUID();let old:Record<string,unknown>|null=null,oldRoles:string[]=[];let oldOverrides:Record<string,boolean>={};if(id){old=await record(db,'users',id);oldRoles=await protectUser(db,actor,id);for(const r of (await db.query<{permission_id:string;allowed:boolean}>('SELECT * FROM user_permission_overrides WHERE user_id=$1',[id])).rows)oldOverrides[r.permission_id]=r.allowed;}
 const roleChanged=JSON.stringify([...oldRoles].sort())!==JSON.stringify([...data.role_ids].sort());const overrideChanged=Object.keys({...oldOverrides,...data.overrides}).some(k=>oldOverrides[k]!==data.overrides[k]);
 if((id&&roleChanged)||(!id&&(data.role_ids.length!==1||data.role_ids[0]!=='EMPLOYEE')))required(actor,'roles','manage');
 if(overrideChanged)requirePermission(actor,'permissions.manage');
 if(id&&old?.status!==data.status)required(actor,'users','disable');
 if(id===actor.id&&(data.status!=='ACTIVE'||roleChanged||overrideChanged))throw new AppError(400,'Kendi hesabınızın durumunu veya yetkilerini bu ekrandan değiştiremezsiniz.');
 if(oldRoles.includes('SUPER_ADMIN')&&(!data.role_ids.includes('SUPER_ADMIN')||!['ACTIVE','ON_LEAVE'].includes(data.status))){const count=(await db.query<{n:string}>("SELECT count(*) n FROM users u JOIN user_roles ur ON ur.user_id=u.id WHERE ur.role_id='SUPER_ADMIN' AND u.status IN('ACTIVE','ON_LEAVE') AND u.archived_at IS NULL AND u.id<>$1",[id])).rows[0];if(Number(count.n)<1)throw new AppError(400,'Son aktif süper yönetici kaldırılamaz.');}
 if(roleChanged||overrideChanged)await validateGrants(db,actor,data.role_ids,data.overrides);await validateUserOrg(db,data,target);
 const cols=['personnel_no','first_name','last_name','photo','email','phone','extension','company_id','location_id','department_id','unit_id','job_title_id','manager_user_id','start_date','employee_type_id','username','status'] as const;const vals=cols.map(k=>data[k]??null);
 if(id)await db.query(`UPDATE users SET ${cols.map((c,i)=>c+'=$'+(i+1)).join(',')},updated_at=now(),archived_at=CASE WHEN $17='LEFT' THEN now() ELSE NULL END WHERE id=$18`,[...vals,id]);else{await db.query(`INSERT INTO users(${cols.join(',')},id) VALUES(${[...vals,target].map((_,i)=>'$'+(i+1)).join(',')})`,[...vals,target]);await db.query('INSERT INTO credentials(user_id,password_hash) VALUES($1,$2)',[target,passwordHash]);}
 if(!id||roleChanged||overrideChanged)await writeGrants(db,target,data.role_ids,data.overrides);if(id&&(roleChanged||overrideChanged||old?.status!==data.status))await db.query('DELETE FROM sessions WHERE user_id=$1',[id]);await audit(db,actor.id,id?'user.updated':'user.created','user',target);if(roleChanged)await audit(db,actor.id,'role.changed','user',target);if(overrideChanged)await audit(db,actor.id,'permission.changed','user',target);if(id&&old?.status!==data.status)await audit(db,actor.id,data.status==='ACTIVE'?'user.activated':'user.disabled','user',target);return {id:target,...(password?{temporaryPassword:password}:{})};});}
export async function userAction(actor:Identity,id:string,action:string,payload:Record<string,unknown>){if(action==='status'){const next=status.parse(payload.status);return transaction(async db=>{await lock(db);actor=await acting(db,actor);required(actor,'users','disable');if(id===actor.id)throw new AppError(400,'Kendi hesabınızı pasife alamazsınız.');await record(db,'users',id);const roles=await protectUser(db,actor,id);if(roles.includes('SUPER_ADMIN')&&!['ACTIVE','ON_LEAVE'].includes(next)){const remaining=await db.query("SELECT u.id FROM users u JOIN user_roles ur ON ur.user_id=u.id WHERE ur.role_id='SUPER_ADMIN' AND u.status IN('ACTIVE','ON_LEAVE') AND u.archived_at IS NULL AND u.id<>$1",[id]);if(!remaining.rows.length)throw new AppError(400,'Son aktif süper yönetici pasife alınamaz.');}await db.query("UPDATE users SET status=$1,updated_at=now(),archived_at=CASE WHEN $1='LEFT' THEN now() ELSE NULL END WHERE id=$2",[next,id]);await db.query('DELETE FROM sessions WHERE user_id=$1',[id]);await audit(db,actor.id,next==='ACTIVE'?'user.activated':'user.disabled','user',id);return {id};});}if(action==='reset-password'){const password=typeof payload.password==='string'&&payload.password?payload.password:temporaryPassword();const hashed=await hashPassword(password);return transaction(async db=>{await lock(db);actor=await acting(db,actor);required(actor,'users','reset_password');await record(db,'users',id);await protectUser(db,actor,id);await db.query('UPDATE credentials SET password_hash=$1,changed_at=now() WHERE user_id=$2',[hashed,id]);await db.query('UPDATE users SET must_change_password=true,updated_at=now() WHERE id=$1',[id]);await db.query('DELETE FROM sessions WHERE user_id=$1',[id]);await audit(db,actor.id,'password.reset','user',id);return {temporaryPassword:password};});}throw new AppError(404,'İşlem bulunamadı.');}
export async function saveOrg(actor:Identity,resource:string,payload:unknown,id?:string){const config=orgResources[resource];if(!config)throw new AppError(404,'Bölüm bulunamadı.');const data=orgSchema.parse(payload);return transaction(async db=>{await lock(db);actor=await acting(db,actor);required(actor,config.permission,id?'edit':'create');if(id){const old=await record(db,config.table,id);if(old.active!==data.active)required(actor,config.permission,'disable');if(resource!=='companies'&&old.company_id!==data.company_id)throw new AppError(400,'Mevcut kaydın şirketi değiştirilemez. Yeni kayıt oluşturun.');if(resource==='units'&&old.department_id!==data.department_id)throw new AppError(400,'Mevcut birimin departmanı değiştirilemez.');}
 const target=id??randomUUID();if(resource!=='companies'){if(!data.company_id)throw new AppError(400,'Şirket seçin.');await checkCompany(db,'companies',data.company_id,data.company_id);}if(resource==='units'&&!data.department_id)throw new AppError(400,'Departman seçin.');await checkCompany(db,'departments',data.department_id,data.company_id);
 if(resource==='departments'&&data.parent_id){await checkCompany(db,'departments',data.parent_id,data.company_id);const chain=(await db.query<{id:string}>('WITH RECURSIVE chain AS (SELECT id,parent_id FROM departments WHERE id=$1 UNION SELECT d.id,d.parent_id FROM departments d JOIN chain c ON d.id=c.parent_id) SELECT id FROM chain',[data.parent_id])).rows;if(chain.some(r=>r.id===target))throw new AppError(400,'Departman hiyerarşisi döngü oluşturamaz.');}if(data.manager_user_id){const manager=await record(db,'users',data.manager_user_id);if(manager.status!=='ACTIVE'||manager.archived_at)throw new AppError(400,'Aktif yönetici seçin.');}
 const cols=config.fields,values=cols.map(c=>{const value=data[c as keyof typeof data];return value??(c==='timezone'?'Europe/Istanbul':null);});if(id)await db.query(`UPDATE ${config.table} SET ${cols.map((c,i)=>c+'=$'+(i+1)).join(',')} WHERE id=$${cols.length+1}`,[...values,id]);else await db.query(`INSERT INTO ${config.table}(${cols.join(',')},id) VALUES(${[...values,target].map((_,i)=>'$'+(i+1)).join(',')})`,[...values,target]);await audit(db,actor.id,resource+(id?'.updated':'.created'),resource,target);return {id:target};});}
export async function saveRole(actor:Identity,payload:unknown,id?:string){const data=z.object({id:z.string().regex(/^[A-Z][A-Z0-9_]{2,63}$/),name:z.string().trim().min(1).max(80),active:z.boolean(),permissions:z.array(z.enum(allPermissionIds as [string,...string[]])).max(100)}).strict().parse(payload);return transaction(async db=>{await lock(db);actor=await acting(db,actor);required(actor,'roles','manage');if(data.id==='SUPER_ADMIN'||id==='SUPER_ADMIN')throw new AppError(403,'Süper yönetici rolü değiştirilemez.');if(id&&id!==data.id)throw new AppError(400,'Rol kodu değiştirilemez.');if(data.permissions.some(p=>!can(actor,p)))throw new AppError(403,'Sahip olmadığınız yetkiyi veremezsiniz.');if(id){await record(db,'roles',id);const old=(await db.query<{permission_id:string}>('SELECT permission_id FROM role_permissions WHERE role_id=$1',[id])).rows;if(old.some(p=>!can(actor,p.permission_id)))throw new AppError(403,'Bu rolü yönetemezsiniz.');await db.query('UPDATE roles SET name=$1,active=$2 WHERE id=$3',[data.name,data.active,id]);}else await db.query('INSERT INTO roles(id,name,active) VALUES($1,$2,$3)',[data.id,data.name,data.active]);await db.query('DELETE FROM role_permissions WHERE role_id=$1',[data.id]);for(const p of new Set(data.permissions))await db.query('INSERT INTO role_permissions VALUES($1,$2)',[data.id,p]);await db.query('DELETE FROM sessions WHERE user_id IN(SELECT user_id FROM user_roles WHERE role_id=$1)',[data.id]);await audit(db,actor.id,'role.changed','role',data.id);return {id:data.id};});}
export async function adminRead(actor:Identity,resource:string,url:URL,id?:string){const db=database();if(resource==='summary'){requirePermission(actor,'admin.view');const stats:Record<string,number>={};for(const [key,sql]of Object.entries({total:'SELECT count(*) n FROM users',active:"SELECT count(*) n FROM users WHERE status='ACTIVE'",inactive:"SELECT count(*) n FROM users WHERE status IN('INACTIVE','LEFT')",companies:'SELECT count(*) n FROM companies',locations:'SELECT count(*) n FROM locations',departments:'SELECT count(*) n FROM departments'}))stats[key]=Number((await db.query<{n:string}>(sql)).rows[0].n);return {stats};}
 if(resource==='options'){if(!can(actor,'admin.view')||!['users.view','users.create','users.edit','users.manage','organization.view',...Object.values(orgResources).flatMap(r=>[r.permission+'.view',r.permission+'.manage',r.permission+'.create',r.permission+'.edit'])].some(p=>can(actor,p)))throw new AppError(403,'Yetkiniz bulunmuyor.');const options:Record<string,unknown>={};for(const [key,cfg]of Object.entries(orgResources))options[key]=(await db.query(`SELECT id,name,active${key!=='companies'?',company_id':''}${['units','job-titles'].includes(key)?',department_id':''} FROM ${cfg.table} ORDER BY name`)).rows;options.managers=(await db.query("SELECT id,first_name || ' ' || last_name name FROM users WHERE status='ACTIVE' AND archived_at IS NULL ORDER BY first_name LIMIT 2000")).rows;options.employeeTypes=(await db.query('SELECT id,name FROM employee_types WHERE active=true ORDER BY name')).rows;options.roles=(await db.query('SELECT id,name,active FROM roles ORDER BY name')).rows;options.rolePermissions=(await db.query('SELECT * FROM role_permissions')).rows;return options;}
 if(resource==='users'){required(actor,'users','view');if(id){const u=await record(db,'users',id);return {user:u,roles:await rolesFor(db,id),overrides:(await db.query('SELECT permission_id,allowed FROM user_permission_overrides WHERE user_id=$1',[id])).rows};}const values:unknown[]=[],where:string[]=[];const q=url.searchParams.get('q')?.trim().slice(0,100);if(q){values.push('%'+q+'%');where.push(`(u.first_name ILIKE $${values.length} OR u.last_name ILIKE $${values.length} OR u.username ILIKE $${values.length} OR u.email ILIKE $${values.length} OR u.personnel_no ILIKE $${values.length})`);}for(const key of ['company_id','location_id','department_id','status']){const v=url.searchParams.get(key);if(v){values.push(v);where.push(`u.${key}=$${values.length}`);}}const role=url.searchParams.get('role');if(role){values.push(role);where.push(`EXISTS(SELECT 1 FROM user_roles ur WHERE ur.user_id=u.id AND ur.role_id=$${values.length})`);}const condition=where.length?' WHERE '+where.join(' AND '):'';const total=Number((await db.query<{n:string}>('SELECT count(*) n FROM users u'+condition,values)).rows[0].n);const page=Math.max(1,Math.min(100000,Number(url.searchParams.get('page'))||1)),size=20;const sort={name:'u.first_name',created:'u.created_at',personnel:'u.personnel_no',username:'u.username'}[url.searchParams.get('sort')??'name']??'u.first_name';values.push(size,(page-1)*size);const rows=(await db.query(`SELECT u.*,c.name company_name,l.name location_name,d.name department_name,j.name job_title_name,m.first_name || ' ' || m.last_name manager_name,(SELECT string_agg(role_id,', ' ORDER BY role_id) FROM user_roles WHERE user_id=u.id) roles FROM users u LEFT JOIN companies c ON c.id=u.company_id LEFT JOIN locations l ON l.id=u.location_id LEFT JOIN departments d ON d.id=u.department_id LEFT JOIN job_titles j ON j.id=u.job_title_id LEFT JOIN users m ON m.id=u.manager_user_id ${condition} ORDER BY ${sort} ${url.searchParams.get('dir')==='desc'?'DESC':'ASC'},u.id LIMIT $${values.length-1} OFFSET $${values.length}`,values)).rows;return {rows,total,page,size};}
 if(resource==='roles'){required(actor,'roles','view');return {rows:(await db.query('SELECT * FROM roles ORDER BY name')).rows,permissions:(await db.query('SELECT * FROM role_permissions')).rows};}
 const cfg=orgResources[resource];if(cfg){required(actor,cfg.permission,'view');return {rows:(await db.query(`SELECT * FROM ${cfg.table} ORDER BY name`)).rows};}throw new AppError(404,'Bölüm bulunamadı.');}
