import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {DB,database} from './db';
import {Identity,can} from './permissions';
import {write,permit} from './workflows';
import {AppError} from './security';
import {audit} from './admin';
import {proofFile} from './proof-files';
import {syncOrientationAssetAcceptance} from './academy';
export const handoverRuleSchema=z.object({delivery_photo:z.boolean().default(false),delivery_signature:z.boolean().default(false),delivery_document:z.boolean().default(false),return_photo:z.boolean().default(false),return_signature:z.boolean().default(false),return_condition:z.boolean().default(false)}).strict();
export const handoverSchema=z.object({condition:z.string().trim().max(500).default(''),damage:z.string().trim().max(1000).default(''),missing_accessories:z.string().trim().max(1000).default(''),notes:z.string().trim().max(1000).default(''),accessories:z.array(z.object({name:z.string().trim().min(1).max(100),present:z.boolean()}).strict()).max(30).default([]),photos:z.array(proofFile.refine(f=>f.mime.startsWith('image/'))).max(8).default([]),documents:z.array(proofFile).max(8).default([])}).strict().refine(d=>[...d.photos,...d.documents].reduce((n,f)=>n+f.data.length,0)<=300000,'Eklerin toplamı en fazla 220 KB olabilir.');
export type Handover=z.infer<typeof handoverSchema>;
export type Rules=z.infer<typeof handoverRuleSchema>;
type Assignment={id:string;user_id:string;status:string;rules_snapshot:Rules};
export async function categoryRules(db:DB,id:string){const r=(await db.query<{handover_rules:Rules}>('SELECT handover_rules FROM inventory_categories WHERE id=$1',[id])).rows[0];return handoverRuleSchema.parse(r?.handover_rules??{});}
export async function writeHandover(db:DB,actor:string,assignment:Assignment,phase:'DELIVERY'|'RETURN',value:unknown){const d=handoverSchema.parse(value),rules=handoverRuleSchema.parse(assignment.rules_snapshot);if((phase==='DELIVERY'?rules.delivery_photo:rules.return_photo)&&!d.photos.length)throw new AppError(400,'Bu kategoride fotoğraf zorunludur.');if(phase==='DELIVERY'&&rules.delivery_document&&!d.documents.length)throw new AppError(400,'Bu kategoride teslim evrakı zorunludur.');if(phase==='RETURN'&&rules.return_condition&&!d.condition)throw new AppError(400,'İade durum değerlendirmesi zorunludur.');await db.query('INSERT INTO asset_handover(id,assignment_id,phase,actor_id,counterparty_id,condition,damage,missing_accessories,notes,accessories,photos,documents) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)',[randomUUID(),assignment.id,phase,actor,assignment.user_id,d.condition,d.damage,d.missing_accessories,d.notes,JSON.stringify(d.accessories),JSON.stringify(d.photos),JSON.stringify(d.documents)]);}
export async function handoverDetail(a:Identity,id:string){z.string().uuid().parse(id);if(a.must_change_password)throw new AppError(401,'Şifrenizi değiştirin.');const row=(await database().query<Assignment&{asset_number:string;brand:string;model:string}>(`SELECT a.id,a.user_id,a.status,a.rules_snapshot,i.asset_number,i.brand,i.model FROM asset_assignments a JOIN inventory_items i ON i.id=a.inventory_id WHERE a.id=$1 AND (a.user_id=$2 AND $3::boolean OR $4::boolean)`,[id,a.id,can(a,'portal.assets.view'),can(a,'admin.view')&&can(a,'assignments.view')])).rows[0];if(!row)throw new AppError(404,'Zimmet bulunamadı.');const handovers=(await database().query<Handover&{phase:string;created_at:string}>('SELECT phase,condition,damage,missing_accessories,notes,accessories,photos,documents,created_at::text FROM asset_handover WHERE assignment_id=$1 ORDER BY created_at',[id])).rows,acceptances=(await database().query<{phase:string;accepted_at:string;form_version:number}>('SELECT phase,accepted_at::text,form_version FROM assignment_acceptances WHERE assignment_id=$1',[id])).rows;return {item:row,handovers,acceptances};}
export async function prepareReturn(a:Identity,id:string,payload:unknown){z.string().uuid().parse(id);return write(a,'assignments.return',true,async(db,live)=>{const r=(await db.query<Assignment>('SELECT id,user_id,status,rules_snapshot FROM asset_assignments WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!r||r.status!=='ACTIVE')throw new AppError(409,'Aktif zimmet bulunamadı.');await writeHandover(db,live.id,r,'RETURN',payload);await audit(db,live.id,'assignment.return_prepared','assignment',id);return {id};});}
export async function acceptAssignment(a:Identity,id:string,phase:'DELIVERY'|'RETURN'){z.string().uuid().parse(id);return write(a,'portal.assets.view',false,async(db,live)=>{const r=(await db.query<Assignment>('SELECT id,user_id,status,rules_snapshot FROM asset_assignments WHERE id=$1 AND user_id=$2 FOR UPDATE',[id,live.id])).rows[0];if(!r)throw new AppError(404,'Zimmet bulunamadı.');if(r.status!=='ACTIVE')throw new AppError(409,'Zimmet artık kabul edilemez.');if(!(await db.query('SELECT id FROM asset_handover WHERE assignment_id=$1 AND phase=$2',[id,phase])).rows.length)throw new AppError(409,'Önce teslim/iade formu hazırlanmalıdır.');const existing=await db.query('SELECT id FROM assignment_acceptances WHERE assignment_id=$1 AND phase=$2',[id,phase]);if(existing.rows.length)throw new AppError(409,'Bu form zaten kabul edildi.');await db.query('INSERT INTO assignment_acceptances(id,assignment_id,user_id,phase,form_version) VALUES($1,$2,$3,$4,1)',[randomUUID(),id,live.id,phase]);await syncOrientationAssetAcceptance(db,live.id,id,phase);await audit(db,live.id,'assignment.accepted','assignment',id,{phase,form_version:1});return {id};});}
export async function serviceHistory(a:Identity,id:string){permit(a,'inventory.view',true);z.string().uuid().parse(id);return (await database().query<{id:string;issue:string;provider:string;sent_date:string;returned_date:string|null;work:string;cost:string|null;notes:string;document:z.infer<typeof proofFile>|null}>('SELECT id,issue,provider,sent_date::text,returned_date::text,work,cost,notes,document FROM inventory_service_history WHERE inventory_id=$1 ORDER BY sent_date DESC,id LIMIT 100',[id])).rows;}
export async function saveService(a:Identity,id:string,payload:unknown){z.string().uuid().parse(id);const d=z.object({issue:z.string().trim().min(1).max(1000),provider:z.string().trim().min(1).max(200),sent_date:z.string().date(),returned_date:z.string().date().nullable(),work:z.string().max(3000).default(''),cost:z.number().min(0).max(999999999).nullable(),notes:z.string().max(1000).default(''),document:proofFile.nullable()}).strict().parse(payload);if(d.returned_date&&d.returned_date<d.sent_date)throw new AppError(400,'Dönüş tarihi gönderimden önce olamaz.');return write(a,'inventory.manage',true,async(db,live)=>{if(!(await db.query('SELECT id FROM inventory_items WHERE id=$1',[id])).rows.length)throw new AppError(404,'Envanter bulunamadı.');const target=randomUUID();await db.query('INSERT INTO inventory_service_history(id,inventory_id,issue,provider,sent_date,returned_date,work,cost,notes,document,actor_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)',[target,id,d.issue,d.provider,d.sent_date,d.returned_date,d.work,d.cost,d.notes,d.document?JSON.stringify(d.document):null,live.id]);await audit(db,live.id,'inventory.service_recorded','inventory',id);return {id:target};});}
