import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {database,transaction,lock,DB} from './db';
import {Identity,can} from './permissions';
import {identityFor} from './auth-core';
import {audit} from './admin';
import {AppError} from './security';
import {uploadedImageValid} from './upload';
import {validateBrandFile} from './brand-files';
import {BrandRow,signatureMarkup} from './brand-shared';
import {foldText} from './directory-shared';
const uuid=z.string().regex(/^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$/i);
export function brandPermit(a:Identity,p:string){if(a.must_change_password||!can(a,p))throw new AppError(403,'Bu işlem için yetkiniz bulunmuyor.');}
async function write<T>(a:Identity,p:string,fn:(db:DB,live:Identity)=>Promise<T>){return transaction(async db=>{await lock(db);const live=await identityFor(db,a.id);if(!live)throw new AppError(401,'Yeniden giriş yapın.');brandPermit(live,p);return fn(db,live);});}
const meta=z.object({title:z.string().trim().min(1).max(200),category_id:uuid,company_id:uuid.nullable().default(null),audience_all:z.boolean(),description:z.string().max(3000).default(''),usage_note:z.string().max(3000).default(''),tags:z.array(z.string().trim().min(1).max(60)).max(15).default([])}).strict();
const thumb=z.string().max(55000).refine(v=>uploadedImageValid(v)&&Buffer.from(v.split(',')[1],'base64').length<=40000,'Önizleme en fazla 40 KB PNG/JPEG/WebP olmalıdır.').nullable().default(null);
const file=z.object({version:z.string().trim().min(1).max(40),file_name:z.string().max(150),file_type:z.string().max(150),file_data:z.string().max(270000),thumbnail:thumb}).strict();
async function insertVersion(db:DB,a:Identity,id:string,payload:unknown){const f=file.parse(payload),bytes=validateBrandFile(f.file_name,f.file_type,f.file_data),vid=randomUUID();await db.query('INSERT INTO brand_asset_versions(id,asset_id,version,file_name,file_type,file_data,file_size,thumbnail,uploaded_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)',[vid,id,f.version,f.file_name,f.file_type,f.file_data,bytes,f.thumbnail,a.id]);return vid;}
async function getAsset(db:DB,id:string){const row=(await db.query<BrandRow>('SELECT * FROM brand_assets WHERE id=$1 FOR UPDATE',[uuid.parse(id)])).rows[0];if(!row)throw new AppError(404,'Materyal bulunamadı.');return row;}
export async function saveAsset(a:Identity,payload:unknown,id?:string){const input=z.object({meta,file:file.optional()}).strict().parse(payload);if(id&&input.file)throw new AppError(400,'Dosya değişikliği için yeni versiyon yükleyin.');if(!id&&!input.file)throw new AppError(400,'Dosya seçin.');return write(a,'brand_center.manage',async(db,live)=>{const d=input.meta;if(id)await getAsset(db,id);if(!d.audience_all&&!d.company_id)throw new AppError(400,'Şirkete özel materyal için şirket seçin.');if(!(await db.query('SELECT id FROM brand_categories WHERE id=$1 AND active',[d.category_id])).rows.length)throw new AppError(400,'Aktif kategori seçin.');if(d.company_id&&!(await db.query('SELECT id FROM companies WHERE id=$1 AND active AND archived_at IS NULL',[d.company_id])).rows.length)throw new AppError(400,'Aktif şirket seçin.');const aid=id??randomUUID(),v=[aid,d.title,d.category_id,d.company_id,d.audience_all,d.description,d.usage_note,d.tags,live.id];await db.query(id?'UPDATE brand_assets SET title=$2,category_id=$3,company_id=$4,audience_all=$5,description=$6,usage_note=$7,tags=$8,updated_at=now() WHERE id=$1 AND $9::uuid IS NOT NULL':'INSERT INTO brand_assets(id,title,category_id,company_id,audience_all,description,usage_note,tags,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)',v);const versionId=input.file?await insertVersion(db,live,aid,input.file):undefined;await audit(db,live.id,id?'brand_asset.updated':'brand_asset.created','brand_asset',aid);return {id:aid,versionId};});}
export async function addVersion(a:Identity,id:string,payload:unknown){return write(a,'brand_center.manage',async(db,live)=>{await getAsset(db,id);const versionId=await insertVersion(db,live,id,payload);await db.query('UPDATE brand_assets SET updated_at=now() WHERE id=$1',[id]);await audit(db,live.id,'brand_asset.version_uploaded','brand_version',versionId);return {id,versionId};});}
export async function assetAction(a:Identity,id:string,payload:unknown){const d=z.object({action:z.enum(['current','archive']),version_id:uuid.optional()}).strict().parse(payload);return write(a,'brand_center.manage',async(db,live)=>{await getAsset(db,id);if(d.action==='current'){if(!d.version_id)throw new AppError(400,'Versiyon seçin.');if(!(await db.query('SELECT id FROM brand_asset_versions WHERE asset_id=$1 AND id=$2',[id,d.version_id])).rows.length)throw new AppError(404,'Versiyon bulunamadı.');await db.query("UPDATE brand_asset_versions SET status='ARCHIVED' WHERE asset_id=$1 AND status='CURRENT'",[id]);await db.query("UPDATE brand_asset_versions SET status='CURRENT',published_at=now() WHERE id=$1",[d.version_id]);await db.query('UPDATE brand_assets SET archived=false,updated_at=now() WHERE id=$1',[id]);}else {await db.query('UPDATE brand_assets SET archived=true,updated_at=now() WHERE id=$1',[id]);await db.query("UPDATE brand_asset_versions SET status='ARCHIVED' WHERE asset_id=$1 AND status='CURRENT'",[id]);}await audit(db,live.id,'brand_asset.'+(d.action==='current'?'current':'archived'),'brand_asset',id);return {id};});}
export const brandVisibility="NOT a.archived AND v.status='CURRENT' AND v.published_at<=now() AND (a.audience_all OR a.company_id=(SELECT company_id FROM users WHERE id=$1))";
const versionJoin="LEFT JOIN LATERAL(SELECT id,version,file_name,file_type,file_size,thumbnail,status,published_at,created_at,uploaded_by FROM brand_asset_versions WHERE asset_id=a.id ORDER BY (status='CURRENT') DESC,created_at DESC,id DESC LIMIT 1)v ON true";
const cols="a.id,a.title,a.category_id,a.company_id,a.audience_all,a.description,a.usage_note,a.tags,a.created_at,a.updated_at,c.name AS category_name,co.name AS company_name,v.id AS version_id,v.version,v.file_name,v.file_type,v.file_size,v.thumbnail,v.published_at,CASE WHEN a.archived THEN 'ARCHIVED' ELSE v.status END AS status";
const from=`FROM brand_assets a JOIN brand_categories c ON c.id=a.category_id LEFT JOIN companies co ON co.id=a.company_id ${versionJoin}`;
export async function assetList(a:Identity,p=new URLSearchParams(),admin=false){brandPermit(a,admin?'brand_center.manage':'brand_center.view');for(const k of p.keys())if(!['q','page','category_id','company_id','file_type','status','tag'].includes(k))throw new AppError(400,'Geçersiz filtre.');const page=z.coerce.number().int().min(1).max(100000).parse(p.get('page')||1),values:unknown[]=[a.id],where=[admin?'$1::uuid IS NOT NULL':brandVisibility];if(p.get('q')){values.push('%'+foldText(p.get('q')!.slice(0,100)).replace(/[\\%_]/g,'\\$&')+'%');where.push(`portal_fold(a.title) LIKE $${values.length}`);}for(const k of ['category_id','company_id'])if(p.get(k)){values.push(uuid.parse(p.get(k)));where.push('a.'+k+'=$'+values.length);}if(p.get('file_type')){values.push(p.get('file_type')!.slice(0,150));where.push('v.file_type=$'+values.length);}if(p.get('tag')){values.push(p.get('tag')!.slice(0,60));where.push('$'+values.length+'=ANY(a.tags)');}if(p.get('status')){values.push(z.enum(['CURRENT','DRAFT','ARCHIVED']).parse(p.get('status')));where.push("(CASE WHEN a.archived THEN 'ARCHIVED' ELSE v.status END)=$"+values.length);}const out=(await database().query<{rows:BrandRow[];total:number}>(`WITH matches AS(SELECT a.id ${from} WHERE ${where.join(' AND ')}),chosen AS(SELECT a.id FROM brand_assets a JOIN matches m ON m.id=a.id ORDER BY a.updated_at DESC,a.id LIMIT 20 OFFSET ${(page-1)*20}) SELECT (SELECT count(*)::int FROM matches) AS total,COALESCE((SELECT jsonb_agg(r ORDER BY r.updated_at DESC,r.id) FROM(SELECT ${cols} ${from} JOIN chosen ON chosen.id=a.id)r),'[]') AS rows`,values)).rows[0];return {...out,page,size:20};}
export async function assetDetail(a:Identity,id:string,admin=false){brandPermit(a,admin?'brand_center.manage':'brand_center.view');const item=(await database().query<BrandRow>(`SELECT ${cols},u.first_name||' '||u.last_name AS uploaded_by_name ${from} LEFT JOIN users u ON u.id=v.uploaded_by WHERE a.id=$2 AND ${admin?'$1::uuid IS NOT NULL':brandVisibility}`,[a.id,uuid.parse(id)])).rows[0];if(!item)throw new AppError(404,'Materyal bulunamadı.');const versions=admin?(await database().query<BrandRow>('SELECT v.id,v.version,v.status,v.file_name,v.file_type,v.file_size,v.created_at,v.published_at,u.first_name||\' \'||u.last_name AS uploaded_by_name FROM brand_asset_versions v JOIN users u ON u.id=v.uploaded_by WHERE asset_id=$1 ORDER BY created_at DESC,v.id DESC',[id])).rows:[];return {item,versions};}
export async function downloadAsset(a:Identity,id:string,versionId?:string){brandPermit(a,'brand_center.download');brandPermit(a,versionId?'brand_center.manage':'brand_center.view');const row=(await database().query<BrandRow>(`SELECT v.file_name,v.file_type,v.file_data FROM brand_assets a JOIN brand_asset_versions v ON v.asset_id=a.id WHERE a.id=$2 AND ${versionId?'v.id=$3 AND $1::uuid IS NOT NULL':brandVisibility}`,[a.id,uuid.parse(id),...(versionId?[uuid.parse(versionId)]:[])])).rows[0];if(!row)throw new AppError(404,'Dosya bulunamadı.');return {name:row.file_name,type:row.file_type,bytes:Buffer.from(row.file_data,'base64')};}
export async function brandOptions(a:Identity,admin=false){brandPermit(a,admin?'brand_center.manage':'brand_center.view');return (await database().query<BrandRow>(`SELECT COALESCE((SELECT jsonb_agg(c ORDER BY c.name) FROM(SELECT id,name,active FROM brand_categories ${admin?'':'WHERE active'})c),'[]') AS categories,COALESCE((SELECT jsonb_agg(c ORDER BY c.name) FROM(SELECT id,name FROM companies WHERE active AND archived_at IS NULL)c),'[]') AS companies`)).rows[0];}
export async function saveBrandCategory(a:Identity,payload:unknown){const d=z.object({id:uuid.optional(),name:z.string().trim().min(1).max(120),active:z.boolean().default(true)}).strict().parse(payload);return write(a,'brand_center.manage',async(db,live)=>{const id=d.id??randomUUID();await db.query('INSERT INTO brand_categories(id,name,active) VALUES($1,$2,$3) ON CONFLICT(id) DO UPDATE SET name=excluded.name,active=excluded.active',[id,d.name,d.active]);await audit(db,live.id,'brand_category.updated','brand_category',id);return {id};});}
const template=z.object({id:uuid.optional(),name:z.string().trim().min(1).max(120),company_id:uuid.nullable().default(null),logo:z.string().max(280000).refine(uploadedImageValid,'Geçerli PNG/JPEG/WebP logo seçin.').nullable().default(null),corporate_text:z.string().max(300).default(''),website:z.string().max(500).default('').refine(v=>!v||URL.canParse(v)&&new URL(v).protocol==='https:'&&!new URL(v).username&&!new URL(v).password,'HTTPS web adresi girin.'),legal_footer:z.string().max(1500).default(''),active:z.boolean().default(true)}).strict();
export async function signatureTemplates(a:Identity){brandPermit(a,'email_signature.manage');return (await database().query<BrandRow>("SELECT COALESCE((SELECT jsonb_agg(x ORDER BY x.name) FROM(SELECT t.*,c.name AS company_name FROM email_signature_templates t LEFT JOIN companies c ON c.id=t.company_id)x),'[]') AS rows,COALESCE((SELECT jsonb_agg(x ORDER BY x.name) FROM(SELECT id,name FROM companies WHERE active AND archived_at IS NULL)x),'[]') AS companies")).rows[0];}
export async function saveSignatureTemplate(a:Identity,payload:unknown){const d=template.parse(payload);return write(a,'email_signature.manage',async(db,live)=>{if(d.company_id&&!(await db.query('SELECT id FROM companies WHERE id=$1 AND active AND archived_at IS NULL',[d.company_id])).rows.length)throw new AppError(400,'Aktif şirket seçin.');const id=d.id??randomUUID();if(d.id&&!(await db.query('SELECT id FROM email_signature_templates WHERE id=$1',[id])).rows.length)throw new AppError(404,'Şablon bulunamadı.');if(d.active)await db.query('UPDATE email_signature_templates SET active=false WHERE company_id IS NOT DISTINCT FROM $1 AND id<>$2',[d.company_id,id]);await db.query('INSERT INTO email_signature_templates(id,company_id,name,logo,corporate_text,website,legal_footer,active,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(id) DO UPDATE SET company_id=excluded.company_id,name=excluded.name,logo=excluded.logo,corporate_text=excluded.corporate_text,website=excluded.website,legal_footer=excluded.legal_footer,active=excluded.active,updated_by=excluded.updated_by,updated_at=now()',[id,d.company_id,d.name,d.logo,d.corporate_text,d.website,d.legal_footer,d.active,live.id]);await audit(db,live.id,'email_signature.updated','email_signature',id);return {id};});}
export async function ownSignature(a:Identity){brandPermit(a,'email_signature.use');const p=(await database().query<BrandRow>("SELECT u.first_name||' '||u.last_name AS name,u.email,u.phone,u.extension,j.name AS job_title,c.name AS company,coalesce(t.logo,c.logo) AS logo,t.name AS template_name,t.corporate_text,t.website,t.legal_footer FROM users u LEFT JOIN companies c ON c.id=u.company_id LEFT JOIN job_titles j ON j.id=u.job_title_id LEFT JOIN LATERAL(SELECT * FROM email_signature_templates WHERE active AND (company_id=u.company_id OR company_id IS NULL) ORDER BY (company_id IS NOT NULL) DESC LIMIT 1)t ON true WHERE u.id=$1 AND u.status IN('ACTIVE','ON_LEAVE') AND u.archived_at IS NULL",[a.id])).rows[0];if(!p)throw new AppError(401,'Yeniden giriş yapın.');if(!p.template_name)throw new AppError(404,'Henüz aktif imza şablonu bulunmuyor.');return {...signatureMarkup(p),profile:p};}
