export const brandPermissions=['corporate_communications.view','brand_center.view','brand_center.download','brand_center.manage','email_signature.use','email_signature.manage'];
export const ownBrandPermissions=brandPermissions.filter(p=>!p.endsWith('.manage'));
export const brandStatus:Record<string,string>={DRAFT:'Taslak',CURRENT:'Güncel',ARCHIVED:'Arşivlendi'};
export const brandFileTypes:Record<string,string>={'image/png':'PNG','image/jpeg':'JPG','image/webp':'WebP','image/svg+xml':'SVG','application/pdf':'PDF','application/vnd.openxmlformats-officedocument.presentationml.presentation':'PowerPoint (.pptx)','application/vnd.openxmlformats-officedocument.wordprocessingml.document':'Word (.docx)'};
export const brandAccept='.png,.jpg,.jpeg,.webp,.svg,.pdf,.pptx,.docx';
export const photoTags=['Merkez Ofis','Showroom','Etkinlik','Kurumsal','Yönetim Binası','Diğer'];
export type BrandRow=Record<string,any>;
export function escapeHTML(value:unknown){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));}
export function signatureMarkup(p:BrandRow){const esc=escapeHTML,lines=[p.job_title,p.company,p.corporate_text].filter(Boolean),contact=[p.email,p.phone,p.extension?'Dahili: '+p.extension:''].filter(Boolean);const plain=[p.name,...lines,...contact,p.website,p.legal_footer].filter(Boolean).join('\n');const logo=p.logo&&/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(p.logo)?`<td style="padding-right:18px;vertical-align:top"><img src="${esc(p.logo)}" width="110" alt="${esc(p.company||'Koyuncu Grup')}" style="max-width:110px;height:auto;border:0"></td>`:'';const website=p.website&&/^https:\/\//i.test(p.website)?`<div style="margin-top:6px"><a href="${esc(p.website)}" style="color:#0074cc">${esc(p.website)}</a></div>`:'';return {plain,html:`<table role="presentation" cellpadding="0" cellspacing="0" style="font-family:Arial,Helvetica,sans-serif;font-size:12px;color:#18324d"><tbody><tr>${logo}<td style="border-left:2px solid #0074cc;padding-left:18px"><strong style="font-size:17px;color:#00182c">${esc(p.name)}</strong>${lines.map(l=>`<div style="margin-top:4px">${esc(l)}</div>`).join('')}<div style="margin-top:10px">${contact.map(esc).join(' · ')}</div>${website}</td></tr>${p.legal_footer?`<tr><td colspan="2" style="padding-top:14px;font-size:10px;color:#65758b;max-width:500px">${esc(p.legal_footer)}</td></tr>`:''}</tbody></table>`};}
