import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {DB,database,transaction,lock} from './db';
import {Identity,can} from './permissions';
import {identityFor} from './auth-core';
import {audit,requirePermission} from './admin';
import {AppError,assertOrigin} from './security';
import {ContentKind,contentKinds,portalContentPermission,homepageDefaults,HomepageSettings,DashboardContent,ContentRow,slugify,targetNames} from './content-shared';
type Row=Record<string,any>;
const guid=z.string().regex(/^[a-f0-9]{8}(-[a-f0-9]{4}){3}-[a-f0-9]{12}$/i);
const short=z.string().trim().max(500).default('');
const stamp=z.string().datetime({offset:true});
const nullableStamp=z.union([stamp,z.literal(''),z.null()]).optional().transform(v=>v||null);
export function kindOf(value:string):ContentKind{if(!contentKinds.includes(value as ContentKind))throw new AppError(404,'İçerik bölümü bulunamadı.');return value as ContentKind;}
function imageValid(value:string){if(['/images/hero/building.webp','/images/hero/lounge.webp'].includes(value))return true;const match=value.match(/^data:image\/(png|jpeg|webp);base64,([A-Za-z0-9+/]+=*)$/);if(!match)return false;const data=Buffer.from(match[2],'base64');return data.length<=200000&&(match[1]==='png'?data.subarray(0,8).equals(Buffer.from('89504e470d0a1a0a','hex')):match[1]==='jpeg'?data.subarray(0,3).equals(Buffer.from('ffd8ff','hex')):data.subarray(0,4).toString()==='RIFF'&&data.subarray(8,12).toString()==='WEBP');}
const image=z.string().max(280000).refine(imageValid,'En fazla 200 KB geçerli PNG/JPG/WebP seçin.').nullable().optional();
const target=z.object({type:z.enum(['company_id','location_id','department_id','unit_id','role_id','user_id']),id:z.string().min(1).max(80)}).strict();
const common=z.object({title:z.string().trim().min(1).max(200),slug:z.string().trim().max(140).optional(),summary:short,body:z.string().max(50000).default(''),cover:image,thumbnail:image,author_id:guid.optional(),priority:z.number().int().min(0).max(2).default(0),publish_at:stamp,expires_at:nullableStamp,audience_all:z.boolean(),targets:z.array(target).max(500)}).strict();
const categoryFields={category_id:guid};
const eventFields={event_start:stamp,event_end:stamp,venue:short,online:z.boolean(),online_url:z.string().max(2000).default('').refine(v=>!v||/^https:\/\//i.test(v)&&URL.canParse(v),'HTTPS adresi girin.'),capacity:z.number().int().min(1).max(100000).nullable().optional(),participation_required:z.boolean(),rsvp_deadline:nullableStamp};
const documentFields={...categoryFields,version:z.string().trim().min(1).max(40),file_name:z.string().trim().min(1).max(150).regex(/^[^\x00-\x1f/\\]+$/),file_type:z.enum(['application/pdf','text/plain']),file_data:z.string().max(270000).optional()};
function schema(kind:ContentKind){return kind==='events'?common.extend(eventFields):kind==='documents'?common.extend(documentFields):common.extend(categoryFields);}
function permit(actor:Identity,p:string){if(actor.must_change_password)throw new AppError(401,'Şifrenizi değiştirin.');requirePermission(actor,p);}
function portalPermit(actor:Identity,kind:ContentKind){if(actor.must_change_password||!can(actor,portalContentPermission[kind]))throw new AppError(403,'Bu içeriğe erişim yetkiniz bulunmuyor.');}
async function write<T>(actor:Identity,p:string,fn:(db:DB,live:Identity)=>Promise<T>){return transaction(async db=>{await lock(db);const live=await identityFor(db,actor.id);if(!live)throw new AppError(401,'Yeniden giriş yapın.');permit(live,p);return fn(db,live);});}
async function record(db:DB,kind:ContentKind,id:string){guid.parse(id);const row=(await db.query<Row>(`SELECT * FROM ${kind} WHERE id=$1 FOR UPDATE`,[id])).rows[0];if(!row)throw new AppError(404,'İçerik bulunamadı.');return row;}
const targetTables:Record<string,string>={company_id:'companies',location_id:'locations',department_id:'departments',unit_id:'units',role_id:'roles',user_id:'users'};
function validateFile(data:Row,old?:Row){if(!data.file_data){if(!old||old.file_type!==data.file_type||old.file_name!==data.file_name)throw new AppError(400,'Doküman dosyasını seçin.');return;}if(!/^[A-Za-z0-9+/]+=*$/.test(data.file_data))throw new AppError(400,'Dosya biçimi geçersiz.');const buffer=Buffer.from(data.file_data,'base64');if(buffer.length<1||buffer.length>200000)throw new AppError(400,'Dosya en fazla 200 KB olmalıdır.');if(data.file_type==='application/pdf'&&(buffer.subarray(0,5).toString()!=='%PDF-'||!data.file_name.toLowerCase().endsWith('.pdf')))throw new AppError(400,'Geçerli PDF dosyası seçin.');if(data.file_type==='text/plain'&&(!data.file_name.toLowerCase().endsWith('.txt')||buffer.includes(0)))throw new AppError(400,'Geçerli TXT dosyası seçin.');}
export async function saveContent(actor:Identity,kind:ContentKind,payload:unknown,id?:string){const parsed=schema(kind).parse(payload) as Row;return write(actor,kind+'.'+(id?'edit':'create'),async(db,live)=>{const old=id?await record(db,kind,id):undefined;if(old?.status==='PUBLISHED')permit(live,kind+'.publish');const data={...parsed};const targets=data.targets as {type:string;id:string}[];delete data.targets;if(data.audience_all&&targets.length||!data.audience_all&&!targets.length)throw new AppError(400,'Tüm kullanıcılar veya en az bir hedef seçin.');if(data.expires_at&&new Date(data.expires_at)<=new Date(data.publish_at))throw new AppError(400,'Yayın bitişi başlangıçtan sonra olmalıdır.');
 if(kind==='events'){if(new Date(data.event_end)<=new Date(data.event_start)||data.rsvp_deadline&&new Date(data.rsvp_deadline)>new Date(data.event_start))throw new AppError(400,'Etkinlik tarihlerini kontrol edin.');if(data.online&&!data.online_url)throw new AppError(400,'Online etkinlik bağlantısını girin.');if(old&&data.capacity){const count=(await db.query<Row>('SELECT count(*)::int AS n FROM event_participants WHERE event_id=$1 AND attending',[id])).rows[0].n;if(data.capacity<count)throw new AppError(400,'Kapasite mevcut katılımcı sayısından küçük olamaz.');}}
 else if(!(await db.query(`SELECT id FROM ${kind}_categories WHERE id=$1 AND active`,[data.category_id])).rows.length)throw new AppError(400,'Geçerli kategori seçin.');
 if(kind==='documents')validateFile(data,old);
 data.author_id=data.author_id??old?.author_id??live.id;if(!(await db.query('SELECT id FROM users WHERE id=$1 AND archived_at IS NULL',[data.author_id])).rows.length)throw new AppError(400,'Geçerli yazar seçin.');
 if(old){if(data.slug&&data.slug!==old.slug)throw new AppError(400,'Mevcut bağlantıyı korumak için slug değiştirilemez.');data.slug=old.slug;}else{data.slug=slugify(data.slug||data.title);if(!data.slug)throw new AppError(400,'Geçerli slug girin.');}
 for(const t of targets){if(t.type!=='role_id')guid.parse(t.id);const table=targetTables[t.type];const active=t.type==='user_id'?"status='ACTIVE' AND archived_at IS NULL":t.type==='role_id'?'active':"active AND archived_at IS NULL";if(!(await db.query(`SELECT id FROM ${table} WHERE id=$1 AND ${active}`,[t.id])).rows.length)throw new AppError(400,'Hedef kitlede geçersiz/pasif kayıt var.');}
 const targetId=id??randomUUID();const cols=Object.keys(data).filter(k=>data[k]!==undefined),values=cols.map(k=>data[k]);await db.query(id?`UPDATE ${kind} SET ${cols.map((c,i)=>c+'=$'+(i+1)).join(',')},updated_at=now() WHERE id=$${cols.length+1}`:`INSERT INTO ${kind}(${cols.join(',')},id) VALUES(${[...values,targetId].map((_,i)=>'$'+(i+1)).join(',')})`,[...values,targetId]);await db.query(`DELETE FROM ${kind}_audience WHERE content_id=$1`,[targetId]);for(const t of targets)await db.query(`INSERT INTO ${kind}_audience(id,content_id,${t.type}) VALUES($1,$2,$3) ON CONFLICT DO NOTHING`,[randomUUID(),targetId,t.id]);await audit(db,live.id,kind+(id?'.updated':'.created'),kind,targetId);return {id:targetId};});}
export async function contentAction(actor:Identity,kind:ContentKind,id:string,action:string){const states:Record<string,string>={publish:'PUBLISHED',unpublish:'DRAFT',archive:'ARCHIVED',cancel:'CANCELLED',complete:'COMPLETED'};if(!states[action]||kind!=='events'&&['cancel','complete'].includes(action))throw new AppError(404,'İşlem bulunamadı.');return write(actor,kind+'.'+(['publish','unpublish'].includes(action)?'publish':'manage'),async db=>{await record(db,kind,id);await db.query(`UPDATE ${kind} SET status=$2,updated_at=now() WHERE id=$1`,[id,states[action]]);await audit(db,actor.id,kind+'.'+({publish:'published',unpublish:'unpublished',archive:'archived',cancel:'cancelled',complete:'completed'} as Record<string,string>)[action],kind,id);return {id};});}
const effective=(kind:ContentKind)=>`CASE WHEN c.status<>'PUBLISHED' THEN c.status ${kind==='events'?"WHEN c.event_end<=now() THEN 'COMPLETED'":''} WHEN c.expires_at<=now() THEN 'EXPIRED' WHEN c.publish_at>now() THEN 'PLANNED' ELSE 'PUBLISHED' END`;
const categoryJoin=(kind:ContentKind)=>kind==='events'?'':` LEFT JOIN ${kind}_categories cat ON cat.id=c.category_id`;
const categoryColumn=(kind:ContentKind)=>kind==='events'?"''::text AS category_name":'cat.name AS category_name';
function pageOf(params:URLSearchParams){return z.coerce.number().int().min(1).max(100000).parse(params.get('page')||1);}
export async function adminContentList(actor:Identity,kind:ContentKind,params=new URLSearchParams()):Promise<{rows:ContentRow[];total:number;page:number}>{permit(actor,kind+'.view');const page=pageOf(params),values:unknown[]=[],clauses:string[]=[];function add(sql:string,value:unknown){values.push(value);clauses.push(sql.replaceAll('?',`$${values.length}`));}if(params.get('q'))add('(c.title ILIKE ? OR c.summary ILIKE ?)','%'+params.get('q')!.slice(0,120)+'%');if(params.get('status'))add(effective(kind)+'=?',params.get('status'));if(kind!=='events'&&params.get('category_id'))add('c.category_id=?',guid.parse(params.get('category_id')));const audience=params.get('audience');if(audience==='all')clauses.push('c.audience_all');else if(audience&&targetNames[audience])clauses.push(`EXISTS(SELECT 1 FROM ${kind}_audience a WHERE a.content_id=c.id AND a.${audience} IS NOT NULL)`);if(params.get('from'))add('c.publish_at>=?::date',z.string().date().parse(params.get('from')));if(params.get('to'))add("c.publish_at<(?::date+interval '1 day')",z.string().date().parse(params.get('to')));const sort=params.get('sort')==='title'?'title':'publish_at',dir=params.get('dir')==='asc'?'ASC':'DESC';const where=clauses.length?' WHERE '+clauses.join(' AND '):'';const result=(await database().query<{rows:ContentRow[];total:number}>(`WITH filtered AS (SELECT c.id,c.title,c.slug,c.publish_at,c.audience_all,${effective(kind)} AS display_status,${categoryColumn(kind)} FROM ${kind} c${categoryJoin(kind)}${where}) SELECT (SELECT count(*)::int FROM filtered) AS total,COALESCE((SELECT jsonb_agg(r) FROM (SELECT * FROM filtered ORDER BY ${sort} ${dir},id LIMIT 20 OFFSET ${(page-1)*20})r),'[]'::jsonb) AS rows`,values)).rows[0];return {...result,page};}
export async function adminContentDetail(actor:Identity,kind:ContentKind,id:string){permit(actor,kind+'.view');guid.parse(id);const columns=kind==='documents'?"c.id,c.title,c.slug,c.category_id,c.summary,c.body,c.cover,c.thumbnail,c.author_id,c.priority,c.publish_at,c.expires_at,c.status,c.audience_all,c.version,c.file_name,c.file_type,c.created_at,c.updated_at":'c.*';const [item,targets,participants]=await Promise.all([database().query<Row>(`SELECT ${columns},${effective(kind)} AS display_status FROM ${kind} c WHERE c.id=$1`,[id]),database().query<Row>(`SELECT company_id,location_id,department_id,unit_id,role_id,user_id FROM ${kind}_audience WHERE content_id=$1`,[id]),kind==='events'?database().query<Row>("SELECT p.user_id,p.attending,p.updated_at,concat_ws(' ',u.first_name,u.last_name) AS name FROM event_participants p JOIN users u ON u.id=p.user_id WHERE p.event_id=$1 ORDER BY p.attending DESC,u.first_name",[id]):Promise.resolve({rows:[]})]);if(!item.rows[0])throw new AppError(404,'İçerik bulunamadı.');return {item:item.rows[0],targets:targets.rows.flatMap(row=>Object.entries(row).filter(([,id])=>id).map(([type,id])=>({type,id}))),participants:participants.rows};}
export async function contentOptions(actor:Identity,kind:ContentKind){if(!['view','create','edit'].some(a=>can(actor,kind+'.'+a)))throw new AppError(403,'Yetkiniz bulunmuyor.');permit(actor,'admin.view');const sections=[['companies','company_id'],['locations','location_id'],['departments','department_id'],['units','unit_id'],['roles','role_id'],['users','user_id']];const selections=sections.map(([table,key])=>`COALESCE((SELECT jsonb_agg(r) FROM (SELECT id,${table==='users'?"concat_ws(' ',first_name,last_name,' · ',username)":'name'} AS name ${['locations','departments','units'].includes(table)?',company_id':''} FROM ${table} WHERE ${table==='users'?"status='ACTIVE' AND archived_at IS NULL":table==='roles'?'active':'active AND archived_at IS NULL'} ORDER BY name)r),'[]'::jsonb) AS ${key}`);selections.push(kind==='events'?"'[]'::jsonb AS categories":`COALESCE((SELECT jsonb_agg(r) FROM (SELECT id,name FROM ${kind}_categories WHERE active ORDER BY name)r),'[]'::jsonb) AS categories`);return (await database().query<Row>('SELECT '+selections.join(','))).rows[0];}
const viewer=`SELECT id,company_id,location_id,department_id,unit_id,$2::text[] AS role_ids FROM users WHERE id=$1 AND status IN('ACTIVE','ON_LEAVE') AND archived_at IS NULL`;
function visibility(kind:ContentKind){return `c.status='PUBLISHED' AND c.publish_at<=now() AND (c.expires_at IS NULL OR c.expires_at>now()) AND (c.audience_all OR EXISTS(SELECT 1 FROM ${kind}_audience a WHERE a.content_id=c.id AND (a.company_id=v.company_id OR a.location_id=v.location_id OR a.department_id=v.department_id OR a.unit_id=v.unit_id OR a.role_id=ANY(v.role_ids) OR a.user_id=v.id)))`;}
function publicColumns(kind:ContentKind,detail=false){return `c.id,c.title,c.slug,c.summary,c.cover,c.thumbnail,c.publish_at,c.priority,${categoryColumn(kind)}${detail?",c.body,concat_ws(' ',author.first_name,author.last_name) AS author_name":''}${kind==='events'?",c.event_start,c.event_end,c.venue,c.online,c.online_url,c.capacity,c.participation_required,c.rsvp_deadline,(SELECT p.attending FROM event_participants p WHERE p.event_id=c.id AND p.user_id=$1) AS attending":''}${kind==='documents'?',c.version,c.file_name,c.file_type':''}`;}
export async function publicContentList(actor:Identity,kind:ContentKind,params=new URLSearchParams()):Promise<{rows:ContentRow[];total:number;page:number}>{portalPermit(actor,kind);const page=pageOf(params);const result=(await database().query<{rows:ContentRow[];total:number}>(`WITH viewer AS (${viewer}),visible AS (SELECT ${publicColumns(kind)} FROM ${kind} c CROSS JOIN viewer v${categoryJoin(kind)} WHERE ${visibility(kind)} AND (c.title ILIKE $3 OR c.summary ILIKE $3)) SELECT (SELECT count(*)::int FROM visible) AS total,COALESCE((SELECT jsonb_agg(r) FROM (SELECT * FROM visible ORDER BY priority DESC,publish_at DESC,id LIMIT 20 OFFSET ${(page-1)*20})r),'[]'::jsonb) AS rows`,[actor.id,actor.roles,'%'+(params.get('q')||'').slice(0,120)+'%'])).rows[0];return {...result,page};}
export async function publicContentDetail(actor:Identity,kind:ContentKind,slug:string,db:DB=database()){portalPermit(actor,kind);if(!/^[a-z0-9]+(-[a-z0-9]+)*$/.test(slug)||slug.length>140)throw new AppError(404,'İçerik bulunamadı.');const row=(await db.query<ContentRow>(`WITH viewer AS (${viewer}) SELECT ${publicColumns(kind,true)} FROM ${kind} c CROSS JOIN viewer v JOIN users author ON author.id=c.author_id${categoryJoin(kind)} WHERE c.slug=$3 AND ${visibility(kind)}`,[actor.id,actor.roles,slug])).rows[0];if(!row)throw new AppError(404,'İçerik bulunamadı.');return row;}
export async function documentDownload(actor:Identity,slug:string){portalPermit(actor,'documents');const row=(await database().query<Row>(`WITH viewer AS (${viewer}) SELECT c.file_name,c.file_type,c.file_data FROM documents c CROSS JOIN viewer v WHERE c.slug=$3 AND ${visibility('documents')}`,[actor.id,actor.roles,slug])).rows[0];if(!row)throw new AppError(404,'Doküman bulunamadı.');return {name:row.file_name,type:row.file_type,bytes:Buffer.from(row.file_data,'base64')};}
export async function participate(actor:Identity,slug:string,payload:unknown){const data=z.object({attending:z.boolean()}).strict().parse(payload);return transaction(async db=>{await lock(db);const live=await identityFor(db,actor.id);if(!live)throw new AppError(401,'Yeniden giriş yapın.');const event=await publicContentDetail(live,'events',slug,db);const now=Date.now();if(!event.participation_required||new Date(event.event_start!).getTime()<=now||event.rsvp_deadline&&new Date(event.rsvp_deadline).getTime()<now)throw new AppError(409,'Bu etkinlik için katılım süresi kapalı.');if(data.attending&&event.capacity){const count=(await db.query<Row>('SELECT count(*)::int AS n FROM event_participants WHERE event_id=$1 AND attending AND user_id<>$2',[event.id,live.id])).rows[0].n;if(count>=event.capacity)throw new AppError(409,'Etkinlik kapasitesi doldu.');}await db.query('INSERT INTO event_participants(event_id,user_id,attending) VALUES($1,$2,$3) ON CONFLICT(event_id,user_id) DO UPDATE SET attending=excluded.attending,updated_at=now()',[event.id,live.id,data.attending]);return {attending:data.attending};});}
const homeSchema=z.object({hero_title:z.string().max(160),hero_subtitle:z.string().max(300),hero_image:image,hero_active:z.boolean(),corporate_image:image,corporate_quote:z.string().max(250),corporate_caption:z.string().max(120),corporate_active:z.boolean(),announcements_title:z.string().min(1).max(80),events_title:z.string().min(1).max(80),news_title:z.string().min(1).max(80)}).strict();
export async function homepageRead(actor:Identity){permit(actor,'homepage.view');const row=(await database().query<Row>('SELECT settings FROM homepage_content WHERE id=1')).rows[0];return {...homepageDefaults,...row?.settings} as HomepageSettings;}
export async function saveHomepage(actor:Identity,payload:unknown){const data=homeSchema.parse(payload);return write(actor,'homepage.manage',async db=>{await db.query('INSERT INTO homepage_content(id,settings,updated_by) VALUES(1,$1,$2) ON CONFLICT(id) DO UPDATE SET settings=excluded.settings,updated_by=excluded.updated_by,updated_at=now()',[JSON.stringify(data),actor.id]);await audit(db,actor.id,'homepage.updated','homepage','1');return {ok:true};});}
export async function dashboardContent(actor:Identity):Promise<DashboardContent>{if(!can(actor,'portal.home.view')||actor.must_change_password)throw new AppError(403,'Yetkiniz bulunmuyor.');const subqueries=(['announcements','news','events'] as const).map(kind=>can(actor,portalContentPermission[kind])?`COALESCE((SELECT jsonb_agg(r) FROM (SELECT ${publicColumns(kind)} FROM ${kind} c CROSS JOIN viewer v${categoryJoin(kind)} WHERE ${visibility(kind)}${kind==='events'?' AND c.event_start>now()':''} ORDER BY ${kind==='events'?'c.event_start ASC':'c.priority DESC,c.publish_at DESC'},c.id LIMIT 3)r),'[]'::jsonb) AS ${kind}`:`'[]'::jsonb AS ${kind}`);const row=(await database().query<Row>(`WITH viewer AS (${viewer}) SELECT ${subqueries.join(',')},(SELECT settings FROM homepage_content WHERE id=1) AS homepage`,[actor.id,actor.roles])).rows[0];return {announcements:row.announcements,news:row.news,events:row.events,homepage:{...homepageDefaults,...row.homepage}};}
export async function readContentJSON(request:Request){assertOrigin(request);const raw=await request.text();if(raw.length>900000)throw new AppError(413,'Gönderilen içerik çok büyük.');try{return JSON.parse(raw);}catch{throw new AppError(400,'Gönderilen veri okunamadı.');}}
