import {z} from 'zod';
import {database} from './db';
import {Identity,can} from './permissions';
import {AppError} from './security';
import {Birthday,DirectoryData,Person,SearchGroup,foldText} from './directory-shared';
import {contentKinds,contentNames,portalContentPermission} from './content-shared';
export function directoryAllowed(a:Identity){return !a.must_change_password&&can(a,'directory.view')&&can(a,'portal.directory.view');}
function permit(a:Identity){if(!directoryAllowed(a))throw new AppError(403,'Rehber görüntüleme yetkiniz bulunmuyor.');}
const guid=z.string().regex(/^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$/i);
export const directoryVisible=(alias:string)=>`${alias}.show_in_directory AND ${alias}.status IN('ACTIVE','ON_LEAVE') AND ${alias}.archived_at IS NULL`;
const joins=`FROM users u LEFT JOIN companies c ON c.id=u.company_id LEFT JOIN locations l ON l.id=u.location_id LEFT JOIN departments d ON d.id=u.department_id LEFT JOIN units un ON un.id=u.unit_id LEFT JOIN job_titles j ON j.id=u.job_title_id`;
const columns="u.id,u.first_name||' '||u.last_name AS name,u.photo,j.name AS job_title,d.name AS department,c.name AS company,l.name AS location,un.name AS unit";
function pattern(q:string){return '%'+foldText(q.trim().slice(0,100)).replace(/[\\%_]/g,'\\$&')+'%';}
function searchWhere(contact:boolean,param:string){return `(portal_fold(u.first_name||' '||u.last_name) LIKE ${param} ${contact?`OR portal_fold(u.email||' '||coalesce(u.extension,'')) LIKE ${param}`:''} OR portal_fold(c.name) LIKE ${param} OR portal_fold(l.name) LIKE ${param} OR portal_fold(d.name) LIKE ${param} OR portal_fold(un.name) LIKE ${param} OR portal_fold(j.name) LIKE ${param} OR portal_fold(u.expertise) LIKE ${param})`;}
// Only projected operational fields leave this query. Description, attachment and
// health information are never selected for directory consumers.
function absence(a:Identity,detail=false){if(!can(a,'absence.view_basic'))return {select:'NULL::jsonb AS absence',join:''};const mayType=detail?(can(a,'absence.view_leave_type')?'true':`((u.id=$1 OR u.manager_user_id=$1) AND NOT EXISTS(SELECT 1 FROM user_permission_overrides deny WHERE deny.user_id=$1 AND deny.permission_id='absence.view_leave_type' AND NOT deny.allowed))`):'false';return {select:`CASE WHEN ab.id IS NULL THEN NULL ELSE jsonb_strip_nulls(jsonb_build_object('until',ab.end_date::text,'return_date',(CASE WHEN ab.part='AM' THEN ab.end_date WHEN extract(isodow FROM ab.end_date+1)=6 THEN ab.end_date+3 WHEN extract(isodow FROM ab.end_date+1)=7 THEN ab.end_date+2 ELSE ab.end_date+1 END)::text,'backup',CASE WHEN backup.id IS NULL THEN NULL ELSE jsonb_build_object('id',backup.id,'name',backup.first_name||' '||backup.last_name,'job_title',bj.name) END,'leave_type',CASE WHEN ${mayType} THEN ab.type_name END,'from',CASE WHEN ${mayType} THEN ab.start_date::text END)) END AS absence`,join:`LEFT JOIN LATERAL(SELECT lr.id,lr.start_date,lr.end_date,lr.part,lr.backup_user_id,lt.name AS type_name FROM leave_requests lr JOIN leave_types lt ON lt.id=lr.type_id WHERE lr.owner_id=u.id AND lr.status='APPROVED' AND (now() AT TIME ZONE coalesce(l.timezone,'Europe/Istanbul'))::date BETWEEN lr.start_date AND lr.end_date AND (lr.part='FULL' OR lr.part='AM' AND (now() AT TIME ZONE coalesce(l.timezone,'Europe/Istanbul'))::time<time '12:00' OR lr.part='PM' AND (now() AT TIME ZONE coalesce(l.timezone,'Europe/Istanbul'))::time>=time '12:00') ORDER BY lr.start_date DESC,lr.created_at DESC,lr.id LIMIT 1)ab ON true LEFT JOIN users backup ON backup.id=ab.backup_user_id AND ${directoryVisible('backup')} LEFT JOIN job_titles bj ON bj.id=backup.job_title_id`};}
export async function directoryList(a:Identity,p=new URLSearchParams(),compact=false):Promise<DirectoryData>{permit(a);for(const key of p.keys())if(!['q','page','company_id','location_id','department_id','unit_id'].includes(key))throw new AppError(400,'Geçersiz filtre.');const page=z.coerce.number().int().min(1).max(100000).parse(p.get('page')||1),size=compact?5:20,values:unknown[]=[a.id],where=[directoryVisible('u'),'$1::uuid IS NOT NULL'];if(p.get('q')?.trim()){values.push(pattern(p.get('q')!));where.push(searchWhere(can(a,'directory.view_contact_details'),'$'+values.length));}for(const key of ['company_id','location_id','department_id','unit_id'])if(p.get(key)){values.push(guid.parse(p.get(key)));where.push('u.'+key+'=$'+values.length);}const ab=absence(a);const out=(await database().query<DirectoryData>(`WITH filtered AS(SELECT u.id,u.first_name||' '||u.last_name AS name ${joins} WHERE ${where.join(' AND ')}),chosen AS(SELECT id FROM filtered ORDER BY name,id LIMIT ${size} OFFSET ${(page-1)*size}) SELECT (SELECT count(*)::int FROM filtered) AS total,COALESCE((SELECT jsonb_agg(x ORDER BY x.name,x.id) FROM(SELECT ${columns},${ab.select} ${joins.replace('FROM users u','FROM chosen page JOIN users u ON u.id=page.id')} ${ab.join})x),'[]') AS rows`,values)).rows[0];return {...out,page,size};}
export async function personDetail(a:Identity,id:string):Promise<Person>{permit(a);const ab=absence(a,true),contact=can(a,'directory.view_contact_details');const row=(await database().query<Person>(`SELECT ${columns},u.expertise AS expertise,${ab.select}${contact?',u.email,u.phone,u.extension':''},CASE WHEN manager.id IS NULL THEN NULL ELSE jsonb_build_object('id',manager.id,'name',manager.first_name||' '||manager.last_name) END AS manager ${joins} ${ab.join} LEFT JOIN users manager ON manager.id=u.manager_user_id AND ${directoryVisible('manager')} WHERE u.id=$2 AND ${directoryVisible('u')} AND $1::uuid IS NOT NULL`,[a.id,guid.parse(id)])).rows[0];if(!row)throw new AppError(404,'Kişi bulunamadı.');return row;}
export async function directoryOptions(a:Identity){permit(a);return (await database().query<Record<string,any>>(`SELECT ${[['companies','company_id'],['locations','location_id'],['departments','department_id'],['units','unit_id']].map(([table,key])=>`COALESCE((SELECT jsonb_agg(x ORDER BY x.name) FROM(SELECT o.id,o.name${table!=='companies'?',o.company_id':''} FROM ${table} o WHERE o.active AND o.archived_at IS NULL AND EXISTS(SELECT 1 FROM users u WHERE ${directoryVisible('u')} AND u.${key}=o.id))x),'[]') AS ${table}`).join(',')}`)).rows[0];}
export async function birthdays(a:Identity):Promise<Birthday[]>{if(!directoryAllowed(a))return [];return (await database().query<Birthday>(`WITH dates AS(SELECT day::date AS day,(day::date-(now() AT TIME ZONE 'Europe/Istanbul')::date)::int AS days_away FROM generate_series((now() AT TIME ZONE 'Europe/Istanbul')::date, (now() AT TIME ZONE 'Europe/Istanbul')::date+7,interval '1 day')day) SELECT u.id,u.first_name||' '||u.last_name AS name,u.photo,j.name AS job_title,extract(day FROM dates.day)::int AS day,extract(month FROM dates.day)::int AS month,dates.days_away FROM dates JOIN users u ON extract(month FROM u.birth_date)=extract(month FROM dates.day) AND extract(day FROM u.birth_date)=extract(day FROM dates.day) LEFT JOIN job_titles j ON j.id=u.job_title_id WHERE ${directoryVisible('u')} AND u.show_birthday ORDER BY days_away,name,u.id LIMIT 12`)).rows;}
export async function backupCandidates(a:Identity,p=new URLSearchParams()){for(const key of p.keys())if(!['q','approval_id'].includes(key))throw new AppError(400,'Geçersiz filtre.');let owner=a.id;const ap=p.get('approval_id');if(ap){if(!can(a,'approvals.view')||!can(a,'approvals.approve'))throw new AppError(403,'Onay yetkiniz bulunmuyor.');const r=(await database().query<{owner_id:string}>("SELECT l.owner_id FROM approvals ap JOIN leave_requests l ON l.id=ap.leave_id WHERE ap.id=$1 AND ap.approver_id=$2 AND ap.status='PENDING' AND ap.stage='MANAGER' AND l.status='PENDING_MANAGER'",[guid.parse(ap),a.id])).rows[0];if(!r)throw new AppError(404,'Onay bulunamadı.');owner=r.owner_id;}else if(!can(a,'leave.create'))throw new AppError(403,'İzin oluşturma yetkiniz bulunmuyor.');return {rows:(await database().query(`SELECT u.id,u.first_name||' '||u.last_name AS name,j.name AS job_title,d.name AS department ${joins} WHERE ${directoryVisible('u')} AND u.id<>$1 AND ${searchWhere(false,'$2')} ORDER BY u.first_name,u.id LIMIT 20`,[owner,pattern(p.get('q')??'')])).rows};}
export async function globalSearch(a:Identity,p=new URLSearchParams()):Promise<{groups:SearchGroup[]}>{if(a.must_change_password)throw new AppError(403,'Şifrenizi değiştirin.');for(const key of p.keys())if(key!=='q')throw new AppError(400,'Geçersiz arama.');const q=p.get('q')?.trim()??'';if(q.length<2)return {groups:[]};const parts:string[]=[];
if(directoryAllowed(a))parts.push(`SELECT 'people' AS kind,'Kişiler' AS label,id,title,link FROM(SELECT u.id,u.first_name||' '||u.last_name AS title,'/directory/'||u.id AS link ${joins} WHERE ${directoryVisible('u')} AND ${searchWhere(can(a,'directory.view_contact_details'),'$3')} ORDER BY u.first_name,u.id LIMIT 4)x`);
for(const kind of contentKinds){if(!can(a,portalContentPermission[kind]))continue;parts.push(`SELECT '${kind}' AS kind,'${contentNames[kind]}' AS label,id,title,link FROM(SELECT c.id,c.title,'/${kind}/'||c.slug AS link FROM ${kind} c CROSS JOIN viewer v WHERE c.status='PUBLISHED' AND c.publish_at<=now() AND (c.expires_at IS NULL OR c.expires_at>now()) AND (c.audience_all OR EXISTS(SELECT 1 FROM ${kind}_audience ta WHERE ta.content_id=c.id AND (ta.company_id=v.company_id OR ta.location_id=v.location_id OR ta.department_id=v.department_id OR ta.unit_id=v.unit_id OR ta.user_id=v.id OR ta.role_id=ANY(v.role_ids)))) AND portal_fold(c.title||' '||c.summary) LIKE $3 ORDER BY c.publish_at DESC,c.id LIMIT 4)x`);}
if(can(a,'brand_center.view'))parts.push(`SELECT 'brand' AS kind,'Marka Merkezi' AS label,id,title,link FROM(SELECT a.id,a.title,'/brand-center/'||a.id AS link FROM brand_assets a JOIN brand_asset_versions bv ON bv.asset_id=a.id AND bv.status='CURRENT' CROSS JOIN viewer v WHERE NOT a.archived AND bv.published_at<=now() AND (a.audience_all OR a.company_id=v.company_id) AND portal_fold(a.title) LIKE $3 ORDER BY a.updated_at DESC,a.id LIMIT 4)x`);
if(can(a,'requests.view_own'))parts.push(`SELECT 'requests' AS kind,'Taleplerim' AS label,id,title,link FROM(SELECT r.id,r.subject AS title,'/requests/'||r.id AS link FROM requests r WHERE r.owner_id=$1 AND portal_fold(r.subject) LIKE $3 ORDER BY r.created_at DESC,r.id LIMIT 4)x`);
if(!parts.length)return {groups:[]};const rows=(await database().query<{kind:string;label:string;id:string;title:string;link:string}>(`WITH viewer AS(SELECT id,company_id,location_id,department_id,unit_id,$2::text[] AS role_ids FROM users WHERE id=$1 AND status IN('ACTIVE','ON_LEAVE') AND archived_at IS NULL) ${parts.join(' UNION ALL ')}`,[a.id,a.roles,pattern(q)])).rows;const groups:SearchGroup[]=[];for(const row of rows){let g=groups.find(g=>g.kind===row.kind);if(!g){g={kind:row.kind,label:row.label,rows:[]};groups.push(g);}g.rows.push({id:row.id,title:row.title,link:row.link});}return {groups};}
