import {handoverRuleSchema,handoverSchema,categoryRules,writeHandover} from './asset-proof';
import {uploadedImageValid} from './upload';
import {createNotification} from './notifications';
import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {database,transaction,lock,DB} from './db';
import {identityFor} from './auth-core';
import {Identity,can} from './permissions';
import {audit,requirePermission} from './admin';
import {AppError} from './security';
import {extraFields,AssetSummary} from './inventory-shared';
type Row=Record<string,any>;
const uuid=z.string().uuid();
// Seeded categories use PostgreSQL UUIDs derived from MD5, without RFC version bits.
const categoryId=z.string().regex(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);
const text=z.string().trim().max(2000).default('');
const date=z.string().date();
const nullableDate=z.union([date,z.literal(''),z.null()]).optional().transform(v=>v||null);
const code=z.string().trim().min(1).max(80).transform(v=>v.toUpperCase());
const states=z.enum(['STOCK','ASSIGNED','SERVICE','FAULTY','LOST','SCRAPPED','RETURNED','INACTIVE']);
const returnStates=z.enum(['STOCK','SERVICE','FAULTY','LOST','SCRAPPED','INACTIVE']);
const categorySchema=z.object({handover_rules:handoverRuleSchema.optional(),name:z.string().trim().min(1).max(100),code,icon:z.string().trim().max(40).default('package'),description:text,active:z.boolean(),field_profile:z.enum(['BASIC','COMPUTER','PHONE','SIM','MONITOR']).default('BASIC')}).strict();
const image=z.string().max(280000).refine(uploadedImageValid,'En fazla 200 KB geçerli PNG, JPEG veya WebP görseli seçin.').nullable().optional();
const itemSchema=z.object({asset_number:code,category_id:categoryId,brand:z.string().trim().max(100),model:z.string().trim().max(150),serial_number:z.string().trim().max(120).nullable().optional().transform(v=>v?v.toUpperCase():null),company_id:uuid,location_id:uuid,department_id:z.union([uuid,z.literal(''),z.null()]).optional().transform(v=>v||null),purchase_date:nullableDate,warranty_end:nullableDate,supplier:text,invoice_number:text,notes:text,image,status:states,extras:z.record(z.string(),z.string().trim().max(200)).default({})}).strict();
function permit(actor:Identity,p:string){if(actor.must_change_password)throw new AppError(401,'Şifrenizi değiştirin.');requirePermission(actor,p);}
async function write<T>(actor:Identity,p:string,fn:(db:DB,live:Identity)=>Promise<T>){return transaction(async db=>{await lock(db);const live=await identityFor(db,actor.id);if(!live)throw new AppError(401,'Yeniden giriş yapın.');permit(live,p);return fn(db,live);});}
async function item(db:DB,id:string){uuid.parse(id);const row=(await db.query<Row>('SELECT * FROM inventory_items WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!row)throw new AppError(404,'Envanter bulunamadı.');return row;}
export async function saveCategory(actor:Identity,payload:unknown,id?:string){const data=categorySchema.parse(payload);if(id)categoryId.parse(id);return write(actor,'inventory_categories.manage',async db=>{const target=id??randomUUID();if(id){const old=(await db.query<Row>('SELECT * FROM inventory_categories WHERE id=$1',[id])).rows[0];if(!old)throw new AppError(404,'Kategori bulunamadı.');if(old.field_profile!==data.field_profile&&(await db.query('SELECT id FROM inventory_items WHERE category_id=$1 LIMIT 1',[id])).rows.length)throw new AppError(400,'Kullanılan kategorinin alan profili değiştirilemez.');}
 const cols=Object.keys(data),values=Object.values(data);await db.query(id?`UPDATE inventory_categories SET ${cols.map((c,i)=>c+'=$'+(i+1)).join(',')} WHERE id=$${cols.length+1}`:`INSERT INTO inventory_categories(${cols.join(',')},id) VALUES(${[...values,target].map((_,i)=>'$'+(i+1)).join(',')})`,[...values,target]);await audit(db,actor.id,id?'inventory_category.updated':'inventory_category.created','inventory_category',target);return {id:target};});}
export async function saveItem(actor:Identity,payload:unknown,id?:string){const data=itemSchema.parse(payload);return write(actor,id?'inventory.edit':'inventory.create',async(db,live)=>{const old=id?await item(db,id):null;
 if(data.status==='ASSIGNED'&&old?.status!=='ASSIGNED')throw new AppError(400,'Zimmetli durumu yalnızca zimmet işlemiyle atanır.');
 if(old?.status==='ASSIGNED'&&data.status!=='ASSIGNED')throw new AppError(409,'Önce aktif zimmeti iade alın.');
 if(old&&old.status!==data.status)permit(live,'inventory.manage');
 const category=(await db.query<Row>('SELECT active,field_profile FROM inventory_categories WHERE id=$1',[data.category_id])).rows[0];if(!category||(!category.active&&old?.category_id!==data.category_id))throw new AppError(400,'Aktif kategori seçin.');
 if(Object.keys(data.extras).some(k=>!extraFields[category.field_profile].some(([key])=>key===k)))throw new AppError(400,'Kategori alanları geçersiz.');
 for(const [field,table]of [['company_id','companies'],['location_id','locations'],['department_id','departments']] as const){if(!data[field])continue;const r=(await db.query<Row>(`SELECT * FROM ${table} WHERE id=$1`,[data[field]])).rows[0];if(!r||(table!=='companies'&&r.company_id!==data.company_id)||((!r.active||r.archived_at)&&old?.[field]!==data[field]))throw new AppError(400,'Aktif ve aynı şirkete bağlı organizasyon seçin.');}
 const target=id??randomUUID(),cols=Object.keys(data),values=Object.values(data).map((v,i)=>cols[i]==='extras'?JSON.stringify(v):v??null);
 await db.query(id?`UPDATE inventory_items SET ${cols.map((c,i)=>c+'=$'+(i+1)).join(',')},updated_at=now() WHERE id=$${cols.length+1}`:`INSERT INTO inventory_items(${cols.join(',')},id) VALUES(${[...values,target].map((_,i)=>'$'+(i+1)).join(',')})`,[...values,target]);
 await audit(db,actor.id,!id?'inventory.created':data.status==='INACTIVE'&&old?.status!=='INACTIVE'?'inventory.disabled':'inventory.updated','inventory',target);return {id:target};});}
export async function changeItemStatus(actor:Identity,id:string,payload:unknown){const {status}=z.object({status:states}).strict().parse(payload);return write(actor,'inventory.manage',async db=>{const old=await item(db,id);if(old.status==='ASSIGNED'||status==='ASSIGNED')throw new AppError(409,'Aktif zimmet için zimmet/iade işlemini kullanın.');await db.query('UPDATE inventory_items SET status=$2,updated_at=now() WHERE id=$1',[id,status]);await audit(db,actor.id,status==='INACTIVE'?'inventory.disabled':'inventory.updated','inventory',id);return {id};});}
export async function assignItem(actor:Identity,payload:unknown){const data=z.object({inventory_id:uuid,user_id:uuid,assigned_at:date,note:text,handover:handoverSchema.optional()}).strict().parse(payload);return write(actor,'assignments.create',async db=>{const inv=await item(db,data.inventory_id);if(!['STOCK','RETURNED'].includes(inv.status))throw new AppError(409,'Yalnızca stoktaki/iade edilmiş envanter zimmetlenebilir.');if(!(await db.query("SELECT id FROM users WHERE id=$1 AND status='ACTIVE' AND archived_at IS NULL",[data.user_id])).rows.length)throw new AppError(400,'Aktif çalışan seçin.');if(data.assigned_at>new Date().toISOString().slice(0,10))throw new AppError(400,'Zimmet tarihi gelecekte olamaz.');const last=(await db.query<Row>('SELECT max(returned_at)::text AS last FROM asset_assignments WHERE inventory_id=$1',[data.inventory_id])).rows[0]?.last;if(last&&data.assigned_at<last)throw new AppError(400,'Zimmet tarihi son iadeden önce olamaz.');const id=randomUUID();await db.query('INSERT INTO asset_assignments(id,inventory_id,user_id,assigned_at,delivered_by,note) VALUES($1,$2,$3,$4,$5,$6)',[id,data.inventory_id,data.user_id,data.assigned_at,actor.id,data.note]);const rules=await categoryRules(db,inv.category_id);await db.query('UPDATE asset_assignments SET rules_snapshot=$2 WHERE id=$1',[id,JSON.stringify(rules)]);await writeHandover(db,actor.id,{id,user_id:data.user_id,status:'ACTIVE',rules_snapshot:rules},'DELIVERY',data.handover??{});await db.query("UPDATE inventory_items SET status='ASSIGNED',updated_at=now() WHERE id=$1",[data.inventory_id]);await audit(db,actor.id,'assignment.created','assignment',id);await createNotification(db,{recipient:data.user_id,event:'assignment.created',entityId:id,type:'INVENTORY',title:'Yeni zimmet atandı',message:[inv.brand,inv.model].filter(Boolean).join(' ')+' üzerinize zimmetlendi.',link:'/my-assets',key:'assignment.created:'+id});return {id};});}
export async function returnAssignment(actor:Identity,id:string,payload:unknown){uuid.parse(id);const data=z.object({returned_at:date,return_note:text,return_condition:returnStates}).strict().parse(payload);return write(actor,'assignments.return',async db=>{const a=(await db.query<Row>('SELECT *,assigned_at::text AS assigned_date FROM asset_assignments WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!a)throw new AppError(404,'Zimmet bulunamadı.');if(a.returned_at)throw new AppError(409,'Zimmet zaten iade alınmış.');await item(db,a.inventory_id);const prepared=(await db.query("SELECT id FROM asset_handover WHERE assignment_id=$1 AND phase='RETURN'",[id])).rows.length;const rules=handoverRuleSchema.parse(a.rules_snapshot??{});if(!prepared)await writeHandover(db,actor.id,{id:a.id,user_id:a.user_id,status:a.status,rules_snapshot:rules},'RETURN',{});if(rules.return_signature&&!(await db.query("SELECT id FROM assignment_acceptances WHERE assignment_id=$1 AND phase='RETURN'",[id])).rows.length)throw new AppError(409,'Çalışan önce iade formunu portalda kabul etmelidir.');if(data.returned_at<a.assigned_date||data.returned_at>new Date().toISOString().slice(0,10))throw new AppError(400,'İade tarihini kontrol edin.');await db.query("UPDATE asset_assignments SET returned_at=$2,received_by=$3,return_note=$4,return_condition=$5,status='RETURNED' WHERE id=$1",[id,data.returned_at,actor.id,data.return_note,data.return_condition]);await db.query('UPDATE inventory_items SET status=$2,updated_at=now() WHERE id=$1',[a.inventory_id,data.return_condition]);await audit(db,actor.id,'assignment.returned','assignment',id);await createNotification(db,{recipient:a.user_id,event:'assignment.returned',entityId:id,type:'INVENTORY',title:'Zimmetiniz sonlandırıldı',message:'Envanter iade işleminiz tamamlandı.',link:'/my-assets',key:'assignment.returned:'+id});return {id};});}
export async function updateAssignment(actor:Identity,id:string,payload:unknown){uuid.parse(id);const data=z.object({note:text}).strict().parse(payload);return write(actor,'assignments.manage',async db=>{const result=await db.query('UPDATE asset_assignments SET note=$2 WHERE id=$1 AND returned_at IS NULL RETURNING id',[id,data.note]);if(!result.rows.length)throw new AppError(409,'Yalnızca aktif zimmetin notu değiştirilebilir.');await audit(db,actor.id,'assignment.updated','assignment',id);return {id};});}
const joins=`FROM inventory_items i JOIN inventory_categories c ON c.id=i.category_id JOIN companies co ON co.id=i.company_id JOIN locations l ON l.id=i.location_id LEFT JOIN asset_assignments a ON a.inventory_id=i.id AND a.returned_at IS NULL LEFT JOIN users u ON u.id=a.user_id`;
const columns=`i.id,i.asset_number,i.category_id,i.brand,i.model,i.serial_number,i.company_id,i.location_id,i.status,c.name AS category_name,co.name AS company_name,l.name AS location_name,concat_ws(' ',u.first_name,u.last_name) AS assignee,a.id AS assignment_id`;
function pagination(params:URLSearchParams){return {page:z.coerce.number().int().min(1).max(100000).parse(params.get('page')||1),size:20};}
export async function listInventory(actor:Identity,params=new URLSearchParams()):Promise<{rows:Row[];total:number;page:number;size:number}>{permit(actor,'inventory.view');const {page,size}=pagination(params),values:unknown[]=[],clauses:string[]=[];const add=(sql:string,value:unknown)=>{values.push(value);clauses.push(sql.replaceAll('?',`$${values.length}`));};const q=(params.get('q')||'').slice(0,120);if(q)add("(i.asset_number ILIKE ? OR i.serial_number ILIKE ? OR i.brand ILIKE ? OR i.model ILIKE ?)",'%'+q+'%');for(const key of ['category_id','company_id','location_id'])if(params.get(key))add(`i.${key}=?`,(key==='category_id'?categoryId:uuid).parse(params.get(key)));if(params.get('status'))add('i.status=?',states.parse(params.get('status')));if(params.get('assigned')==='yes')clauses.push('a.id IS NOT NULL');if(params.get('assigned')==='no')clauses.push("i.status='STOCK'");const where=clauses.length?' WHERE '+clauses.join(' AND '):'';const sort=({asset_number:'i.asset_number',category:'c.name',brand:'i.brand',status:'i.status',created:'i.created_at'} as Record<string,string>)[params.get('sort')||'asset_number']||'i.asset_number';const dir=params.get('dir')==='desc'?'DESC':'ASC';
 const row=(await database().query<Row>(`SELECT (SELECT count(*)::int ${joins}${where}) AS total,COALESCE((SELECT jsonb_agg(r) FROM (SELECT ${columns} ${joins}${where} ORDER BY ${sort} ${dir},i.id LIMIT ${size} OFFSET ${(page-1)*size}) r),'[]'::jsonb) AS rows`,values)).rows[0];return {rows:row.rows,total:row.total,page,size};}
export async function listCategories(actor:Identity){permit(actor,'inventory_categories.view');return {rows:(await database().query('SELECT * FROM inventory_categories ORDER BY name')).rows};}
const historySelect=`SELECT a.id,a.inventory_id,a.user_id,a.assigned_at::text,a.returned_at::text,a.note,a.return_note,a.return_condition,a.status,i.asset_number,i.brand,i.model,concat_ws(' ',u.first_name,u.last_name) AS employee,concat_ws(' ',d.first_name,d.last_name) AS delivered_by_name,concat_ws(' ',r.first_name,r.last_name) AS received_by_name FROM asset_assignments a JOIN inventory_items i ON i.id=a.inventory_id JOIN users u ON u.id=a.user_id JOIN users d ON d.id=a.delivered_by LEFT JOIN users r ON r.id=a.received_by`;
export async function inventoryDetail(actor:Identity,id:string){permit(actor,'inventory.view');uuid.parse(id);const [rows,history]=await Promise.all([database().query<Row>(`SELECT i.*,i.purchase_date::text,i.warranty_end::text,c.name AS category_name,c.field_profile,co.name AS company_name,l.name AS location_name,de.name AS department_name,concat_ws(' ',u.first_name,u.last_name) AS assignee ${joins} LEFT JOIN departments de ON de.id=i.department_id WHERE i.id=$1`,[id]),can(actor,'assignments.view')?database().query(historySelect+' WHERE a.inventory_id=$1 ORDER BY a.created_at DESC',[id]):Promise.resolve({rows:[]})]);if(!rows.rows[0])throw new AppError(404,'Envanter bulunamadı.');return {item:rows.rows[0],history:history.rows};}
export async function listAssignments(actor:Identity,params=new URLSearchParams()):Promise<Row & {rows:Row[];total:number;page:number;size:number}>{permit(actor,'assignments.view');const {page,size}=pagination(params);const q='%'+(params.get('q')||'').slice(0,120)+'%';const state=params.get('status')||'';if(state&&!['ACTIVE','RETURNED'].includes(state))throw new AppError(400,'Geçersiz durum.');const base=historySelect+" WHERE (i.asset_number ILIKE $1 OR concat_ws(' ',u.first_name,u.last_name) ILIKE $1) AND ($2='' OR a.status=$2)";return {...(await database().query<{rows:Row[];total:number}>(`WITH filtered AS (${base}) SELECT (SELECT count(*)::int FROM filtered) AS total,COALESCE((SELECT jsonb_agg(r) FROM (SELECT * FROM filtered ORDER BY assigned_at DESC,id LIMIT ${size} OFFSET ${(page-1)*size}) r),'[]'::jsonb) AS rows`,[q,state])).rows[0],page,size};}
export async function inventoryOptions(actor:Identity){if(!can(actor,'admin.view')||!['inventory.view','inventory.create','inventory.edit','assignments.view','assignments.create'].some(p=>can(actor,p)))throw new AppError(403,'Yetkiniz bulunmuyor.');const includeUsers=can(actor,'assignments.create');return (await database().query<Row>(`SELECT
 COALESCE((SELECT jsonb_agg(r) FROM (SELECT id,name,active,field_profile FROM inventory_categories ORDER BY name)r),'[]'::jsonb) AS categories,
 COALESCE((SELECT jsonb_agg(r) FROM (SELECT id,name,active FROM companies WHERE archived_at IS NULL ORDER BY name)r),'[]'::jsonb) AS companies,
 COALESCE((SELECT jsonb_agg(r) FROM (SELECT id,name,company_id,active FROM locations WHERE archived_at IS NULL ORDER BY name)r),'[]'::jsonb) AS locations,
 COALESCE((SELECT jsonb_agg(r) FROM (SELECT id,name,company_id,active FROM departments WHERE archived_at IS NULL ORDER BY name)r),'[]'::jsonb) AS departments,
 ${includeUsers?"COALESCE((SELECT jsonb_agg(r) FROM (SELECT id,concat_ws(' ',first_name,last_name,' · ',username) AS name FROM users WHERE status='ACTIVE' AND archived_at IS NULL ORDER BY first_name)r),'[]'::jsonb)":"'[]'::jsonb"} AS users`)).rows[0];}
export async function ownAssets(actor:Identity,params=new URLSearchParams(),limit=20):Promise<AssetSummary>{if(actor.must_change_password||!can(actor,'portal.assets.view'))throw new AppError(403,'Yetkiniz bulunmuyor.');for(const key of params.keys())if(!['page','history'].includes(key))throw new AppError(400,'Geçersiz filtre.');const {page}=pagination(params);const history=params.get('history')==='1';const size=Math.min(20,Math.max(1,limit));return (await database().query<AssetSummary>(`WITH owned AS (SELECT a.id,a.assigned_at::text,a.returned_at::text,i.asset_number,i.brand,i.model,i.serial_number,i.image,c.name AS category_name FROM asset_assignments a JOIN inventory_items i ON i.id=a.inventory_id JOIN inventory_categories c ON c.id=i.category_id WHERE a.user_id=$1 AND a.returned_at IS ${history?'NOT ':''}NULL) SELECT (SELECT count(*)::int FROM owned) AS total,COALESCE((SELECT jsonb_agg(r) FROM (SELECT * FROM owned ORDER BY assigned_at DESC,id LIMIT $2 OFFSET $3)r),'[]'::jsonb) AS rows`,[actor.id,size,(page-1)*size])).rows[0];}
