import {uploadedImageValid} from './upload';
import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {DB,database,transaction,lock} from './db';
import {identityFor} from './auth-core';
import {Identity,can} from './permissions';
import {AppError} from './security';
import {audit} from './admin';
import {createNotification} from './notifications';
import {AgendaData} from './meeting-shared';
type Row=Record<string,any>;
const uuid=z.string().regex(/^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$/i);
const local=z.string().regex(/^\d{4}-\d{2}-\d{2}T(?:[01]\d|2[0-3]):[0-5]\d$/).refine(v=>{const d=new Date(v+'Z');return !Number.isNaN(d.getTime())&&d.toISOString().slice(0,16)===v;});
function permit(a:Identity,p:string){if(a.must_change_password||!can(a,p))throw new AppError(403,'Bu işlem için yetkiniz bulunmuyor.');}
async function fresh(db:DB,a:Identity,p:string){const v=await identityFor(db,a.id);if(!v)throw new AppError(401,'Yeniden giriş yapın.');permit(v,p);return v;}
function params(p:URLSearchParams,allowed:string[]){for(const key of p.keys())if(!allowed.includes(key))throw new AppError(400,'Geçersiz filtre.');}
function pageOf(p:URLSearchParams){return z.coerce.number().int().min(1).max(100000).parse(p.get('page')||1);}
function day(value:string){if(!/^\d{4}-\d{2}-\d{2}$/.test(value)||Number.isNaN(Date.parse(value))||new Date(value).toISOString().slice(0,10)!==value)throw new AppError(400,'Geçerli tarih seçin.');return value;}
export function maxReservationHours(){const v=Number(process.env.MEETING_MAX_HOURS??8);return Number.isFinite(v)&&v>0&&v<=168?v:8;}
const roomJoin='meeting_rooms r JOIN locations l ON l.id=r.location_id JOIN companies c ON c.id=l.company_id';
const activeRoom='r.active AND l.active AND l.archived_at IS NULL AND c.active AND c.archived_at IS NULL';
const roomCols='r.id,r.name,r.code,r.location_id,l.company_id,l.name AS location_name,c.name AS company_name,l.timezone,r.floor,r.capacity,r.description,r.image,r.features,r.active';
export async function meetingOptions(a:Identity,admin=false){if(admin){if(!can(a,'meeting_rooms.manage')&&!can(a,'meeting_reservations.manage'))throw new AppError(403,'Yetkiniz bulunmuyor.');}else permit(a,'meeting_rooms.view');return (await database().query<Row>(`SELECT (SELECT location_id FROM users WHERE id=$1) AS default_location_id,COALESCE((SELECT timezone FROM locations WHERE id=(SELECT location_id FROM users WHERE id=$1)),'Europe/Istanbul') AS timezone,COALESCE((SELECT jsonb_agg(x ORDER BY x.name) FROM(SELECT l.id,l.name,l.company_id,c.name AS company_name,l.timezone FROM locations l JOIN companies c ON c.id=l.company_id WHERE l.active AND l.archived_at IS NULL AND c.active AND c.archived_at IS NULL)x),'[]') AS locations ,COALESCE((SELECT jsonb_agg(x ORDER BY x.name) FROM(SELECT r.id,r.name,r.location_id,r.capacity FROM ${roomJoin} ${admin?'':'WHERE '+activeRoom})x),'[]') AS rooms`,[a.id])).rows[0];}
export async function roomList(a:Identity,p=new URLSearchParams(),admin=false){permit(a,admin?'meeting_rooms.manage':'meeting_rooms.view');params(p,['page','q','location_id','company_id','capacity','start','end','active']);const values:unknown[]=[],where:string[]=[];function add(sql:string,v:unknown){values.push(v);where.push(sql.replace('?',`$${values.length}`));}if(!admin)where.push(activeRoom);else if(p.get('active'))add('r.active=?',z.enum(['true','false']).parse(p.get('active'))==='true');if(p.get('q'))add("(r.name||' '||r.code) ILIKE ?",'%'+p.get('q')!.slice(0,100)+'%');if(p.get('location_id'))add('r.location_id=?',uuid.parse(p.get('location_id')));else if(!admin&&!p.has('location_id'))add('r.location_id=(SELECT location_id FROM users WHERE id=?)',a.id);if(p.get('company_id'))add('l.company_id=?',uuid.parse(p.get('company_id')));if(p.get('capacity'))add('r.capacity>=?',z.coerce.number().int().positive().parse(p.get('capacity')));
let available='true';if(p.get('start')||p.get('end')){const start=local.parse(p.get('start')),end=local.parse(p.get('end'));if(start>=end)throw new AppError(400,'Başlangıç bitişten önce olmalı.');values.push(start,end,maxReservationHours());const n=values.length;available=`((${`$${n-2}`}::timestamp AT TIME ZONE l.timezone)>now() AND (${`$${n-1}`}::timestamp AT TIME ZONE l.timezone)>(${`$${n-2}`}::timestamp AT TIME ZONE l.timezone) AND (${`$${n-1}`}::timestamp AT TIME ZONE l.timezone)-(${`$${n-2}`}::timestamp AT TIME ZONE l.timezone)<=make_interval(secs=>${`$${n}`}::double precision*3600) AND NOT EXISTS(SELECT 1 FROM meeting_reservations b WHERE b.room_id=r.id AND b.status='ACTIVE' AND b.start_at<(${`$${n-1}`}::timestamp AT TIME ZONE l.timezone) AND b.end_at>(${`$${n-2}`}::timestamp AT TIME ZONE l.timezone)))`;}
const page=pageOf(p);values.push((page-1)*20);return (await database().query<Row>(`WITH items AS(SELECT ${roomCols},${available} AS available FROM ${roomJoin} ${where.length?'WHERE '+where.join(' AND '):''}) SELECT (SELECT count(*)::int FROM items) AS total,COALESCE((SELECT jsonb_agg(x) FROM(SELECT * FROM items ORDER BY name,id LIMIT 20 OFFSET $${values.length})x),'[]') AS rows`,values)).rows[0];}
export async function roomDetail(a:Identity,id:string){permit(a,'meeting_rooms.manage');const result=(await database().query<Row>(`SELECT ${roomCols},COALESCE((SELECT jsonb_agg(x) FROM(SELECT b.id,b.title,b.start_at,b.end_at,u.first_name||' '||u.last_name AS organizer_name FROM meeting_reservations b JOIN users u ON u.id=b.organizer_id WHERE b.room_id=r.id AND b.status='ACTIVE' AND b.end_at>now() ORDER BY b.start_at LIMIT 20)x),'[]') AS upcoming FROM ${roomJoin} WHERE r.id=$1`,[uuid.parse(id)])).rows[0];if(!result)throw new AppError(404,'Oda bulunamadı.');return result;}
const roomSchema=z.object({name:z.string().trim().min(1).max(120),code:z.string().trim().min(1).max(40),location_id:uuid,floor:z.string().trim().max(40).default(''),capacity:z.coerce.number().int().min(1).max(10000),description:z.string().max(2000).default(''),image:z.string().max(280000).refine(uploadedImageValid,'En fazla 200 KB geçerli PNG, JPEG veya WebP görseli seçin.').nullable().default(null),features:z.array(z.string().trim().min(1).max(60)).max(20).default([]),active:z.boolean().default(true)}).strict();
export async function saveRoom(a:Identity,body:unknown,id?:string){const input=roomSchema.parse(body);if(id)uuid.parse(id);if(input.image&&Buffer.from(input.image.split(',')[1]??'','base64').length>200000)throw new AppError(400,'Görsel en fazla 200 KB olabilir.');if(input.image&&!/^data:image\/(?:png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(input.image))throw new AppError(400,'Görsel PNG/JPEG/WebP ve en fazla 200 KB olmalı.');return transaction(async db=>{await lock(db);await fresh(db,a,'meeting_rooms.manage');const loc=(await db.query<Row>('SELECT l.id FROM locations l JOIN companies c ON c.id=l.company_id WHERE l.id=$1 AND l.active AND l.archived_at IS NULL AND c.active AND c.archived_at IS NULL',[input.location_id])).rows[0];if(!loc)throw new AppError(400,'Aktif bir lokasyon seçin.');const old=id?(await db.query<Row>('SELECT * FROM meeting_rooms WHERE id=$1 FOR UPDATE',[id])).rows[0]:null;if(id&&!old)throw new AppError(404,'Oda bulunamadı.');if(old&&old.location_id!==input.location_id&&(await db.query('SELECT id FROM meeting_reservations WHERE room_id=$1 LIMIT 1',[id])).rows.length)throw new AppError(409,'Rezervasyon geçmişi olan odanın lokasyonu değiştirilemez.');const rid=id??randomUUID(),v=[rid,input.name,input.code,input.location_id,input.floor,input.capacity,input.description,input.image,JSON.stringify([...new Set(input.features)]),input.active];await db.query(id?'UPDATE meeting_rooms SET name=$2,code=$3,location_id=$4,floor=$5,capacity=$6,description=$7,image=$8,features=$9,active=$10,updated_at=now() WHERE id=$1':'INSERT INTO meeting_rooms(id,name,code,location_id,floor,capacity,description,image,features,active) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',v);await audit(db,a.id,!id?'meeting_room.created':old?.active&&!input.active?'meeting_room.disabled':'meeting_room.updated','meeting_room',rid);return {id:rid};});}
const bookingSchema=z.object({room_id:uuid,title:z.string().trim().min(1).max(160),description:z.string().max(2000).default(''),start:local,end:local}).strict();
async function bookingTimes(db:DB,input:z.infer<typeof bookingSchema>){const r=(await db.query<Row>(`SELECT r.id,r.name,l.timezone,($2::timestamp AT TIME ZONE l.timezone) AS start_at,($3::timestamp AT TIME ZONE l.timezone) AS end_at,now() AS current_at,
 to_char(($2::timestamp AT TIME ZONE l.timezone) AT TIME ZONE l.timezone,'YYYY-MM-DD"T"HH24:MI') AS start_local,to_char(($3::timestamp AT TIME ZONE l.timezone) AT TIME ZONE l.timezone,'YYYY-MM-DD"T"HH24:MI') AS end_local,
 EXISTS(SELECT 1 FROM (VALUES(interval '1 hour'),(interval '-1 hour'))o(delta) WHERE (($2::timestamp AT TIME ZONE l.timezone)+o.delta) AT TIME ZONE l.timezone=$2::timestamp OR (($3::timestamp AT TIME ZONE l.timezone)+o.delta) AT TIME ZONE l.timezone=$3::timestamp) AS ambiguous
 FROM ${roomJoin} WHERE r.id=$1 AND ${activeRoom} FOR UPDATE OF r`,[input.room_id,input.start,input.end])).rows[0];if(!r)throw new AppError(400,'Oda aktif değil veya bulunamadı.');if(r.start_local!==input.start||r.end_local!==input.end||r.ambiguous)throw new AppError(400,'Saat dilimi geçişinde geçersiz veya belirsiz saat seçtiniz.');if(new Date(r.start_at)>=new Date(r.end_at))throw new AppError(400,'Başlangıç bitişten önce olmalı.');if(new Date(r.start_at)<=new Date(r.current_at))throw new AppError(400,'Geçmiş tarihe rezervasyon yapılamaz.');if(new Date(r.end_at).getTime()-new Date(r.start_at).getTime()>maxReservationHours()*3600000)throw new AppError(400,`Rezervasyon en fazla ${maxReservationHours()} saat olabilir.`);return r;}
export async function saveReservation(a:Identity,body:unknown,id?:string){const input=bookingSchema.parse(body);if(id)uuid.parse(id);try{return await transaction(async db=>{await lock(db);await fresh(db,a,id?'meeting_reservations.edit_own':'meeting_reservations.create');if(id){const old=(await db.query<Row>('SELECT * FROM meeting_reservations WHERE id=$1 AND organizer_id=$2 FOR UPDATE',[id,a.id])).rows[0];if(!old)throw new AppError(404,'Rezervasyon bulunamadı.');if(old.status!=='ACTIVE'||new Date(old.start_at)<=new Date())throw new AppError(409,'Yalnız gelecekteki aktif rezervasyonlar düzenlenebilir.');}const times=await bookingTimes(db,input),rid=id??randomUUID();if((await db.query("SELECT id FROM meeting_reservations WHERE room_id=$1 AND status='ACTIVE' AND id<>$2 AND start_at<$4 AND end_at>$3 LIMIT 1",[input.room_id,rid,times.start_at,times.end_at])).rows.length)throw new AppError(409,'Bu saat aralığında oda dolu. Başka bir saat veya oda seçin.');if(id)await db.query('UPDATE meeting_reservations SET room_id=$2,title=$3,description=$4,start_at=$5,end_at=$6,updated_at=now() WHERE id=$1',[rid,input.room_id,input.title,input.description,times.start_at,times.end_at]);else await db.query('INSERT INTO meeting_reservations(id,room_id,title,description,start_at,end_at,organizer_id) VALUES($1,$2,$3,$4,$5,$6,$7)',[rid,input.room_id,input.title,input.description,times.start_at,times.end_at,a.id]);await audit(db,a.id,id?'meeting_reservation.updated':'meeting_reservation.created','meeting_reservation',rid);if(!id)await createNotification(db,{recipient:a.id,event:'meeting.created',entityId:rid,type:'SYSTEM',title:'Toplantı odası rezervasyonunuz oluşturuldu',message:input.title+' · '+times.name,link:'/meeting-rooms/my-reservations',key:'meeting.created:'+rid});return {id:rid};});}catch(e){if((e as {code?:string}).code==='23P01')throw new AppError(409,'Bu saat aralığında oda dolu.');throw e;}}
export async function cancelReservation(a:Identity,id:string,admin=false){uuid.parse(id);return transaction(async db=>{await lock(db);await fresh(db,a,admin?'meeting_reservations.manage':'meeting_reservations.cancel_own');const row=(await db.query<Row>('SELECT * FROM meeting_reservations WHERE id=$1'+(admin?'':' AND organizer_id=$2')+' FOR UPDATE',admin?[id]:[id,a.id])).rows[0];if(!row)throw new AppError(404,'Rezervasyon bulunamadı.');if(row.status!=='ACTIVE'||new Date(row.start_at)<=new Date())throw new AppError(409,'Yalnız gelecekteki aktif rezervasyonlar iptal edilebilir.');await db.query("UPDATE meeting_reservations SET status='CANCELLED',updated_at=now() WHERE id=$1",[id]);await audit(db,a.id,admin?'meeting_reservation.admin_cancelled':'meeting_reservation.cancelled','meeting_reservation',id);if(admin&&row.organizer_id!==a.id)await createNotification(db,{recipient:row.organizer_id,event:'meeting.admin_cancelled',entityId:id,type:'SYSTEM',title:'Toplantı rezervasyonunuz yönetici tarafından iptal edildi',message:row.title,link:'/meeting-rooms/my-reservations',key:'meeting.admin_cancelled:'+id});return {ok:true};});}
const bookingCols="b.id,b.room_id,b.organizer_id,b.title,b.description,b.start_at,b.end_at,CASE WHEN b.status='ACTIVE' AND b.end_at<=now() THEN 'COMPLETED' ELSE b.status END AS status,r.name AS room_name,l.name AS location_name,l.id AS location_id,l.company_id,c.name AS company_name,l.timezone,u.first_name||' '||u.last_name AS organizer_name,to_char(b.start_at AT TIME ZONE l.timezone,'YYYY-MM-DD\"T\"HH24:MI') AS start_local,to_char(b.end_at AT TIME ZONE l.timezone,'YYYY-MM-DD\"T\"HH24:MI') AS end_local";
const bookingJoin='meeting_reservations b JOIN meeting_rooms r ON r.id=b.room_id JOIN locations l ON l.id=r.location_id JOIN companies c ON c.id=l.company_id JOIN users u ON u.id=b.organizer_id';
export async function reservationList(a:Identity,p=new URLSearchParams(),admin=false){permit(a,admin?'meeting_reservations.manage':'meeting_reservations.view_own');params(p,['page','q','location_id','company_id','room_id','organizer','date','status','sort']);const values:unknown[]=[],where:string[]=[];function add(sql:string,v:unknown){values.push(v);where.push(sql.replaceAll('?',`$${values.length}`));}if(!admin)add('b.organizer_id=?',a.id);if(p.get('q'))add("(b.title||' '||r.name) ILIKE ?",'%'+p.get('q')!.slice(0,100)+'%');for(const [key,col]of [['location_id','l.id'],['company_id','l.company_id'],['room_id','r.id']])if(p.get(key))add(col+'=?',uuid.parse(p.get(key)));if(p.get('organizer')&&admin)add("(u.first_name||' '||u.last_name) ILIKE ?",'%'+p.get('organizer')!.slice(0,100)+'%');if(p.get('date'))add("b.start_at<((?::date+1)::timestamp AT TIME ZONE l.timezone) AND b.end_at>(?::date::timestamp AT TIME ZONE l.timezone)",day(p.get('date')!));const status=z.enum(['ACTIVE','COMPLETED','CANCELLED','']).parse(p.get('status')??(admin?'':'ACTIVE'));if(status==='ACTIVE')where.push("b.status='ACTIVE' AND b.end_at>now()");if(status==='COMPLETED')where.push("(b.status='COMPLETED' OR b.status='ACTIVE' AND b.end_at<=now())");if(status==='CANCELLED')where.push("b.status='CANCELLED'");const sort=z.enum(['asc','desc']).parse(p.get('sort')||'asc');values.push((pageOf(p)-1)*20);return (await database().query<Row>(`WITH items AS(SELECT ${bookingCols} FROM ${bookingJoin} ${where.length?'WHERE '+where.join(' AND '):''}) SELECT (SELECT count(*)::int FROM items) AS total,COALESCE((SELECT jsonb_agg(x) FROM(SELECT * FROM items ORDER BY start_at ${sort},id LIMIT 20 OFFSET $${values.length})x),'[]') AS rows`,values)).rows[0];}
export async function reservationDetail(a:Identity,id:string){permit(a,'meeting_reservations.view_own');const r=(await database().query<Row>(`SELECT ${bookingCols} FROM ${bookingJoin} WHERE b.id=$1 AND b.organizer_id=$2`,[uuid.parse(id),a.id])).rows[0];if(!r)throw new AppError(404,'Rezervasyon bulunamadı.');return r;}
export async function agenda(a:Identity,p=new URLSearchParams(),fullMonth=false):Promise<AgendaData>{permit(a,'calendar.view_own');params(p,['date','month']);if(p.has('date')&&p.has('month'))throw new AppError(400,'Tek tarih aralığı seçin.');const month=p.get('month');fullMonth=fullMonth||!!month;if(month&&!/^\d{4}-\d{2}$/.test(month))throw new AppError(400,'Geçerli ay seçin.');const date=month?day(month+'-01'):p.get('date')?day(p.get('date')!):null;
return (await database().query<AgendaData>(`WITH viewer AS(SELECT u.*,COALESCE(l.timezone,'Europe/Istanbul') AS tz,ARRAY(SELECT ur.role_id FROM user_roles ur JOIN roles ro ON ro.id=ur.role_id AND ro.active WHERE ur.user_id=u.id) AS role_ids FROM users u LEFT JOIN locations l ON l.id=u.location_id WHERE u.id=$1), bounds AS(SELECT v.*,COALESCE($2::date,(now() AT TIME ZONE v.tz)::date) AS day FROM viewer v), span AS(SELECT b.*,${fullMonth?"date_trunc('month',day::timestamp)":'day::timestamp'} AT TIME ZONE tz AS start_at,(${fullMonth?"date_trunc('month',day::timestamp)+interval '1 month'":"day+interval '1 day'"})::timestamp AT TIME ZONE tz AS end_at FROM bounds b), items AS(
 SELECT b.id,'MEETING' AS kind,b.title,b.start_at,b.end_at,r.name AS venue,'/meeting-rooms/my-reservations/'||b.id AS link,NULL::text AS start_date,NULL::text AS end_date,NULL::text AS part FROM meeting_reservations b JOIN meeting_rooms r ON r.id=b.room_id CROSS JOIN span v WHERE $3 AND b.organizer_id=$1 AND b.status<>'CANCELLED' AND b.start_at<v.end_at AND b.end_at>v.start_at
 UNION ALL SELECT e.id,'EVENT',e.title,e.event_start,e.event_end,e.venue,'/events/'||e.slug,NULL,NULL,NULL FROM events e JOIN event_participants ep ON ep.event_id=e.id AND ep.user_id=$1 AND ep.attending CROSS JOIN span v WHERE $4 AND e.status='PUBLISHED' AND e.publish_at<=now() AND (e.expires_at IS NULL OR e.expires_at>now()) AND e.event_start<v.end_at AND e.event_end>v.start_at AND (e.audience_all OR EXISTS(SELECT 1 FROM events_audience ta WHERE ta.content_id=e.id AND(ta.company_id=v.company_id OR ta.location_id=v.location_id OR ta.department_id=v.department_id OR ta.unit_id=v.unit_id OR ta.user_id=v.id OR ta.role_id=ANY(v.role_ids))))
 UNION ALL SELECT b.id,'LEAVE',t.name,b.start_date::timestamp AT TIME ZONE v.tz,(b.end_date+1)::timestamp AT TIME ZONE v.tz,'İzinli','/leave/'||b.id,b.start_date::text,b.end_date::text,b.part FROM leave_requests b JOIN leave_types t ON t.id=b.type_id CROSS JOIN span v WHERE $5 AND b.owner_id=$1 AND b.status='APPROVED' AND b.start_date<(v.end_at AT TIME ZONE v.tz)::date AND b.end_date>=(v.start_at AT TIME ZONE v.tz)::date
 UNION ALL SELECT s.id,'TRAINING',s.title,s.starts_at,s.ends_at,COALESCE(NULLIF(s.venue,''),s.provider),'/training',NULL,NULL,NULL FROM training_sessions s JOIN training_session_participants sp ON sp.session_id=s.id CROSS JOIN span v WHERE $6 AND sp.user_id=$1 AND s.cancelled_at IS NULL AND s.starts_at<v.end_at AND s.ends_at>v.start_at)
 SELECT day::text AS date,tz AS timezone,COALESCE((SELECT jsonb_agg(x ORDER BY x.start_at,x.id) FROM items x),'[]') AS rows FROM span`,[a.id,date,can(a,'meeting_reservations.view_own'),can(a,'portal.events.view'),can(a,'leave.view_own'),can(a,'academy.catalog.view')])).rows[0];}
