import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {DB,database,transaction} from './db';
import {Identity,can} from './permissions';
import {identityFor} from './auth-core';
import {AppError} from './security';
import {notificationTypes,internalNotificationLink,NotificationRow} from './engagement-shared';
export function notificationPermit(a:Identity){if(a.must_change_password||!can(a,'notifications.view_own'))throw new AppError(403,'Bildirimleri görüntüleme yetkiniz bulunmuyor.');}
// SQL fragment for existing RBAC semantics, including explicit user deny and SUPER_ADMIN.
export function permissionSQL(alias:string,permission:string){return `(EXISTS(SELECT 1 FROM user_roles ur JOIN roles ro ON ro.id=ur.role_id AND ro.active WHERE ur.user_id=${alias}.id AND ro.id='SUPER_ADMIN') OR (NOT EXISTS(SELECT 1 FROM user_permission_overrides o WHERE o.user_id=${alias}.id AND o.permission_id='${permission}' AND NOT o.allowed) AND (EXISTS(SELECT 1 FROM user_permission_overrides o WHERE o.user_id=${alias}.id AND o.permission_id='${permission}' AND o.allowed) OR EXISTS(SELECT 1 FROM user_roles ur JOIN roles ro ON ro.id=ur.role_id AND ro.active JOIN role_permissions p ON p.role_id=ur.role_id WHERE ur.user_id=${alias}.id AND p.permission_id='${permission}'))))`;}
type Notice={recipient:string;event:string;entityId:string;type:typeof notificationTypes[number];title:string;message?:string;link:string;key:string};
export async function createNotification(db:DB,n:Notice){if(!internalNotificationLink(n.link))throw new AppError(400,'Geçersiz bildirim bağlantısı.');await db.query(`INSERT INTO workflow_notifications(id,recipient_id,event,entity_id,type,title,message,link,dedup_key) SELECT $1,u.id,$3,$4,$5,$6,$7,$8,$9 FROM users u WHERE u.id=$2 AND u.status IN('ACTIVE','ON_LEAVE') AND u.archived_at IS NULL AND ${permissionSQL('u','notifications.view_own')} ON CONFLICT(recipient_id,dedup_key) WHERE dedup_key IS NOT NULL DO NOTHING`,[randomUUID(),n.recipient,n.event,n.entityId,n.type,n.title.slice(0,200),(n.message??'').slice(0,400),n.link,n.key]);}
export async function workflowNotification(db:DB,recipient:string,event:string,id:string,key=event+':'+id){const row=event.startsWith('request.')?{leave_status:null}:(await db.query<{leave_status:string|null}>("SELECT (SELECT status FROM leave_requests WHERE id=$1) AS leave_status",[id])).rows[0];const leave=!!row.leave_status;let title='Talebiniz güncellendi',type:Notice['type']=leave?'LEAVE':'REQUEST',link=(leave?'/leave/':'/requests/')+id,message='';if(event==='approval.pending'){type='APPROVAL';title=leave?'Yeni izin talebi onayınızı bekliyor':'Yeni talep onayınızı bekliyor';link='/approvals';}else if(event==='approval.approved'){title=leave?(row.leave_status==='PENDING_HR'?'Yöneticiniz izin talebinizi onayladı':'İzin talebiniz onaylandı'):'Talebiniz yönetici tarafından onaylandı';if(row.leave_status==='PENDING_HR')message='Talebiniz İK onayı bekliyor.';}else if(event==='approval.rejected')title=leave?'İzin talebiniz reddedildi':'Talebiniz reddedildi';else if(event==='request.routed'||event==='request.assigned'){title=event==='request.routed'?'Departmanınıza yeni talep ulaştı':'Size bir talep atandı';link='/admin/requests/'+id;}else if(event==='request.completed')title='Talebiniz tamamlandı';else if(event==='request.rejected')title='Talebiniz reddedildi';else if(event==='request.review')title='Talebiniz inceleniyor';else if(event==='request.in_progress')title='Talebiniz işleme alındı';await createNotification(db,{recipient,event,entityId:id,type,title,message,link,key});}
export async function unreadCount(a:Identity){notificationPermit(a);return (await database().query<{unread:number}>('SELECT count(*)::int AS unread FROM workflow_notifications WHERE recipient_id=$1 AND NOT is_read',[a.id])).rows[0];}
const columns='id,type,title,message,link,is_read,created_at::text';
export async function notificationList(a:Identity,params=new URLSearchParams(),dropdown=false){notificationPermit(a);const allowed=dropdown?[]:['page','read'];for(const k of params.keys())if(!allowed.includes(k))throw new AppError(400,'Geçersiz filtre.');if(dropdown)return (await database().query<{rows:NotificationRow[];unread:number}>(`SELECT (SELECT count(*)::int FROM workflow_notifications WHERE recipient_id=$1 AND NOT is_read) AS unread,COALESCE((SELECT jsonb_agg(r) FROM (SELECT ${columns} FROM workflow_notifications WHERE recipient_id=$1 ORDER BY created_at DESC,id DESC LIMIT 8)r),'[]'::jsonb) AS rows`,[a.id])).rows[0];const page=z.coerce.number().int().min(1).max(100000).parse(params.get('page')||1),read=params.get('read')??'';if(!['','yes','no'].includes(read))throw new AppError(400,'Geçersiz filtre.');const where="recipient_id=$1"+(read?" AND is_read="+(read==='yes'?'true':'false'):'');return {...(await database().query<{rows:NotificationRow[];total:number}>(`WITH filtered AS (SELECT ${columns} FROM workflow_notifications WHERE ${where}) SELECT (SELECT count(*)::int FROM filtered) AS total,COALESCE((SELECT jsonb_agg(r) FROM (SELECT * FROM filtered ORDER BY created_at DESC,id DESC LIMIT 20 OFFSET ${(page-1)*20})r),'[]'::jsonb) AS rows`,[a.id])).rows[0],page};}
export async function readNotification(a:Identity,id:string,read=true){if(id!=='all')z.string().uuid().parse(id);return transaction(async db=>{const live=await identityFor(db,a.id);if(!live)throw new AppError(401,'Yeniden giriş yapın.');notificationPermit(live);if(id==='all'){await db.query('UPDATE workflow_notifications SET is_read=true WHERE recipient_id=$1 AND NOT is_read',[a.id]);return {ok:true};}const r=await db.query<{link:string}>('UPDATE workflow_notifications SET is_read=$3 WHERE id=$1 AND recipient_id=$2 RETURNING link',[id,a.id,read]);if(!r.rows.length)throw new AppError(404,'Bildirim bulunamadı.');return {ok:true,link:internalNotificationLink(r.rows[0].link)?r.rows[0].link:'/notifications'};});}
// One set-based fanout, only at explicit publish/save actions; no scheduler and no backfill spam.
export async function contentNotifications(db:DB,kind:'announcements'|'events'|'news',id:string){const permission=kind==='events'?'portal.events.view':kind==='news'?'portal.communications.view':'portal.announcements.view',type=kind==='events'?'EVENT':kind==='news'?'SYSTEM':'ANNOUNCEMENT';await db.query(`INSERT INTO workflow_notifications(id,recipient_id,event,entity_id,type,title,message,link,dedup_key) SELECT md5('content-notice:'||$1||':'||c.id::text||':'||u.id::text)::uuid,u.id,$1||'.published',c.id,$2,CASE WHEN $1='events' THEN 'Yeni etkinlik: ' WHEN $1='news' THEN 'Yeni haber: ' ELSE 'Kurumsal duyuru: ' END||left(c.title,160),left(c.summary,300),'/'||$1||'/'||c.slug,$1||':published:'||c.id::text FROM ${kind} c CROSS JOIN users u WHERE c.id=$3 AND c.status='PUBLISHED' AND c.publish_at<=now() AND (c.expires_at IS NULL OR c.expires_at>now()) ${kind==='announcements'?"AND (c.priority>=1 OR EXISTS(SELECT 1 FROM announcements_categories ac WHERE ac.id=c.category_id AND ac.name IN('Aramıza Katılanlar','Terfi & Yeni Görev','Organizasyon Değişikliği')))":kind==='events'?'AND c.event_end>now()':''} AND u.status IN('ACTIVE','ON_LEAVE') AND u.archived_at IS NULL AND ${permissionSQL('u',permission)} AND ${permissionSQL('u','notifications.view_own')} AND (c.audience_all OR EXISTS(SELECT 1 FROM ${kind}_audience a WHERE a.content_id=c.id AND (a.user_id=u.id OR a.company_id=u.company_id OR a.location_id=u.location_id OR a.department_id=u.department_id OR a.unit_id=u.unit_id OR EXISTS(SELECT 1 FROM user_roles ur JOIN roles ro ON ro.id=ur.role_id AND ro.active WHERE ur.user_id=u.id AND ur.role_id=a.role_id)))) ON CONFLICT(recipient_id,dedup_key) WHERE dedup_key IS NOT NULL DO NOTHING`,[kind,type,id]);}
// On-demand, self-only birthday event. Date-only comparison in Istanbul; no cron, age or year disclosure.
export async function syncPersonalNotifications(actor:Identity){notificationPermit(actor);return transaction(async db=>{
 const live=await identityFor(db,actor.id);if(!live)throw new AppError(401,'Yeniden giriş yapın.');notificationPermit(live);
 const day=(await db.query<{day:string}>(`SELECT to_char(now() AT TIME ZONE 'Europe/Istanbul','YYYY-MM-DD') AS day FROM users WHERE id=$1 AND show_birthday AND to_char(birth_date,'MM-DD')=to_char(now() AT TIME ZONE 'Europe/Istanbul','MM-DD')`,[live.id])).rows[0];
 if(day)await createNotification(db,{recipient:live.id,event:'birthday.today',entityId:live.id,type:'SYSTEM',title:'Doğum gününüz kutlu olsun!',message:'Koyuncu Grup ailesi olarak mutlu bir yaş dileriz.',link:'/notifications',key:'birthday:'+day.day});return (await db.query<{unread:number}>('SELECT count(*)::int AS unread FROM workflow_notifications WHERE recipient_id=$1 AND NOT is_read',[live.id])).rows[0];});}
