import {z} from 'zod';
import {database} from './db';
import {Identity,can} from './permissions';
import {permit} from './workflows';
import {directoryVisible,directoryAllowed} from './directory';
import {Person} from './directory-shared';
import {AppError} from './security';
import {surveyAudience} from './surveys';
export async function organization(a:Identity,p=new URLSearchParams()){permit(a,'organization.view_portal');if(!directoryAllowed(a))throw new AppError(403,'Rehber yetkisi gerekli.');const id=p.get('person')?z.string().uuid().parse(p.get('person')):null,page=z.coerce.number().int().min(1).max(100000).parse(p.get('page')||1),q='%'+(p.get('q')??'').slice(0,100)+'%';const result=(await database().query<{person:Person|null;manager:Person|null;rows:Person[];total:number}>(`WITH visible AS (SELECT u.id,concat_ws(' ',u.first_name,u.last_name) AS name,u.photo,j.name AS job_title,d.name AS department,un.name AS unit,c.name AS company,l.name AS location,CASE WHEN ${directoryVisible('m')} THEN m.id END AS manager_id FROM users u LEFT JOIN users m ON m.id=u.manager_user_id LEFT JOIN job_titles j ON j.id=u.job_title_id LEFT JOIN departments d ON d.id=u.department_id LEFT JOIN units un ON un.id=u.unit_id LEFT JOIN companies c ON c.id=u.company_id LEFT JOIN locations l ON l.id=u.location_id WHERE ${directoryVisible('u')}),selected AS (SELECT * FROM visible WHERE id=$1),list AS (SELECT * FROM visible WHERE CASE WHEN $1::uuid IS NOT NULL THEN manager_id=$1 WHEN $2<>'%%' THEN portal_fold(name||' '||coalesce(department,'')||' '||coalesce(company,'')) LIKE portal_fold($2) ELSE manager_id IS NULL END) SELECT (SELECT to_jsonb(x) FROM selected x) AS person,(SELECT to_jsonb(v) FROM visible v JOIN selected s ON v.id=s.manager_id) AS manager,(SELECT count(*)::int FROM list) AS total,COALESCE((SELECT jsonb_agg(x) FROM (SELECT * FROM list ORDER BY name,id LIMIT 20 OFFSET ${(page-1)*20})x),'[]') AS rows`,[id,q])).rows[0];if(id&&!result.person)throw new AppError(404,'Kişi bulunamadı.');return {...result,page};}
export async function organizationHistory(a:Identity,id:string,page=1){permit(a,'organization.history',true);z.string().uuid().parse(id);page=z.number().int().min(1).max(100000).parse(page);return (await database().query<{changes:Record<string,{old:string|null;new:string|null}>;at:string;actor:string}>(`SELECT details->'organization' AS changes,l.created_at::text AS at,concat_ws(' ',u.first_name,u.last_name) AS actor FROM audit_logs l LEFT JOIN users u ON u.id=l.actor_user_id WHERE l.entity_type='user' AND l.entity_id=$1 AND l.details ? 'organization' ORDER BY l.created_at DESC,l.id LIMIT 20 OFFSET ${(page-1)*20}`,[id])).rows;}
export async function companies(a:Identity,page=1){permit(a,'portal.company.view');page=z.number().int().min(1).max(100000).parse(page);return (await database().query<{total:number;rows:{id:string;name:string;logo:string|null;description:string;website:string;phone:string|null;address:string|null;contact:{id:string;name:string}|null;locations:{id:string;name:string;address:string;phone:string}[]}[]}>(`WITH selected AS (SELECT id,name,logo,description,website,phone,address,contact_user_id FROM companies WHERE active AND archived_at IS NULL ORDER BY name,id LIMIT 20 OFFSET ${(page-1)*20}) SELECT (SELECT count(*)::int FROM companies WHERE active AND archived_at IS NULL) AS total,COALESCE((SELECT jsonb_agg(x) FROM (SELECT c.id,c.name,c.logo,c.description,c.website,c.phone,c.address,CASE WHEN $1::boolean AND ${directoryVisible('u')} THEN jsonb_build_object('id',u.id,'name',concat_ws(' ',u.first_name,u.last_name)) END AS contact,COALESCE((SELECT jsonb_agg(l) FROM (SELECT id,name,address,phone FROM locations WHERE company_id=c.id AND active AND archived_at IS NULL ORDER BY name LIMIT 100)l),'[]') AS locations FROM selected c LEFT JOIN users u ON u.id=c.contact_user_id)x),'[]') AS rows`,[directoryAllowed(a)])).rows[0];}
export type DueItem={title:string;kind:string;due:string;link:string;days:number};
export async function deadlines(a:Identity,p=new URLSearchParams()){permit(a,'deadlines.view');const window=z.enum(['30','15','7','overdue']).parse(p.get('window')||'30'),page=z.coerce.number().int().min(1).max(100000).parse(p.get('page')||1),parts:string[]=[];
if(can(a,'admin.view')&&can(a,'inventory.view'))parts.push("SELECT asset_number||' · '||brand||' '||model AS title,'Envanter Garanti' AS kind,warranty_end AS due,'/admin/inventory/'||id AS link FROM inventory_items WHERE status<>'INACTIVE'");
if(can(a,'training.view_own')||can(a,'admin.view')&&can(a,'training.manage'))parts.push(`SELECT c.title AS title,'Sertifika' AS kind,t.valid_until AS due,'${can(a,'admin.view')&&can(a,'training.manage')?'/admin/people/training':'/training'}' AS link FROM training_assignments t JOIN training_courses c ON c.id=t.course_id WHERE t.status='COMPLETED' AND ${can(a,'admin.view')&&can(a,'training.manage')?'true':'t.user_id=$1'}`);
if(can(a,'training.view_own'))parts.push("SELECT c.title AS title,'Eğitim Son Tarihi' AS kind,t.due_date AS due,'/training' AS link FROM training_assignments t JOIN training_courses c ON c.id=t.course_id WHERE t.user_id=$1 AND t.status IN('ASSIGNED','IN_PROGRESS')");
if(can(a,'orientation.view_own'))parts.push("SELECT t.title,'Oryantasyon Adımı' AS kind,t.deadline AS due,'/orientation' AS link FROM employee_checklist_tasks t JOIN employee_checklists c ON c.id=t.checklist_id WHERE c.user_id=$1 AND c.kind='ONBOARDING' AND c.status='OPEN' AND t.status='OPEN'");
if(can(a,'admin.view')&&can(a,'fleet.view'))parts.push("SELECT v.plate AS title,d.kind,d.due,'/admin/fleet/'||v.id AS link FROM fleet_vehicles v CROSS JOIN LATERAL (VALUES('Araç Muayene',v.inspection_date),('Trafik Sigortası',v.insurance_end),('Kasko',v.casco_end),('Araç Bakım',v.next_service_date))d(kind,due) WHERE v.status<>'INACTIVE'");
if(!parts.length)return {rows:[] as DueItem[],total:0,page};return {...(await database().query<{rows:DueItem[];total:number}>(`WITH all_due AS (${parts.join(' UNION ALL ')}),filtered AS (SELECT title,kind,due::text,link,(due-(now() AT TIME ZONE 'Europe/Istanbul')::date)::int AS days FROM all_due WHERE $1::uuid IS NOT NULL AND due IS NOT NULL AND ${window==='overdue'?"due<(now() AT TIME ZONE 'Europe/Istanbul')::date":`due BETWEEN (now() AT TIME ZONE 'Europe/Istanbul')::date AND (now() AT TIME ZONE 'Europe/Istanbul')::date+${Number(window)}`}) SELECT (SELECT count(*)::int FROM filtered) AS total,COALESCE((SELECT jsonb_agg(x) FROM (SELECT * FROM filtered ORDER BY due,title LIMIT 20 OFFSET ${(page-1)*20})x),'[]') AS rows`,[a.id])).rows[0],page};}
export type MyAreaItem={label:string;count:number;link:string};
export async function myArea(a:Identity):Promise<MyAreaItem[]>{permit(a,'my_area.view');const parts:string[]=[];function add(p:string,label:string,link:string,sql:string){if(can(a,p))parts.push(`SELECT '${label}' AS label,'${link}' AS link,(${sql})::int AS count`);}
add('approvals.view','Bekleyen Onaylar','/approvals',"SELECT count(*) FROM approvals WHERE approver_id=$1 AND status='PENDING'");
add('requests.view_own','Açık Taleplerim','/requests',"SELECT count(*) FROM requests WHERE owner_id=$1 AND status NOT IN('COMPLETED','REJECTED','CANCELLED')");
add('tasks.view_own','Bana Atanan Tasklar','/tasks',"SELECT count(*) FROM ticket_tasks WHERE assignee_id=$1 AND status IN('OPEN','IN_PROGRESS')");
add('people_tasks.view_own','Operasyonel Görevlerim','/tasks',"SELECT count(*) FROM employee_checklist_tasks t JOIN employee_checklists c ON c.id=t.checklist_id WHERE c.status='OPEN' AND t.status='OPEN' AND (t.assignee_id=$1 OR t.assignee_id IS NULL AND t.department_id=(SELECT department_id FROM users WHERE id=$1))");
add('surveys.view_own','Bekleyen Anketler','/surveys',`SELECT count(*) FROM surveys s JOIN users u ON u.id=$1 WHERE s.status='PUBLISHED' AND now() BETWEEN s.starts_at AND s.ends_at AND ${surveyAudience} AND NOT EXISTS(SELECT 1 FROM survey_participation p WHERE p.survey_id=s.id AND p.user_id=$1)`);
add('training.view_own','Bekleyen Eğitimler','/training',"SELECT count(*) FROM training_assignments WHERE user_id=$1 AND status IN('ASSIGNED','IN_PROGRESS')");
add('orientation.view_own','Oryantasyon Adımları','/orientation',"SELECT count(*) FROM employee_checklist_tasks t JOIN employee_checklists c ON c.id=t.checklist_id WHERE c.user_id=$1 AND c.kind='ONBOARDING' AND c.status='OPEN' AND t.status='OPEN' AND t.required");
add('meeting_reservations.view_own','Yaklaşan Toplantılar','/meeting-rooms/my-reservations',"SELECT count(*) FROM meeting_reservations WHERE organizer_id=$1 AND status='ACTIVE' AND start_at>=now() AND start_at<now()+interval '30 days'");
for(const [kind,p,label] of [['announcements','portal.announcements.view','Okunması Gereken Duyurular'],['documents','portal.documents.view','Okunması Gereken Dokümanlar']])add(p,label,'/'+kind,`SELECT count(*) FROM ${kind} c JOIN users u ON u.id=$1 WHERE c.status='PUBLISHED' AND c.publish_at<=now() AND (c.expires_at IS NULL OR c.expires_at>now()) AND c.acknowledgement_required AND (c.audience_all OR EXISTS(SELECT 1 FROM ${kind}_audience ta WHERE ta.content_id=c.id AND (ta.company_id=u.company_id OR ta.location_id=u.location_id OR ta.department_id=u.department_id OR ta.unit_id=u.unit_id OR ta.user_id=u.id OR EXISTS(SELECT 1 FROM user_roles ur JOIN roles r ON r.id=ur.role_id AND r.active WHERE ur.user_id=u.id AND ur.role_id=ta.role_id)))) AND NOT EXISTS(SELECT 1 FROM content_acknowledgements ack WHERE ack.kind='${kind}' AND ack.content_id=c.id AND ack.user_id=$1 AND ack.revision=c.acknowledgement_revision)`);
if(!parts.length)return [];return (await database().query<MyAreaItem>(parts.join(' UNION ALL '),[a.id])).rows;}
