import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {DB,database,transaction,lock} from './db';
import {Identity,can} from './permissions';
import {write,permit,user} from './workflows';
import {audit} from './admin';
import {AppError} from './security';
import {createNotification} from './notifications';
import {managedEmployee,assignOne,courseRecord} from './academy';
import {Orientation,OrientationStep} from './academy-shared';
import {directoryVisible,directoryAllowed} from './directory';
const uid=z.string().regex(/^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$/i),text=z.string().max(3000).default('');
const stepSchema=z.object({title:z.string().trim().min(1).max(200),description:text,stage:z.enum(['DAY','WEEK','MONTH']),kind:z.enum(['INFO','VIDEO','DOCUMENT','ACK','TRAINING','SESSION','TASK','PERSON','ASSET','LINK']),reference_id:uid.nullable().default(null),reference_kind:z.enum(['announcements','documents']).nullable().default(null),url:z.string().max(1000).refine(s=>!s||s.startsWith('/')&&!s.startsWith('//')&&!/[\\\\\r\n]/.test(s)||/^https:\/\//i.test(s),'Güvenli bağlantı girin.').default(''),responsible_id:uid.nullable().default(null)}).strict();
export type Template={id:string;title:string;layer:string;target_id:string|null;steps:z.infer<typeof stepSchema>[];active:boolean};
async function validateStep(db:DB,s:z.infer<typeof stepSchema>){if(['TRAINING','SESSION','DOCUMENT','ACK','PERSON'].includes(s.kind)&&!s.reference_id)throw new AppError(400,'Bağlı kayıt seçin.');if(['ACK','DOCUMENT'].includes(s.kind)&&!s.reference_kind)throw new AppError(400,'Doküman veya duyuru türü seçin.');const table=s.kind==='TRAINING'?'training_courses':s.kind==='SESSION'?'training_sessions':s.kind==='PERSON'?'users':['DOCUMENT','ACK'].includes(s.kind)?s.reference_kind:s.kind==='ASSET'?'asset_assignments':null;if(table&&s.reference_id&&!(await db.query(`SELECT id FROM ${table} WHERE id=$1`,[s.reference_id])).rows.length)throw new AppError(400,'Bağlı kayıt bulunamadı.');if(s.responsible_id)await user(db,s.responsible_id);}
export async function saveTemplate(a:Identity,payload:unknown,id?:string){const d=z.object({title:z.string().min(1).max(200),layer:z.enum(['GROUP','COMPANY','DEPARTMENT','UNIT','ROLE']),target_id:z.string().max(80).nullable(),steps:z.array(stepSchema).min(1).max(100),active:z.boolean()}).strict().parse(payload);if((d.layer==='GROUP')!==(d.target_id===null))throw new AppError(400,'Katman hedefini seçin.');return write(a,'orientation.manage',true,async(db,live)=>{if(d.target_id){const table={COMPANY:'companies',DEPARTMENT:'departments',UNIT:'units',ROLE:'roles'}[d.layer as 'COMPANY'];if(!table||!(await db.query(`SELECT id FROM ${table} WHERE id=$1`,[d.target_id])).rows.length)throw new AppError(400,'Katman hedefi bulunamadı.');}for(const s of d.steps)await validateStep(db,s);const target=id??randomUUID();await db.query('INSERT INTO orientation_templates(id,title,layer,target_id,steps,active,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(id) DO UPDATE SET title=excluded.title,layer=excluded.layer,target_id=excluded.target_id,steps=excluded.steps,active=excluded.active,updated_by=excluded.updated_by,updated_at=now()',[target,d.title,d.layer,d.target_id,JSON.stringify(d.steps),d.active,live.id]);await audit(db,live.id,'orientation.template_saved','orientation_template',target);return {id:target};});}
export async function templates(a:Identity,page=1){permit(a,'orientation.manage',true);page=z.number().int().min(1).max(100000).parse(page);return (await database().query<Template>(`SELECT * FROM orientation_templates ORDER BY title,id LIMIT 20 OFFSET ${(page-1)*20}`)).rows;}
async function orientationRecord(db:DB,a:Identity,id:string,manage=false){uid.parse(id);const r=(await db.query<Orientation>(`SELECT o.id,o.user_id,o.title,o.buddy_id,o.status,o.starts_on::text,o.completed_at::text,concat_ws(' ',u.first_name,u.last_name) AS employee,CASE WHEN ${directoryVisible('b')} THEN concat_ws(' ',b.first_name,b.last_name) END AS buddy_name FROM employee_orientations o JOIN users u ON u.id=o.user_id LEFT JOIN users b ON b.id=o.buddy_id WHERE o.id=$1`,[id])).rows[0];if(!r)throw new AppError(404,'Oryantasyon bulunamadı.');if(manage||r.user_id!==a.id)await managedEmployee(db,a,r.user_id,'orientation.manage','orientation.manage_team');else permit(a,'orientation.view_own');return r;}
export async function startOrientation(a:Identity,payload:unknown){const d=z.object({user_id:uid,title:z.string().min(1).max(200),starts_on:z.string().date(),buddy_id:uid.nullable(),template_ids:z.array(uid).min(1).max(10)}).strict().parse(payload);return write(a,'orientation.manage',true,async(db,live)=>{const u=await user(db,d.user_id);if(d.buddy_id){if(d.buddy_id===d.user_id)throw new AppError(400,'Buddy farklı bir çalışan olmalı.');await user(db,d.buddy_id);}const ts=(await db.query<Template>('SELECT * FROM orientation_templates WHERE id=ANY($1::uuid[]) AND active',[[...new Set(d.template_ids)]])).rows;if(ts.length!==new Set(d.template_ids).size)throw new AppError(400,'Aktif şablonları seçin.');const org=(await db.query<{unit_id:string}>('SELECT unit_id FROM users WHERE id=$1',[d.user_id])).rows[0];for(const t of ts){const matches=t.layer==='GROUP'||t.layer==='COMPANY'&&t.target_id===u.company_id||t.layer==='DEPARTMENT'&&t.target_id===u.department_id||t.layer==='UNIT'&&t.target_id===org.unit_id||t.layer==='ROLE'&&(await db.query('SELECT 1 FROM user_roles WHERE user_id=$1 AND role_id=$2',[d.user_id,t.target_id])).rows.length;if(!matches)throw new AppError(400,'Şablon çalışanın şirket/departman/rol kapsamıyla eşleşmiyor.');}if((await db.query("SELECT id FROM employee_orientations WHERE user_id=$1 AND status='ACTIVE'",[d.user_id])).rows.length)throw new AppError(409,'Çalışanın aktif oryantasyonu var.');const id=randomUUID();await db.query('INSERT INTO employee_orientations(id,user_id,title,buddy_id,template_ids,starts_on,created_by) VALUES($1,$2,$3,$4,$5,$6,$7)',[id,d.user_id,d.title,d.buddy_id,d.template_ids,d.starts_on,live.id]);for(const t of ts)for(const s of t.steps){await validateStep(db,s);if(s.kind==='ASSET'&&s.reference_id&&!(await db.query('SELECT id FROM asset_assignments WHERE id=$1 AND user_id=$2',[s.reference_id,d.user_id])).rows.length)throw new AppError(400,'Zimmet çalışana ait değil.');const due=(await db.query<{date:string}>('SELECT ($1::date+$2::int)::text AS date',[d.starts_on,{DAY:0,WEEK:6,MONTH:29}[s.stage]])).rows[0].date;await db.query('INSERT INTO employee_orientation_steps(id,orientation_id,title,description,stage,kind,reference_id,reference_kind,url,responsible_id,due_date,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)',[randomUUID(),id,s.title,s.description,s.stage,s.kind,s.reference_id,s.reference_kind,s.url,s.responsible_id,due,live.id]);if(s.kind==='TRAINING'&&s.reference_id){const completed=(await db.query("SELECT id FROM training_assignments WHERE user_id=$1 AND course_id=$2 AND status='COMPLETED' AND (valid_until IS NULL OR valid_until>=current_date) ORDER BY assigned_at DESC LIMIT 1",[d.user_id,s.reference_id])).rows.length;if(!completed)await assignOne(db,live,await courseRecord(db,s.reference_id),d.user_id,d.starts_on,due,'COMPANY');}}
await createNotification(db,{recipient:d.user_id,event:'orientation.started',entityId:id,type:'SYSTEM',title:'Oryantasyonunuz başladı',message:d.title,link:'/orientation',key:'orientation:'+id});await audit(db,live.id,'orientation.started','employee_orientation',id);return {id};});}
export async function orientationList(a:Identity,page=1,manage=false){permit(a,manage?can(a,'admin.view')&&can(a,'orientation.manage')?'orientation.manage':'orientation.manage_team':'orientation.view_own');page=z.number().int().min(1).max(100000).parse(page);return (await database().query<Orientation>(`SELECT o.id,o.user_id,o.title,o.status,o.starts_on::text,o.completed_at::text,concat_ws(' ',u.first_name,u.last_name) AS employee FROM employee_orientations o JOIN users u ON u.id=o.user_id WHERE ${manage?can(a,'admin.view')&&can(a,'orientation.manage')?'$1::uuid IS NOT NULL':'u.manager_user_id=$1':'o.user_id=$1'} ORDER BY o.created_at DESC,o.id LIMIT 20 OFFSET ${(page-1)*20}`,[a.id])).rows;}
export async function orientationDetail(a:Identity,id:string){return transaction(async db=>{await lock(db);const item=await orientationRecord(db,a,id);const rows=(await db.query<OrientationStep>(`SELECT s.*,s.due_date::text,s.completed_at::text,CASE WHEN kind='TRAINING' THEN (SELECT '/academy/learning/'||id FROM training_assignments t WHERE t.user_id=s.user_id AND t.course_id=s.reference_id ORDER BY assigned_at DESC LIMIT 1) WHEN kind IN('ACK','DOCUMENT') AND reference_kind='documents' THEN (SELECT '/documents/'||slug FROM documents WHERE id=s.reference_id) WHEN kind IN('ACK','DOCUMENT') AND reference_kind='announcements' THEN (SELECT '/announcements/'||slug FROM announcements WHERE id=s.reference_id) WHEN kind='PERSON' THEN '/directory/'||reference_id WHEN kind='ASSET' THEN '/my-assets' WHEN kind='SESSION' THEN '/calendar' END AS link FROM orientation_step_progress s WHERE orientation_id=$1 AND user_id=$2 ORDER BY CASE s.stage WHEN 'DAY' THEN 0 WHEN 'WEEK' THEN 1 ELSE 2 END,s.due_date,s.created_at,s.id`,[id,item.user_id])).rows;const done=rows.filter(s=>s.done).length,progress=rows.length?Math.round(done/rows.length*100):0;
// Completion remains a projection. Only its timestamp is recorded idempotently; no copied business records.
if(rows.length&&done===rows.length&&item.status!=='COMPLETED'){await db.query("UPDATE employee_orientations SET status='COMPLETED',completed_at=now() WHERE id=$1 AND status='ACTIVE'",[id]);item.status='COMPLETED';item.completed_at=new Date().toISOString();}
const visibleBuddy=directoryAllowed(a)&&item.buddy_name?item.buddy_id:null;
return {item:{...item,buddy_id:visibleBuddy,buddy_name:visibleBuddy?item.buddy_name:null},rows,progress,own:item.user_id===a.id};});}
export async function completeStep(a:Identity,id:string){return write(a,'orientation.view_own',false,async(db,live)=>{uid.parse(id);const s=(await db.query<OrientationStep>('SELECT * FROM employee_orientation_steps WHERE id=$1',[id])).rows[0];if(!s)throw new AppError(404,'Adım bulunamadı.');const o=await orientationRecord(db,live,s.orientation_id);if(o.user_id!==live.id)throw new AppError(403,'Yalnız kendi adımınızı tamamlayabilirsiniz.');if(['TRAINING','ACK','DOCUMENT','ASSET','SESSION'].includes(s.kind))throw new AppError(409,'Bu adım bağlı sistemden otomatik hesaplanır.');if(s.completed_at)throw new AppError(409,'Adım zaten tamamlandı.');await db.query('UPDATE employee_orientation_steps SET completed_at=now(),completed_by=$2 WHERE id=$1',[id,live.id]);return {id};});}
export async function managerTask(a:Identity,id:string,payload:unknown,stepId?:string){const d=z.object({title:z.string().min(1).max(200),description:text,stage:z.enum(['DAY','WEEK','MONTH']),due_date:z.string().date(),responsible_id:uid.nullable()}).strict().parse(payload);const global=can(a,'admin.view')&&can(a,'orientation.manage');return write(a,global?'orientation.manage':'orientation.manage_team',false,async(db,live)=>{const o=await orientationRecord(db,live,id,true);if(o.status!=='ACTIVE')throw new AppError(409,'Tamamlanan oryantasyona görev eklenemez.');if(d.responsible_id)await user(db,d.responsible_id);const target=stepId??randomUUID();if(stepId){const s=(await db.query<{kind:string;completed_at:string}>('SELECT kind,completed_at FROM employee_orientation_steps WHERE id=$1 AND orientation_id=$2',[uid.parse(stepId),id])).rows[0];if(!s||s.kind!=='TASK'||s.completed_at)throw new AppError(409,'Yalnız açık görev düzenlenebilir.');await db.query('UPDATE employee_orientation_steps SET title=$2,description=$3,stage=$4,due_date=$5,responsible_id=$6 WHERE id=$1',[target,d.title,d.description,d.stage,d.due_date,d.responsible_id]);}else await db.query("INSERT INTO employee_orientation_steps(id,orientation_id,title,description,stage,kind,due_date,responsible_id,created_by) VALUES($1,$2,$3,$4,$5,'TASK',$6,$7,$8)",[target,id,d.title,d.description,d.stage,d.due_date,d.responsible_id,live.id]);await audit(db,live.id,'orientation.manager_task_saved','orientation_step',target);return {id:target};});}
export async function orientationContext(a:Identity){permit(a,'orientation.view_own');const d=(await database().query<{manager:{id:string;name:string}|null;department:string|null;unit:string|null;location:string|null;address:string|null;phone:string|null}>(`SELECT CASE WHEN $2::boolean AND ${directoryVisible('m')} THEN jsonb_build_object('id',m.id,'name',concat_ws(' ',m.first_name,m.last_name)) END AS manager,d.name AS department,un.name AS unit,l.name AS location,l.address,l.phone FROM users u LEFT JOIN users m ON m.id=u.manager_user_id LEFT JOIN departments d ON d.id=u.department_id LEFT JOIN units un ON un.id=u.unit_id LEFT JOIN locations l ON l.id=u.location_id WHERE u.id=$1`,[a.id,directoryAllowed(a)])).rows[0];return d;}

export async function templateDetail(a:Identity,id:string){permit(a,'orientation.manage',true);uid.parse(id);const r=(await database().query<Template>('SELECT * FROM orientation_templates WHERE id=$1',[id])).rows[0];if(!r)throw new AppError(404,'Şablon bulunamadı.');return r;}
