import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {database} from './db';
import {Identity,can} from './permissions';
import {write,permit,user} from './workflows';
import {AppError} from './security';
import {audit} from './admin';
import {createNotification} from './notifications';
import {proofFile,ProofFile} from './proof-files';
import {Checklist,PeopleTask,Course,TrainingAssignment,Choice} from './people-shared';
const uid=z.string().uuid(),date=z.string().date(),text=z.string().trim().max(3000).default('');
const kind=z.enum(['ONBOARDING','OFFBOARDING']);
const permission=(k:string)=>k==='ONBOARDING'?'onboarding.manage':'offboarding.manage';
export async function peopleOptions(a:Identity){if(!['onboarding.manage','offboarding.manage','training.manage','departures.manage'].some(p=>can(a,p)))throw new AppError(403,'Yetkiniz bulunmuyor.');permit(a,'admin.view');const tables=['users','companies','locations','departments','units','roles'];return (await database().query<Record<string,Choice[]>&{users:Choice[];departments:Choice[]}>('SELECT '+tables.map(table=>`COALESCE((SELECT jsonb_agg(x) FROM (SELECT id,${table==='users'?"concat_ws(' ',first_name,last_name)":'name'} AS name FROM ${table} WHERE ${table==='users'?'archived_at IS NULL':table==='roles'?'active':'active AND archived_at IS NULL'} ORDER BY name LIMIT 1000)x),'[]') AS ${table}`).join(','))).rows[0];}

export async function saveChecklist(a:Identity,payload:unknown){const d=z.object({user_id:uid,kind,title:z.string().trim().min(1).max(200),tasks:z.array(z.object({title:z.string().trim().min(1).max(200),department_id:uid.nullable(),assignee_id:uid.nullable(),deadline:date.nullable()}).strict()).min(1).max(100)}).strict().parse(payload);return write(a,permission(d.kind),true,async(db,live)=>{await user(db,d.user_id);for(const t of d.tasks){if(!t.assignee_id&&!t.department_id)throw new AppError(400,'Görev sorumlusu veya departman seçin.');if(t.assignee_id)await user(db,t.assignee_id);if(t.department_id&&!(await db.query('SELECT id FROM departments WHERE id=$1 AND active AND archived_at IS NULL',[t.department_id])).rows.length)throw new AppError(400,'Aktif departman seçin.');}const id=randomUUID();await db.query('INSERT INTO employee_checklists(id,user_id,kind,title,created_by) VALUES($1,$2,$3,$4,$5)',[id,d.user_id,d.kind,d.title,live.id]);for(const t of d.tasks)await db.query('INSERT INTO employee_checklist_tasks(id,checklist_id,title,department_id,assignee_id,deadline) VALUES($1,$2,$3,$4,$5,$6)',[randomUUID(),id,t.title,t.department_id,t.assignee_id,t.deadline]);await audit(db,live.id,'checklist.created',d.kind,id);return {id};});}
export async function checklistList(a:Identity,k:string,page=1){kind.parse(k);permit(a,permission(k),true);page=Math.max(1,Math.min(100000,Math.floor(page)||1));return (await database().query<{rows:Checklist[];total:number}>(`WITH list AS (SELECT c.*,c.completed_at::text,concat_ws(' ',u.first_name,u.last_name) AS employee,(SELECT count(*)::int FROM asset_assignments aa WHERE aa.user_id=c.user_id AND aa.returned_at IS NULL) AS active_assets FROM employee_checklists c JOIN users u ON u.id=c.user_id WHERE c.kind=$1) SELECT (SELECT count(*)::int FROM list) AS total,COALESCE((SELECT jsonb_agg(x) FROM (SELECT * FROM list ORDER BY created_at DESC,id LIMIT 20 OFFSET $2)x),'[]') AS rows`,[k,(page-1)*20])).rows[0];}
export async function checklistDetail(a:Identity,id:string){uid.parse(id);const c=(await database().query<Checklist>(`SELECT c.*,c.completed_at::text,concat_ws(' ',u.first_name,u.last_name) AS employee,(SELECT count(*)::int FROM asset_assignments aa WHERE aa.user_id=c.user_id AND aa.returned_at IS NULL) AS active_assets FROM employee_checklists c JOIN users u ON u.id=c.user_id WHERE c.id=$1`,[id])).rows[0];if(!c)throw new AppError(404,'Kayıt bulunamadı.');permit(a,permission(c.kind),true);const tasks=(await database().query<PeopleTask>(`SELECT t.*,t.deadline::text,t.completed_at::text,concat_ws(' ',u.first_name,u.last_name) AS assignee_name,d.name AS department_name FROM employee_checklist_tasks t LEFT JOIN users u ON u.id=t.assignee_id LEFT JOIN departments d ON d.id=t.department_id WHERE checklist_id=$1 ORDER BY deadline NULLS LAST,id`,[id])).rows;return {item:c,tasks};}
export async function completeChecklist(a:Identity,id:string,reason=''){uid.parse(id);const record=(await database().query<Checklist>('SELECT * FROM employee_checklists WHERE id=$1',[id])).rows[0];if(!record)throw new AppError(404,'Kayıt bulunamadı.');return write(a,permission(record.kind),true,async(db,live)=>{const c=(await db.query<Checklist>('SELECT * FROM employee_checklists WHERE id=$1 FOR UPDATE',[id])).rows[0];if(c.status!=='OPEN')throw new AppError(409,'İşlem zaten tamamlandı.');const outstanding=(await db.query<{tasks:number;assets:number}>(`SELECT (SELECT count(*)::int FROM employee_checklist_tasks WHERE checklist_id=$1 AND status<>'DONE') AS tasks,(SELECT count(*)::int FROM asset_assignments WHERE user_id=$2 AND returned_at IS NULL) AS assets`,[id,c.user_id])).rows[0];if(outstanding.tasks||c.kind==='OFFBOARDING'&&outstanding.assets){if(c.kind!=='OFFBOARDING')throw new AppError(409,'Önce açık görevleri tamamlayın.');permit(live,'offboarding.override',true);if(reason.trim().length<10)throw new AppError(409,'Açık görev/zimmet var. Yetkili istisnası için en az 10 karakter gerekçe zorunlu.');await audit(db,live.id,'offboarding.override','checklist',id,{reason:reason.slice(0,500),...outstanding});}await db.query("UPDATE employee_checklists SET status='COMPLETED',completed_at=now(),override_reason=$2 WHERE id=$1",[id,reason.slice(0,500)]);await audit(db,live.id,'checklist.completed',c.kind,id);return {id};});}
export async function peopleTasks(a:Identity){permit(a,'people_tasks.view_own');return (await database().query<PeopleTask>(`SELECT t.id,t.title,t.assignee_id,t.department_id,t.deadline::text,t.status,t.completed_at::text FROM employee_checklist_tasks t JOIN employee_checklists c ON c.id=t.checklist_id JOIN users u ON u.id=$1 WHERE c.status='OPEN' AND t.status='OPEN' AND (t.assignee_id=$1 OR t.assignee_id IS NULL AND t.department_id=u.department_id) ORDER BY t.deadline NULLS LAST,t.id LIMIT 100`,[a.id])).rows;}
export async function completePeopleTask(a:Identity,id:string,admin=false){uid.parse(id);return write(a,admin?'admin.view':'people_tasks.update_own',admin,async(db,live)=>{const t=(await db.query<PeopleTask&{kind:string;parent_status:string}>(`SELECT t.*,c.kind,c.status AS parent_status FROM employee_checklist_tasks t JOIN employee_checklists c ON c.id=t.checklist_id WHERE t.id=$1 FOR UPDATE OF t,c`,[id])).rows[0];if(!t)throw new AppError(404,'Görev bulunamadı.');if(admin)permit(live,permission(t.kind),true);else {permit(live,'people_tasks.view_own');const u=await user(db,live.id);if(t.assignee_id!==live.id&&(t.assignee_id||t.department_id!==u.department_id))throw new AppError(404,'Görev bulunamadı.');}if(t.status!=='OPEN'||t.parent_status!=='OPEN')throw new AppError(409,'Görev artık tamamlanamaz.');await db.query("UPDATE employee_checklist_tasks SET status='DONE',completed_by=$2,completed_at=now() WHERE id=$1",[id,live.id]);await audit(db,live.id,'checklist.task_completed','task',id);return {id};});}
export async function saveDeparture(a:Identity,payload:unknown){const d=z.object({user_id:uid,departure_date:date,kind:z.enum(['RESIGNATION','DISMISSAL','RETIREMENT','CONTRACT_END','PROBATION','OTHER']),reason:text,notes:text}).strict().parse(payload);return write(a,'departures.manage',true,async(db,live)=>{if(!(await db.query('SELECT id FROM users WHERE id=$1',[d.user_id])).rows.length)throw new AppError(404,'Kullanıcı bulunamadı.');await db.query(`INSERT INTO employee_departures(user_id,departure_date,kind,reason,notes,updated_by) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(user_id) DO UPDATE SET departure_date=EXCLUDED.departure_date,kind=EXCLUDED.kind,reason=EXCLUDED.reason,notes=EXCLUDED.notes,updated_by=EXCLUDED.updated_by,updated_at=now()`,[d.user_id,d.departure_date,d.kind,d.reason,d.notes,live.id]);await audit(db,live.id,'employee.departure','user',d.user_id);return {id:d.user_id};});}
export async function saveCourse(a:Identity,payload:unknown){const d=z.object({title:z.string().trim().min(1).max(200),category:z.string().trim().min(1).max(100),description:text,active:z.boolean().default(true)}).strict().parse(payload);return write(a,'training.manage',true,async(db,live)=>{const id=randomUUID();await db.query('INSERT INTO training_courses(id,title,category,description,active,created_by) VALUES($1,$2,$3,$4,$5,$6)',[id,d.title,d.category,d.description,d.active,live.id]);await audit(db,live.id,'training.created','training',id);return {id};});}
export async function courses(a:Identity){permit(a,'training.manage',true);return (await database().query<Course>('SELECT id,title,category,description,active FROM training_courses ORDER BY title LIMIT 200')).rows;}
export async function assignTraining(a:Identity,payload:unknown){const d=z.object({course_id:uid,due_date:date,audience_all:z.boolean(),targets:z.array(z.object({type:z.enum(['company_id','location_id','department_id','unit_id','role_id','user_id']),id:z.string().min(1).max(80)})).max(500)}).strict().parse(payload);if(d.audience_all===!!d.targets.length)throw new AppError(400,'Hedef kitle seçin.');return write(a,'training.manage',true,async(db,live)=>{if(!(await db.query('SELECT id FROM training_courses WHERE id=$1 AND active',[d.course_id])).rows.length)throw new AppError(400,'Aktif eğitim seçin.');const ids=(await db.query<{id:string}>(`SELECT u.id FROM users u WHERE u.status IN('ACTIVE','ON_LEAVE') AND u.archived_at IS NULL AND ($1::boolean OR EXISTS(SELECT 1 FROM jsonb_array_elements($2::jsonb)t WHERE t->>'type'='user_id' AND t->>'id'=u.id::text OR t->>'type'='company_id' AND t->>'id'=u.company_id::text OR t->>'type'='location_id' AND t->>'id'=u.location_id::text OR t->>'type'='department_id' AND t->>'id'=u.department_id::text OR t->>'type'='unit_id' AND t->>'id'=u.unit_id::text OR t->>'type'='role_id' AND EXISTS(SELECT 1 FROM user_roles ur JOIN roles ro ON ro.id=ur.role_id AND ro.active WHERE ur.user_id=u.id AND ur.role_id=t->>'id')))`,[d.audience_all,JSON.stringify(d.targets)])).rows;let count=0;for(const u of ids){const id=randomUUID(),r=await db.query('INSERT INTO training_assignments(id,course_id,user_id,assigned_by,due_date) VALUES($1,$2,$3,$4,$5) ON CONFLICT DO NOTHING RETURNING id',[id,d.course_id,u.id,live.id,d.due_date]);if(r.rows.length){count++;await createNotification(db,{recipient:u.id,event:'training.assigned',entityId:id,type:'SYSTEM',title:'Size eğitim atandı',link:'/training',key:'training:'+id});}}await audit(db,live.id,'training.assigned','training',d.course_id,{count});return {count};});}
export async function trainingList(a:Identity,admin=false,page=1){permit(a,admin?'training.manage':'training.view_own',admin);page=Math.max(1,Math.min(100000,Math.floor(page)||1));return (await database().query<{rows:TrainingAssignment[];total:number}>(`WITH list AS (SELECT a.id,a.user_id,a.course_id,a.due_date::text,a.status,a.completed_at::text,a.valid_until::text,a.certificate IS NOT NULL AS has_certificate,c.title,concat_ws(' ',u.first_name,u.last_name) AS employee FROM training_assignments a JOIN training_courses c ON c.id=a.course_id JOIN users u ON u.id=a.user_id WHERE $2::boolean OR a.user_id=$1) SELECT (SELECT count(*)::int FROM list) AS total,COALESCE((SELECT jsonb_agg(x) FROM (SELECT * FROM list ORDER BY due_date,id LIMIT 20 OFFSET $3)x),'[]') AS rows`,[a.id,admin,(page-1)*20])).rows[0];}
export async function completeTraining(a:Identity,id:string,payload:unknown){uid.parse(id);const d=z.object({valid_until:date.nullable(),certificate:proofFile.nullable()}).strict().parse(payload);return write(a,'training.manage',true,async(db,live)=>{const r=await db.query("UPDATE training_assignments SET status='COMPLETED',completed_at=now(),valid_until=$2,certificate=$3 WHERE id=$1 AND status IN('ASSIGNED','IN_PROGRESS') RETURNING id",[id,d.valid_until,d.certificate?JSON.stringify(d.certificate):null]);if(!r.rows.length)throw new AppError(409,'Eğitim zaten sonuçlanmış veya bulunamadı.');await audit(db,live.id,'training.completed','training_assignment',id);return {id};});}
export async function trainingFile(a:Identity,id:string){uid.parse(id);permit(a,'training.view_own');const r=(await database().query<{certificate:ProofFile}>(`SELECT certificate FROM training_assignments WHERE id=$1 AND (user_id=$2 OR $3::boolean)`,[id,a.id,can(a,'admin.view')&&can(a,'training.manage')])).rows[0];if(!r?.certificate)throw new AppError(404,'Belge bulunamadı.');return r.certificate;}
