import {z} from 'zod';
import {database} from './db';
import {Identity,can} from './permissions';
import {permit} from './workflows';
import {AppError} from './security';
import {surveyAudience} from './surveys';
import {permissionSQL} from './notifications';
import {ReportSection,ReportBlock,ReportRow,reportSections} from './report-shared';
export function reportPermit(a:Identity,kind:ReportSection){permit(a,'reports.view_management',true);permit(a,'reports.view_'+(kind==='people'?'hr':kind),true);}
export async function reportOptions(a:Identity){permit(a,'reports.view_management',true);return (await database().query<Record<string,{id:string;name:string}[]>>(`SELECT ${['companies','locations','departments','units'].map(t=>`COALESCE((SELECT jsonb_agg(x) FROM (SELECT id,name FROM ${t} WHERE archived_at IS NULL ORDER BY name)x),'[]') AS ${t}`).join(',')}`)).rows[0];}
export async function report(a:Identity,kind:ReportSection,p=new URLSearchParams()):Promise<ReportBlock[]>{if(!(kind in reportSections))throw new AppError(404,'Rapor bulunamadı.');reportPermit(a,kind);const filters:Record<string,string>={};for(const k of ['company_id','location_id','department_id','unit_id'])if(p.get(k))filters[k]=z.string().uuid().parse(p.get(k));for(const k of ['from','to'])if(p.get(k))filters[k]=z.string().date().parse(p.get(k));if(filters.from&&filters.to&&filters.from>filters.to)throw new AppError(400,'Tarih aralığını kontrol edin.');const page=z.coerce.number().int().min(1).max(100000).parse(p.get('page')||1),offset=(page-1)*20;
const values:unknown[]=[],positions:Record<string,string>={};for(const [k,v] of Object.entries(filters)){values.push(v);positions[k]='$'+values.length;}
const org=(alias:string,keys=['company_id','location_id','department_id','unit_id'])=>keys.filter(k=>positions[k]).map(k=>`${alias}.${k}=${positions[k]}::uuid`).join(' AND ')||'true';
const period=(col:string)=>[positions.from?`${col}>=${positions.from}::date`:null,positions.to?`${col}<${positions.to}::date+interval '1 day'`:null].filter(Boolean).join(' AND ')||'true';
const base=`WITH people AS (SELECT u.* FROM users u WHERE ${org('u')}), `;
const blocks:{title:string;sql:string}[]=[];function add(title:string,sql:string){blocks.push({title,sql});}
const group=(table:string,column:string,label:string)=>`SELECT COALESCE(g.name,'Tanımsız') AS "${label}",count(*)::int AS "Adet" FROM x LEFT JOIN ${table} g ON g.id=x.${column} GROUP BY g.id,g.name ORDER BY count(*) DESC,g.name LIMIT 100`;
if(kind==='hr'){
 const b=base+`x AS (SELECT * FROM people) `;
 add('Çalışan Özeti',b+`SELECT count(*)::int AS "Toplam",count(*) FILTER(WHERE status IN('ACTIVE','ON_LEAVE') AND archived_at IS NULL)::int AS "Aktif",count(*) FILTER(WHERE status IN('INACTIVE','LEFT') OR archived_at IS NOT NULL)::int AS "Pasif / Ayrılmış",count(*) FILTER(WHERE EXISTS(SELECT 1 FROM leave_requests l WHERE l.owner_id=x.id AND l.status='APPROVED' AND (now() AT TIME ZONE 'Europe/Istanbul')::date BETWEEN l.start_date AND l.end_date))::int AS "Bugün Ofis Dışında",round(avg(((now() AT TIME ZONE 'Europe/Istanbul')::date-start_date)/365.25) FILTER(WHERE status IN('ACTIVE','ON_LEAVE') AND start_date<=current_date),1) AS "Ortalama Kıdem (Yıl)",count(*) FILTER(WHERE date_trunc('month',start_date)=date_trunc('month',current_date))::int AS "Bu Ay İşe Giren",(SELECT count(*)::int FROM employee_departures d JOIN x ON x.id=d.user_id WHERE date_trunc('month',d.departure_date)=date_trunc('month',current_date)) AS "Bu Ay Ayrılan" FROM x`);
 for(const [table,column,label] of [['companies','company_id','Şirket'],['locations','location_id','Lokasyon'],['departments','department_id','Departman'],['units','unit_id','Birim']])add(label+' Dağılımı',b+group(table,column,label));
 add('Aylık İşe Giriş / Ayrılış Trendi',b+`SELECT ay AS "Ay",sum(giris)::int AS "İşe Giriş",sum(cikis)::int AS "Ayrılış" FROM (SELECT to_char(start_date,'YYYY-MM') ay,count(*) giris,0 cikis FROM x WHERE start_date IS NOT NULL AND ${period('start_date')} GROUP BY ay UNION ALL SELECT to_char(d.departure_date,'YYYY-MM') ay,0,count(*) FROM employee_departures d JOIN x ON x.id=d.user_id WHERE ${period('d.departure_date')} GROUP BY ay)t GROUP BY ay ORDER BY ay DESC LIMIT 60`);
 add('Yıllık İşe Giriş / Ayrılış Trendi',b+`SELECT yil AS "Yıl",sum(giris)::int AS "İşe Giriş",sum(cikis)::int AS "Ayrılış" FROM (SELECT extract(year FROM start_date)::int yil,count(*) giris,0 cikis FROM x WHERE start_date IS NOT NULL AND ${period('start_date')} GROUP BY yil UNION ALL SELECT extract(year FROM d.departure_date)::int yil,0,count(*) FROM employee_departures d JOIN x ON x.id=d.user_id WHERE ${period('d.departure_date')} GROUP BY yil)t GROUP BY yil ORDER BY yil DESC LIMIT 30`);
 add('İzin Özeti',b+`SELECT COALESCE(d.name,'Tanımsız') AS "Departman",COALESCE(loc.name,'Tanımsız') AS "Lokasyon",COALESCE(sum(l.days) FILTER(WHERE l.status='APPROVED'),0) AS "Onaylı Gün",COALESCE(sum(l.days) FILTER(WHERE l.status IN('PENDING_MANAGER','PENDING_HR')),0) AS "Bekleyen Gün" FROM leave_requests l JOIN x ON x.id=l.owner_id LEFT JOIN departments d ON d.id=l.owner_department_id LEFT JOIN locations loc ON loc.id=l.location_id WHERE ${period('l.start_date')} GROUP BY d.id,d.name,loc.id,loc.name ORDER BY d.name LIMIT 100`);
 if(can(a,'departures.manage'))add('Ayrılış Türleri / Nedenleri — Hassas İK',b+`SELECT d.kind AS "Tür",d.reason AS "Neden",count(*)::int AS "Adet" FROM employee_departures d JOIN x ON x.id=d.user_id WHERE ${period('d.departure_date')} GROUP BY d.kind,d.reason ORDER BY count(*) DESC LIMIT 100`);
}
if(kind==='inventory'){
 if(filters.unit_id)throw new AppError(400,'Envanter için birim filtresi desteklenmiyor; departman seçin.');
 const b=`WITH x AS (SELECT i.* FROM inventory_items i WHERE ${org('i',['company_id','location_id','department_id'])} AND ${period('i.purchase_date')}) `;
 add('Kategori / Durum',b+`SELECT c.name AS "Kategori",count(*)::int AS "Toplam",${[['ASSIGNED','Zimmetli'],['STOCK','Stokta'],['SERVICE','Serviste'],['FAULTY','Arızalı'],['LOST','Kayıp'],['SCRAPPED','Hurda'],['INACTIVE','Pasif']].map(([s,l])=>`count(*) FILTER(WHERE x.status='${s}')::int AS "${l}"`).join(',')} FROM x JOIN inventory_categories c ON c.id=x.category_id GROUP BY c.id,c.name ORDER BY c.name LIMIT 100`);
 for(const [t,c,l] of [['companies','company_id','Şirket'],['locations','location_id','Lokasyon'],['departments','department_id','Departman']])add(l+' Dağılımı',b+group(t,c,l));
 add('Zimmet / Teslim Uyarıları',b+`SELECT count(*) FILTER(WHERE a.returned_at IS NULL AND u.status IN('LEFT','INACTIVE'))::int AS "Ayrılmış Çalışanda Aktif",count(*) FILTER(WHERE a.returned_at IS NULL AND NOT EXISTS(SELECT 1 FROM assignment_acceptances ac WHERE ac.assignment_id=a.id AND ac.phase='DELIVERY'))::int AS "Kabul Eksik",count(*) FILTER(WHERE a.returned_at IS NULL AND NOT EXISTS(SELECT 1 FROM asset_handover h WHERE h.assignment_id=a.id AND h.phase='DELIVERY' AND jsonb_array_length(h.photos)>0))::int AS "Teslim Fotoğrafı Eksik",count(*) FILTER(WHERE a.returned_at IS NULL AND EXISTS(SELECT 1 FROM asset_handover h WHERE h.assignment_id=a.id AND h.phase='RETURN'))::int AS "İade Bekleyen",count(*) FILTER(WHERE EXISTS(SELECT 1 FROM asset_handover h WHERE h.assignment_id=a.id AND h.phase='RETURN' AND h.damage<>''))::int AS "Hasarlı İade",count(*) FILTER(WHERE EXISTS(SELECT 1 FROM asset_handover h WHERE h.assignment_id=a.id AND h.phase='RETURN' AND h.missing_accessories<>''))::int AS "Eksik Aksesuar" FROM asset_assignments a JOIN x ON x.id=a.inventory_id JOIN users u ON u.id=a.user_id`);
 add('Garanti / Kullanıcısız Cihaz',b+`SELECT count(*)::int AS "Toplam",count(*) FILTER(WHERE warranty_end BETWEEN current_date AND current_date+30)::int AS "Garanti 30 Gün",count(*) FILTER(WHERE NOT EXISTS(SELECT 1 FROM asset_assignments a WHERE a.inventory_id=x.id AND a.returned_at IS NULL))::int AS "Aktif Kullanıcısı Yok" FROM x`);
 add('En Eski Cihazlar',b+`SELECT asset_number AS "Envanter No",brand AS "Marka",model AS "Model",purchase_date::text AS "Alım Tarihi",warranty_end::text AS "Garanti Bitişi" FROM x ORDER BY purchase_date NULLS LAST,id LIMIT 20 OFFSET ${offset}`);
 add('Servis Sıklığı / Maliyeti',b+`SELECT x.asset_number AS "Envanter",c.name AS "Kategori",count(*)::int AS "Servis Sayısı",count(*) FILTER(WHERE s.issue<>'')::int AS "Arıza Kaydı",COALESCE(sum(s.cost),0) AS "Servis Maliyeti" FROM inventory_service_history s JOIN x ON x.id=s.inventory_id JOIN inventory_categories c ON c.id=x.category_id WHERE ${period('s.sent_date')} GROUP BY x.id,x.asset_number,c.name ORDER BY count(*) DESC,x.asset_number LIMIT 20 OFFSET ${offset}`);
 add('Kategori Servis Sayısı',b+`SELECT c.name AS "Kategori",count(*)::int AS "Servis",COALESCE(sum(s.cost),0) AS "Maliyet" FROM inventory_service_history s JOIN x ON x.id=s.inventory_id JOIN inventory_categories c ON c.id=x.category_id WHERE ${period('s.sent_date')} GROUP BY c.name ORDER BY count(*) DESC LIMIT 100`);
}
if(kind==='service_desk'){
 const b=base+`x AS (SELECT r.* FROM requests r JOIN people u ON u.id=r.owner_id WHERE ${period('r.created_at')}) `,open="status NOT IN('COMPLETED','REJECTED','CANCELLED')";
 add('Ticket Özeti',b+`SELECT count(*)::int AS "Toplam",count(*) FILTER(WHERE ${open})::int AS "Açık",count(*) FILTER(WHERE status='COMPLETED')::int AS "Tamamlanan",count(*) FILTER(WHERE status='REJECTED')::int AS "Reddedilen",count(*) FILTER(WHERE ${open} AND deadline<now())::int AS "Geciken",round(avg(extract(epoch FROM accepted_at-created_at)/3600)::numeric,2) AS "Ortalama Kabul (Saat)",round(avg(extract(epoch FROM completed_at-created_at)/3600)::numeric,2) AS "Ortalama Çözüm (Saat)",count(*) FILTER(WHERE sla_due_at IS NOT NULL AND status NOT IN('REJECTED','CANCELLED') AND COALESCE(completed_at,now())>sla_due_at)::int AS "SLA Aşıldı",count(*) FILTER(WHERE ${open} AND now()<=sla_due_at AND sla_due_at-now()<=(sla_due_at-created_at)*0.1)::int AS "SLA Yaklaşıyor",count(*) FILTER(WHERE sla_due_at IS NOT NULL AND status NOT IN('REJECTED','CANCELLED') AND COALESCE(completed_at,now())<=sla_due_at AND (status='COMPLETED' OR sla_due_at-now()>(sla_due_at-created_at)*0.1))::int AS "SLA İçinde" FROM x`);
 add('Departman / Tür / Öncelik',b+`SELECT d.name AS "Sorumlu Departman",t.name AS "Talep Türü",x.priority AS "Öncelik",count(*)::int AS "Adet" FROM x JOIN departments d ON d.id=x.department_id JOIN request_types t ON t.id=x.type_id GROUP BY d.name,t.name,x.priority ORDER BY count(*) DESC LIMIT 100`);
 add('Sorumlu Açık İşleri',b+`SELECT COALESCE(NULLIF(concat_ws(' ',u.first_name,u.last_name),''),'Atanmamış') AS "Sorumlu",count(*)::int AS "Açık Ticket" FROM x LEFT JOIN users u ON u.id=x.assignee_id WHERE x.${open} GROUP BY u.id,u.first_name,u.last_name ORDER BY count(*) DESC LIMIT 100`);
 add('Geciken Tasklar',b+`SELECT t.title AS "Görev",concat_ws(' ',u.first_name,u.last_name) AS "Sorumlu",t.deadline::text AS "Son Tarih",x.number AS "Ticket" FROM ticket_tasks t JOIN x ON x.id=t.request_id JOIN users u ON u.id=t.assignee_id WHERE t.status IN('OPEN','IN_PROGRESS') AND t.deadline<now() ORDER BY t.deadline,t.id LIMIT 20 OFFSET ${offset}`);
}
if(kind==='surveys'){
 // Never join anonymous answers to people or segment their responses. No answer content is exposed here.
 const scope=Object.keys(filters).some(k=>k.endsWith('_id'));
 add('Anket Katılımı',`WITH selected AS (SELECT s.* FROM surveys s WHERE ${period('s.starts_at')} ${scope?`AND NOT s.anonymous AND EXISTS(SELECT 1 FROM users u WHERE ${org('u')} AND ${surveyAudience})`:''}),eligible AS (SELECT s.id,count(*)::int n FROM selected s CROSS JOIN users u WHERE u.status IN('ACTIVE','ON_LEAVE') AND u.archived_at IS NULL AND ${permissionSQL('u','surveys.view_own')} AND ${surveyAudience} ${scope?'AND '+org('u'):''} GROUP BY s.id),answers AS (SELECT p.survey_id,count(*)::int n FROM survey_participation p JOIN selected s ON s.id=p.survey_id JOIN users u ON u.id=p.user_id WHERE ${scope?org('u'):'true'} GROUP BY p.survey_id) SELECT s.title AS "Anket",CASE WHEN s.status='PUBLISHED' AND now() BETWEEN s.starts_at AND s.ends_at THEN 'Aktif' WHEN s.status='CLOSED' OR now()>s.ends_at THEN 'Tamamlanan' ELSE 'Taslak / Yaklaşan' END AS "Durum",COALESCE(e.n,0) AS "Atanan",CASE WHEN s.anonymous AND COALESCE(a.n,0)<s.privacy_threshold THEN NULL ELSE COALESCE(a.n,0) END AS "Cevaplayan",CASE WHEN s.anonymous AND COALESCE(a.n,0)<s.privacy_threshold THEN NULL ELSE GREATEST(0,COALESCE(e.n,0)-COALESCE(a.n,0)) END AS "Bekleyen",CASE WHEN s.anonymous AND COALESCE(a.n,0)<s.privacy_threshold THEN NULL ELSE round(100.0*COALESCE(a.n,0)/NULLIF(e.n,0),1) END AS "Katılım %",CASE WHEN s.anonymous THEN 'Anonim; eşik altı sayılar gizlenir' ELSE 'İsimli' END AS "Gizlilik" FROM selected s LEFT JOIN eligible e ON e.id=s.id LEFT JOIN answers a ON a.survey_id=s.id ORDER BY s.starts_at DESC,s.id LIMIT 20 OFFSET ${offset}`);
}
if(kind==='training'){
 const b=base+`x AS (SELECT t.* FROM training_assignments t JOIN people u ON u.id=t.user_id WHERE ${period('t.assigned_at')}) `;
 add('Eğitim Özeti',b+`SELECT count(*)::int AS "Atanan",count(*) FILTER(WHERE status='COMPLETED')::int AS "Tamamlanan",count(*) FILTER(WHERE status IN('ASSIGNED','IN_PROGRESS'))::int AS "Bekleyen",count(*) FILTER(WHERE status IN('ASSIGNED','IN_PROGRESS') AND due_date<current_date)::int AS "Süresi Geçen" FROM x`);
 add('Sertifika Süresi Yaklaşan',b+`SELECT concat_ws(' ',u.first_name,u.last_name) AS "Çalışan",c.title AS "Eğitim",x.valid_until::text AS "Geçerlilik" FROM x JOIN users u ON u.id=x.user_id JOIN training_courses c ON c.id=x.course_id WHERE x.valid_until<=current_date+30 ORDER BY x.valid_until,x.id LIMIT 20 OFFSET ${offset}`);
}
if(kind==='fleet'){
 if(filters.department_id||filters.unit_id)throw new AppError(400,'Filo için şirket/lokasyon filtrelerini kullanın.');
 const b=`WITH x AS (SELECT v.* FROM fleet_vehicles v WHERE ${org('v',['company_id','location_id'])} AND ${period('v.created_at')}) `;
 add('Filo Özeti',b+`SELECT count(*)::int AS "Toplam",${[['ASSIGNED','Tahsisli'],['POOL','Havuzda'],['SERVICE','Serviste'],['FAULTY','Arızalı'],['INACTIVE','Pasif']].map(([s,l])=>`count(*) FILTER(WHERE status='${s}')::int AS "${l}"`).join(',')} FROM x`);
 for(const [t,c,l] of [['companies','company_id','Şirket'],['locations','location_id','Lokasyon']])add(l+' Dağılımı',b+group(t,c,l));
 add('Yaklaşan / Geçmiş Süreler',b+`SELECT plate AS "Plaka",inspection_date::text AS "Muayene",insurance_end::text AS "Sigorta",casco_end::text AS "Kasko",next_service_date::text AS "Bakım",next_service_km AS "Bakım KM",km AS "Mevcut KM" FROM x WHERE status<>'INACTIVE' AND (LEAST(inspection_date,insurance_end,casco_end,next_service_date)<=current_date+30 OR next_service_km<=km) ORDER BY LEAST(inspection_date,insurance_end,casco_end,next_service_date),id LIMIT 20 OFFSET ${offset}`);
}
if(kind==='people'){
 const b=base+`x AS (SELECT c.* FROM employee_checklists c JOIN people u ON u.id=c.user_id WHERE ${period('c.created_at')}) `;
 add('Onboarding / Offboarding',b+`SELECT CASE x.kind WHEN 'ONBOARDING' THEN 'Onboarding' ELSE 'Offboarding' END AS "Süreç",count(*) FILTER(WHERE x.status='OPEN')::int AS "Aktif",count(*) FILTER(WHERE x.status='COMPLETED')::int AS "Tamamlanan",(SELECT count(*)::int FROM employee_checklist_tasks t JOIN x c ON c.id=t.checklist_id WHERE c.kind=x.kind AND c.status='OPEN' AND t.status='OPEN' AND t.deadline<current_date) AS "Geciken Görev" FROM x GROUP BY x.kind`);
 add('Ayrılmış Çalışandaki Zimmetler',base+`x AS (SELECT p.id,concat_ws(' ',p.first_name,p.last_name) AS name FROM people p WHERE p.status IN('LEFT','INACTIVE') OR EXISTS(SELECT 1 FROM employee_departures d WHERE d.user_id=p.id AND d.departure_date<=current_date)) SELECT x.name AS "Çalışan",i.asset_number AS "Envanter",a.assigned_at::text AS "Teslim" FROM x JOIN asset_assignments a ON a.user_id=x.id AND a.returned_at IS NULL JOIN inventory_items i ON i.id=a.inventory_id ORDER BY x.name,i.asset_number LIMIT 20 OFFSET ${offset}`);
}
// One database round-trip for the selected report section; no per-row queries.
const selects=blocks.map((b,i)=>`'b${i}',COALESCE((SELECT jsonb_agg(r) FROM (${b.sql})r),'[]'::jsonb)`);const result=(await database().query<{data:Record<string,ReportRow[]>}>('SELECT jsonb_build_object('+selects.join(',')+') AS data',values)).rows[0].data;return blocks.map((b,i)=>({title:b.title,rows:result['b'+i]}));}
export function reportCSV(blocks:ReportBlock[]){const cell=(v:unknown)=>'"'+String(v??'').replace(/^(?:\s*[=+@\-]|[\t\r])/, "' $&").replaceAll('"','""')+'"';return '\ufeff'+blocks.flatMap(b=>[[cell(b.title)],...(b.rows.length?[Object.keys(b.rows[0]).map(cell),...b.rows.map(r=>Object.values(r).map(cell))]:[['Kayıt bulunmuyor.']]),[]]).map(r=>r.join(';')).join('\r\n');}
