import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {DB,database,transaction,lock} from './db';
import {Identity,can} from './permissions';
import {identityFor} from './auth-core';
import {audit} from './admin';
import {AppError} from './security';
import {createNotification,permissionSQL} from './notifications';
import {EngagementSummary,suggestionStatuses} from './engagement-shared';
export type Row=Record<string,any>;
const uid=z.string().uuid();
export function suggestionPermit(a:Identity,p:string){if(a.must_change_password||!can(a,p))throw new AppError(403,'Bu işlem için yetkiniz bulunmuyor.');}
async function write<T>(a:Identity,p:string,fn:(db:DB,a:Identity)=>Promise<T>){return transaction(async db=>{await lock(db);const live=await identityFor(db,a.id);if(!live)throw new AppError(401,'Yeniden giriş yapın.');suggestionPermit(live,p);return fn(db,live);});}
const attachment=z.object({name:z.string().trim().min(1).max(150).regex(/^[^\x00-\x1f/\\]+$/),mime:z.enum(['application/pdf','image/png','image/jpeg','image/webp']),data:z.string().max(270000).regex(/^[A-Za-z0-9+/]+=*$/)}).strict().nullable().optional();
function fileBytes(f:z.infer<typeof attachment>){if(!f)return null;const b=Buffer.from(f.data,'base64'),valid=f.mime==='application/pdf'?b.subarray(0,5).toString()==='%PDF-':f.mime==='image/png'?b.subarray(0,8).toString('hex')==='89504e470d0a1a0a':f.mime==='image/jpeg'?b.subarray(0,3).toString('hex')==='ffd8ff':b.subarray(0,4).toString()==='RIFF'&&b.subarray(8,12).toString()==='WEBP';if(!valid||b.length>200000)throw new AppError(400,'Ek, en fazla 200 KB gerçek PDF/PNG/JPEG/WebP olmalıdır.');return b;}
async function history(db:DB,a:Identity,id:string,event:string,status:string,note=''){const historyId=randomUUID();await db.query('INSERT INTO suggestion_status_history(id,suggestion_id,actor_id,event,status,note) VALUES($1,$2,$3,$4,$5,$6)',[historyId,id,a.id,event,status,note]);return historyId;}
export async function suggestionTypes(a:Identity){suggestionPermit(a,'suggestions.create');return {rows:(await database().query<Row>('SELECT id,name,group_name FROM suggestion_types WHERE active ORDER BY name')).rows};}
export async function createSuggestion(a:Identity,payload:unknown){const d=z.object({type_id:z.string().max(60),subject:z.string().trim().min(1).max(200),description:z.string().trim().min(1).max(5000),category:z.string().trim().max(100).default(''),priority:z.enum(['LOW','NORMAL','HIGH','URGENT']).default('NORMAL'),attachment}).strict().parse(payload);const bytes=fileBytes(d.attachment);return write(a,'suggestions.create',async(db,live)=>{if(!(await db.query('SELECT id FROM suggestion_types WHERE id=$1 AND active',[d.type_id])).rows.length)throw new AppError(400,'Aktif kayıt türü seçin.');const id=randomUUID();await db.query(`INSERT INTO suggestions(id,owner_id,type_id,subject,description,category,priority,company_id,location_id,department_id,file_name,file_type,file_data) SELECT $1,u.id,$3,$4,$5,$6,$7,u.company_id,u.location_id,u.department_id,$8,$9,$10 FROM users u WHERE u.id=$2`,[id,live.id,d.type_id,d.subject,d.description,d.category,d.priority,d.attachment?.name??null,d.attachment?.mime??null,bytes]);await history(db,live,id,'created','SUBMITTED');await audit(db,live.id,'suggestion.created','suggestion',id);return {id};});}
const columns=`s.id,s.number,s.owner_id,s.type_id,s.subject,s.category,s.priority,s.status,s.assignee_id,s.company_id,s.location_id,s.department_id,s.created_at::text,s.updated_at::text,t.name AS type_name,t.group_name,concat_ws(' ',u.first_name,u.last_name) AS owner_name,concat_ws(' ',a.first_name,a.last_name) AS assignee_name,co.name AS company_name,lo.name AS location_name,de.name AS department_name`;
const joins=`FROM suggestions s JOIN suggestion_types t ON t.id=s.type_id JOIN users u ON u.id=s.owner_id LEFT JOIN users a ON a.id=s.assignee_id LEFT JOIN companies co ON co.id=s.company_id LEFT JOIN locations lo ON lo.id=s.location_id LEFT JOIN departments de ON de.id=s.department_id`;
export async function suggestionList(a:Identity,params=new URLSearchParams(),admin=false):Promise<{rows:Row[];total:number;page:number}>{suggestionPermit(a,admin?'suggestions.manage':'suggestions.view_own');const page=z.coerce.number().int().min(1).max(100000).parse(params.get('page')||1),values:unknown[]=[a.id],clauses=[admin?'$1::uuid IS NOT NULL':'s.owner_id=$1'];function add(expr:string,value:unknown){values.push(value);clauses.push(expr.replaceAll('?',`$${values.length}`));}for(const k of params.keys())if(!['q','status','type_id','company_id','location_id','department_id','assignee_id','from','to','sort','dir','page'].includes(k))throw new AppError(400,'Geçersiz filtre.');if(params.get('q'))add('(s.subject ILIKE ? OR s.number::text ILIKE ? OR concat_ws(\' \',u.first_name,u.last_name) ILIKE ?)','%'+params.get('q')!.slice(0,120)+'%');const status=params.get('status');if(status==='open')clauses.push("s.status IN('SUBMITTED','REVIEW','WAITING')");else if(status){if(!suggestionStatuses[status])throw new AppError(400,'Geçersiz durum.');add('s.status=?',status);}if(params.get('type_id'))add('s.type_id=?',params.get('type_id'));if(admin)for(const key of ['company_id','location_id','department_id','assignee_id'])if(params.get(key))add('s.'+key+'=?',uid.parse(params.get(key)));if(params.get('from'))add('s.created_at>=?::date',z.string().date().parse(params.get('from')));if(params.get('to'))add("s.created_at<(?::date+interval '1 day')",z.string().date().parse(params.get('to')));const sort=['number','subject','status','updated_at'].includes(params.get('sort')??'')?params.get('sort'):'created_at',dir=params.get('dir')==='asc'?'ASC':'DESC';return {...(await database().query<{rows:Row[];total:number}>(`WITH filtered AS (SELECT ${columns} ${joins} WHERE ${clauses.join(' AND ')}) SELECT (SELECT count(*)::int FROM filtered) AS total,COALESCE((SELECT jsonb_agg(r) FROM (SELECT * FROM filtered ORDER BY ${sort} ${dir},id LIMIT 20 OFFSET ${(page-1)*20})r),'[]'::jsonb) AS rows`,values)).rows[0],page};}
export async function suggestionDetail(a:Identity,id:string,admin=false){uid.parse(id);suggestionPermit(a,admin?'suggestions.manage':'suggestions.view_own');const item=(await database().query<Row>(`SELECT ${columns},s.description,s.file_name,s.file_type ${joins} WHERE s.id=$1 AND ${admin?'$2::uuid IS NOT NULL':'s.owner_id=$2'}`,[id,a.id])).rows[0];if(!item)throw new AppError(404,'Kayıt bulunamadı.');const extra=(await database().query<{history:Row[];responses:Row[]}>(`SELECT COALESCE((SELECT jsonb_agg(h ORDER BY h.created_at,h.id) FROM (SELECT h.id,h.event,h.status,h.note,h.created_at::text,concat_ws(' ',u.first_name,u.last_name) AS actor_name FROM suggestion_status_history h JOIN users u ON u.id=h.actor_id WHERE h.suggestion_id=$1)h),'[]'::jsonb) AS history,COALESCE((SELECT jsonb_agg(r ORDER BY r.created_at,r.id) FROM (SELECT r.id,r.body,r.created_at::text,concat_ws(' ',u.first_name,u.last_name) AS actor_name FROM suggestion_responses r JOIN users u ON u.id=r.actor_id WHERE r.suggestion_id=$1)r),'[]'::jsonb) AS responses`,[id])).rows[0];return {item,...extra};}
export async function manageSuggestion(a:Identity,id:string,payload:unknown){uid.parse(id);const d=z.discriminatedUnion('action',[z.object({action:z.literal('status'),status:z.enum(['REVIEW','WAITING','CLOSED','REJECTED']),note:z.string().trim().max(1000).default('')}),z.object({action:z.literal('assign'),assignee_id:uid}),z.object({action:z.literal('reply'),body:z.string().trim().min(1).max(5000),idempotency_key:uid})]).parse(payload);return write(a,'suggestions.manage',async(db,live)=>{const s=(await db.query<Row>('SELECT id,owner_id,status,assignee_id FROM suggestions WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!s)throw new AppError(404,'Kayıt bulunamadı.');if(d.action==='reply'){const exists=(await db.query<Row>('SELECT suggestion_id,actor_id,body FROM suggestion_responses WHERE idempotency_key=$1',[d.idempotency_key])).rows[0];if(exists){if(exists.suggestion_id!==id||exists.actor_id!==live.id||exists.body!==d.body)throw new AppError(409,'İşlem anahtarı başka bir yanıt için kullanılmış.');return {id};}}if(['CLOSED','REJECTED'].includes(s.status))throw new AppError(409,'Kapatılmış/reddedilmiş kayıt değiştirilemez.');let next=s.status,event='status',note='',key='';if(d.action==='assign'){if(s.assignee_id===d.assignee_id)return {id};const target=await identityFor(db,d.assignee_id);if(!target||!can(target,'suggestions.manage'))throw new AppError(400,'Öneri yönetme yetkisi olan aktif sorumlu seçin.');await db.query('UPDATE suggestions SET assignee_id=$2,updated_at=now() WHERE id=$1',[id,d.assignee_id]);note=target.first_name+' '+target.last_name+' kişisine atandı.';event='assigned';}else if(d.action==='reply'){next='ANSWERED';event='responded';key=d.idempotency_key;await db.query('INSERT INTO suggestion_responses(id,suggestion_id,actor_id,body,idempotency_key) VALUES($1,$2,$3,$4,$5)',[randomUUID(),id,live.id,d.body,key]);}else {if(s.status===d.status)return {id};if(d.status==='REJECTED'&&!d.note)throw new AppError(400,'Red nedeni zorunludur.');next=d.status;note=d.note;}
if(d.action!=='assign')await db.query('UPDATE suggestions SET status=$2,updated_at=now() WHERE id=$1',[id,next]);const h=await history(db,live,id,event,next,note);await audit(db,live.id,'suggestion.'+(event==='status'?next.toLowerCase():event),'suggestion',id);if(d.action!=='assign'){await createNotification(db,{recipient:s.owner_id,event:'suggestion.'+next.toLowerCase(),entityId:id,type:'SUGGESTION',title:next==='ANSWERED'?'Önerinize / bildiriminize yanıt verildi':'Öneriniz / bildiriminiz: '+suggestionStatuses[next],message:next==='ANSWERED'?'Yetkili yanıtını kayıt detayından okuyabilirsiniz.':'Kaydınızın durumu güncellendi.',link:'/suggestions/'+id,key:'suggestion:'+id+':'+(key||h)});}return {id};});}
export async function suggestionFile(a:Identity,id:string,admin=false){await suggestionDetail(a,id,admin);const f=(await database().query<Row>('SELECT file_name,file_type,file_data FROM suggestions WHERE id=$1 AND file_data IS NOT NULL',[id])).rows[0];if(!f)throw new AppError(404,'Ek bulunamadı.');return f;}
export async function suggestionOptions(a:Identity){suggestionPermit(a,'suggestions.manage');return (await database().query<Row>(`SELECT COALESCE((SELECT jsonb_agg(r) FROM (SELECT id,name FROM suggestion_types WHERE active ORDER BY name)r),'[]') AS types,COALESCE((SELECT jsonb_agg(r) FROM (SELECT u.id,concat_ws(' ',u.first_name,u.last_name) AS name FROM users u WHERE u.status IN('ACTIVE','ON_LEAVE') AND u.archived_at IS NULL AND ${permissionSQL('u','suggestions.manage')} ORDER BY name)r),'[]') AS users,COALESCE((SELECT jsonb_agg(r) FROM (SELECT id,name FROM companies WHERE archived_at IS NULL ORDER BY name)r),'[]') AS companies,COALESCE((SELECT jsonb_agg(r) FROM (SELECT id,name FROM locations WHERE archived_at IS NULL ORDER BY name)r),'[]') AS locations,COALESCE((SELECT jsonb_agg(r) FROM (SELECT id,name FROM departments WHERE archived_at IS NULL ORDER BY name)r),'[]') AS departments`)).rows[0];}
export async function dashboardEngagement(a:Identity):Promise<EngagementSummary>{suggestionPermit(a,'portal.home.view');const suggestions=can(a,'suggestions.view_own');return (await database().query<EngagementSummary>(`WITH mine AS (${suggestions?"SELECT s.id,s.number,s.subject,s.status,s.created_at::text,t.name AS type_name,t.group_name FROM suggestions s JOIN suggestion_types t ON t.id=s.type_id WHERE s.owner_id=$1":"SELECT NULL::uuid AS id,0 AS number,'' AS subject,'' AS status,'' AS created_at,'' AS type_name,'' AS group_name WHERE false"}) SELECT ${can(a,'notifications.view_own')?"(SELECT count(*)::int FROM workflow_notifications WHERE recipient_id=$1 AND NOT is_read)":'0'} AS unread,(SELECT count(*)::int FROM mine WHERE group_name='SUGGESTION') AS suggestion_count,(SELECT count(*)::int FROM mine WHERE group_name='NOTICE') AS notice_count,COALESCE((SELECT jsonb_agg(r) FROM (SELECT * FROM (SELECT *,row_number() OVER(PARTITION BY group_name ORDER BY created_at DESC,id DESC) AS rank FROM mine)ranked WHERE rank<=2 ORDER BY created_at DESC,id DESC)r),'[]'::jsonb) AS suggestions WHERE $1::uuid IS NOT NULL`,[a.id])).rows[0];}
