import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {database,DB} from './db';
import {Identity} from './permissions';
import {write,permit} from './workflows';
import {AppError} from './security';
import {audit} from './admin';
import {permissionSQL} from './notifications';
import {Survey,Answer,SurveyResults} from './survey-shared';
const uuid=z.string().uuid();
const question=z.object({id:z.string().regex(/^[a-zA-Z0-9_-]{1,60}$/),title:z.string().trim().min(1).max(300),type:z.enum(['SINGLE','MULTIPLE','YES_NO','SCALE_5','SCALE_10','SHORT','LONG']),required:z.boolean(),options:z.array(z.string().trim().min(1).max(200)).max(30).default([])}).strict();
const schema=z.object({title:z.string().trim().min(1).max(200),description:z.string().max(3000).default(''),anonymous:z.boolean(),required:z.boolean(),starts_at:z.string().datetime({offset:true}),ends_at:z.string().datetime({offset:true}),privacy_threshold:z.number().int().min(5).max(100).default(5),audience_all:z.boolean(),targets:z.array(z.object({type:z.enum(['company_id','location_id','department_id','unit_id','role_id','user_id']),id:z.string().min(1).max(80)}).strict()).max(500),questions:z.array(question).min(1).max(50)}).strict();
// Same OR audience semantics and organization/role source as the content modules.
export const surveyAudience=`(s.audience_all OR EXISTS(SELECT 1 FROM jsonb_array_elements(s.targets) a WHERE (a->>'type'='user_id' AND a->>'id'=u.id::text) OR (a->>'type'='company_id' AND a->>'id'=u.company_id::text) OR (a->>'type'='location_id' AND a->>'id'=u.location_id::text) OR (a->>'type'='department_id' AND a->>'id'=u.department_id::text) OR (a->>'type'='unit_id' AND a->>'id'=u.unit_id::text) OR (a->>'type'='role_id' AND EXISTS(SELECT 1 FROM user_roles ur JOIN roles ro ON ro.id=ur.role_id AND ro.active WHERE ur.user_id=u.id AND ur.role_id=a->>'id'))))`;
const eligible=`u.status IN('ACTIVE','ON_LEAVE') AND u.archived_at IS NULL AND ${permissionSQL('u','surveys.view_own')} AND ${surveyAudience}`;
async function record(db:DB,id:string){uuid.parse(id);const s=(await db.query<Survey>('SELECT *,starts_at::text,ends_at::text FROM surveys WHERE id=$1',[id])).rows[0];if(!s)throw new AppError(404,'Anket bulunamadı.');return s;}
export async function saveSurvey(a:Identity,payload:unknown,id?:string){const d=schema.parse(payload);if(new Date(d.ends_at)<=new Date(d.starts_at))throw new AppError(400,'Bitiş başlangıçtan sonra olmalıdır.');if(d.audience_all===!!d.targets.length)throw new AppError(400,'Herkes veya hedef kitle seçin.');if(new Set(d.questions.map(q=>q.id)).size!==d.questions.length)throw new AppError(400,'Soru kodları benzersiz olmalı.');for(const q of d.questions)if(['SINGLE','MULTIPLE'].includes(q.type)&&(q.options.length<2||new Set(q.options).size!==q.options.length))throw new AppError(400,'En az iki farklı seçenek girin.');return write(a,'surveys.manage',true,async(db,live)=>{if(id&&(await record(db,id)).status!=='DRAFT')throw new AppError(409,'Yayınlanan anketin soru ve gizlilik ayarları değiştirilemez.');const target=id??randomUUID();const keys=Object.keys(d),values=Object.entries(d).map(([k,v])=>['targets','questions'].includes(k)?JSON.stringify(v):v);await db.query(id?`UPDATE surveys SET ${keys.map((k,i)=>k+'=$'+(i+1)).join(',')} WHERE id=$${values.length+1}`:`INSERT INTO surveys(${keys.join(',')},id,created_by) VALUES(${[...values,target,live.id].map((_,i)=>'$'+(i+1)).join(',')})`,id?[...values,target]:[...values,target,live.id]);await audit(db,live.id,'survey.saved','survey',target);return {id:target};});}
export async function surveyStatus(a:Identity,id:string,status:'PUBLISHED'|'CLOSED'){return write(a,'surveys.manage',true,async(db,live)=>{const s=await record(db,id);if(status==='PUBLISHED'&&s.status!=='DRAFT'||status==='CLOSED'&&s.status!=='PUBLISHED')throw new AppError(409,'Geçersiz durum geçişi.');await db.query('UPDATE surveys SET status=$2 WHERE id=$1',[id,status]);if(status==='PUBLISHED')await db.query(`INSERT INTO workflow_notifications(id,recipient_id,event,entity_id,type,title,message,link,dedup_key) SELECT gen_random_uuid(),u.id,'survey.published',s.id,'SYSTEM','Yeni anketiniz var',s.title,'/surveys/'||s.id,'survey:'||s.id FROM surveys s CROSS JOIN users u WHERE s.id=$1 AND ${eligible} AND ${permissionSQL('u','notifications.view_own')} ON CONFLICT(recipient_id,dedup_key) WHERE dedup_key IS NOT NULL DO NOTHING`,[id]);await audit(db,live.id,'survey.'+status.toLowerCase(),'survey',id);return {id};});}
export async function surveyList(a:Identity,p=new URLSearchParams(),admin=false){permit(a,admin?'surveys.manage':'surveys.view_own',admin);const page=z.coerce.number().int().min(1).max(100000).parse(p.get('page')||1),q='%'+(p.get('q')??'').slice(0,100)+'%';return {...(await database().query<{rows:Survey[];total:number}>(`WITH list AS (SELECT s.id,s.title,s.anonymous,s.required,s.status,s.starts_at::text,s.ends_at::text,EXISTS(SELECT 1 FROM survey_participation p WHERE p.survey_id=s.id AND p.user_id=$1) AS answered FROM surveys s JOIN users u ON u.id=$1 WHERE s.title ILIKE $2 ${admin?'':`AND s.status='PUBLISHED' AND now() BETWEEN s.starts_at AND s.ends_at AND ${eligible}`}) SELECT (SELECT count(*)::int FROM list) AS total,COALESCE((SELECT jsonb_agg(r) FROM (SELECT * FROM list ORDER BY ends_at,id LIMIT 20 OFFSET ${(page-1)*20})r),'[]'::jsonb) AS rows`,[a.id,q])).rows[0],page};}
export async function surveyDetail(a:Identity,id:string,admin=false){permit(a,admin?'surveys.manage':'surveys.view_own',admin);const s=await record(database(),id);if(!admin&&!(await database().query(`SELECT s.id FROM surveys s JOIN users u ON u.id=$2 WHERE s.id=$1 AND s.status='PUBLISHED' AND now() BETWEEN s.starts_at AND s.ends_at AND ${eligible}`,[id,a.id])).rows.length)throw new AppError(404,'Anket bulunamadı.');const answered=!!(await database().query('SELECT 1 FROM survey_participation WHERE survey_id=$1 AND user_id=$2',[id,a.id])).rows.length;return {...s,answered};}
export async function submitSurvey(a:Identity,id:string,payload:unknown){const data=z.record(z.string(),z.union([z.string().max(4000),z.number(),z.array(z.string().max(200)).max(30)])).parse(payload);return write(a,'surveys.view_own',false,async(db,live)=>{const s=await record(db,id);if(!(await db.query(`SELECT s.id FROM surveys s JOIN users u ON u.id=$2 WHERE s.id=$1 AND s.status='PUBLISHED' AND now() BETWEEN s.starts_at AND s.ends_at AND ${eligible}`,[id,live.id])).rows.length)throw new AppError(404,'Anket bulunamadı.');if((await db.query('SELECT 1 FROM survey_participation WHERE survey_id=$1 AND user_id=$2',[id,live.id])).rows.length)throw new AppError(409,'Bu anketi zaten yanıtladınız.');const answers:Record<string,Answer>={};if(Object.keys(data).some(k=>!s.questions.some(q=>q.id===k)))throw new AppError(400,'Geçersiz soru.');for(const q of s.questions){const v=data[q.id];if(v===undefined||v===''||Array.isArray(v)&&!v.length){if(q.required)throw new AppError(400,'Zorunlu soruları yanıtlayın.');continue;}const valid=q.type==='SINGLE'?typeof v==='string'&&q.options.includes(v):q.type==='MULTIPLE'?Array.isArray(v)&&new Set(v).size===v.length&&v.every(x=>q.options.includes(x)):q.type==='YES_NO'?['Evet','Hayır'].includes(String(v)):q.type.startsWith('SCALE')?typeof v==='number'&&Number.isInteger(v)&&v>=1&&v<=(q.type==='SCALE_5'?5:10):typeof v==='string'&&v.length<=(q.type==='SHORT'?300:4000);if(!valid)throw new AppError(400,'Yanıt biçimini kontrol edin.');answers[q.id]=v;}
await db.query('INSERT INTO survey_participation(survey_id,user_id) VALUES($1,$2)',[id,live.id]);await db.query('INSERT INTO survey_responses(id,survey_id,user_id,answers) VALUES($1,$2,$3,$4)',[randomUUID(),id,s.anonymous?null:live.id,JSON.stringify(answers)]);return {ok:true};});}
export async function surveyResults(a:Identity,id:string):Promise<SurveyResults>{permit(a,'surveys.results',true);const s=await record(database(),id),counts=(await database().query<{assigned:number;answered:number}>(`SELECT (SELECT count(*)::int FROM users u JOIN surveys s ON s.id=$1 WHERE ${eligible}) AS assigned,(SELECT count(*)::int FROM survey_responses WHERE survey_id=$1) AS answered`,[id])).rows[0];const suppressed=s.anonymous&&counts.answered<s.privacy_threshold,result:SurveyResults={...counts,pending:Math.max(0,counts.assigned-counts.answered),participation:counts.assigned?Math.round(counts.answered/counts.assigned*100):0,suppressed,questions:[]};if(suppressed)return result;
const aggregate=(await database().query<{question:string;value:Answer;count:number}>(`SELECT e.key AS question,e.value,count(*)::int AS count FROM survey_responses r CROSS JOIN LATERAL jsonb_each(r.answers)e WHERE survey_id=$1 GROUP BY e.key,e.value`,[id])).rows;
result.questions=s.questions.map(q=>{const rows=aggregate.filter(r=>r.question===q.id);if(['SHORT','LONG'].includes(q.type))return {title:q.title,counts:[],texts:rows.map(r=>String(r.value))};const groups=new Map<string,number>();for(const r of rows)for(const v of Array.isArray(r.value)?r.value:[r.value])groups.set(String(v),(groups.get(String(v))??0)+r.count);return {title:q.title,counts:[...groups].map(([label,count])=>({label,count})),texts:[]};});return result;}
export async function surveyOptions(a:Identity){permit(a,'surveys.manage',true);const tables={company_id:'companies',location_id:'locations',department_id:'departments',unit_id:'units',role_id:'roles',user_id:'users'};return (await database().query<Record<string,{id:string;name:string}[]>>('SELECT '+Object.entries(tables).map(([key,table])=>`COALESCE((SELECT jsonb_agg(r) FROM (SELECT id,${key==='user_id'?"concat_ws(' ',first_name,last_name)":'name'} AS name FROM ${table} WHERE ${key==='user_id'?"status IN('ACTIVE','ON_LEAVE') AND archived_at IS NULL":key==='role_id'?'active':'active AND archived_at IS NULL'} ORDER BY name LIMIT 1000)r),'[]'::jsonb) AS ${key}`).join(','))).rows[0];}
