import {randomUUID} from 'node:crypto';
import {createNotification} from './notifications';
type Ticket={id:string;department_id:string;status:string};
type Task={id:string;request_id:string;title:string;assignee_id:string;priority:string;deadline:string|null;status:string;request_status:string};
type OwnTask={id:string;title:string;priority:string;deadline:string|null;status:string;request_number:number};
import {z} from 'zod';
import {database} from './db';
import {Identity,can} from './permissions';
import {AppError} from './security';
import {write,user,scoped,history,detail,permit} from './workflows';
const uid=z.string().regex(/^[a-f0-9]{8}(-[a-f0-9]{4}){3}-[a-f0-9]{12}$/i);
export async function ticketTasks(a:Identity,id:string,admin=false){await detail(a,'requests',id,admin);return {rows:(await database().query(`SELECT t.id,t.title,t.assignee_id,concat_ws(' ',u.first_name,u.last_name) AS assignee_name,t.priority,t.deadline::text,t.status,t.completed_at::text FROM ticket_tasks t JOIN users u ON u.id=t.assignee_id WHERE request_id=$1 ORDER BY t.created_at,t.id LIMIT 100`,[id])).rows};}
export async function saveTask(a:Identity,requestId:string,payload:unknown,id?:string){uid.parse(requestId);if(id)uid.parse(id);const d=z.object({title:z.string().trim().min(1).max(200),assignee_id:uid,priority:z.enum(['LOW','NORMAL','HIGH','URGENT']).default('NORMAL'),deadline:z.string().datetime({offset:true}).nullable().optional(),status:z.enum(['OPEN','IN_PROGRESS','DONE','CANCELLED']).default('OPEN')}).strict().parse(payload);return write(a,'requests.manage',true,async(db,live)=>{
 const r=(await db.query<Ticket>('SELECT * FROM requests WHERE id=$1 FOR UPDATE',[requestId])).rows[0];if(!r||!await scoped(db,live,r.department_id))throw new AppError(404,'Talep bulunamadı.');if(['PENDING_MANAGER','COMPLETED','REJECTED','CANCELLED'].includes(r.status))throw new AppError(409,'Bu aşamada görev düzenlenemez.');await user(db,d.assignee_id);const old=id?(await db.query<Task>('SELECT * FROM ticket_tasks WHERE id=$1 AND request_id=$2 FOR UPDATE',[id,requestId])).rows[0]:null;if(id&&!old)throw new AppError(404,'Görev bulunamadı.');if(old&&['DONE','CANCELLED'].includes(old.status))throw new AppError(409,'Sonuçlanmış görev değiştirilemez.');const target=id??randomUUID();if(id)await db.query("UPDATE ticket_tasks SET title=$2,assignee_id=$3,priority=$4,deadline=$5,status=$6,completed_at=CASE WHEN $6='DONE' THEN now() ELSE NULL END,updated_at=now() WHERE id=$1",[target,d.title,d.assignee_id,d.priority,d.deadline??null,d.status]);else await db.query("INSERT INTO ticket_tasks(id,request_id,title,assignee_id,priority,deadline,status,completed_at,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,CASE WHEN $7='DONE' THEN now() ELSE NULL END,$8)",[target,requestId,d.title,d.assignee_id,d.priority,d.deadline??null,d.status,live.id]);await history(db,live,'requests',requestId,id?'task.updated':'task.created',r.status,JSON.stringify({task:target,old:old?{title:old.title,assignee:old.assignee_id,deadline:old.deadline,status:old.status}:null,new:d}));if(!old||old.assignee_id!==d.assignee_id)await createNotification(db,{recipient:d.assignee_id,event:'task.assigned',entityId:target,type:'REQUEST',title:'Size bir alt görev atandı',message:d.title,link:'/tasks',key:'task.assigned:'+target+':'+randomUUID()});return {id:target};});}
export async function myTasks(a:Identity,page=1){permit(a,'tasks.view_own');page=Math.max(1,Math.min(100000,Math.floor(page)));return {...(await database().query<{total:number;rows:OwnTask[]}>(`WITH mine AS (SELECT t.id,t.title,t.priority,t.deadline::text,t.status,r.number AS request_number FROM ticket_tasks t JOIN requests r ON r.id=t.request_id WHERE t.assignee_id=$1 AND t.status IN('OPEN','IN_PROGRESS') AND r.status NOT IN('COMPLETED','REJECTED','CANCELLED')) SELECT (SELECT count(*)::int FROM mine) AS total,COALESCE((SELECT jsonb_agg(r) FROM (SELECT * FROM mine ORDER BY deadline NULLS LAST,id LIMIT 20 OFFSET ${(page-1)*20})r),'[]'::jsonb) AS rows`,[a.id])).rows[0],page};}
export async function updateOwnTask(a:Identity,id:string,payload:unknown){uid.parse(id);const {status}=z.object({status:z.enum(['IN_PROGRESS','DONE'])}).strict().parse(payload);return write(a,'tasks.update_own',false,async(db,live)=>{permit(live,'tasks.view_own');const r=(await db.query<Task>('SELECT t.*,r.status AS request_status FROM ticket_tasks t JOIN requests r ON r.id=t.request_id WHERE t.id=$1 AND t.assignee_id=$2 FOR UPDATE OF t,r',[id,live.id])).rows[0];if(!r)throw new AppError(404,'Görev bulunamadı.');if(!['OPEN','IN_PROGRESS'].includes(r.status)||['COMPLETED','REJECTED','CANCELLED'].includes(r.request_status))throw new AppError(409,'Görev artık değiştirilemez.');await db.query("UPDATE ticket_tasks SET status=$2,completed_at=CASE WHEN $2='DONE' THEN now() ELSE NULL END,updated_at=now() WHERE id=$1",[id,status]);await history(db,live,'requests',r.request_id,'task.updated',r.request_status,r.title+': '+r.status+' → '+status);return {id};});}
