export const workflowPermissions=['requests.view_own','requests.create','requests.view_department','requests.assign','requests.update','requests.manage','request_types.view','request_types.manage','leave.view_own','leave.create','leave.view_department','leave.manage','leave_types.view','leave_types.manage','leave_balances.view','leave_balances.manage','approvals.view','approvals.approve'];
export const ownWorkflowPermissions=['requests.view_own','requests.create','leave.view_own','leave.create'];
export const workflowNames:Record<string,string>={'request-types':'Talep Türleri',requests:'Talepler','leave-types':'İzin Türleri',leave:'İzin Talepleri','leave-balances':'İzin Bakiyeleri',approvals:'Onaylarım'};
export const workflowStatus:Record<string,string>={SUBMITTED:'Gönderildi',REVIEW:'İnceleniyor',PENDING_MANAGER:'Yönetici Onayı Bekliyor',PENDING_HR:'İK Onayı Bekliyor',APPROVED:'Onaylandı',REJECTED:'Reddedildi',IN_PROGRESS:'İşlemde',COMPLETED:'Tamamlandı',CANCELLED:'İptal',PENDING:'Onay Bekliyor'};
export const requestOpen=['SUBMITTED','REVIEW','PENDING_MANAGER','APPROVED','IN_PROGRESS'];
export function workDays(start:string,end:string,part='FULL',holidays:string[]=[]){const a=new Date(start+'T00:00:00Z'),b=new Date(end+'T00:00:00Z');if(!Number.isFinite(+a)||!Number.isFinite(+b)||a.toISOString().slice(0,10)!==start||b.toISOString().slice(0,10)!==end||b<a||(+b-+a)/86400000>366)throw Error('Geçerli bir tarih aralığı seçin (en fazla 367 gün).');if(part!=='FULL'&&start!==end)throw Error('Yarım gün için başlangıç ve bitiş aynı olmalıdır.');let days=0;for(let d=+a;d<=+b;d+=86400000){const date=new Date(d);if(![0,6].includes(date.getUTCDay())&&!holidays.includes(date.toISOString().slice(0,10)))days++;}return part==='FULL'?days:days*.5;}
export function balanceNumbers(total:number,used:number,pending:number){return {total,used,pending,remaining:total-used-pending};}

export const workflowEvents:Record<string,string>={'request.created':'Talep oluşturuldu','request.assigned':'Sorumlu kişi atandı','request.review':'Talep inceleniyor','request.in_progress':'İşleme alındı','request.completed':'Talep tamamlandı','request.rejected':'Talep reddedildi','request.approved':'Yönetici onayladı','request.cancelled':'Talep iptal edildi','leave.created':'İzin talebi oluşturuldu','leave.approved':'İzin onaylandı','leave.rejected':'İzin reddedildi','leave.cancelled':'İzin iptal edildi'};
