CREATE TABLE IF NOT EXISTS app_lock(id integer PRIMARY KEY CHECK(id=1));
INSERT INTO app_lock VALUES(1) ON CONFLICT DO NOTHING;
CREATE TABLE IF NOT EXISTS companies(id uuid PRIMARY KEY, name text NOT NULL, code text NOT NULL UNIQUE, logo text, active boolean NOT NULL DEFAULT true, archived_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS locations(id uuid PRIMARY KEY, name text NOT NULL, code text NOT NULL, company_id uuid NOT NULL REFERENCES companies(id), address text, city text, district text, country text DEFAULT 'Türkiye', latitude double precision CHECK(latitude BETWEEN -90 AND 90), longitude double precision CHECK(longitude BETWEEN -180 AND 180), timezone text NOT NULL DEFAULT 'Europe/Istanbul', phone text, active boolean NOT NULL DEFAULT true, archived_at timestamptz, UNIQUE(company_id,code));
CREATE TABLE IF NOT EXISTS departments(id uuid PRIMARY KEY, name text NOT NULL, code text NOT NULL, company_id uuid NOT NULL REFERENCES companies(id), parent_id uuid REFERENCES departments(id), manager_user_id uuid, active boolean NOT NULL DEFAULT true, archived_at timestamptz, CHECK(parent_id IS DISTINCT FROM id), UNIQUE(company_id,code));
CREATE TABLE IF NOT EXISTS units(id uuid PRIMARY KEY, name text NOT NULL, code text NOT NULL, company_id uuid NOT NULL REFERENCES companies(id), department_id uuid NOT NULL REFERENCES departments(id), manager_user_id uuid, active boolean NOT NULL DEFAULT true, archived_at timestamptz, UNIQUE(company_id,code));
CREATE TABLE IF NOT EXISTS job_titles(id uuid PRIMARY KEY, name text NOT NULL, code text NOT NULL, company_id uuid NOT NULL REFERENCES companies(id), department_id uuid REFERENCES departments(id), active boolean NOT NULL DEFAULT true, archived_at timestamptz, UNIQUE(company_id,code));
CREATE TABLE IF NOT EXISTS employee_types(id text PRIMARY KEY, name text NOT NULL, active boolean NOT NULL DEFAULT true);
CREATE TABLE IF NOT EXISTS users(id uuid PRIMARY KEY, personnel_no text NOT NULL UNIQUE, first_name text NOT NULL, last_name text NOT NULL, photo text, email text NOT NULL UNIQUE, phone text, extension text, company_id uuid REFERENCES companies(id), location_id uuid REFERENCES locations(id), department_id uuid REFERENCES departments(id), unit_id uuid REFERENCES units(id), job_title_id uuid REFERENCES job_titles(id), manager_user_id uuid REFERENCES users(id), start_date date, employee_type_id text REFERENCES employee_types(id), username text NOT NULL UNIQUE, status text NOT NULL DEFAULT 'ACTIVE' CHECK(status IN('ACTIVE','INACTIVE','ON_LEAVE','LEFT')), must_change_password boolean NOT NULL DEFAULT true, last_login timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), archived_at timestamptz, CHECK(manager_user_id IS DISTINCT FROM id), CHECK(username=lower(username)), CHECK(email=lower(email)));
DO $$ BEGIN ALTER TABLE departments ADD CONSTRAINT departments_manager_fk FOREIGN KEY(manager_user_id) REFERENCES users(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE units ADD CONSTRAINT units_manager_fk FOREIGN KEY(manager_user_id) REFERENCES users(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE TABLE IF NOT EXISTS credentials(user_id uuid PRIMARY KEY REFERENCES users(id), password_hash text NOT NULL, changed_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS sessions(token_hash text PRIMARY KEY, user_id uuid NOT NULL REFERENCES users(id), expires_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS sessions_user_idx ON sessions(user_id);
CREATE INDEX IF NOT EXISTS sessions_expiry_idx ON sessions(expires_at);
CREATE TABLE IF NOT EXISTS roles(id text PRIMARY KEY, name text NOT NULL, builtin boolean NOT NULL DEFAULT false, active boolean NOT NULL DEFAULT true);
CREATE TABLE IF NOT EXISTS permissions(id text PRIMARY KEY, name text NOT NULL, group_name text NOT NULL);
CREATE TABLE IF NOT EXISTS user_roles(user_id uuid NOT NULL REFERENCES users(id), role_id text NOT NULL REFERENCES roles(id), PRIMARY KEY(user_id,role_id));
CREATE TABLE IF NOT EXISTS role_permissions(role_id text NOT NULL REFERENCES roles(id), permission_id text NOT NULL REFERENCES permissions(id), PRIMARY KEY(role_id,permission_id));
CREATE TABLE IF NOT EXISTS user_permission_overrides(user_id uuid NOT NULL REFERENCES users(id), permission_id text NOT NULL REFERENCES permissions(id), allowed boolean NOT NULL, PRIMARY KEY(user_id,permission_id));
CREATE TABLE IF NOT EXISTS audit_logs(id uuid PRIMARY KEY, actor_user_id uuid REFERENCES users(id), action text NOT NULL, entity_type text NOT NULL, entity_id text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS audit_entity_idx ON audit_logs(entity_type,entity_id,created_at);
CREATE TABLE IF NOT EXISTS login_limits(key_hash text PRIMARY KEY, count integer NOT NULL DEFAULT 1, window_end timestamptz NOT NULL);
CREATE INDEX IF NOT EXISTS users_company_idx ON users(company_id);
CREATE INDEX IF NOT EXISTS users_location_idx ON users(location_id);
CREATE INDEX IF NOT EXISTS users_department_idx ON users(department_id);
CREATE INDEX IF NOT EXISTS users_manager_idx ON users(manager_user_id);
CREATE INDEX IF NOT EXISTS users_status_idx ON users(status);
CREATE INDEX IF NOT EXISTS departments_company_idx ON departments(company_id);
CREATE INDEX IF NOT EXISTS departments_parent_idx ON departments(parent_id);
CREATE INDEX IF NOT EXISTS units_department_idx ON units(department_id);

ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS details jsonb;
ALTER TABLE users ADD COLUMN IF NOT EXISTS expertise text NOT NULL DEFAULT '';
