BEGIN;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS details jsonb;
CREATE TABLE IF NOT EXISTS employee_checklists(id uuid PRIMARY KEY,user_id uuid NOT NULL REFERENCES users,kind text NOT NULL CHECK(kind IN('ONBOARDING','OFFBOARDING')),title text NOT NULL,status text NOT NULL DEFAULT 'OPEN' CHECK(status IN('OPEN','COMPLETED')),created_by uuid NOT NULL REFERENCES users,created_at timestamptz NOT NULL DEFAULT now(),completed_at timestamptz,override_reason text NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS employee_checklist_tasks(id uuid PRIMARY KEY,checklist_id uuid NOT NULL REFERENCES employee_checklists,title text NOT NULL,department_id uuid REFERENCES departments,assignee_id uuid REFERENCES users,deadline date,status text NOT NULL DEFAULT 'OPEN' CHECK(status IN('OPEN','DONE')),completed_by uuid REFERENCES users,completed_at timestamptz,CHECK((status='DONE')=(completed_at IS NOT NULL)),CHECK(department_id IS NOT NULL OR assignee_id IS NOT NULL));
CREATE TABLE IF NOT EXISTS employee_departures(user_id uuid PRIMARY KEY REFERENCES users,departure_date date NOT NULL,kind text NOT NULL CHECK(kind IN('RESIGNATION','DISMISSAL','RETIREMENT','CONTRACT_END','PROBATION','OTHER')),reason text NOT NULL DEFAULT '',notes text NOT NULL DEFAULT '',updated_by uuid NOT NULL REFERENCES users,updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS training_courses(id uuid PRIMARY KEY,title text NOT NULL,category text NOT NULL,description text NOT NULL DEFAULT '',active boolean NOT NULL DEFAULT true,created_by uuid NOT NULL REFERENCES users,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS training_assignments(id uuid PRIMARY KEY,course_id uuid NOT NULL REFERENCES training_courses,user_id uuid NOT NULL REFERENCES users,assigned_by uuid NOT NULL REFERENCES users,assigned_at timestamptz NOT NULL DEFAULT now(),due_date date NOT NULL,status text NOT NULL DEFAULT 'ASSIGNED' CHECK(status IN('ASSIGNED','IN_PROGRESS','COMPLETED','CANCELLED')),completed_at timestamptz,valid_until date,certificate jsonb,CHECK((status='COMPLETED')=(completed_at IS NOT NULL)));
CREATE UNIQUE INDEX IF NOT EXISTS training_active_assignment ON training_assignments(course_id,user_id) WHERE status IN('ASSIGNED','IN_PROGRESS');
CREATE INDEX IF NOT EXISTS training_assignment_user ON training_assignments(user_id,status,due_date);
CREATE INDEX IF NOT EXISTS checklist_user_status ON employee_checklists(user_id,status,kind);
CREATE INDEX IF NOT EXISTS checklist_task_owner ON employee_checklist_tasks(assignee_id,status,deadline);
CREATE INDEX IF NOT EXISTS checklist_task_parent ON employee_checklist_tasks(checklist_id);
ALTER TABLE inventory_categories ADD COLUMN IF NOT EXISTS handover_rules jsonb NOT NULL DEFAULT '{}';
ALTER TABLE asset_assignments ADD COLUMN IF NOT EXISTS rules_snapshot jsonb NOT NULL DEFAULT '{}';
CREATE TABLE IF NOT EXISTS asset_handover(id uuid PRIMARY KEY,assignment_id uuid NOT NULL REFERENCES asset_assignments,phase text NOT NULL CHECK(phase IN('DELIVERY','RETURN')),actor_id uuid NOT NULL REFERENCES users,counterparty_id uuid NOT NULL REFERENCES users,condition text NOT NULL,damage text NOT NULL DEFAULT '',missing_accessories text NOT NULL DEFAULT '',notes text NOT NULL DEFAULT '',accessories jsonb NOT NULL DEFAULT '[]',photos jsonb NOT NULL DEFAULT '[]',documents jsonb NOT NULL DEFAULT '[]',created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(assignment_id,phase));
CREATE TABLE IF NOT EXISTS assignment_acceptances(id uuid PRIMARY KEY,assignment_id uuid NOT NULL REFERENCES asset_assignments,user_id uuid NOT NULL REFERENCES users,phase text NOT NULL CHECK(phase IN('DELIVERY','RETURN')),form_version integer NOT NULL DEFAULT 1,accepted_at timestamptz NOT NULL DEFAULT now(),UNIQUE(assignment_id,phase));
CREATE TABLE IF NOT EXISTS inventory_service_history(id uuid PRIMARY KEY,inventory_id uuid NOT NULL REFERENCES inventory_items,issue text NOT NULL,provider text NOT NULL,sent_date date NOT NULL,returned_date date,work text NOT NULL DEFAULT '',cost numeric(14,2),document jsonb,notes text NOT NULL DEFAULT '',actor_id uuid NOT NULL REFERENCES users,created_at timestamptz NOT NULL DEFAULT now(),CHECK(returned_date IS NULL OR returned_date>=sent_date),CHECK(cost IS NULL OR cost>=0));
CREATE INDEX IF NOT EXISTS inventory_service_item ON inventory_service_history(inventory_id,sent_date);
CREATE INDEX IF NOT EXISTS asset_handover_assignment ON asset_handover(assignment_id,phase);
DROP TRIGGER IF EXISTS handover_immutable ON asset_handover;
CREATE TRIGGER handover_immutable BEFORE UPDATE OR DELETE ON asset_handover FOR EACH ROW EXECUTE FUNCTION workflow_immutable();
DROP TRIGGER IF EXISTS acceptance_immutable ON assignment_acceptances;
CREATE TRIGGER acceptance_immutable BEFORE UPDATE OR DELETE ON assignment_acceptances FOR EACH ROW EXECUTE FUNCTION workflow_immutable();
DROP TRIGGER IF EXISTS service_immutable ON inventory_service_history;
CREATE TRIGGER service_immutable BEFORE UPDATE OR DELETE ON inventory_service_history FOR EACH ROW EXECUTE FUNCTION workflow_immutable();
COMMIT;
